### DISCUSSION TITLE
AWS SAM connectors are now generally available

### DISCUSSION THREAD

**Discussion by hoffa** [aws/serverless-application-model#2532] [Announcements]
[AWS SAM connectors](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/managing-permissions-connectors.html) are now generally available. They simplify enabling permissions between resources.

You specify the source and destination resource along with the permission category (`Read` or `Write`), and SAM automatically creates the necessary policy resources.

For example:

```yaml
MyConnector:
  Type: AWS::Serverless::Connector
  Properties:
    Source:
      Id: MyFunction
    Destination:
      Id: MyTable
    Permissions:
      - Write
```

Relevant docs:
- [What's New announcement](https://aws.amazon.com/about-aws/whats-new/2022/10/aws-sam-serverless-connectors/)
- [Properties reference](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-connector.html)
- [List of supported resources](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/reference-sam-connector.html)
