### DISCUSSION TITLE
Lambda Logs definition in template

### DISCUSSION THREAD

**Discussion by GuidoNebiolo** [aws/serverless-application-model#2665] [Ideas]
### Describe your idea/feature/enhancement

I wish the SAM Translator would generate also the CloudWatch LogGroup for a declared Lambda.
In this way the deployment will be consistent during deletion and delete also the log group.

### Proposal

Additional property for AWS::Serverless::Function which generate the AWS::Logs::LogGroup associated.

Now:
``` yaml
  MyService:
    Type: AWS::Serverless::Function
    Properties:
      ...

  MyLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${MyService}

```

Proposal:
``` yaml
  MyService:
    Type: AWS::Serverless::Function
    Properties:
      LogGroup: enabled
```
or
``` yaml
  MyService:
    Type: AWS::Serverless::Function
    Properties:
      LogGroup:
        RetentionInDays: 7
        DeletionPolicy: Retain/Delete
```

Things to consider:
[ ] The [SAM documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification.html) will need to be updated
[ ] Compatibility with previous version, if the new property is not explicitly provided, the log group should not be generated
