### DISCUSSION TITLE
Allow `State` property to be set for `EventBridgeRule` event source

### DISCUSSION THREAD

**Discussion by sliedig** [aws/serverless-application-model#2667] [Ideas]
### Describe your idea/feature/enhancement

Today, when you create a EventBridge rule that has a function target, there is no way to disable the rule through the template. 

I wish the SAM Translator would allow me to explicitly ENABLE and DISABLE the rule in my SAM template

### Proposal

Add `State` to event source definition.

```
      Events:
        StatusChangedEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: UnicornEventBus
            State: DISABLED
            Pattern:
              source:
                - unicorn.contracts
              detail-type:
                - ContractStatusChanged
```

Things to consider:
[x] The [SAM documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification.html) will need to be updated

### Additional Details
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-state
