### DISCUSSION TITLE
Possible to Use SAM with multiple API Gateways in different template.yml with custom domains?

### DISCUSSION THREAD

**Discussion by EchoWhiskeyZero** [aws/serverless-application-model#2703] [Questions] [answered]
I'm new to AWS SAM and really struggling with this. I'm trying to achieve the following.

API Gateway hosting a custom domain (api.hostname.com)
Multiple microservice projects (app1, app2, app3).
Each microservice with their own lambdas (doSomething, doSomethingElse).

So it would look like this:

**Microservice Project 1 (separate template.yml)**
api.hostname.com/app1/doSomething
api.hostname.com/app1/doSomethingElse

**Microservice Project 2  (separate template.yml)**
api.hostname.com/app2/doSomething
api.hostname.com/app2/doSomethingElse

The challenge that I run into is that in the first project, I create the custom domain in the first project and everything works correctly but the second project fails because the custom API domain has already been created by the first project.

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Domain:
        DomainName: api.hostname.com
        CertificateArn: <CERTIFICATE ARN>
        Route53:
          HostedZoneId: <HOSTED ZONE ID>

![Screenshot 2022-12-05 064800](https://user-images.githubusercontent.com/97957462/205630304-840b0493-ea1d-4861-ba73-df730da4278d.jpg)

Is there anyone with a similar setup that might be able to help (or be able to share your template.yml)?

**Comment by EchoWhiskeyZero** [comment]
I think what I'm trying to do is to create my custom domain name on API Gateway outside of SAM (using CloudFormation), and then within my SAM app associate it to the pre-existing custom domain name (already defined in API Gateway) when I create an API Gateway instance using SAM. So instead of SAM creating the custom domain name, i'm trying to use SAM to associate it to the custom domain that was already defined.

From the docs, I see a lot about creating custom domains using SAM but not sure how to associate it to a custom domain that already exists: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-domainname.html#aws-resource-apigateway-domainname--examples

Any ideas how to do that?

**Reply by hoffa** [reply]
I don't have any solutions at the moment, but do https://github.com/aws/serverless-application-model/issues/349 and https://github.com/aws/serverless-application-model/issues/2175 seem relevant to what you're describing?

**Reply by EchoWhiskeyZero** [reply]
Great, thanks @hoffa. This is very similar to what I'm trying to do.

**Comment by troycampano** [comment, marked as answer]
I was able to achieve this; the key is the `AWS::ApiGateway::BasePathMapping` definition.  You can either define your custom dns name (let's say api.hostname.com) manually using the Console or CloudFormation or it's better to define the DNS in your "root" SAM Lambda project because you can automatically associate your Route 53 DNS A record to API Gateway.

But let's assume you already have `api.hostname.com` added as a custom domain in API Gateway. Set up two SAM projects, one for each of your microservices. Define an API Gateway in each:
```yml
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
```

If you want your microservice to also create the DNS record and associate it to your API Gateway, you can do this instead (but note, only do this in your top-level / root microservice...what would service the `/` path):
```yml
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Domain:
        DomainName: api.hostname.com
        CertificateArn: <YOUR CERTIFICATE ARN>
        Route53:
          HostedZoneId: <YOUR HOSTED ZONE ID>
```

Then create your lambda function and associate the Lambda's event to your API Gateway (using RestApiId):

```yml
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
```

Now here's the really important part. Create a new API Mapping associating the API Gateway to a path using the custom domain. This enables different paths to be routed to different API Gateways.

```yml
  Microservice01Mapping:
    Type: 'AWS::ApiGateway::BasePathMapping'
    Properties:
      BasePath: 'path1'
      DomainName: api.hostname.com
      RestApiId: !Ref ApiGatewayApi
      Stage: Prod
```

This will result in an API that can be called at: `https://api.hostname.com/path1`. If you'd like this to be the root of the API, just change `BasePath` from `path1` to `''`. 

You essentially want to take this same approach for your second microservice. The only real change you need to make is to change the `BasePath` in your mapping to be unique.

In the end you can have two microservice projects, each with multiple lambdas, all using a single custom DNS name which looks like this:

https://api.hostname.com/path1
https://api.hostname.com/path2
https://api.hostname.com/path3
https://api.hostname.com/path4

Where `path1` and `path2` can be separate Lambdas in the same microservice and `path3` and `path4` can be two other lambdas in your second microservice project. This enables you have to have modularity and decide how many lambdas make up each service or microservice. The only downside here (depends on your opinion) is you're creating multiple API Gateways per microservice/project, which is the "Multiple API Gateways" approach mentioned here: https://docs.aws.amazon.com/prescriptive-guidance/latest/modernization-integrating-microservices/api-gateway-pattern.html

Hope this helps.
