### DISCUSSION TITLE
AWS::Serverless::Api Models removing keys from schema

### DISCUSSION THREAD

**Discussion by ldhbsg** [aws/serverless-application-model#2708] [Questions] [answered]
Hi. I am having some issues with the models section when deploying my API. Everything is deploying, but there seems to be a check that removes certain keys in the schema. Main ones I am having issues with adding are minProperties and maxProperties. Everything deploys but that those key value pairs are missing.

I have tried the exact same schema with the AWS::ApiGateway::Model and it works fine. It seems to be an issue when the requested resources in the SAM template get converted to CloudFormation. Can someone please help? minLength and maxLength do work on strings also I tried.

Also if I am doing it in the wrong way in SAM please do let me know. Although I do not think that is the issue as min and max Length do work as they should on the api model.

This is an example of the schema tried in both AWS::Serverless::Api and AWS::ApiGateway::Model:

```
required:
  - property1
  - property2
  - property3
  - property4
type: object
minProperties: 4
maxProperties: 4
properties:
  property1:
      type: string
      enum:
        - option1
        - option2
        - option3
  property2:
      type: string
      enum:
        - a
        - b
  property3:
      type: string
      pattern: ^[a-zA-Z0-9]+$
  property4:
      required:
        - test
      type: object
      maxProperties: 1
      properties:
        test:
            type: string
            enum:
              - small
              - medium
              - large
```

I have also tried `additionalProperties` and that one is being removed too.
