### DISCUSSION TITLE
Support ScheduleV2 Events in Serverless Application Repository 🙏

### DISCUSSION THREAD

**Discussion by BourgoisMickael** [aws/serverless-application-model#2712] [Ideas]
```yml
SomeLambda:
  Type: AWS::Serverless::Function
  Properties:
    Events:
      ScheduleEvent:
        Type: ScheduleV2
```

Try to publish this to the Serverless Application Repository

```
sam publish --template-file template.yml
```

> Error: Invalid Serverless Application Specification document. Number of errors found: 1. Errors: Resource with id [SomeLambda] is invalid. Event with id [ScheduleEvent] is invalid. Resource dict has missing or invalid value for key Type. Event Type is: ScheduleV2.

🙏🙏

**Comment by hoffa** [comment]
Can you clarify what you mean? We already support [`ScheduleV2`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-schedulev2.html):

```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      Handler: foo
      InlineCode: bar
      Events:
        Schedule:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: rate(1 day)
```

Deploy:

```
sam deploy --region us-west-2 --resolve-s3 --capabilities CAPABILITY_IAM --stack-name test-2712 --template template.yaml
```

Which deploys correctly.
