### DISCUSSION TITLE
Proposal: Static Websites

### DISCUSSION THREAD

**Discussion by brettstack** [aws/serverless-application-model#2743] [Ideas]
SAM should provide a way to easily create static websites hosted on S3 and CloudFront. The purpose of this Issue is to gather requirements from the community to ensure we address primary use-cases.

Requirements:

1. Create an S3 Bucket configured with `WebsiteConfiguration`
    1. Option for enabling S3 redirect configuration for clean SPA routes
    1. Allow specifying `CodeUri` which points to the assets directory to upload to S3.
        1. Currently, Lambda Functions get uploaded to an **existing** S3 Bucket prior to SAM transformation, whereas the S3 bucket for websites will be created within the stack. One option is to upload to an existing S3 Bucket (the same one used for Lambda and APIs) and have a CloudFormation Custom Resource for copying to the Website S3 bucket.
        1. The same Custom Resource could be used for deployments (invalidate CloudFront cache)
        1. `CodeUri` should be optional to allow users to handle UI deployments external to SAM.
        1. We may decide to punt the CodeUri/Deployment story as a follow-up so that we can deliver the infrastructure story first.
1. Create a CloudFront distribution to provide caching, edge nodes, custom domain support, etc.
    1. CloudFront distribution should provide opinionated defaults, but all properties should be configurable by end user
1. Allow for specifying a custom domain name
    1. Route53 configuration
    1. ACM Certificate (optionally pass in your own)
    1. Support for redirecting non-www to www

Please describe your use case and let us know how SAM could make it easier for you to create websites.

**Comment by Nr18** [comment]
This would be very helpful currently i have already done this by using CodePipeline, CodeBuild and CFN resources with CustomResources as followed:

- CodeBuild packages the web application and is used as `OutputArtifacts`
- The template deploys with a `SourceBucketName` & `SourceObjectKey` parameter that points to the `OutputArtifact`
- The templates create a bunch of resources like S3, CloudFront & Cognito stuff
- Custom resource accept variable like: `IdentityPoolId`, `UserPoolId`, `UserPoolWebClientId`, `AppSyncEndpoint`, `CloudFrontDistributionId`
- Custom resource will
  - Download the and Unzip
  - Merge/override configuration options based on the passed variable
  - Compare the "local" files with the one on S3, if there are files on S3 that are not in the local copy mark it as "toBeRemoved"
  - Upload all files except the index.html
  - Upload index.html (index.html references to specific versions are uploaded in the previous step)
  - Invalidate core files: (index.html, settings.js, etc)
  - Remove the "toBeRemoved" files 

These steps are used by web applications that are build for Aurelia or Angular they have a build system that point to a specific version in the index.html file: `/app.[SOME_HASH].bundle.js`.

**Comment by brysontyrrell** [comment]
Ideally, for me, I'd like SAM to handle the bucket content and not any of the configuration. This has use cases past just static web content.

Something fairly simple such as:
```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  WebBucket:
    Type: AWS::S3:Bucket

  WebBucketContent:
    Type: AWS::Serverless::BucketContent
    Properties:
      BucketName: !Ref WebBucket
      ContentUri: ./path/to/content/dir
      SyncOptions: # Optional: Default behavior is to sync the Bucket's content with the artifact exactly
        - IgnoreExisting # Do not overwrite existing files in the Bucket
        - Preserve # Do not delete files in the Bucket not in the artifact
```

During the `package` process the `ContentUri` location would be zipped up and uploaded to the S3 Bucket SAM is sending artifacts to and the value replaced with the S3 URI - identically to how Lambda packages are handled.

Then during deployment the custom CloudFormation resource can pull in that content artifact and perform the appropriate sync operation with the target bucket.
