### DISCUSSION TITLE
RFC: Define multiple sources and destinations on a connector

### DISCUSSION THREAD

**Discussion by ccaum** [aws/serverless-application-model#2761] [Ideas]
<h2>Status: Closed</h2>
We will move forward with part of this RFC. Soon, you will be able to define multiple destinations in a single connector with a single set of permissions.

<h2>Problem</h2>SAM connectors currently need to be defined once for each relationship in your stack. This promotes verbosity, bloated SAM templates, and templates that are difficult to quickly understand and maintain. If you were to draw connectors as arrows on a whiteboard signifying how data and events flow between two resources, the only type of relationship that can be expressed is a one-to-one mapping.<br>

![Screen Shot 2022-12-20 at 11 16 20 AM](https://user-images.githubusercontent.com/467617/209030863-7b4d7c6f-72e8-43e2-878b-fdb0372ea5fe.png)
![Screen Shot 2022-12-20 at 11 16 20 AM](https://user-images.githubusercontent.com/467617/209030863-7b4d7c6f-72e8-43e2-878b-fdb0372ea5fe.png)

For example, the template below demonstrates two connections between a single Lambda and two SQS queues. The connections all require identical Read/Write permissions and all have the same source resource. The connectors take up the majority of the template’s lines of code. <br><br><pre>Resources:<br>  StockCheckerFunction:<br>    Type: AWS::Serverless::Function<br>    Properties:<br>      CodeUri: functions/stock_checker/<br>      Handler: app.lambda_handler<br>      Runtime: python3.9<br>      Architectures:<br>        - x86_64<br>        <br>  StockSellQueue:<br>    Type: AWS::SQS::Queue<br>  StockBuyQueue:<br>    Type: AWS::SQS::Queue<br>    <br>  FunctionToSellQueueConnector:<br>    Type: AWS::Serverless::Connector<br>    Properties:<br>      Source:<br>        Id: StockCheckerFunction<br>       Destination:<br>        Id: StockSellQueue<br>      Permissions:<br>        - Write<br>  FunctionToBuyQueueConnector:<br>    Type: AWS::Serverless::Connector<br>    Properties:<br>      Source:<br>        Id: StockCheckerFunction<br>       Destination:<br>        Id: StockBuyQueue<br>      Permissions:<br>        - Write</pre><br>Similarly, your application may require multiple SAM functions reading and writing to a single DynamoDB. Again, the connectors make up the majority of the template’s lines of code.<br><br><pre>Resources:<br>  StockBuyFunction:<br>    Type: AWS::Serverless::Function<br>    Properties:<br>      CodeUri: functions/stock_buyer/<br>      Handler: app.lambda_handler<br>      Runtime: python3.9<br>      Architectures:<br>        - x86_64<br>  StockSellFunction:<br>    Type: AWS::Serverless::Function<br>    Properties:<br>      CodeUri: functions/stock_seller/<br>      Handler: app.lambda_handler<br>      Runtime: python3.9<br>      Architectures:<br>        - x86_64<br>        <br>  TransactionTable:<br>    Type: AWS::Serverless::SimpleTable<br>    Properties:<br>      PrimaryKey:<br>        Name: Id<br>        Type: String<br>      ProvisionedThroughput:<br>        ReadCapacityUnits: 1<br>        WriteCapacityUnits: 1<br>        <br>  BuyFunctionToTableConnector:<br>    Type: AWS::Serverless::Connector<br>    Properties:<br>      Source:<br>        Id: StockBuyFunction<br>      Destination:<br>        Id: TransactionTable<br>      Permissions:<br>        - Write<br>  FunctionToBuyQueueConnector:<br>    Type: AWS::Serverless::Connector<br>    Properties:<br>      Source:<br>        Id: StockSellFunction<br>      Destination:<br>        Id: TransactionTable <br>      Permissions:<br>        - Write</pre><br><h2>Proposed Solution</h2>Allow connector resources to define either multiple sources for a single destination and single set of Read/Write permissions, or define multiple destinations for a single source and single set of Read/Write permissions. Conceptually, relationships where a one-to-many or many-to-one relationship exists should be expressed as a single connector.<br><br>

| <h3>One-to-many relationship</h3> | <h3>Many-to-one relationship</h3> |
| --- | --- |
|  ![Screen Shot 2022-12-20 at 11 11 28 AM](https://user-images.githubusercontent.com/467617/209030871-dd08695c-a36d-48da-8455-16c6fd95b60b.png) |  ![Screen Shot 2022-12-20 at 11 11 20 AM](https://user-images.githubusercontent.com/467617/209030868-f16a58c8-2cb1-413d-88b7-ef8df6260a77.png) |

To use the first example in the Problem section above, the proposed connector definition would look like this:<br><pre>Resources:<br>  StockCheckerFunction:<br>    Type: AWS::Serverless::Function<br>    Properties:<br>      CodeUri: functions/stock_checker/<br>      Handler: app.lambda_handler<br>      Runtime: python3.9<br>      Architectures:<br>        - x86_64<br>        <br>  StockSellQueue:<br>    Type: AWS::SQS::Queue<br>  StockBuyQueue:<br>    Type: AWS::SQS::Queue<br>    <br>  FunctionToQueueConnector:<br>    Type: AWS::Serverless::Connector<br>    Properties:<br>      Source:<br>        Id: StockCheckerFunction<br>      Destination:<br>        - Id: StockSellQueue<br>        - Id: StockBuyQueue<br>      Permissions:<br>        - Write</pre>For the second example in the Problem section above, the proposed connector definition would look like this:<br><pre>Resources:<br>  StockBuyFunction:<br>    Type: AWS::Serverless::Function<br>    Properties:<br>      CodeUri: functions/stock_buyer/<br>      Handler: app.lambda_handler<br>      Runtime: python3.9<br>      Architectures:<br>        - x86_64<br>  StockSellFunction:<br>    Type: AWS::Serverless::Function<br>    Properties:<br>      CodeUri: functions/stock_seller/<br>      Handler: app.lambda_handler<br>      Runtime: python3.9<br>      Architectures:<br>        - x86_64<br>        <br>  TransactionTable:<br>    Type: AWS::Serverless::SimpleTable<br>    Properties:<br>      PrimaryKey:<br>        Name: Id<br>        Type: String<br>      ProvisionedThroughput:<br>        ReadCapacityUnits: 1<br>        WriteCapacityUnits: 1<br>        <br>  FunctionToTableConnector:<br>    Type: AWS::Serverless::Connector<br>    Properties:<br>      Source:<br>        - Id: StockBuyFunction<br>        - Id: StockSellFunction<br>      Destination:<br>        Id: TransactionTable<br>      Permissions:<br>        - Write</pre><br><h3>Pros/Cons</h3>

Pros | Cons
-- | --
| 1) Simpler to read and write <br><br> 2) Easier to quickly understand  <br><br> 3) Expanding a one-to-many or many-to-one relationship is easy  |  1) If an additional resource needs to be added to a one-to-many or many-to-one relationship but requires a different set of permissions, it must be defined as a new connector. This makes sense as it is a new type of relationship. <br><br> 2) If an existing resource in a one-to-many or many-to-one relationship needs to be updated to require different permissions than the other resources in the relationship, it must be refactored out of the existing connector and into a new connector. Again, this makes sense because it is a new type of relationship. |

<h2>FAQ</h2><b>Why not allow both multiple sources and multiple destinations simultaneously?</b><br>It promotes misuse of connectors. SAM connectors are intended to simplify architecting an application by describing how resources interact. Permissions are automatically generated from the relationships defined by connectors. If the defined interactions become too obscure, it defeats the purpose of connectors. If three sources interact with multiple destinations, it is unclear if each possible relationship is actually needed for the application to function properly. In short, allowing both multiple sources and multiple destinations to be defined in the same connector promotes authoring code that is difficult to understand and maintain over time.<br><br><b>Can different sets of permissions be applied to different sources/destinations in the same connector?</b><br>No. Ideally, connectors are used to easily model how resources in your application interact. Each connector models one type of interaction. By limiting each connector to defining a single type of interaction, SAM code is easier to read and understand how resources interact with each other.<br>

**Comment by CGarces** [comment]
Why not use and aproach like policy templates?

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html

For me the syntaxes is more simpler, the code is more compact and easy to follow. Also the connector is declared in the policy section, made more sense (for me) than declare the policy in another part of the template.


```
Resources:
  StockCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/stock_checker/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
    Policies:
       - serverlessConnectorPolicy:
         - Destination:
          - Id: StockSellQueue
          - Id: StockBuyQueue
        - Permissions:
           - Write
   
  StockSellQueue:
    Type: AWS::SQS::Queue
  StockBuyQueue:
    Type: AWS::SQS::Queue

```

**Reply by ccaum** [reply]
Thanks @CGarces. Are you commenting on where the connector definition should live or on how multiple sources and destinations are defined in a single connector? In a future release we will be allowing you to define a connector as part of a source or destination resource. This RFC is just focused on how multiple sources or destinations should be defined in a single connector.

**Comment by hoffa** [comment]
I like how succinct the syntax is, but unsure how beneficial it is if we merge https://github.com/aws/serverless-application-model/pull/2772.

If this RFC gets implemented and https://github.com/aws/serverless-application-model/pull/2772 gets merged, there'll be essentially 4 ways of specifying the same connections:

1. Multiple `AWS::Serverless::Connector`s referencing same `Source`:

    ```yaml
    Bar:
      Type: AWS::Serverless::Connector
      Properties:
        Source:
          Id: Foo
        Destination:
          Id: Bar
        Permissions:
          - Write
    
    Egg:
      Type: AWS::Serverless::Connector
      Properties:
        Source:
          Id: Foo
        Destination:
          Id: Egg
        Permissions:
          - Write
    ```

1. Multiple `Destination`s on the same `AWS::Serverless::Connector` (i.e. this RFC):

    ```yaml
    BarAndEgg:
      Type: AWS::Serverless::Connector
      Properties:
        Source:
          Id: Foo
        Destination:
          - Id: Bar
          - Id: Egg
        Permissions:
          - Write
    ```

1. Multiple connectors attached to source resource (i.e. https://github.com/aws/serverless-application-model/pull/2772):

    ```yaml
    Foo:
      Type: ...
      Properties:
        ...
      Connectors:
        Bar:
          Destination:
            Id: Bar
          Permissions:
            - Write
        Egg:
          Destination:
            Id: Egg
          Permissions:
            - Write
    ```

1. Multiple `Destination`s on the same connector attached to source resource (i.e. this RFC + https://github.com/aws/serverless-application-model/pull/2772):

    ```yaml
    Foo:
      Type: ...
      Properties:
        ...
      Connectors:
        BarAndEgg:
          Destination:
            - Id: Bar
            - Id: Egg
          Permissions:
            - Write
    ```

One concern is the potential added cognitive load in having to understand and choose one of the alternatives above.
Another is that this RFC doesn't adapt well to changing templates.

For example, assume the following connector:

```yaml
Foo:
  Type: AWS::Serverless::Connector
  Properties:
    Source:
      - Id: Foo
    Destination:
      - Id: Bar
      - Id: Egg
    Permissions:
      - Read
```

If we then want to also give `Write` permissions to `Egg`, we'd have to either create a separate connector that gives `Foo` `Write` permissions to `Egg` (reducing clarity), or move `Egg` from `Foo` into its separate connector with `Read`/`Write` permissions (requiring multiple lines of diffs).

If we only support https://github.com/aws/serverless-application-model/pull/2772, it requires writing more lines, but potentially improves clarity and consistency (and diffs in changes are purely additive).

**Comment by ljacobsson** [comment]
Starting a bit off topic-

One thing I don't like with both PolicyTemplates and Connectors is that developers have to rely on documentation to understand what IAM policy it generates, but I can see beyond that and appreciate simplifying IAM anyway :-)

However - the `Write` permission includes `Delete`, which to me is problematic. Writing data is not the same as deleting it, and developers should be encouraged to follow principle of least principle.

I suggest introducting a new `Permissions` option, namely `Delete`. This will make refactoring even worse with the suggested solution as there will be too many permutations of connections to choose from.

Could the following make that a bit simpler?

```
  MyConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        - Id: Foo
      Destination:
        Read:
          - Id: Bar
        Write:
          - Id: Bar
          - Id: Egg
        Delete:
          - Id: Bar
```

In this example, `Foo` is allowed to read and delete from `Bar`, but only write to `Egg`
