### DISCUSSION TITLE
Reference external dynamodb stream in SAM Template

### DISCUSSION THREAD

**Discussion by ash1425** [aws/serverless-application-model#2932] [Questions] [answered]
We have existing dynamodb stream (created historically using terraform) which we would like use for invoking one of our lambda. Is there a way to refer external resources in SAM template ?

**Comment by aahung** [comment, marked as answer]
Does hardcoding the stream ARN work for you? (snippet from [our doc](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-dynamodb.html#sam-function-dynamodb-stream))

```
Events:
  DDBEvent:
    Type: DynamoDB
    Properties:
      Stream: arn:aws:dynamodb:us-east-1:123456789012:table/TestTable/stream/2016-08-11T21:21:33.291
      StartingPosition: TRIM_HORIZON
      BatchSize: 10
      Enabled: false
```
