### DISCUSSION TITLE
Bug: TITLE

### DISCUSSION THREAD

**Discussion by josedugu** [aws/serverless-application-model#2957] [Questions]
Hi there I am having an issue when I try to create a lambda with function URL, this is the code that I found on aws docs but is not working

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: Just test
Transform: AWS::Serverless-2016-10-31
Resources:
wompiWebHook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/wompi
      Handler: index.handler
      Runtime: nodejs18.x
      AutoPublishAlias: live
      FunctionUrlConfig:
        AuthType: NONE
```
The issue is "Property FunctionUrlConfig is not allowed.yaml-schema", as my undertanding it means that FunctionUrlConfig is not included on sam.schema.json

Any ideas how to fix that, help me please?

windows  11
Node js 18
sam version 1.172.0
oregon

{
  "version": "1.72.0",
  "system": {
    "python": "3.8.8",
    "os": "Windows-10-10.0.22621-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}
