### DISCUSSION TITLE
Feature request: SAM Connector Suggestions

### DISCUSSION THREAD

**Discussion by allanchua101** [aws/serverless-application-model#2996] [Ideas]
### Describe your idea/feature/enhancement

Seeing multi-destination connector update was really awesome! However, there are a few more opportunities to improve this feature IMHO.

1. Support for services is limited
2. We could still reduce the number of lines required to define connectors in batch.

### Proposal

1. Add support for the following services:
   - Secrets manager (Highly used in production apps)
   - SSM parameter (Highly used in production apps)
   - SES
   - Rekognition
   - KMS
   - CloudWatch
   - CodeCommit
   - CodePipeline
   - CodeBuild
   - CodeDeploy
   - Firehose
2. We could reduce number of lines if we can get hold of the following syntax:

```yaml
  GetStripePrices:
    Type: AWS::Serverless::Function
    WriteConnectors:
      - Id: SampleTableA
      - Id: SampleTableB
      - Arn: arn:aws:secretsmanager:ap-southeast-1::secret:sample-credential-Lw92LOwe
    ReadConnectors:
      - Id: SampleTableC
      - Id: SampleTableB
      - Arn: arn:aws:secretsmanager:ap-southeast-1::secret:sample-credential-Lw92LOwe
```

Cheers guys!

**Comment by jfuss** [comment]
@allanchua101 Thanks for the feature request. Since this relates to the spec over the CLI, I will transfer this to the correct repo.

**Comment by ccaum** [comment]
Thanks, @allanchua101. 

Regarding simplifying connector syntax, I hear you that connectors can be verbose to write, but we think it's best to be explicit about the list of permissions assigned to each connector via a `Permissions` property. This makes it easier to mix and match permissions as well as makes it simpler for us to add new permissions in the future without disrupting existing naming conventions.

Thank you for the list of services you'd like to see supported by connectors. I'd like to learn more about how you'd like to use them with SSM and Secrets Manager specifically. Would it look something like the following?

```
Resources:
  AppSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      ... {omitted for brevity} ...
  Function1:
    Type: AWS::Serverless::Function
    Connectors:
      FunctionReadSecret:
        Permissions:
          - Read
        Destination:
          - AppSecret
    Properties:
      ... {omitted for brevity} ...
  Function2:
    Type: AWS::Serverless::Function
    Connectors:
      FunctionReadSecret:
        Permissions:
          - Read
        Destination:
          - AppSecret
    Properties:
      ... {omitted for brevity} ...
```

In the above example, you would expect the function to automatically be able to read the `AppSecret` secret? Would you ever want write permissions? If so, why?
