### DISCUSSION TITLE
Generated `PolicyDocument` doesn't include `Version`.

### DISCUSSION THREAD

**Discussion by garretwilson** [aws/serverless-application-model#3269] [Ideas]
Let's say I indicate a policy for my `AWS::Serverless::Function` like this:

```yaml
      …
      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName: FooBus
```

SAM will generate a policy that looks like this:

```json
        …
        "Policies": [
          {
            "PolicyName": "FooFunctionRolePolicy0",
            "PolicyDocument": {
              "Statement": [
                {
                  "Action": "events:PutEvents",
                  …
```

Note that no `Version` is specified in the `PolicyDocument`. According to the [`Version` documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_version.html) for IAM JSON policy elements:

> … you should always include a `Version` element and set it to `2012-10-17` …

Thus the generated policy isn't following AWS' own recommendations.
