### DISCUSSION TITLE
Feature request: Add TimeoutInMillis Property to API Event Source

### DISCUSSION THREAD

**Discussion by AaronCowan** [aws/serverless-application-model#3287] [Ideas]
For an API, I would like to be able to set the integration timeout for one or all resource integration requests.

Currently, the HTTP API event source allows setting [TimeoutInMillis](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-httpapi.html), but you cannot do this for the API event source.

Current Example

```
SomeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/code.handler
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /hello_world
            Method: GET
            TimeoutInMillis: 5000
```

Desired Functionality
```
# At the function level
SomeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/code.handler
      Events:
        Api:
          Type: Api # Api only
          Properties:
            Path: /hello_world
            Method: GET
            TimeoutInMillis: 5000 # Currently not supported

# At the global level
Globals:
  Api:
    Integrations:
      TimeoutInMillis: 5000
```
