### DISCUSSION TITLE
Feature request: Support synchronous StepFunctions executions from API Gateway

### DISCUSSION THREAD

**Discussion by ljacobsson** [aws/serverless-application-model#3305] [Ideas]
### Describe your idea/feature/enhancement
I feel that there's a lot of improvements around the DX when creating an API Gateway -> StepFunctions Express sync integration. When working with a Lambda the DX is great, but with StepFunctions we have to dive in to writing OpenAPI spec to map the state machine output to the response. 

### Proposal
I wish the SAM translator could do something like this
```
MyExpressStateMachine:
  Type: AWS::Serverless::StateMachine
  Properties:
     ...
     Events:
       ApiEvent:
         Type: Api:
           Properties:
             Path: /{id}
             Method: get
             InvocationType: synchronous
```

The output from the statemachine should be mapped to the response body from API Gateway.
