### DISCUSSION TITLE
AWS SAM method response

### DISCUSSION THREAD

**Discussion by royassis** [aws/serverless-application-model#3388] [Questions] [answered]
Hey there

Does SAM templates support method responses at this time?

![image](https://github.com/aws/serverless-application-model/assets/34189329/7c882e5a-7fe8-4f59-81ec-fb7291120c31)

**Comment by GavinZZ** [comment]
~Hi there, thanks for reaching out and creating a discussion post. `AWS::Serverless::Api` currently do not explicitly support method response. However, a workaround is that you can define CloudFormation resource `AWS::ApiGateway::Method`. Here is an example provided~:
```
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: MyNewStageName

  MyApiGatewayRootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: MOCK
      ResourceId: !GetAtt MyApi.RootResourceId
      RestApiId: !Ref MyApi
      MethodResponses: <your-desired-setup>
```

~This would allow you to use method responses along with `AWS::Serverless::Api` resource.~
