### DISCUSSION TITLE
Support for AWS::Synthetics::Canary deploy

### DISCUSSION THREAD

**Discussion by daaru00** [aws/serverless-application-model#3537] [Ideas]
### Describe your idea/feature/enhancement

I wish SAM CLI would support [AWS::Synthetics::Canary](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html) deployments as for Lambda Functions. 

If I understand well [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-synthetics-canary-code.html#cfn-synthetics-canary-code-script) the code need to be uploaded to an S3 bucket as zip artifact or included inline into **Script** property like:
```yaml
MySampleCanary:
  Type: "AWS::Synthetics::Canary"
  Properties:
    Name: samplecanary
    ExecutionRoleArn: "arn:aws:iam::123456789012:role/my-lambda-execution-role-to-run-canary"
    Code:
      Handler: pageLoadBlueprint.handler
      Script: "<here the code>" # <------------------- here the inline script code
    ArtifactS3Location: s3://my-results-bucket
    RuntimeVersion: syn-1.0
    Schedule:
      Expression: "rate(1 minute)"
      DurationInSeconds: 3600
```
it is very inconvenient to write the script inline inside the template (eslint not working, differences through git cannot be compared comfortably, forces to copy, escape, and paste code from a separate .js script..).

### Proposal

It would be great to have a configuration similar to this one:
```yaml
MySampleCanary::
  Type: AWS::Serverless::Canary
  Properties:
    Name: samplecanary
    RuntimeVersion: syn-1.0
    CodeUri: src/ # <-------------------------------- here the script directory
    Handler: pageLoadBlueprint.handler
    ArtifactS3Location: s3://my-results-bucket
    Schedule:
      Expression: "rate(1 minute)"
      DurationInSeconds: 3600
```
in order to be able to create script inside local directory `./src` (for example) and then automatically create/update Canaries source code script.

### Additional Details

If I understand well the Canary code is internally loaded as a Lambda Layer, maybe it would be easier to take inspiration from `AWS::Serverless::LayerVersion` instead of `AWS::Serverless::Function`.
