### DISCUSSION TITLE
Defining `BinaryMediaTypes` globally is enabling `base64` for all api end-points and overriding it from local is not reflecting possible.

### DISCUSSION THREAD

**Discussion by JayaKrishnaNamburu** [aws/serverless-application-model#3558] [Questions] [answered]
Hello,

I have 2 end-points, once is `/upload` and another is `/save`. 
For `/upload`, i need binary encoded enabled. As, i am trying to allow a file upload by connecting a lambda function.

But at the same time, the `BinaryMediaTypes` is applying for the `/save` end-point too. Which just needs to be `application/json`. I have searched everywhere for the result but turns out the settings apply globally and i need have a different templates. But then then they run at different ports. Is there any where that the settings can be overwritten ?

Here is a example of my sam template file.
```yml
Globals:
    Api:
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
        AllowMethods: "'*'"
      BinaryMediaTypes:
        - '*/*'

Environment:
  Variables:
    ENDPOINT_URL: null

Resources:
  savetos32:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Description: ''
      MemorySize: 128
      Timeout: 3
      Handler: upload-images/index.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - arn:aws:logs:*:*:*
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /upload
            Method: POST


      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto

  savetodocuments:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Description: ''
      MemorySize: 128
      Timeout: 3
      Handler: upload-documents/index.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - arn:aws:logs:*:*:*
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /save
            Method: POST
            BinaryMediaTypes: []
            Integration:
              Type: lambda-proxy
              PassthroughBehavior: WHEN_NO_MATCH
              IntegrationResponses:
                - StatusCode: 200
                  ResponseTemplates:
                    application/json: '{"statusCode": 200}'
        Api2:
          Type: Api
          Properties:
            Path: /save
            Method: OPTIONS
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto

```

**Comment by GavinZZ** [comment, marked as answer]
Reason of this is because if the property defined in globals section has type `array`, we actually concatenate the array defined in globals with the local property. Unfortunately there's no override on this behaviour. What you could do is not define `BinaryMediaTypes` in globals.

**Reply by JayaKrishnaNamburu** [reply]
Hey thanks fro the response, but i removed the `BinaryMediaTypes` from the globals. And moved it to just the `/upload` end-point. But it still doesn't seem to be applied. 

```yml
Globals:
    Api:
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
        AllowMethods: "'*'"

Environment:
  Variables:
    ENDPOINT_URL: null

Resources:
  savetos32:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Handler: upload-images/index.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - arn:aws:logs:*:*:*
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            BinaryMediaTypes: '*/*'
            Path: /upload
            Method: POST


      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto

  savetodocuments:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Handler: upload-documents/index.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - arn:aws:logs:*:*:*
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /save
            Method: POST
            Integration:
              Type: lambda-proxy
              PassthroughBehavior: WHEN_NO_MATCH
              IntegrationResponses:
                - StatusCode: 200
                  ResponseTemplates:
                    application/json: '{"statusCode": 200}'
        Api2:
          Type: Api
          Properties:
            Path: /save
            Method: OPTIONS
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
```

I still get the following errors. Since the request is not being accepted as binary ?
```
2024-03-06 17:48:59,293 | UnicodeDecodeError while processing HTTP request: 'utf-8' codec
can't decode byte 0x89 in position 137: invalid start byte
2024-03-06 17:48:59,295 | Lambda execution failed ()
2024-03-06 17:48:59 127.0.0.1 - - [06/Mar/2024 17:48:59] "POST /upload HTTP/1.1" 502 -
```

**Reply by JayaKrishnaNamburu** [reply]
If the behaviour can't be applied. Should i have multiple `tempalte.yml` files for api gateway's and try to start at same port which i think is not the best approach.

**Reply by GavinZZ** [reply]
### Template issues
The template you provided seems to be an invalid template. I noticed a couple of issues which should results in `sam build` failure. I'm not sure how you bypass the issue and come to deployment step.

1. API event source doesn't support defining `BinaryMediaTypes` as a property, see [documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-api.html).
```
Events:
        Api1:
          Type: Api
          Properties:
            BinaryMediaTypes: '*/*'
            Path: /upload
            Method: POST
```
2.  You cannot define `Integration` as a property under API event source. 
3. `BinaryMediaTypes` is a property that takes in a list value as input not a string.


### Back to your question
Unfortunately, the property `BinaryMediaTypes` is configured at the API Gateway level, not endpoint level. This seems that you cannot have an API Gateway with different binary media types set for each endpoint. However, what you can do is to define two API Gateway, one for each media type.

Here is an example 
```
Globals:
    Api:
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
        AllowMethods: "'*'"

Resources:
  ApiWithBinaryMediaTypesSet:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      BinaryMediaTypes: 
        - '*/*'

  ApiWithoutBinaryMediaTypes:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

  savetos32:
    Type: AWS::Serverless::Function
    Properties:
      ...
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /upload
            Method: POST
            RestApiId: !Ref ApiWithBinaryMediaTypesSet

  savetodocuments:
    Type: AWS::Serverless::Function
    Properties:
      ...
      Events:
        Api2:
          Type: Api
          Properties:
            Path: /save
            Method: POST
            RestApiId: !Ref ApiWithoutBinaryMediaTypes
```
