### DISCUSSION TITLE
Bug: Lambda function (with alias) doesn't create a new version after its layer is updated, even if `AutoPublishAliasAllProperties` is set to `true`

### DISCUSSION THREAD

**Discussion by zhanzhenzhen** [aws/serverless-application-model#3612] [Questions] [answered]
### Description:

If we use alias for a lambda function (for provisioned concurrency, etc), it won't create a new version after its layer is updated, even if `AutoPublishAliasAllProperties` is set to `true`. So the alias still points to the old layer version. But the `$LATEST` version is synced with the new layer version. Am I missing something, or is it a bug?

### Steps to reproduce:

1. Create those 4 files, then `sam build`, then `sam deploy`. Visit the output URL.
2. After initial deployment, replace the string `"old layer"` with `"new layer"` in the `layer/layer.mjs` file. Build and deploy it again. Visit the output URL.

`template.yaml`:

```yaml
AWSTemplateFormatVersion: "2010-09-09"

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Runtime: nodejs20.x
    Architectures:
      - arm64
    MemorySize: 128
    Timeout: 8

Resources:
  Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${AWS::StackName}-Layer
      CompatibleArchitectures:
        - arm64
      CompatibleRuntimes:
        - nodejs20.x
      ContentUri: layer
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: nodejs20.x
      BuildArchitecture: arm64

  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: Main
      AutoPublishAliasAllProperties: true
      CodeUri: lambda
      Handler: app.handler
      Layers:
        - !Ref Layer
      Events:
        Api:
          Type: Api
          Properties:
            Path: /app
            Method: GET

Outputs:
  URL:
    Description: "Test URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/app"
```

`lambda/app.mjs`:

```js
import layer from "/opt/nodejs/layer.mjs";

export const handler = async (event, context) => {
    const response = {
        statusCode: 200,
        body: JSON.stringify({fnVersion: process.env.AWS_LAMBDA_FUNCTION_VERSION, layer: layer})
    };
    return response;
};
```

`layer/layer.mjs`:

```js
export default "old layer";
```

`samconfig.toml`:

```toml
version = 0.1

[default]
[default.global.parameters]
stack_name = "TestApp"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "TestApp"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
```

### Observed result:

In step 1, the result is: `{"fnVersion":"1","layer":"old layer"}`.

In step 2, the result remains the same.

### Expected result:

I expect the result in step 2 to be `{"fnVersion":"2","layer":"new layer"}`.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux-6.1.90-99.173.amzn2023.x86_64-x86_64-with-glibc2.34
3. `sam --version`: 1.114.0
4. AWS region: us-east-1

**Comment by hnnasit** [comment]
Hi @zhanzhenzhen, thanks for reporting the issue. After chatting with the SAM team, this seems like a known issue. I am transferring the ticket to their repo for the SAM team to provide more context and any workaround.

**Comment by paulhcsun** [comment, marked as answer]
Hi @zhanzhenzhen, 
As @hnnasit mentioned we are currently aware of this issue. Here is some context and a workaround:

### Context + Root cause
The reason the AutoPublishAliasAllProperties property is not picking up the changes to the Layers property is because of the specific ordering that we have when transforming the resources listed in a SAM template. The [current implementation](https://github.com/aws/serverless-application-model/blob/308d9ce7c310379576fd7eeaeb66ba92776fc1cc/samtranslator/translator/translator.py#L250-L294) will translate all `AWS::Serverless::Functions` before translating the `AWS::Serverless::LayerVersion`. Because the `Serverless::Function` is translated first, the `!Ref` to the `Serverless::LayerVersion` will not have changed yet - that changes after we transform the `LayerVersion` but by then it won't go back to transform the `Serverless::Function` a second time.

Because SAM doesn't resolve intrinsics, we wouldn't necessarily consider this a bug, but we can definitely understand that it is not a great experience for our customers. 

To address this issue with a fix, we would have to change the order in which resources are transformed which could result in unintended consequences. We have broken existing templates in the past so we try to tread carefully when making changes like this where it is difficult to estimate the full impact it would have on other customers.

### Workaround
As a workaround, you can pass a combined `shasum` of the `.zip` used for the LayerVersion's `ContentUri` + the Lambda function code to the `AutoPublishCodeSha256` property. This means that whenever the lambda or the referenced layer is changed then a new lambda version will be created.

```
shasum ~/.../layer.zip
26babb64f2c18e1a845cbdb684e6ef2f99319773  /.../Downloads/layer.zip
```

The combined shasum can be passed in as a global paramater:
```
Parameters:
  AutoDeployVersion:
    Type: String

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      ...
      AutoPublishAlias: foo
      AutoPublishAliasAllProperties: True
      AutoPublishCodeSha256: !Ref AutoDeployVersion
      Layers:
        - !Ref TestEnvLayer
 ```
and this can be set with the `--parameters AutoDeployVersion="sha value"` flag through the CLI deployment command you are using.

Please give this a try and let me know if you have any other questions!
