### ISSUE TITLE
Ref to API Gateway RestApi from AWS::Serverless::Function Api Event Source

### ISSUE THREAD

**Issue by balldarrens** [aws/serverless-application-model#104]
Update - I have figured this out.  Using ${ServerlessRestApi}, of which is not documented in a clear way, this is possible to build the URL.  This is in an example provide in the examples folder.  Just was not clear, or I was just foggy when reading that.

`Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/"`

I am wanting to output (Outputs) the underlying API Gateway RestApi from a AWS::Serverless::Function that is allowing this to be auto-generated.  I have multiple AWS::Serverless::Function's in play, but as a short example:

```
Resources:
  Create:
    Type: AWS::Serverless::Function
    Properties:
      Handler: meta/create.create
      CodeUri: app/
      Runtime: nodejs4.3
      Policies: AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          DYNAMODB_TABLE_ENV: !Sub '${ServiceName}-${Stage}'
      Events:
        ApiEventSource:
          Type: Api
          Properties:
            Path: /
            Method: POST

  Delete:
    Type: AWS::Serverless::Function
    Properties:
      Handler: meta/delete.delete
      CodeUri: app/
      Runtime: nodejs4.3
      Policies: AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          DYNAMODB_TABLE_ENV: !Sub '${ServiceName}-${Stage}'
      Events:
        ApiEventSource:
          Type: Api
          Properties:
            Path: /meta/{metaId}
            Method: DELETE
```

How is one to access the API rest api, for example to output the url?  Is there an example of this somewhere?

**Comment by syang** [comment]
@balldarrens Thanks for sharing, this is exactly what I have been searching for. I really wanted to achieve the following
- have a single 'source of truth' for my Api-Gateway + Lambda stack (see this issue https://github.com/awslabs/serverless-application-model/issues/140) -- this is about long-term correctness for my solution
- hopefully, not necessarily to define a verbose Swagger file -- this is about the long-term readability maintainability easiness.

BTW, in your above solution, if I want to add a custom authorizer without doing verbose Swagger definition?

**Comment by wjordan** [comment]
For my own future reference (when I find this issue again via Google in the future), here are the documentation references (I agree it's not laid out in a clear way):

- The hard-coded `ServerlessRestApi` logical ID of the 'Implicit API' resource is documented in the 'internal' document ["CloudFormation Resources Generated by SAM"](https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api).
- The hard-coded API Gateway URL format `https://[api-id].execute-api.[region].amazonaws.com/[stage]` is documented at the top of ["Set up Custom Domain Name for an API in API Gateway"](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html) in the API Gateway Developer Guide.

**Comment by smarks** [comment]
It may be documented as described above, but not well enough to be functional. 
this issue should be reopened.

**Comment by jlhood** [comment]
Reopening to address improving documentation.

**Comment by maletor** [comment]
I think it's more than documentation. You get a circular reference trying to input the API URL into an environment variable.

**Comment by keetonian** [comment]
@maletor I don't think you need to input the API URL into an environment variable, you get the API ID and anything else needed to create the URL from the event object.

Here's a sample API Event Object from the Lambda documentation: https://docs.aws.amazon.com/lambda/latest/dg/with-on-demand-https.html

**Comment by awsjeffg** [comment]
@balldarrens @maletor did the documentation mentioned by @keetonian help with this issue? We are closing this issue due to inactivity, but please re-open of you are still having issues with this feature, in particular with the documentation.

**Comment by vilunet** [comment]
I have a similar issue, I got SAM to generate the API and wanting to call one of the Lambda functions to call into the API (in SteteMachine). How Can the ServerlessRestApi be refereed in AWS::Serverless::Function code? Still, the documentation is not clear

**Comment by specious** [comment]
If you define one or more functions that have an API event source that triggers that function and do not also define a gateway API that you then link to these functions by specifying `RestApiId: !Ref <api-name>`, then sam-cli will create what is called an "implicit" API and it will name it `ServerlessRestApi`. That API will have one stage which will be named `Prod`.

This means that a template like this one will actually deploy a function behind an automatically created API gateway:

```yml
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda function behind an API gateway

Resources:
  MyLambdaFunction: # you define this
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: lambda.zip
      PackageType: Zip
      Description: This lambda does something useful
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        RootGet: # you define this
          Type: Api
          Properties:
            Path: /
            Method: GET

Outputs:
  API:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApi.Stage}/"
``` 

Given so much confusing information, it took me some time to figure all this out.
