### ISSUE TITLE
Unable to declare lambda with S3ReadPolicy on S3 bucket that it is set as a trigger 

### ISSUE THREAD

**Issue by whimzyLive** [aws/serverless-application-model#1109]
**Description:**
When defining `AWS::Serverless::Function` as a trigger of `AWS::S3::Bucket`, currently it is impossible to SAM predefined policies with restricred access.

so for example let's take a look at following template:
```yml
  MyBucket:
    Type: AWS::S3::Bucket

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DemoS3TriggerMyFunction
      Handler: my-function.js
      CodeUri: ./main
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref MyBucket
      Events:
        receivingUpload:
          Type: S3
          Properties:
            Bucket: !Ref MyBucket
            Events:
              - s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: 'data/receiving/'
                  - Name: suffix
                    Value: '.json'
``` 
This will fail with:  `Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Circular dependency between resources: [MyFunctionRole, MyFunction, MyFunctionreceivingUploadPermission, MyBucket]

if I was to replace S3ReadPolicy not to be restricted to given bucket and make it more generic, it works fine.
Where as below will work without any problem.
```yml
  MyBucket:
    Type: AWS::S3::Bucket

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DemoS3TriggerMyFunction
      Handler: my-function.js
      CodeUri: ./main
      Policies:
        - S3ReadPolicy:
            BucketName: '*'
      Events:
        receivingUpload:
          Type: S3
          Properties:
            Bucket: !Ref MyBucket
            Events:
              - s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: 'data/receiving/'
                  - Name: suffix
                    Value: '.json'
``` 

Which I think makes sense because in second resource definitions, AWS::IAM::ROLE created by SAM for MyFunction doesn't need to rely on specific bucket.
This is fine in this scenario, where giving read access to all S3Bucket won't do that much of damage, but If I was to use `S3CrudPolicy` and not being able to limit permissions to S3, it can potentially be very harmful.

I would be happy to do a PR, but will need someone to point me to correct file/dir I need to work with.
Thanks.

**Comment by keetonian** [comment]
A common workaround for this is to use the `BucketName` parameter of the `AWS::S3::Bucket` resource to give it a name and pass that same name into your lambda function policy template. This is a limitation of the CloudFormation S3 resource.

This is similar to #616

**Comment by tebruno99** [comment]
Its a little odd that we can't setup events on the same bucket that we are trying to read from. This seems like a pretty basic setup. Are there any plans to fix this?

**Comment by ShreyaGangishetty** [comment]
@tebruno99 Do you mean setting up events on existing S3 bucket? SAM currently doesn't support updating existing S3 buckets.

Could you please provide more information on your usecase?

**Comment by tebruno99** [comment]
When we write a new Template to create a new stack that is a Function and a S3 bucket. The function that is defined cannot receive events from the Bucket
```
  MainBucket:
    Type: AWS::S3::Bucket
  EntityImportWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      CodeUri: ./entity-import-worker/
      Handler: entity-import-worker
      Runtime: go1.x
      Events:
        MainS3Event:
          Type: S3
          Properties:
            Bucket: !Ref MainBucket
            Events:
              - s3:ObjectCreated:*
              - s3:ObjectRestore:Completed
      Policies:
        -
          S3ReadPolicy:
            BucketName: !Ref MainBucket
```
This simple template results in a circular dependency that cannot be deployed. Even though it clearly isn't circular. The bucket will be created before the Function, and the policy will be created after the bucket, so it shouldn't be circular.
