### ISSUE TITLE
Handle ParameterName value with or without '/' when creaing generating SSMParameterReadPolicy policy

### ISSUE THREAD

**Issue by whimzyLive** [aws/serverless-application-model#1112]
**Description:**
When using `SSMParameterReadPolicy` policy template with `ParameterName` !Ref..ed to SSM resource `SSMParameterReadPolicy` will generate incorrect arn mapping.
For example:
```yml
  MyCredParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /prefix/environment/applications/mycred
      Type: String
      Value: !Sub |
        {
          "accessKeyId": "<Your accessKeyId>",
          "accessKeySecret": "<Your accessKeySecret>"
        }

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: file-name.js
      Runtime: nodejs8.10
      CodeUri: dir
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Ref MyCredParameter
      Events:
        SomeEvent:
          Type: SNS
          Properties:
            Topic: !Ref MyTopic
      Environment:
        Variables:
          MY_CRED: !Ref MyCredParameter
``` 

Here I am creating SSM resource and lambda function that will use this SSM parameter, as well as I am using SAM policy templates to allow `MyFunction` to allow read access to `MyCredParameter`.

This will deploy successfully, However, when Lambda tries to get value from SSM params with name process.env.MY_CRED, it will fail.

After some debugging I found out that, My lambda function role had permission to call `arn:aws:ssm:my-region:000000000:parameter//prefix/environment/applications/mycred` SSM parameter instead of `arn:aws:ssm:my-region:000000000:parameter/prefix/environment/applications/mycred`.
Notice that extra '/' after parameter in first arn.

**Observed result:**
This was because SAM policy templates uses `ParameterName` as is to create arn without doing any sort of validation. 
```json
{
"SSMParameterReadPolicy": {
      "Description": "Gives access to a parameter to load secrets in this account. If not using default key, KMSDecryptPolicy will also be needed.",
      "Parameters": {
        "ParameterName": {
          "Description":"The name of the secret stored in SSM in your account."
        }
      },
      "Definition": {
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "ssm:DescribeParameters"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "ssm:GetParameters",
              "ssm:GetParameter",
              "ssm:GetParametersByPath"
            ],
            "Resource": {
              "Fn::Sub": [
                "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${parameterName}",
                {
                  "parameterName": {
                    "Ref": "ParameterName"
                  }
                }
              ]
            }
          }
        ]
      }
    },
}
```

**Expected result:**
It would be nice to have this `ParameterName`  validated and add or remove `/` based on validation.
Or accept `ParameterName` with `/` and do not add `/` while creating policy, since all SSM parameter name must start with `/` to be a valid SSM Name.
