### ISSUE TITLE
Updating API resource policy using mappings

### ISSUE THREAD

**Issue by aayush1141988** [aws/serverless-application-model#1162]
I recently ran into an issue where resource policy on my API was getting updated but was not effective. So essentially a new deployment was not being created by SAM. It's because SAM processes the template before any mapping substitutions and according to SAM nothing changed and it doesn't generate a deployment. However, cloud-formation does the substitutions and updates the API. So you see updated policy in the console but its not effective.

**Steps to reproduce the issue:**
```yaml
Resources:
  LambdaAPIDefinition:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: {Ref: Stage}
      DefinitionBody: REPLACE_WITH_SWAGGER_DEFINITION
      Auth:
        DefaultAuthorizer: AWS_IAM
        ResourcePolicy:
          CustomStatements:
          - Effect: Allow
            Principal:
              AWS: { 'Fn::FindInMap': [Map1, Map2,  ReadOnlyApiAccounts] }
            Action: "execute-api:Invoke"
            Resource:
            - {'Fn::Sub': 'arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:*'}
          
Mappings:
  Map1:
    Map2:
      ReadOnlyApiAccounts : ["1234567890"]
      AllApiAccounts: ["1234567890"]
```

When i change ReadOnlyApiAccounts, i expect SAM to generate an API Deployment for policy changes to take effect but it doesn't.
