### ISSUE TITLE
AWS SAM : Assume Role Error

### ISSUE THREAD

**Issue by dattatrayhkulkarni** [aws/serverless-application-model#1208]
In my lambda function code, I have an API call for sts - Assume Role.

When I run the lambda function locally, it uses AWS credentials which are configured locally.

My lambda function invocation fails , with an error - AccessDenied: User: <user> is not authorized to perform: sts:AssumeRole on resource: <IAM_ROLE_ARN>

What is the way to handle this?  For my AWS user, I have created a policy which has assume role permission.

**Comment by keetonian** [comment]
@dattatrayhkulkarni  Good question.

On the role that you want to assume, you need the following statement:
```yaml
  CrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: "sts:AssumeRole"
            Principal: <principal>
      ...
```

Then, in the role that your lambda is running in, you need the following policy:
```yaml
...
        Policies:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Resource:
              Fn::Sub: 'arn:aws:iam::${OtherAccountId}:role/${CrossAccountRoleName}'
         ...
```
