### ISSUE TITLE
ApiKeyRequired causes "Internal tranformation failure"

### ISSUE THREAD

**Issue by joehillen** [aws/serverless-application-model#1250]
**Description:**

Setting `ApiKeyRequired: true`  on `AWS::Serverless::API` causes `Internal transform failure.`

**Steps to reproduce the issue:**

Here is some of the configuration I have:

```yaml
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${RepositoryName}-${StageName}
      StageName:
        Ref: StageName
      Auth:
        ApiKeyRequired: true
      EndpointConfiguration: REGIONAL
      CacheClusterEnabled: false
      CacheClusterSize: "0.5"
      MethodSettings:
        - LoggingLevel: !If [NonProd, "INFO", "ERROR"]
          MetricsEnabled: true
          DataTraceEnabled: true
          ResourcePath: "/*"
          HttpMethod: "*"
          # Set CachingEnabled false as default for all resources. To enable caching for a resource configure
          # a MethodSettings entry with CachingEnabled: true, HttpMethod: GET, CacheTtlInSeconds: 3600, and appropriate ResourcePath,
          CachingEnabled: false
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location:
              Fn::Join:
                - ""
                - - "s3://"
                  - Ref: S3BucketName
                  - "/swagger.yml"

  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      Description: CloudFront Only
      UsagePlanName: CloudFront_Only
      ApiStages:
        - ApiId: !Ref RestApi
          Stage: !Ref StageName

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub "${AWS::StackName}-CloudFront-ApiKey"
      Description: "CloudFront API Key"
      Enabled: true
      GenerateDistinctId: false

  ApiKeyUsagePlan:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan
```

If I comment out:

```
Auth:
    ApiKeyRequired: true
```

then it deploys without a problem, but then the API Key is not required on the API Gateway.

I've also tried setting it on a single function, and it fails with the same error.

**Observed result:**

```
Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Internal transform failure.
```
