### ISSUE TITLE
Evaluating Secrets Manager value change

### ISSUE THREAD

**Issue by dalumiller** [aws/serverless-application-model#1267]
**Description:**

This may be more appropriate for CloudFormation vs SAM. 

The issue is regarding lambdas not updating when Secrets Manager secret values are changed. When you set an environment variable in your template to a secret stored in the Secrets Manager, if you change the secret value in the Secrets Manager and roll out an update to CF the lambdas are not seen as having updated

**Steps to reproduce the issue:**
1. Create a secret in the Secrets Manager 
2. Create a lambda with an environment variable referencing a Secrets Manager value (using the `{{resolve:secretmanager...}}` syntax. 
3. Publish that SAM template
3. After publish succeeds, change the value of the secret in the Secrets Manager
4. Re-publish the SAM template, making no changes to the lambda and the SecretString should remain the same since we are only changing the value. So, no change in the template.

**Observed result:**
The newly published template won't update the lambda with the new secret

**Expected result:**
CloudFormation, during it's changeSet creation, would evaluate the Secrets Manager value and the current version of the lambda to see if the values match and if not then the changeSet updates the lambda with the new secret reference.

**Comment by tkeeber** [comment]
Is there any update on this issue? This is a major blocker for us adopting Secret Manager.

**Comment by dudeitssm** [comment]
Bumping this as well. Experienced this for a work project.

**Comment by caiocsgomes** [comment]
Any updates?

**Comment by praveen-adroitminds** [comment]
> The workaround is to add an environment variable that is changed on every deployment. That will force CloudFormation to re-evaluate secrets.

Thanks a lot @squeral 👍🏻

**Comment by ssenchenko** [comment]
The recommended approach to update properties based on values stored in SecretMangers  [AWS Knowledge centre post](https://repost.aws/knowledge-center/cloudformation-stack-update-secrets). However, running a simple plain CloudFormation template (below) demonstrates that Lambda doesn't update the value of the variable even when a new version is specified. So it's not a SAM bug.
```yaml
Resources:
  MyLambda:
    Type: AWS::Lambda::Function
    Metadata:
      SamResourceId: MyFunction
    Properties:
        Code:
          ZipFile: "exports.handler = async () => {\n  const secret = process.env.SECRET;\n
            \ return {\n    statusCode: 200, \n    body: JSON.stringify({\n      message:
            `Hello World. I know secret: ${secret}!`\n    })\n  };\n}\n"
        Handler: index.handler
        Role:
          Fn::GetAtt:
          - MyLambdaRole
          - Arn
        Runtime: nodejs18.x
        Environment:
          Variables:
            SECRET: '{{resolve:secretsmanager:secret-string:SecretString:Key::2ada587d-cc7d-4219-ab2b-78db8dfe00c7}}'
  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
```
However, passing a value stored in a secret manager through an environmental variable is not a recommended practice for many reasons. One should access secrets manager from the function code directly. Code examples in several languages are available right in SecretsManager console
