### ISSUE TITLE
Function Event Schedule - Can't use conditional for "Enabled" property

### ISSUE THREAD

**Issue by muzehyun** [aws/serverless-application-model#1271]
**Description:**
I have created Schedule event for a function.
And I wanted to enable it conditionally
Whatever conditional I have used, it's always enabled.
(I already verified with inverted true/false - conditional might wrong - still always enabled)
I have confirmed through cloudwatch log too.
If I use `Enabled: false` directly, it works well.
- similar issue - #1142 

```
Conditions:
  IsDev:
    Fn::Equals:
      - Ref: Stage
      - dev

SomeFunction:
  Type: AWS::Serverless::Function
  Properties:
    ...
    Events:
      warming:
        Type: Schedule
        Properties:
          Enabled:
            Fn::If:
              - IsDev
              - false
              - true
          Schedule: "cron(* * * * ? *)"
```

**Observed result:**
![Screen Shot 2019-11-28 at 12 40 26 AM](https://user-images.githubusercontent.com/3071771/69790785-fbb5d680-1177-11ea-8b4b-e04b5d5ebe9d.png)

**Expected result:**
Properly "Disabled" based on conditional.
