### ISSUE TITLE
Unsupported Resource Type [AWS::CloudTrail::Trail]

### ISSUE THREAD

**Issue by himanshu219** [aws/serverless-application-model#1275]
**Description:**

```
  LogExportTrail:
    Condition: SetUpCloudTrail
    Type: AWS::CloudTrail::Trail
    DependsOn:
      - CloudTrailExportPolicy
    Properties:
      IsLogging: True
      IsMultiRegionTrail: False
      S3BucketName: !Ref CloudTrailTargetS3BucketName
      TrailName: !Sub "LogExportTrail-${AWS::StackName}"
```

While publishing the sam app containing AWS::CloudTrail::Trail resource type it throws 
following error 

```
Publish Failed
Error: The template contains unsupported resource types. [AWS::CloudTrail::Trail]
Please follow the instructions in https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-applications.html
```

Initially my assumption was since SAM is a derivative of cloudformation so one can define cloudformation resources inside SAM as mentioned in [docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/what-is-sam.html) 
"You can define resources by using AWS CloudFormation in your AWS SAM template." 

Is there any way to define Cloudformation resources in SAM so that I can publish in SAR.
If not then please consider this a feature request to add cloudtrail resources support in [list of supported resources ](https://docs.aws.amazon.com/serverlessrepo/latest/devguide/list-supported-resources.html).
