### ISSUE TITLE
Provisioned Concurrency is not applied

### ISSUE THREAD

**Issue by olifer** [aws/serverless-application-model#1298]
**Description:**

Setting Provisioned Concurrency on AWS::Serverless::Function in a cloudformation does not change aws lambda configuration when deployed.

**Steps to reproduce the issue:**
1. Deploy a lambda with `ProvisionedConcurrencyConfig` property set
```yaml
XLambda:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 40
      MemorySize: !Ref MemorySize
      Runtime: dotnetcore2.1
      Role: !GetAtt XLambdaRole.Arn
      Handler: x::FunctionHandlerAsync
      Tracing: Active   
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 5
      DeploymentPreference:
        Type: !Ref DeploymentPreference
```
**Observed result:**
Check if the config has been applied: 
- Using aws console
![image](https://user-images.githubusercontent.com/1049092/70246446-11c72680-1778-11ea-8663-88db3f7a94f2.png)

- Using aws cli
```
aws lambda list-provisioned-concurrency-configs --function-name x-lambda
{
    "ProvisionedConcurrencyConfigs": []
}
```

**Expected result:**
`ProvisionedConcurrentExecutions` is added to `Provisioned Concurrency Config` on the lambda.
