### ISSUE TITLE
The event source and function provided mapping already exists. Please update or delete the existing mapping with UUID

### ISSUE THREAD

**Issue by MatteoGioioso** [aws/serverless-application-model#1320]
**Description:**
I am trying to implement Dynamodb streams and a trigger for lambda

```
 myFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
        - DynamoDBStreamReadPolicy:
            TableName: !Ref TableName
            StreamName:
              !Select
                - 2
                - !Split
                  -  "/"
                  - Fn::ImportValue:
                      !Sub ${TableName}-streams-arn
      CodeUri: bin/
      Handler: myFunctions
      Events:
        dynamodb:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::ImportValue: !Sub ${TableName}-streams-arn
            StartingPosition: LATEST
            BatchSize: 10
```

The first deployment was successful, however after adding the `DynamoDBStreamReadPolicy` and changed `StartingPosition` from `TRIM_HORIZON` to `LATEST`  I got the following error: 

```
The event source arn (" arn:aws:dynamodb:.../stream/... ") and function (" myFunction-...") provided mapping already exists. Please update or delete the existing mapping with UUID xxxx-xxxx-xxx-xxx (Service: AWSLambda; Status Code: 409; Error Code: ResourceConflictException; Request ID: xxxx-xxxxxxx-xxxx-xxx)
```

**Observed result:**
Error

**Expected result:**
Probably error, but at this point I did not find any explanation

PS: **as my understanding once the event mapping is created must be replaced or deleted?** If yes why it says *"Please update or delete"*? If now I want to change the mapping configuration do I need to remove it, deploy, add it again and redeploy?

Thanks

**Comment by elembie** [comment]
+1

**Comment by sintaro** [comment]
+1

**Comment by shearn89** [comment]
For future Googlers: I had this issue, and it was because there was a manually-created trigger hanging around that wasn't deleted with my stack. Using the CLI to delete by UUID, or going to SQS -> the queue -> Lambda triggers should have let me find it.

**Comment by MatteoGioioso** [comment]
Ok, this is a long standing bug with cloudformation.
Similar happening with Kinesis and it was already spotted in 2018 on the serverless framework.
This is a minimal reproducible case: https://github.com/MatteoGioioso/sls-event-source-mapping-bug
You just need to change `startingPosition` from `TRIM_HORIZON` to `LATEST`

**Comment by cli402** [comment]
Hit the issue same day  trying to update the kinesis source mapping settings.

**Comment by bissli82** [comment]
Please fix, same issue here!

**Comment by myoung34** [comment]
I also ran into and fixed this by calling `aws lambda list-event-source-mappings` to find the orphaned mapping then `aws lambda delete-event-source-mapping --uuid {uuid}` to remove it

**Comment by hoffa** [comment]
Thanks all for the input, very informative.

I'm able to reproduce this with a pure CloudFormation template:

```yaml
Resources:
  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: MyAttribute
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: MyAttribute
          AttributeType: S
      StreamSpecification:
        StreamViewType: KEYS_ONLY
  MyFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.8
      Handler: index.handler
      Role: !GetAtt MyFunctionRole.Arn
      Code:
        ZipFile: |
          def handler(event, context):
              return {'body': 'Hello World!', 'statusCode': 200}
  MyFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaDynamoDBExecutionRole
  MyFunctionMyTableEvent:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt MyTable.StreamArn
      FunctionName: !Ref MyFunction
      StartingPosition: TRIM_HORIZON
```

That template will deploy fine.

But as @MatteoGioioso mentioned, if you change `StartingPosition` from `TRIM_HORIZON` to `LATEST`, you'll get the error:

```
The event source arn ([...]) and function ([...]) provided mapping already exists. Please update or delete the existing mapping with UUID [...]
```
