### ISSUE TITLE
SAM nested stack for AWS::Serverless::Api not working

### ISSUE THREAD

**Issue by dattatrayhkulkarni** [aws/serverless-application-model#1337]
I want to split my SAM application into multiple parts.

I want to create a API ( AWS::Serverless::Api ) in the root stack.

I am creating lambda functions in my child stacks, where I want to give the reference of the API from the root stack to the API Events.

Is this feasible? I didn't find any good examples for the accessing the API from the root stack into child stack?

I tried with the below child template -

```
parenttemplateapi:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:account_id:applications/parent-template
        SemanticVersion: 1.0.0


```

```
HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python2.7
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Method: get
            Path: /hello
            RestApiId: !GetAtt parenttemplateapi.Outputs.ServerlessGW-restApiId

```
When I tried to deploy this template, I got below errors -

> 
_Error: Failed to create changeset for the stack: child-template, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Internal transform failure._

Any pointers/suggestions?

I was referring to below link -

https://aws.amazon.com/blogs/compute/announcing-nested-applications-for-aws-sam-and-the-aws-serverless-application-repository/

Can splitting the template/nested template achieved using some other way?

**Comment by AntonUspehov** [comment]
Hi @dattatrayhkulkarni 
I had the same problem.
And as I found in [documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-api.html):
`RestApiId` - This cannot reference an AWS::Serverless::Api resource defined in another template.

**Comment by hawflau** [comment]
@AntonUspehov is right. `RestApiId` must reference to an AWS::Serverless::Api resource defined in the same template. 
Looking at the code, I don't think it's easy to support referencing API defined not in the same template, because SamTransaltor can't modify API resources defined in an external template. In your example, that would be adding the path `/hello` into the swagger definition of the API in the root stack.

Meanwhile, see the workaround in the comment below, and see if it works for you.

**Comment by hawflau** [comment]
## Workaround to have a `AWS::Serverless::Api` resource in the root stack that triggers a Serverless Function in a child stack

root_stack.yaml:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-issue-1337-workaround

  Sample SAM Template for sam-issue-1337-workaround
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  NestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./nested.template.yaml

  HelloWorldLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction 
      FunctionName:
        Fn::GetAtt:
        - NestedStack
        - Outputs.HelloWorldFunction
      Principal: apigateway.amazonaws.com

  RootApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody: {
        "swagger": "2.0",
        "info": {
          "version": "1.0",
          "title": {
            "Ref": "AWS::StackName"
          }
        },
        "paths": {
          "/hello": {
            "get": {
              "x-amazon-apigateway-integration": {
                "httpMethod": "POST",
                "type": "aws_proxy",
                "uri": {
                  "Fn::Sub": [
                    "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ImportedFunctionArn}/invocations",
                    {
                      "ImportedFunctionArn": {
                        "Fn::GetAtt": [
                          "NestedStack",
                          "Outputs.HelloWorldFunction"
                        ]
                      }
                    }
                  ]
                }
              },
              "responses": {}
            }
          }
        }
      }

```

child_stack.yaml:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-issue-1337-workaround

  Sample SAM Template for sam-issue-1337-workaround
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
```

Basically we need to define a Lambda Permission explicitly that allows the API to invoke the Lambda function. In this example, I defined the Lambda Permission in the root stack, but I think it can be defined in the child stack as well.
