### ISSUE TITLE
Deployment , and rollback, fails when removing ProvisionedConcurrency configuration from Function

### ISSUE THREAD

**Issue by mikebroberts** [aws/serverless-application-model#1353]
If you remove the `ProvisionedConcurrencyConfig` section from an existing `AWS::Serverless::Function` resource then deployment fails with the message:

"Alias with weights can not be used with Provisioned Concurrency (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: ...)"

What's especially nasty about this is that the CloudFormation rollback then fails, leaving the stack in UPDATE_ROLLBACK_FAILED state, and `sam deploy` never finishes.

I'm not impacted by this in production - I'm only experimenting - but I thought you all might want to know.

For reference my initial SAM resource was:

```
  HelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      MemorySize: 512
      Handler: book.HelloWorld::handler
      CodeUri: target/lambda.jar
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 100
```

And I then removed the `ProvisionedConcurrencyConfig` (and child `ProvisionedConcurrentExecutions`) property.

Mike

**Comment by guaccc** [comment]
Hello, I'm currently impacted by this and trying to figure out how to roll back my staging environment.

Does anyone have suggestion? I followed the exact course in adding `ProvisionedConcurrencyConfig` to my `AWS::Serverless::Function` and then after subsequent build failed, I removed it in effort to roll back to original state and am now stuck with referenced error above!

**Comment by hoffa** [comment]
Thanks for reporting this.

I was unable to reproduce:

```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      Handler: foo
      InlineCode: bar
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 100
```

Deploy:

```
sam deploy --region us-west-2 --resolve-s3 --capabilities CAPABILITY_IAM --stack-name test-1353 --template template.yaml
```

Then remove the provisioned concurrency:

```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      Handler: foo
      InlineCode: bar
      AutoPublishAlias: live
```

And deploy again, which succeeds. `ProvisionedConcurrencyConfig` is a pass-through property passed straight to `AWS::Lambda::Alias`, so perhaps it was an issue with the underlying resource that has now been resolved.
