### ISSUE TITLE
sam incorrectly resolve parameters

### ISSUE THREAD

**Issue by mgorski-mg** [aws/serverless-application-model#1360]
I have a problem to pass parameters to enable or disable Lambda Scheduler

Template:
```
Parameters:
  SchedulerCronParameter:
    Type: String
    Description: Enter scheduler cron expresion. Default is cron(0 1 1 * ? *).
    Default: cron(0 1 1 * ? *)
  SchedulerEnabledParameter:
    Type: String
    Description: Enable or disable scheduler. Default is true.
    Default: true
    AllowedValues: [true, false]

Resources:
  ScheduledLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: code/
      Handler: handler.lambda_handler
      Runtime: python3.7
      Timeout: 900
      Tracing: Active
      Events:
        Schedule:
          Properties:
            Name: LambdaScheduler
            Description: Monthly schedule
            **Enabled: !Ref SchedulerEnabledParameter**
            Schedule: !Ref SchedulerCronParameter
            Input: '{"view_only": false}'
          Type: Schedule
```
I think it's because the template is translated before resolving CF Parameters.
Code from SAM translator:
```
if self.Enabled is not None:
            events_rule.State = "ENABLED" if self.Enabled else "DISABLED"
```

If the Parameter is not resolved before translation, it's always set State as 'ENABLED'.

Do you have any workaround for it?

SAM CLI version: 0.39.0
