### ISSUE TITLE
Issue with multiple VPCE's in SourceVpcWhitelist

### ISSUE THREAD

**Issue by keanesf** [aws/serverless-application-model#1372]
**Description:**

If multiple VPCE's are specified in the SourceVpcWhitelist traffic from both VPCE's is denied. 

**Steps to reproduce the issue:**
1. Specify multiple VPCEs in the SourceVpcWhitelist and set the EndpointConfiguration to PRIVATE

Example

```yaml
Resources:        
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: PRIVATE
      Auth:
        ResourcePolicy:
          SourceVpcWhitelist:
            - vpce-1
            - vpce-2
```

2. Send a request in which vpce-1 or vpce-2 is the sourceVpce and the response is an explict deny.  

**Observed result:**

Traffic is not permitted when multiple vpce's are whitelisted. If only once vpce is white listed the issue does not occur.  

**Expected result:**

Traffic is permitted from both whitelisted source vpce's and traffic is denied from a vpce not whitelisted.
