### ISSUE TITLE
Unable to obtain RegionalDomainName and RegionalHostedZoneId from generated CustomDomain object.

### ISSUE THREAD

**Issue by brysontyrrell** [aws/serverless-application-model#1386]
**Description:**

When trying out the new `Domain` object for `AWS::Serverless::Api` in v1.20 I found that the `AWS::ApiGateway::DomainName` resource that's generated uses a random identifier appended onto the logical ID.

Example: `ApiGatewayDomainNamef5d64213a3`

This resource also doesn't use the parent API resource name as a prefix like with other generated resources like the `BasePathMapping` and `ProdStage`.

This makes it where I cannot perform a `!GetAtt` on the autogenerated resource to obtain the domain and hosted zone values to generate a Route 53 record.

My use case for not using the built-in option to create records is using alternative routing strategies (like latency based routing using `SetId`).

**Comment by praneetap** [comment]
@brysontyrrell This is a referable property, just like Deployment and Stage. So you can get the name via !Ref <ApiName>.DomainName. Please lmk if that works!

**Comment by hauboldj** [comment]
Please document this.

**Comment by flagscript** [comment]
Does anyone know the referrable property for the hosted zone id ? Haven't been able to track that one down yet.

**Comment by praneetap** [comment]
@flagscript SAM doesnt create HostedZone resource for you. You can read more about the hosted zone cfn resource [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone.html)

**Comment by flagscript** [comment]
Apologies - I think I didn't describe it well. :)

I'm assuming this creates a `AWS::ApiGateway::DomainName` under the covers. Currently we need to update the R53 Alias record in another account with the `RegionalDomainName` and `RegionalHostedZoneId` created by that resource. 

We're just currently creating our own `AWS::ApiGateway::DomainName` and attaching it to the `AWS::Serverless::Api` directly so we can get these values. I was wondering if there is any shorthand like the !Ref RestApi.Stage we can use to get these values (something like !Ref RestApi. RegionalDomainName) just because the Domain Property syntax would be so much prettier to use and would love to switch to it.

**Comment by aidansteele** [comment]
@praneetap Here's a concrete example. I'd like to deploy my SAM app to multiple regions and use Route53 latency-based routing to decide where to send traffic. This is what I've tried:

```
  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      Domain:
        DomainName: my.example.com
        CertificateArn: !Ref CertificateArn

  Record:
    Type: AWS::Route53::RecordSet
    Properties:
      Region: !Ref AWS::Region
      SetIdentifier: !Ref AWS::Region
      HostedZoneName: example.com.
      Name: my.example.com
      Type: A
      AliasTarget:
        DNSName: !GetAtt Api.GatewayDomain.RegionalDomainName
        HostedZoneId: !GetAtt Api.GatewayDomain.RegionalHostedZoneId
```

This doesn't work, it produces this error message:

> sam-test - UPDATE_ROLLBACK_IN_PROGRESS - [Error] /Resources/Record/Properties/AliasTarget/HostedZoneId/Fn::GetAtt: Resource type AWS::ApiGatewayV2::Api does not support attribute {GatewayDomain.RegionalHostedZoneId}, [Error] /Resources/Record/Properties/AliasTarget/DNSName/Fn::GetAtt: Resource type AWS::ApiGatewayV2::Api does not support attribute {GatewayDomain.RegionalDomainName}

Is there any way to achieve this?
