### ISSUE TITLE
"EventBusName: default" in template causes stabilization error + rollback

### ISSUE THREAD

**Issue by jbesw** [aws/serverless-application-model#1407]
**Description:**
Related to https://github.com/awslabs/serverless-application-model/releases/tag/v1.17.0.

**Steps to reproduce the issue:**
Using this template...
```
      Events:
        Trigger:
          Type: CloudWatchEvent 
          Properties:
            EventBusName: default
            Pattern:
              source:
                - "myApp"
```
.. the deployment will result in a stabilization error and rollback. The rule is created in EventBridge with a truncated name but the stack is rolled back, never deleting this resource.

If this attribute is removed, the rule is created successfully and defaults to the default event bus. However, this attribute is needed to create rules on custom event buses.

**Observed result:**
Rollback/failure.

**Expected result:**
Should create the rule using the default eventbus. Should also provide a useful error.

**Comment by thiezn** [comment]
Seeing the exact same behaviour, thanks for raising this as I was pulling my hair out :)

**Comment by hoffa** [comment]
Unable to reproduce. Tried with the following template:

```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      Handler: foo
      InlineCode: bar
      Events:
        Event:
          Type: CloudWatchEvent
          Properties:
            EventBusName: default
            Pattern:
              source:
                - "myApp"
```

Deploy:

```
sam deploy --region us-west-2 --resolve-s3 --capabilities CAPABILITY_IAM --stack-name test-1407 --template template.yaml
```

Which worked fine, and events rule ARN is as expected. Both `EventBusName` and `Pattern` are pass-through properties, so it likely had to do with the underlying service, but seems resolved now.
