### ISSUE TITLE
Provision Concurrency does not update

### ISSUE THREAD

**Issue by elbert-rival** [aws/serverless-application-model#1425]
**Description:**

We have a lambda function that is being deployed with the AWS SAM cli. On the first creation, the provisioned concurrency gets set correctly. However, if I make an update to the concurrency number and update the stack, the lambda function does not show the change.

For example, if I am creating my stack with a serverless function with the template below, it shows on the AWS Lambda console that the provisioned concurrency is 1.

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs10.x

MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      DeploymentPreference:
        Type: AllAtOnce
      Tracing: Active
      CodeUri: .package/
      Handler: src/lambdas/myFunction.handler
      Timeout: 10
```

Up to this point, everything seems correct, but if I want to update the stack and change the provisioned concurrency number, the AWS Lambda console does not reflect the update. For example, I would expect to see the provision concurrency on the console to be 100, but it stays as 1.

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs10.x

MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 100
      DeploymentPreference:
        Type: AllAtOnce
      Tracing: Active
      CodeUri: .package/
      Handler: src/lambdas/myFunction.handler
      Timeout: 10
```

**Steps to reproduce the issue:**
1. Create a stack with one lambda function with provision concurrency set to 1 (example template above)
2. Update the existing stack with a new provision concurrency number (e.g. 10)

**Observed result:**

Running an update on the stack with a different provision concurrency does not update the concurrency number in the AWS Lambda console.

**Expected result:**

Running an update with changes to the lambda function provision concurrency to update the provision concurrency number on the AWS Lambda console

**Work Around**

Updating with AWS CLI seems to work correctly.

**Comment by brightsparc** [comment]
I have a similar issues where by I want to update Environment variables and have this trigger a deployment, but this doesn't appear to affect any change.

**Comment by praneetap** [comment]
@brightsparc we have a fix rolling out soon which might help with this #1376.

**Comment by sriram-mv** [comment]
are you still experiencing this issue?

**Comment by hoffa** [comment]
I did the following:

```
sam init --name repro-1425-2 --runtime nodejs14.x --dependency-manager npm --app-template hello-world
```

Replaced `template.yaml`:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs14.x

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      DeploymentPreference:
        Type: AllAtOnce
      Tracing: Active
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Timeout: 10
```

Deployed:

```
sam build --use-container
sam deploy --guided
```

Then deployed again with `ProvisionedConcurrentExecutions: 100` and the expected concurrency showed up in Lambda. Tried with other values as well; same results.

Closing as this seems to be fixed.
