### ISSUE TITLE
Changing `minimumCompressionSize` doesn't trigger API deployment.

### ISSUE THREAD

**Issue by hauboldj** [aws/serverless-application-model#1447]
**Description:**

Adding or changing the `minimumCompressionSize` attribute on a `AWS::Serverless::Api` does not trigger a deployment of the API. The hash for the deployment ID does not changes when this attribute is changed.

**Steps to reproduce the issue:**
1. Take a template with an `AWS::Serverless::Api` resource defined
2. Change or add the `minimumCompressionSize` attribute.
3. Deploy

**Observed result:**
The API Gateway Rest API is not deployed
**Expected result:**
The API Gateway Rest API is deployed

**Comment by sriram-mv** [comment]
I was not able to repro this and was able to deploy after changing `MinimumCompressionSize`.

**Comment by AshMenhennett** [comment]
Ran into the same issue, have had conflicting results.

Conclusion is that changing these properties (only tested `minimumCompressionSize`) [Update API](https://docs.aws.amazon.com/apigateway/latest/developerguide/updating-api.html) should update or create a new deployment resource to propagate changes to the gateway stage. Have found that (via SAM) the deployment resource is not updated nor a new one created in the stack changeset, with the config changes requiring AWS CLI/ REST Api calls to redeploy to the stage (kind of defeats the purpose of using SAM to manage state of these resources).

Here is sample config I validated this with yesterday, for reference:

```yaml
Transform: AWS::Serverless-2016-10-31
Description: Sandbox

Resources:

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      # MinimumCompressionSize: 0

  Func:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dev-func
      Handler: lambda.lambda_handler
      Runtime: python3.7
      Timeout: 180
      CodeUri: ./dev
      MemorySize: 1024
      Events:
        FuncGet:
          Type: Api
          Properties:
            Path: "{proxy+}"
            Method: GET
            RestApiId: !Ref Api
        FuncPost:
          Type: Api
          Properties:
            Path: "{proxy+}"
            Method: POST
            RestApiId: !Ref Api
      AutoPublishAlias: current

```
