### ISSUE TITLE
Custom domain with - or _ in base path truncated

### ISSUE THREAD

**Issue by griffy-devopsadmin** [aws/serverless-application-model#1456]
### Description

When deploying an API with a custom domain name and a base path with either - or _ in it, the base path is truncated at the - or _ character.

### Steps to reproduce

Deploy an API with a custom domain defined that includes - or _ such as:

```yaml
Resources:
  MyApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      Name: "myapi"
      EndpointConfiguration: REGIONAL
      StageName: "stage"
      TracingEnabled: True
      OpenApiVersion: 3.0.1
      Domain:
        DomainName: "api.myapi.com"
        CertificateArn: !Ref MyCertificateArn
        EndpointConfiguration: REGIONAL
        BasePath:
          - "dev-v1"
        Route53:
          HostedZoneId: !Ref MyHostedZoneId

```
### Observed result

The custom domain created for the API includes a base path mapping, but it is truncated to "/dev"

### Expected result

The base path should be "/dev-v1"

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 10.15.2
2. `sam --version`: 0.41.0

Note that the base path can be manually corrected in the console and will function correctly.
