### ISSUE TITLE
ProvisionedThroughput cannot be empty..

### ISSUE THREAD

**Issue by raymonstah** [aws/serverless-application-model#1464]
### Description
Getting an issue during `sam deploy` saying that ProvisionedThroughput cannot be empty.

### Steps to reproduce

Here's the table defined in my template.yml
```
  GameRoomTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "connection_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "connection_id"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: connection-idx
          KeySchema:
            - AttributeName: "connection_id"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
```

### Observed result

Please provide command output with `--debug` flag set.

### Expected result

Successful deployment

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
SAM CLI, version 0.43.0

**Comment by scottvelasquez** [comment]
I'm able to reproduce this error when specifying BillingMode as PAY_PER_REQUEST. Adding in ProvisionThroughput as the error requests makes no difference. YAML code formatting doesn't carry over:

TestTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: 'PAY_PER_REQUEST'
      ProvisionedThroughput: 
        ReadCapacityUnits: 0
        WriteCapacityUnits: 0
      KeySchema: 
        AttributeName: record_id
        KeyType: HASH
      KeySchema:
        AttributeName: sort_id
        KeyType: RANGE
      TableName: "test-table"

Is there a workaround or do we need to just manually create tables for now?

**Comment by rsarili** [comment]
I dont know if it would be useful information but I can create on demand dynamodb table with aws cloudformation cli using following template values

Transform: AWS::Serverless-2016-10-31
Table:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: connectionId
        AttributeType: S
      KeySchema:
      - AttributeName: connectionId
        KeyType: HASH
      SSESpecification:
        SSEEnabled: false
      TableName: !Ref TableName

**Comment by mh-holdrent** [comment]
I am having this same error.  Whenever I add a "GlobalSecondaryIndexes" property to my AWS::DynamoDB::Table definition, I get "ProvisionedThroughput cannot be empty" on deploy.  Any status update on this?

**Comment by dsciacca** [comment]
Same issue here as @mh-holdrent if I include GlobalSecondaryIndexes I get the `ProvisionedThroughput cannot be empty` error on deploy. Same table definition works if I switch to LocalSecondaryIndexes, but LSI won't satisfy my use case

**Comment by dsciacca** [comment]
I was able to resolve the issue for my use case. A GSI itself _also_ requires a ProvisionedThroughput section in addition to the table itself requiring a ProvisioinedThroughput section. So to address the OPs issue, you'd update the table definition to:
```
GameRoomTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "connection_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "connection_id"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: connection-idx
          KeySchema:
            - AttributeName: "connection_id"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
```
And you should be all set. Hope this helps!

**Comment by tbholdren** [comment]
Yes, I discovered the same thing shortly after I made this post.  Thanks for confirming.  Perhaps the error message should be updated to make it clear as to which section it is complaining needs ProvisionedThroughput defined?

**Comment by FaridDelgadoTR** [comment]
I found the same issue. I was trying to add the GSI's to the tables without providing the `ProvisionedThroughput` as the [AWS Doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-gsi.html) suggest it's not required.

**Comment by brian-1d3** [comment]
The docs need to be updated to state `Required: Yes` for property `ProvisionedThroughput` under AWS::DynamoDB::Table GlobalSecondaryIndex

**Comment by KhanDoors** [comment]
thanks guys awesome!

**Comment by chasedenecke** [comment]
In my case I had provisionedthroughput for both the table and the secondary index but had set ReadCapacityUnits and WriteCapacityUnits to 0. Setting them to non-zero values fixed the problem.

**Comment by pazfernando** [comment]
I had the same error with the following template:
```
AbundanceTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "UserTopicDayKey"
          AttributeType: "S"
        - 
          AttributeName: "Date"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "UserTopicDayKey"
          KeyType: "HASH"
        - 
          AttributeName: "Date"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "abundance"
```

But I realize that I need do `sam build` after chage the template and afetr do `sam deploy`.

It works now for me.
