### ISSUE TITLE
How to enable full requests/responses data and detailed CloudWatch Metrics?

### ISSUE THREAD

**Issue by mohamedelephant** [aws/serverless-application-model#1488]
**Description:**

I'm having an issue with enabling **Log full requests/responses data** in my API GW that I create from a Swagger file.

I managed to get the configs for **enabling CloudWatch Logs** in INFO level.
I tried to understand the process in this [case](https://github.com/awslabs/serverless-application-model/issues/248#issuecomment-439373158), but no luck to understand what and why should I this snippet. 

**Steps to reproduce the issue:**
1.This is the code that I have for now:
  ```yaml
ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: '/*'
          HttpMethod: '*'
      DefinitionUri: ../Swagger.yaml
      StageName: Prod
```
2. I can see that **Enable CloudWatch  Logs** is enabled in the console. 

**Observed result:**
This will enable **Enable CloudWatch Logs** at INFO level. 

The question here is how to enable **Enable Full requests/responses data** option? 
Also, same to **Enable Detailed CloudWatch Metrics**, how to enable this option?
