### ISSUE TITLE
AWS::Serverless-2016-10-31 macro is not providing the correct logicalID for the lambda versions 

### ISSUE THREAD

**Issue by KarthickEmis** [aws/serverless-application-model#1522]
In order to Create alias for each of the lambda function , we have created an macro which returns the alias with the function version property that has points to GetAtt of LambdaVersion Function.

In Macro, we created the Lambda version function id  based on the Logical Id Generator which sam translator(**version 1.22.0**) used . Once the template is processed with our macro , then it try to process the **AWS::Serverless-2016-10-31** macro , but it returns the different Lambdaversion function id , which leads to below error

**Template error: instance of Fn::GetAtt references undefined resource TestLambdaVersione2dc7a7120**

For Example , 
Our macro generates the version id like **FindAvailableVersion75d094696a**

                   "FunctionVersion": {
                    "Fn::GetAtt": [
                        "FindAvailableVersion75d094696a",
                        "Version"
                    ]
                }

and **AWS::Serverless-2016-10-31** generates like  **FindAvailableVersione7cb0874f3**

                              "FindAvailableVersione7cb0874f3":{
                              "DeletionPolicy":"Retain",
                               "Type":"AWS::Lambda::Version",
                                "Properties":{
                                "FunctionName":{"Ref":"FindAvailableSlots"}}}

Did AWS has recently changed the logic of generating the versionID or we need to change the logic of generating the version id?

**Comment by ShreyaGangishetty** [comment]
@KarthickEmis in v1.22.0 there was a change in calculation of version logical id. `Environment` and `MemorySize` properties of `AWS::Serverless::Function` are added as a part of calculating logical id for version.  This has changed in PR #1310 (https://github.com/awslabs/serverless-application-model/commit/99f5ab7497273e28edc79c614fa2fe6afc289003#diff-87d43f83d256604d59eff480b322bdda)

The logical id calculation for version in SAM can be found here: https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/model/sam_resources.py#L670-L674

Could you please confirm if you have used the same calculation in macro?

**Comment by ShreyaGangishetty** [comment]
@KarthickEmis Could you tell us why you need a macro to generate the version id. You can get the generated resource by referencing `<function-logical-id>.Version` in your template
Please refer to [AWS SAM documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-autopublishalias) for more information

**Comment by jarrettmeyer** [comment]
@ShreyaGangishetty When I use `!GetAtt LambdaFunc.Version`, I get the following cfn-lint error.
```yml
Resources:
    LambdaFunc:
        Type: AWS::Serverless::Function
        Properties:
            AutoPublishAlias: live
            # ...snip...
    WebCloudFront:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                LambdaFunctionAssociations:
                    - EventType: viewer-request
                       IncludeBody: false
                       LambdaFunctionARN: !GetAtt LambdaFunc.Version
            # ...snip...
```
```
[cfn-lint] E1010: Invalid GetAtt for Resources/WebCloudFront/Properties/DistributionConfig/DefaultCacheBehavior/LambdaFunctionAssociations/0/LambdaFunctionARN/Fn::GetAtt
```

When I deploy this, I receive the following error.
```
Template error: every Fn::GetAtt object requires two non-empty parameters, the resource name and the resource attribute
```

What am I missing?
