### ISSUE TITLE
AWS::Serverless::Api Models only support object type

### ISSUE THREAD

**Issue by hurlenko** [aws/serverless-application-model#1559]
**Description:**

Defining api model with type other than `object` (specifically  without a `properties` attribute) results in validation error.

SAM CLI, version 0.43.0

**Steps to reproduce the issue:**
1. Define `Models` property to include a model without the `properties` (for example type `array`) attribute like so:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Models:
        MyModel:
          items:
            type: integer
          type: array
          title: MyModel
```

2. Run `sam validate -t template.yaml`

**Observed result:**

An exception is [raised](https://github.com/awslabs/serverless-application-model/blob/c387fd3c825ee543fbd01c1dc80be53f3a5f0a8a/samtranslator/swagger/swagger.py#L787):

```
ValueError: Invalid input. Value for properties is required
```

**Expected result:**

Successful  validation. `Models` support all types supported by json schema without requirement for `properties`.

**Comment by keetonian** [comment]
It looks like SAM enforces having `properties` in the model [here](https://github.com/awslabs/serverless-application-model/blob/28884c958dfaa1c547e0f0e4ae2b8129f52e34dd/samtranslator/swagger/swagger.py#L781). Looks like we could update this section to remove this check.

**Comment by hurlenko** [comment]
So I tried removing [these two lines](https://github.com/awslabs/serverless-application-model/blob/28884c958dfaa1c547e0f0e4ae2b8129f52e34dd/samtranslator/swagger/swagger.py#L787-L788) and after that `sam validate` succeeded, however running `sam deploy` failed with this error.

```
Error: Failed to create changeset for the stack: model-test, ex: Waiter ChangeSetCreateComplete failed: 
Waiter encountered a terminal failure state Status: FAILED. 
Reason: Transform AWS::Serverless-2016-10-31 failed with: Internal transform failure.
```

Currently a workaround is to define a "dummy" `properties` attribute like this:

```yaml
MyModel:
  properties:
    dummy: dummy
  items:
    type: integer
  type: array
  title: MyModel
```

which produces this APIGW model:

```json
{
  "title" : "MyModel",
  "properties" : { },
  "type" : "array",
  "items" : {
    "type" : "integer"
  }
}
```
The `properties` attribute is never used, as the type of the object is integer, and APIGW validation works as expected.
