### ISSUE TITLE
APIs are not getting deployed on Prod stage

### ISSUE THREAD

**Issue by urvi-desai** [aws/serverless-application-model#1561]
Newly developed APIs are not deploying on Prod stage which can be seen in Resources tab in APIGateway

We are having server less architecture and we are using .Net core (netcoreapp2.1 framework) and AWS.

Below is a sample cloud formation template we are using.

```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: 'ApiGateways: APIGateway'
Transform: 'AWS::Serverless-2016-10-31'
AWS::Serverless::Api
      Properties:
      OpenApiVersion: 3.0.1
      StageName: Prod
      DefinitionUri:
        Bucket: XXX
        Key: !Ref SwaggerKey
      TracingEnabled: true
      MethodSettings:
        - DataTraceEnabled: false
          HttpMethod: '*'
          LoggingLevel: ERROR
          MetricsEnabled: true
          ResourcePath: /*
      Variables:
          API : !Ref APIFunctionName
```

We have only one Stage which is Prod.

After build deployment, in Cloudformation, when we turn "view processed template" on we can see resources with   
"Type": "AWS::ApiGateway::RestApi",   "Type": "AWS::ApiGateway::Deployment" (with APIGatewayDeployment601c725c09), "Type": "AWS::ApiGateway::Stage"

We are deploying our code through Azure devops pipeline.

**Observed result:**
First time of deployment, all APIs are deployed on Prod stage. In second time if new APIs are added then those are not getting deployed on Prod stage.

**Expected result:**
All APIs mentioned in the swagger should get deployed in Prod stage
