### ISSUE TITLE
Proposal: Edge (boolean) on Function

### ISSUE THREAD

**Issue by timoschilling** [aws/serverless-application-model#1569]
**Description:**

If you want to use `AWS::Serverless::Function` for an Lambda@edge, you need to configure a special `AssumeRolePolicyDocument` and an `AutoPublishAlias`. It would be more hany if you just say `Edge: true` on the lambda.

**Current example:**

```yaml
  DownloadRequestTokenFunctionProxy:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      AutoPublishAlias: edge
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action:
              - sts:AssumeRole
      CodeUri: .
```

**Future example:**

```yaml
  DownloadRequestTokenFunctionProxy:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Edge: true
      CodeUri: .
```

**Expected result:**

Both templates delivering the same result. `Edge: true` builds an `AssumeRolePolicyDocument` for `lambda` / `edgelambda` and sets `AutoPublishAlias` to `edge`.

**More possible use cases:**

SAM CLI cloud add validation based on it to warn for the use of layers, runtimes not supported by edge, to hight timeouts (> 30 sec)
