### ISSUE TITLE
Proposal: AWS::Serverless::Role

### ISSUE THREAD

**Issue by timoschilling** [aws/serverless-application-model#1572]
**Description:**

The AWS::Serverless::Lambda Role system with AssumeRolePolicyDocument and his Policy templates is very handy, I would like to get this power to even more use cases.

**Example before:**

```yaml
  ServiceRole:
    Type: AWS::Serverless::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - textract.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: ReadS3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource:
                  - !Sub ${TempBucket.Arn}/*
        - PolicyName: PublishSNS
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: sns:Publish
                Resource:
                  - !Ref Topic
```

**After example:**

```yaml
  ServiceRole:
    Type: AWS::Serverless::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - textract.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - S3ReadPolicy:
            Bucket: !Ref Bucket
        - SNSPublishMessagePolicy: PublishSNS
            TopicName: !Ref Topic
```
 Combined with #1573 it could look like:
```yaml
  ServiceRole:
    Type: AWS::Serverless::Role
    Properties:
      Service:
        - textract.amazonaws.com
      Policies:
        - S3ReadPolicy:
            Bucket: !Ref Bucket
        - SNSPublishMessagePolicy: PublishSNS
            TopicName: !Ref Topic
```
