### ISSUE TITLE
Proposal: simplified AssumeRolePolicyDocument

### ISSUE THREAD

**Issue by timoschilling** [aws/serverless-application-model#1573]
**Description:**

As far as I know `AWS::Serverless::Function.AssumeRolePolicyDocument` has only one use pattern

```yaml
AssumeRolePolicyDocument:
  Version: 2012-10-17
  Statement:
    - Effect: Allow
      Principal:
        Service:
          - <service>.amazonaws.com
          - <service>.amazonaws.com
      Action:
        - sts:AssumeRole
```

It would be very nice to shorten this to
```yaml
AssumeRolePolicyDocument:
  Service:
    - <service>.amazonaws.com
    - <service>.amazonaws.com
```
