### ISSUE TITLE
Change of `CertificateArn` doesn't triggers a redeploy.

### ISSUE THREAD

**Issue by timoschilling** [aws/serverless-application-model#1587]
**Description:**

I have a already deployed Stack including a Api Gateway, the `CertificateArn` is referenced from an template parameter. If I try to change this parameter I get an error.

**Steps to reproduce the issue:**
1. deploy this stack
```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  CertificateArn:
    Type: String
  Domain:
    Type: String
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    Domain:
      DomainName:
        Ref: Domain
      CertificateArn:
        Ref: CertificateArn
      EndpointConfiguration: REGIONAL
      Route53:
        HostedZoneId: XXXXXXXXX
        IpV6: true
Resources:
  ForwardInquiryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ...
      Handler: index.lambda_handler
      Timeout: 30
      Runtime: nodejs12.x
      Events:
        Event:
          Type: Api
          Properties:
            Path: /
            Method: post
```
2. create a changeset which changes the `CertificateArn` parameter to a different certificate (I used the web console)

**Observed result:**

Creating a changeset fails with
> The submitted information didn't contain changes. Submit different information to create a change set.

**Expected result:**

The stack redeploys with the new `CertificateArn`
