### ISSUE TITLE
Accept boolean values in CloudWatchEvent patterns

### ISSUE THREAD

**Issue by davidzerep** [aws/serverless-application-model#1596]
I have a Lambda that is triggered by CloudWatchEvents. I'm trying to match events that have "campaign" in their details as in [this example of the documentation](https://docs.aws.amazon.com/eventbridge/latest/userguide/content-filtering-with-event-patterns.html#filtering-exists-matching). This is the code in the lambda's Events property of my SAM template:

```
feedPost:
    Type: CloudWatchEvent
    Properties:
        EventBusName: my_bus
        Pattern:
            source:
                - mySource
            detail:
                campaign:
                    - exists: true
```

But when it is deploying, in CloudFormation the following error appears:

> Event pattern is not valid. Reason: exists match pattern must be either true or false. at [Source: (String)"{ "source":["mySource"],"detail":{"campaign":[{"exists":"true"}]}}";

So apparently it is taking the true value as a String and fails to deploy.
