### ISSUE TITLE
Secrets manager resolve for VPC endpoint ids in Rest API

### ISSUE THREAD

**Issue by sapessi** [aws/serverless-application-model#1600]
**Description:**

We want to be able to configure API Gateway's private endpoint to create a private API. The VPC endpoint IDs are resolved through secrets manager. With CloudFormation, API Gateway supports two properties in [the `EndpointConfiguration` object](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html): `Type` and an array of `VpcEndpointIds`. With SAM, [the `EndpointConfiguration` property](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-endpointconfiguration) is a string and only supports the equivalent of the `Type` property in CloudFormation. Further, the template fails validation with SAM when we use the `{{resolve:ssm:...}}` syntax for the `EndpointConfiguration`.

**Steps to reproduce the issue:**
```yaml
EndpointConfiguration:
  Types: PRIVATE
  VpcEndpointIds=["{{resolve:ssm:vpcprivatelink-api_gateway-private_vpc_endpoint_id:1}}"]
```

**Observed result:**

**Expected result:**
