### ISSUE TITLE
Can't use DependsOn stage with dynamic stages as parameter

### ISSUE THREAD

**Issue by Ownmarc** [aws/serverless-application-model#1615]
**Description:**

I have been trying to "DependsOn" the stage creation of my AWS::Serverless::Api, but it does not work in a way that let me change the stage with parameters

**Steps to reproduce the issue:**

Lets say I have this:
```
Parameters:
  ParamStage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  myApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: myApi
      StageName: !Ref ParamStage
```
Then I want something to be created when the Stage of myApi is created (so I can't just DependsOn myApi, it needs to wait for its **stage** to be created)

So, based on #313 here is what I tried that did not work :

```
ApiUsagePlanKey:
    Type: "AWS::ApiGateway::UsagePlanKey"
    DependsOn: 
      - myApi.Stage #doesn't work, it can't resolve it
      - !Sub "myApi${ParamStage}Stage" #doesn't work, it says DependsOn needs a String
      - myApidevStage #works, but this is not using my ParamStage and will not work when I use "prod" ParamStage

    Properties:
      KeyId: !Ref myApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan
```

**Observed result:**

Unresolved resource dependencies [myApi.Stage] in the Resources block of the template
Template format error: Every DependsOn value must be a string

**Expected result:**

That the Api wait for stage to be created or that we have a way to access the stage or that I can construct a string for DependsOn
