### ISSUE TITLE
Bug: References always converted into strings for Step Functions definition substitutions - Can't use a CF parameter for TimeoutSeconds attribute (Integer)

### ISSUE THREAD

**Issue by alexcasalboni** [aws/serverless-application-model#1616]
**Description:** when I create a `AWS::Serverless::StateMachine` resource, I'd like to parametrize the value of my state's `TimeoutSeconds` attribute using a CloudFormation parameter.

I've defined the parameter as follows:

```yaml
Parameters: 
  myParameter:
    Type: Number
    Default: 300
```

and I'm referencing it in my task definition as follows:

```yaml
myTask:
  Type: Task
  Resource: !GetAtt myfunction.Arn
  End: true
  TimeoutSeconds: !Ref myParameter
```

**Steps to reproduce the issue:**
1. Define a CloudFormation parameter
2. Define a Step Functions state
3. Try to reference the parameter in the `TimeoutSeconds` attribute

**Observed result:**

The deployment fails with this error message: 

> Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: Expected value of type Integer

**Expected result:**

I'd expect the deploy to succeed since the parameter type and value are valid.

My understanding is that CloudFormation treats every parameter as a string under the hood, even if you define it as `Type: Number`. But then how do I get to use this parameter as an Integer, as SAM is expecting? Is this a SAM issue or a Step Functions issue?

**Comment by bradduhon** [comment]
Glad this is being addressed already!

I just came over here to also add this is an issue when using Fn::FindInMap for instance when I have different TimeoutSeconds between dev, test & prod.

**Comment by bradduhon** [comment]
Not sure if this is the place to post this or open a new report.

This is also an issue with the retry fields: MaxAttempts & BackoffRate.

`
`
`
`MaxAttempts: 
  Fn::FindInMap: [Integration, !Ref STAGE, statesMaxAttempts]
BackoffRate:
  Fn::FindInMap: [Integration, !Ref STAGE, statesBackoffRate]`

Will convert the Integer stored in the Map to a String and throw an error on deployment. This worked in the normal Non-SAM StepFunctions resources.

**Comment by bradduhon** [comment]
Is this still being worked on the branch doesn't seem to have seen activity for a month now.

**Comment by patricknazar** [comment]
I'm spending *hours* trying to figure out a way to simply define the `Resource` attribute in a Task type State to be an ARN from a function defined in the `template.yml` file. IT CANNOT BE DONE!!! If the OP is saying their `Resource: !GetAtt myfunction.Arn` works, I'm STUMPED. You'd think a super simple thing like this would work, all the docs about it are lying, and examples just don't work!! I'm mad, yeah, this is my first angry github comment, I'm done! Dislike this for all I care, this is unacceptable!

**Comment by piersf** [comment]
This seems to still be a problem. We basically can't pass any integer values using the `DefinitionSubstitutions` property to the state machine definition template(in JSON format) residing in a different file. The only solution I've found so far is to hardcode in the state machine definition template all integer values.

**Comment by mattshep** [comment]
I encountered this issue today when trying to use the value of a parameter for the `MaxAttempts` attribute of a `Retry` block.

Template Snippets:
```
  FetchMaxRetryAttempts:
    Type: Number
    Description: "Maximum number of retry attempts for Fetch stage (default: 3)"
    Default: 3
    MinValue: 0
    MaxValue: 3
```

```
            Retry:
              -
                ErrorEquals:
                  - "States.ALL"
                IntervalSeconds: 600
                MaxAttempts: !Ref FetchMaxRetryAttempts
```

Error:
```
Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: Expected value of type Integer at /States/Fetch/Retry[0]/MaxAttempts' (Service: AWSStepFunctions; Status Code: 400; Error Code: InvalidDefinition; Request ID: 2c1fb4e0-5a62-432f-91a7-ff5e225dd903; Proxy: null)
```
