### ISSUE TITLE
AWS::Serverless::HttpApi does not support Name attribute

### ISSUE THREAD

**Issue by jkrebs** [aws/serverless-application-model#1617]
AWS::Serverless::HttpApi transforms into AWS::ApiGatewayV2::Api but it is not possible to specify the Name attribute for the resulting API resource.

`InvalidResourceException('HelloWorldApi', 'property Name not defined for resource of type AWS::Serverless::HttpApi')]`

```SAM CLI, version 0.52.0```

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-api.html

**Comment by chrisoverzero** [comment]
@rowanu It supports [both][] of those.

[both]: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html#sam-httpapi-corsconfiguration

**Comment by rowanu** [comment]
Sorry, my mistake: I was seeing the same error same error message in SAM *CLI* when trying to run `ApiGatewayV2` locally, so will move to that repo.

**Comment by shukrikhalid** [comment]
AWS::Serverless::HttpApi Name will refer to stack_name. I created multiple HttpApi but the name shown in the console is the same name which is stack_name. So far using Description attribute to differentiate list of HttpApi.

```yml
  MainApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      # Name: !Sub ${ResourceEnv}-${ResourceProject}-MainApiGateway
      Description: !Sub ${ResourceEnv}-${ResourceProject}-MainApiGateway
      StageName: !Ref ResourceEnv
```
Hope got an update from the contributor that attribute Name can use in AWS::Serverless::HttpApi 😁
