### ISSUE TITLE
Failed to publish to SAR with Error: ResultPath being null

### ISSUE THREAD

**Issue by alexcasalboni** [aws/serverless-application-model#1618]
**Description:** If you deploy a `AWS::Serverless::StateMachine` with the AWS SAM CLI it works great, but you cannot publish this app/stack to SAR.

**Steps to reproduce the issue:**
1. Define a simple app with a `AWS::Serverless::StateMachine` in it
2. Run `sam package` and `sam publish`

**Observed result:**
App publication fails with this error: 

> Error: SAM template is invalid. It cannot be deployed using AWS CloudFormation due to the following validation error: /Resources/powerTuningStateMachine/Type/Definition/States/Cleaner/ResultPath 'null' values are not allowed in templates

**Expected result:**
I'd expect to app to be published successfully, or at least I'd expect SAM CLI to provide a meaningful error.

**Comment by alexcasalboni** [comment]
@jfuss you can find the whole template here: https://github.com/alexcasalboni/aws-lambda-power-tuning/blob/917d021ce5188e75dee7e4bee0452122ce141769/template.yml

The error I get from SAR is about `ResultPath` being `null`, which is well documented and works fine when I deploy it.

**Comment by cccassidy** [comment]
I was just trying to deploy a stack with the same `ResultPath: null` setting that @alexcasalboni is using and initially saw that cfn-lint was throwing an error about the null value: `E0000 Null value at line X`.  Came across this issue after searching and I was able to deploy my stack just fine with the `null` value as well.  Maybe SAR is running cfn-lint or something similar and rejects on the error?

**Comment by cccassidy** [comment]
Found that the cfn-lint folks are tracking the issue as well:
https://github.com/aws-cloudformation/cfn-python-lint/issues/1657

**Comment by kddejong** [comment]
The CloudFormation service doesn't support `null` values.  `cfn-lint` would capture that error when parsing a template since its not supported by the CloudFormation service.  The issue with cfn-lint is resolved and I don't believe its related.  

the serverless transform should be converting this to a string ([property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-definitionstring)) which makes the template valid for CloudFormation because the null is now in a string.  You can look into cfn-lint issue above for more details on that conversion.

**Comment by xazhao** [comment]
Hello! I tried to reproduce this issue and I can publish to SAR with `ResultPath: null` in a state machine using following template. I believe this issue has been fixed. 

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Metadata:
  AWS::ServerlessRepo::Application:
    Name: my-app
    Description: hello world
    Author: user1
    SpdxLicenseId: Apache-2.0
    Labels: ['tests']
    HomePageUrl: https://github.com/user1/my-app-project
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/user1/my-app-project


Resources:
  MySampleStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        StartAt: MyLambdaState
        States:
          MyLambdaState:
            Type: Task
            Resource: ARN of a lambda function
            ResultPath: null
            End: true
      Role: ARN of an IAM Role

```

Close this issue for now and feel free to reopen if you have other questions
