### ISSUE TITLE
Cache TTL in seconds not reflecting from template

### ISSUE THREAD

**Issue by rishijavia** [aws/serverless-application-model#1620]
**Description:**
Cache TTL is not respected from Template.

**Steps to reproduce the issue:**
1. Template:
```
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Auth: 
        ApiKeyRequired: true
      CacheClusterEnabled: true
      CacheClusterSize: "0.5"
      Cors:
        AllowHeaders: "'*'"
        AllowMethods: "'*'"
        AllowOrigin: "'*'"
      Domain:
        Type: AWS::ApiGateway::DomainConfiguration
        CertificateArn: !Ref MyCertificateArn
        DomainName: !FindInMap [EnvironmentMap, !Ref Environment, MyDomain]
        EndpointConfiguration: EDGE
        Route53:
          HostedZoneId: !FindInMap [EnvironmentMap, !Ref Environment, MyHostedZone]
      MethodSettings:
        - CacheTtlInSeconds: 3600
          CachingEnabled: true
          HttpMethod: GET
          # Route: /v1/myApp/*
          ResourcePath: /~1v1~1myApp~1*
      StageName: !Ref StageName
```

I also have the following resource (dont think its relevant to this issue):
```
AWS::ApiGateway::UsagePlan
AWS::ApiGateway::ApiKey
AWS::ApiGateway::UsagePlanKey
```

**Observed result:**
This creates everything in the template accurately except for cache TTL. I also tried different values between 0 and 3600 range. 

Please see the screenshot below:
![Screen Shot 2020-06-10 at 1 12 04 PM](https://user-images.githubusercontent.com/9010879/84313869-020c0e80-ab1c-11ea-845a-a380d2997569.png)

It is also not caching my request unless I put in a number in the TTL Box manually (which gets removed by subsequent Cloudformation Deploy).

**Expected result:**
 
Cache TTL in seconds should be respected from the template.

**Comment by Karthi96** [comment]
@keetonian Do you have an update for this ?

**Comment by rishijavia** [comment]
The [Method Settings Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-stage-methodsetting.html#cfn-apigateway-stage-methodsetting-resourcepath) says:

> To specify the root path, use only a slash (/). You can use an asterisk (*) as a wildcard to apply method settings to multiple methods.

I was using a wildcard (as mentioned in the original issue) for `ResourcePath` in `MethodSettings`. This is not working so I tried to change it to `/` to have the TTL applied at base stage settings. Using `/` **does not** work either.

Ended up setting the `ResourcePath` in `MethodSettings` as full path:
```
/~1v1~1myApp~1mySubRoute~1{id}
```

Missing wildcard functionality is not ideal but this overrides base stage settings for that particular method and does the trick.

And I set my Lambda Events as the following:
```
      Events:
        GetData:
          Type: Api
          Properties:
            Path: /v1/myApp/mySubRoute/{id}
            Method: GET
            RequestParameters:
              - method.request.path.id:
                  Required: true
                  Caching: true
            RestApiId:
              Ref: ApiGateway
```
Notice the `RequestParameters` section. API Gateway will not cache a unique response for each ids if you are missing this section.

**Comment by Karthi96** [comment]
@rishijavia  Are you able to set the TTL value to API gateway ?

**Comment by rishijavia** [comment]
@Karthi96 yes, I was able to do so by specifying full path of my API route as `ResourcePath` inside of `MethodSettings`

**Comment by Karthi96** [comment]
@rishijavia could you mind help me to set TTL value to API GW. I'm also followed the same but unable to set the values? what could be error here? 

Here is YAML template for SAM.

```
Resources:
  ContentAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: Content API
      StageName: DEV
      CacheClusterEnabled: true
      CacheClusterSize: "0.5"
      MethodSettings:
        - CachingEnabled: true
          CacheTtlInSeconds: 300
          HttpMethod: GET
          ResourcePath: /~1v1~1content~1{className}~1{id}
  GetContent1:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: dist/lambdas/getContent.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ""
      MemorySize: 128
      AutoPublishAlias: live
      Timeout: 15
      Policies:
        - AmazonSSMReadOnlyAccess
      Events:
        Api1:
          Type: Api
          Properties:
            Path: "/v1/content/{className}/{id}"
            Method: GET
            RequestParameters:
              - method.request.path.id:
                  Required: true
                  Caching: true
              - method.request.path.className:
                  Required: true
                  Caching: true
            RestApiId:
              Ref: ContentAPI
```
