### ISSUE TITLE
Create a policy template for AWS Step Functions synchronous (.sync[:2]) state machine execution

### ISSUE THREAD

**Issue by rts-rob** [aws/serverless-application-model#1621]
**Description:**

Currently, the only policy template for starting an execution of an AWS Step Functions state machine is _StepFunctionsExecutionPolicy_ via the "request/response" model. To start an execution of a state machine with the "Run a Job" (.sync) model requires additional permissions.

This means that users, especially those creating nested workflows, must handcraft IAM roles when executing state machines synchronously.

I am submitting a PR separately which contains a proposed _StepFunctionsSyncExecutionPolicy_ template with the additional required permissions per the [Step Functions documentation](https://docs.aws.amazon.com/step-functions/latest/dg/stepfunctions-iam.html).

**Comment by hoffa** [comment]
[Connectors](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/managing-permissions-connectors.html) support Lambda functions executing state machines, and state machines executing state machines.

Use as such:

```yaml
MyConnector:
  Type: AWS::Serverless::Connector
  Properties:
    Source:
      Id: FunctionOrStateMachineLogicalId
    Destination:
      Id: StateMachineLogicalId
    Permissions:
      - Write
```

For reference, function-to-state machine permissions:

https://github.com/aws/serverless-application-model/blob/5e3741c05f0635135469b15db5a2feabdd263440/samtranslator/model/connector_profiles/profiles.json#L288-L310

And state machine-to-state machine permissions:

https://github.com/aws/serverless-application-model/blob/5e3741c05f0635135469b15db5a2feabdd263440/samtranslator/model/connector_profiles/profiles.json#L647-L678
