### ISSUE TITLE
Global Section:  Map doesn't merge when using intrinsic function in resource.

### ISSUE THREAD

**Issue by saurabhshri** [aws/serverless-application-model#1647]
Referring to the documentation [https://github.com/awslabs/serverless-application-model/blob/develop/docs/globals.rst#maps-are-merged](https://github.com/awslabs/serverless-application-model/blob/develop/docs/globals.rst#maps-are-merged), the maps in global and resource section are merged.

I am using this feature to define some global environment variables that stay same across all my lambdas, and then defining resource level variables in each function. This is exactly similar to what's in the documentation, and it works.

```
Globals:
  Function:
    Environment:
      Variables:
        STAGE: Production
        TABLE_NAME: global-table

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          TABLE_NAME: resource-table
          NEW_VAR: hello
```
Result:
```
{
  "STAGE": "Production",
  "TABLE_NAME": "resource-table",
  "NEW_VAR": "hello"
}
```

The issue (?) arises when I use intrinsic function (specifically Fn::If) to populate resource level environment variable. In that case globally defined environment variable do not make their way into the configuration.

```
Conditions:
  IsProd:
    Fn::Equals: [!Ref Env, prod]

Globals:
  Function:
    Environment:
      Variables:
        STAGE: Production
        TABLE_NAME: global-table

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          Fn::If:
            - IsProd
            -
              # is prod: Prod env variables
              ProdKey: ProdValue
            -
              # not prod
              DevKey: DevValue
```
Result:
```
{
  "ProdKey": "ProdValue"
}
```

Expected: 
```
{
  "STAGE": "Production",
  "TABLE_NAME": "global-table",
  "ProdKey": "ProdValue"
}
```

I am not sure if this is an expected/documented behaviour, or an actual issue. I am sorry if I missed something, but this felt natural to me and I expected it to work.

For now at least, I am re-supplying the global env variable. Is there a suggested workaround for this?

**Steps to reproduce the issue:**
1. When defining environment variables in resource section, use Fn::If method.
2. Deploy application.

Let me know if I can provide any more information. Thank you.

**Comment by elbayaaa** [comment]
Hi @saurabhshri,

I think you have an invalid syntax, the correct syntax should be something like:
```
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          keyWithDifferentValueInProdAndDev:
            Fn::If:
              - IsProd
              - ProdValue
              - DevValue
          Prodkey:
            Fn::If:
              - IsProd
              - ProdValue
              - Ref: AWS::NoValue
          Devkey:
            Fn::If:
              - IsProd
              - Ref: AWS::NoValue
              - DevValue
```
I'm going to close the issue, please feel free to reopen if you have further questions.
