### ISSUE TITLE
Canary Generated CodeDeployServiceRole doesnt use PermissionsBoundary

### ISSUE THREAD

**Issue by rasperin** [aws/serverless-application-model#1661]
**Description:**
In our AWS accounts we require the use of PermissionsBoundary, we started implementing DeploymentPreference which generates a CodeDeployServiceRole but it doesn't seem to respect the PermissionsBoundary that is put on the serverless function.

**Steps to reproduce the issue:**
1.
```
Globals:
  Function:
    Runtime: python3.8
    Timeout: 60
    MemorySize: 768
    Handler: lambda_function.lambda_handler
    PermissionsBoundary:
      Fn::Join: [ "", ["arn:aws:iam::", !Ref "AWS::AccountId", !Ref permissionBoundaryName ] ]
    DeploymentPreference:
      Enabled: true
      Type: AllAtOnce #Canary10Percent5Minutes
    Environment:
      Variables:
        region: !Sub '${AWS::Region}'
        nsuid_table_name: !Ref nsuidTableName
```
2. Deploy with aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-cloudformation.yml

**Observed result:**
CodeDeployServiceRole cannot be created (as PermissionsBoundary cannot be applied).
**Expected result:**
CodeDeployServiceRole to be created with the PermissionsBoundary attached.
