### ISSUE TITLE
AWS::Serverless::Api Auth, ApiKeyRequired, and UsagePlan property resource generation is broken for me

### ISSUE THREAD

**Issue by shivatalwar** [aws/serverless-application-model#1665]
**Description:**
```
    ServerlessRestApi:
      Type: AWS::Serverless::Api
      Properties:
        StageName: Prod
        Auth:
          ApiKeyRequired: true
          UsagePlan:
            CreateUsagePlan: PER_API
            Quota:
              Limit: 33333
              Period: DAY
```
**Observed result:**
This does not create any UsagePlan, ApiKey, or UsagePlanKey resources. This also does not set APIKey required on any methods on a fresh deploy. Is this intentional? I have tried using both sam and cloudformation package and deploy CLI tooling. 
The deployed template shows this exact representation on the console, with none of these in the resources tab or in the API Gateway console.

**Expected result:**
I expect the UsagePlan, ApiKey, or UsagePlanKey resources to be provisioned, and each method in my API in this stage to require an APIKey. 

**Separately/ As an aside**, this type of resource generation bug has also occurred surrounding API DomainName configuration. Specifically, I've had to link BasePathMappings and DomainNames using native CloudFormation because of these regressions in Serverless Transforms.
