### ISSUE TITLE
AWS::Serverless::Api - Definining `AWS_IAM` with `CALLER_CREDENTIALS` in China regions cause deployment to fail

### ISSUE THREAD

**Issue by ohadbenita** [aws/serverless-application-model#1667]
**Description:**

We're currently in the process of migrating our infrastructure to one of the AWS CN regions.
The SAM stack deployed used to work in the AWS partition with no issues.

This example fails:

````yaml
  MyExampleApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: my-api-name
      Auth:
        DefaultAuthorizer: AWS_IAM
        InvokeRole: CALLER_CREDENTIALS
````
**Steps to reproduce the issue:**

However, this one succeeds:

````yaml
  MyExampleApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: my-api-name
````
1. Define an API with AWS_IAM --> fails
2. Deploy the stack
3. Remove the stack
4. Remove the `Auth` section.
5. Re-deploy the stack --> succeeds

**Observed result:** The `Auth` section causes CloudFormation to give the following error upon creating the API resource: 

Cross-account pass role is not allowed. (Service: AmazonApiGateway; Status Code: 403; Error Code: AccessDeniedException

**Expected result:** Deployment is successful.
