### ISSUE TITLE
Api Key stage association broken?

### ISSUE THREAD

**Issue by tobiasfeil** [aws/serverless-application-model#1668]
**Description:**

I have a simple API: 
```
Globals:
  Function:
    Timeout: 3

Resources:
  ClockInAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: MyAwesomeStage
      Auth:
        ApiKeyRequired: true
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: ClockInPhoneAPIKey
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ClockInAPI
          StageName: MyAwesomeStage
  ClockInFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: clock_in/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        ClockIn:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /clockIn
            Method: post
            RestApiId: !Ref ClockInAPI

```
When commenting out the portion
```
Auth:
        ApiKeyRequired: true
```
everything works as expected.
But when uncommenting it, and sending a request in Postman that has an API key from the API Gateway Console -> API key in the header like this:
`x-api-key:<apikey>` (without the `<>`)

I get an `x-amzn-ErrorType` of `ForbiddenException`.

My console isn't showing me any associated stages for this API key either, don't know if it would if everything was working properly - I've only done it the SAM way so far.
