### ISSUE TITLE
Create (forward) dependency of implicit resources from "parent resources"

### ISSUE THREAD

**Issue by tobiasfeil** [aws/serverless-application-model#1669]
With the following template:
```
Resources:
  ClockInAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: ClockInPhoneAPIKey
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ClockInAPI
          StageName: Dev
```
I get a
```
UPDATE_FAILED                                                               AWS::ApiGateway::ApiKey                                                     ApiKey                                                                      Invalid stage identifier specified (Service: AmazonApiGateway; Status     
                                                                                                                                                                                                                                    Code: 404; Error Code: NotFoundException; Request ID:                     
                                                                                                                                                                                                                                    63573320-3089-42f5-b3b0-14e39e741905)   
```
when I do `sam build --use-container && sam deploy`. 
When I replace `Dev` with `Development`, it won't work either, However, when I name it `CantNameThisDevOrItWillBreak`, everything deploys alright.

**Comment by aahung** [comment]
First, I can reproduce it.

The issue is not stage cannot be named `Dev`, it is caused by the order of CFN creates each resources.

for `AWS::Serverless::Api` "ClockInAPI" resource, SAM will translate it into multiple resources including
- ClockInAPI (`AWS::ApiGateway::RestApi`)
- ClockInAPIDevStage (`AWS::ApiGateway::Stage`)

And the error you saw is due to CFN tries to create the "ApiKey" before "ClockInAPIDevStage."

The solution is to add a `DependsOn` to "ApiKey":

(tested)
```
  ClockInAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
  ApiKey:
    DependsOn:
      - ClockInAPIDevStage
    Type: AWS::ApiGateway::ApiKey
```

------

Similar issues can be seen in other places as well, for example, in `Function`'s event "Schedule,"

SAM translator will create `EventRule` and `Lambda::Permission`, if `EventRule` is created before `Lambda::Permission` and the event is triggered, the lambda invocation failed. However, this is less an issue.
