### ISSUE TITLE
AWS::Serverless::Function Events not able to add path to an httpapi

### ISSUE THREAD

**Issue by Ownmarc** [aws/serverless-application-model#1695]
**Description:**

When creating an Api using AWS::Serverless::HttpApi with a definition template and then creating a AWS::Serverless::Function that should create a route in this Api, it seems like SAM can't create it.

**Steps to reproduce the issue:**

in my SAM template : 
```
  MyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionUri: api/upload/upload.yaml

  FindBestMatchesFunction:
    Type: AWS::Serverless::Function
    DependsOn: MyApi
    FunctionName: FindBestMatchesFunction
    Description: Find best matches
    Properties:
      CodeUri: api/find_best_matches
      Handler: lambda_function.lambda_handler
      Policies:
        - S3ReadPolicy:
            BucketName: 'my-bucket'
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /match
            Method: POST
```

and here is my openapi definition : 

```
openapi: "3.0.1"
info:
  title: "My Api"
  version: "2020-08-30 23:01:59UTC"
paths:
  /upload:
    post:
      responses:
        default:
          description: "Default response for POST /upload"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "POST"
        uri: "http://99.99.999.999:5001/upload"
        connectionType: "INTERNET"
```

**Observed result:**

If I comment out the definition of "MyApi" in the SAM template, SAM creates the httpapi and attatch the lambda integration properly, but if I define the api with AWS::Serverless::HttpApi, it doesn't add the route to the httpapi. The Lambda function gets created but is never integrated with the httpapi.
![image](https://user-images.githubusercontent.com/24617457/92015194-6bb44700-ed1e-11ea-98ba-496cd93dcf61.png)

I have also tried to create the path in my openapi by adding this to see if the ::function could integrate my lambda function if the path was defined but no luck:

```
/match:
    post:
      operationId: FindBestMatch
```

**Expected result:**

Would expect AWS::Serverless::HttpApi Events to add path to my httpapi and integrate lambda properly.
