### ISSUE TITLE
API Resource Policies for AwsAccountBlacklist/AwsAccountWhitelist require Account ARN not ID

### ISSUE THREAD

**Issue by rmalecky** [aws/serverless-application-model#1705]
**Description:**

When trying to create an API Resource policy to allow cross account access to a Rest API get a 400 error from CloudFormation when I deploy[1].  I used the AWS::Serverless::Api>ApiAuth>ResourcePolicyStatement>AwsAccountWhitelist property and entered a list of aws account ids (ie 111122223333).  When I substitute the account ARNs (ie arn:aws:iam::111122223333:root) the process works.  The SAM specification[2] explicitly mentions account ids[3].  The rests also imply the the AwsAccountWhitelist should take a number not an ARN[4].

It appears when you create a resource policy using account IDs in the console the API converts them to ARNs, but not when suing the API.

It also appears that the translator is stripping leading 0s from account numbers.

[1] example error:

> Invalid policy document. Please check the policy syntax and ensure that Principals are valid. (Service: AmazonApiGateway; Status Code: 400; Error Code:BadRequestException; Request ID: e022e726-91df-4b19-98f3-be798a70e940; Proxy: null)

[2] https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md

[3] 
> To whitelist specific AWS accounts, add AwsAccountWhitelist: [\<list of account ids\>] under ResourcePolicy.

[4] https://github.com/aws/serverless-application-model/blob/master/tests/swagger/test_swagger.py

**Steps to reproduce the issue:**
1. update an API template with an AWS Account Whitelist
``` yml
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Auth:
        ResourcePolicy:
          AwsAccountWhitelist:
            - 111122223333
```
2. run `sam build` and `sam deploy`

**Observed result:**
the deployment fails with error [1]

**Expected result:**
the deployment succeeds and the resource policy is created.

**Comment by hoffa** [comment]
Reproducible example:

```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      Handler: foo
      InlineCode: bar
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /
            RestApiId: !Ref MyApi
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        ResourcePolicy:
          AwsAccountWhitelist:
            - 111122223333
```

Deploy:

```
sam deploy --region us-west-2 --resolve-s3 --capabilities CAPABILITY_IAM --stack-name test-1705-2 --template template.yaml
```

Fails as described.

The transformed templates includes:

```json
    "MyApi": {
      "Type": "AWS::ApiGateway::RestApi",
      "Metadata": {
        "SamResourceId": "MyApi"
      },
      "Properties": {
        "Body": {
          "info": {
            "version": "1.0",
            "title": {
              "Ref": "AWS::StackName"
            }
          },
          "paths": {
            "/": {
              "get": {
                "x-amazon-apigateway-integration": {
                  "httpMethod": "POST",
                  "type": "aws_proxy",
                  "uri": {
                    "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyFunction.Arn}/invocations"
                  }
                },
                "responses": {}
              }
            }
          },
          "swagger": "2.0",
          "x-amazon-apigateway-policy": {
            "Version": "2012-10-17",
            "Statement": {
              "Action": "execute-api:Invoke",
              "Resource": [
                {
                  "Fn::Sub": [
                    "execute-api:/${__Stage__}/GET/",
                    {
                      "__Stage__": "prod"
                    }
                  ]
                }
              ],
              "Effect": "Allow",
              "Principal": {
                "AWS": [
                  "111122223333"
                ]
              }
            }
          }
        }
      }
    }
```

**Comment by hoffa** [comment]
Ok the issue seems to be that unless a number is explicitly a string, YAML will treat it as an integer. And an integer in `Principal` isn't valid, so the deployment fails.

This succeeds (with a valid account ID):

```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      Handler: foo
      InlineCode: bar
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /
            RestApiId: !Ref MyApi
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        ResourcePolicy:
          AwsAccountWhitelist:
            - "111122223333"
```

Ideally SAM would let you know that it must be a string, but since the values are passed as-is to the policy:

https://github.com/aws/serverless-application-model/blob/43b0fc48bf1cd340d8daad4d6fd54b2288a0938f/samtranslator/swagger/swagger.py#L976

And support intrinsic functions:

https://github.com/aws/serverless-application-model/blob/43b0fc48bf1cd340d8daad4d6fd54b2288a0938f/integration/resources/templates/combination/api_with_resource_policies_aws_account.yaml#L14-L15

There's no robust way of us validating the values (see #2533). We'll update the docs to make it clear.
