### ISSUE TITLE
Handling valid JSON array WebSocket messages with SAM and API Gateway

### ISSUE THREAD

**Issue by Borduhh** [aws/serverless-application-model#1709]
**Description:**

Expect to be able to handle IoT incoming messages that are valid JSON arrays with WebSockets using the SAM `template.yaml`.

Example Message: 
```
[2,"4859659084","StatusNotification",{"connectorId":1,"errorCode":"NoError","status":"Preparing","timestamp":"2020-09-09T15:04:58.000Z","vendorErrorCode":"CABLE CONNECTED"}]
```

Example SAM Template Snippet:
```
Resources:
  # Defines API setup and routing based on request action
  StationWebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: StationWebSocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: '$request.body[2]'

  StatusNotificationHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: statusNotification.default
      CodeUri: dist
      Runtime: nodejs12.x
      Policies:
        - AWSLambdaFullAccess
        - CloudWatchLogsFullAccess
        - AmazonAPIGatewayInvokeFullAccess
        - AmazonAPIGatewayAdministrator

  StatusNotificationRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref StationWebSocketApi
      RouteKey: StatusNotification
      AuthorizationType: NONE
      OperationName: StatusNotificationRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref StatusNotificationIntegration

  StatusNotificationIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref StationWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StatusNotificationHandlerFunction.Arn}/invocations
```

If I update `RouteSelectionExpression: '$request.body[2]'` to `RouteSelectionExpression: '$request.body.action'` and send the test message:
```
{"action":"StatusNotification"}
```

Everything works as expected.

**Observed result:**
On deployment:
```
UPDATE_FAILED                    AWS::ApiGatewayV2::Api           StationWebSocketApi              Unexpected variable in         
                                                                                                   selection expression:          
                                                                                                   $request.body[2] (Service:     
                                                                                                   AmazonApiGatewayV2; Status     
                                                                                                   Code: 400; Error Code:         
                                                                                                   BadRequestException; Request   
                                                                                                   ID: 63464cd2-613c-49ca-9986-2e 
                                                                                                   906563c072; Proxy: null)   
```

**Expected result:**
Successful deployment and routing based on the third array element.
