### ISSUE TITLE
CommaDelimitedList Property with AllowedValues - Parameter must be one of AllowedValues

### ISSUE THREAD

**Issue by vtuhtan** [aws/serverless-application-model#1711]
**Description:**

I'd like to use a CommaDelimitedList parameter with AllowedValues constraint. In my case I'd like to prompt user which Code Pipeline notifications should be delivered in the stack.

**Steps to reproduce the issue:**
1. Create a SAM template as follows (I'll omit Pipeline and SNSTopic creation):
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  NotificationEvents:
    Type: CommaDelimitedList
    Default: "codepipeline-pipeline-pipeline-execution-failed"
    AllowedValues:
      - codepipeline-pipeline-action-execution-succeeded
      - codepipeline-pipeline-action-execution-failed
      - codepipeline-pipeline-action-execution-canceled
      - codepipeline-pipeline-action-execution-started
      - codepipeline-pipeline-stage-execution-started
      - codepipeline-pipeline-stage-execution-succeeded
      - codepipeline-pipeline-stage-execution-resumed
      - codepipeline-pipeline-stage-execution-canceled
      - codepipeline-pipeline-stage-execution-failed
      - codepipeline-pipeline-pipeline-execution-failed
      - codepipeline-pipeline-pipeline-execution-canceled
      - codepipeline-pipeline-pipeline-execution-started
      - codepipeline-pipeline-pipeline-execution-resumed
      - codepipeline-pipeline-pipeline-execution-succeeded
      - codepipeline-pipeline-pipeline-execution-superseded
      - codepipeline-pipeline-manual-approval-failed
      - codepipeline-pipeline-manual-approval-needed
      - codepipeline-pipeline-manual-approval-succeeded
....
  Notifications:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      DetailType: BASIC
      EventTypeIds: !Ref NotificationEvents
      Name: !Sub ${ServiceName}_codepipeline_notifications_rule
      Resource: !Sub
        - arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PIPELINE}
        - PIPELINE: !Ref Pipeline
      Targets:
        - TargetAddress: !Ref SNSTopic
          TargetType: SNS
```
2. `sam build`
3. `sam deploy --guided`
4. Enter comma separated values for the parameter:
`Parameter NotificationEvents [codepipeline-pipeline-pipeline-execution-failed]: codepipeline-pipeline-pipeline-execution-failed,codepipeline-pipeline-pipeline-execution-succeeded`

**Observed result:**
Error: Failed to create changeset for the stack: _stack_name_, An error occurred (ValidationError) when calling the CreateChangeSet operation: Parameter 'NotificationEvents' must be one of AllowedValues

**Expected result:**
Parameter values got resolved as array.
