### ISSUE TITLE
Conditional statments not works in AWS::Serverless::Function Events

### ISSUE THREAD

**Issue by pandithdurai** [aws/serverless-application-model#1724]
**Description:**

Conditional statements not works in AWS::Serverless::Function Events

!If [condition, true, false]
```
  APILambda:
    Type: AWS::Serverless::Function
    DependsOn:
      - IAMLambda
    Properties:
      Events:
        HealthcheckEvent:
          Properties:
            RestApiId:
              Ref: APIGateway

            Path: /healthcheck
            Method: GET
            **Auth:
              ApiKeyRequired: !If [CreateProdResources, true, false]**
```

**Observed result:**
Not changing API Key required to true or false in conditional statements
**Expected result:**
It should change true from false or false from true when use conditional statements but nothing changes and no error message
[sam_template.yml.txt](https://github.com/aws/serverless-application-model/files/5275170/sam_template.yml.txt)
