### ISSUE TITLE
Creating an OAuth2Authorizer fails silently if the issuer of certificate provided by the issuer's JWKS endpoint does not match JWT issuer domain

### ISSUE THREAD

**Issue by rdowinton** [aws/serverless-application-model#1727]
**Description:**

Creating an authorizer via a SAM template fails silently if the issuer of the certificates provided by `${issuer}/.well-known/jwks.json` do not match the JWT issuer domain. You will find the deploy appears successful in the console but the authorizer is not actually created.

Creating the authorizer with exactly the same properties via the CLI or dashboard works fine. It seems this validation only occurs via SAM deployments.

Works:
```
Auth:
  DefaultAuthorizer: Auth0Authorizer
  Authorizers:
    Auth0Authorizer:
      JwtConfiguration:
        issuer: "https://rd-paid.eu.auth0.com/"
        audience:
          - "https://api.auth.yoga"
        IdentitySource: "$request.header.Authorizer"
```

Fails:
```
Auth:
  DefaultAuthorizer: Auth0Authorizer
  Authorizers:
    Auth0Authorizer:
      JwtConfiguration:
        issuer: "https://a0.auth.yoga/"
        audience:
          - "https://api.auth.yoga"
        IdentitySource: "$request.header.Authorizer"
```

Certificate issuer in this example is `rd-paid.eu.auth0.com`. You can reproduce it yourself with the above excerpt.

**Steps to reproduce the issue:**
1. Add to your `template.yml` an `AWS::Serverless::HttpApi` resource with an `OAuth2Authorizer` whose JWKS endpoint returns a certificate whose issuer does not match the domain of the `issuer` value in the `JwtConfiguration`.
2. Deploy via `sam deploy --guided`.
3. Upon completion check the AWS dashboard. Despite the deploy appearing successful in the console the authorizer will not have been created.
4. Now change the `issuer` value in `JwtConfiguration` to contain the same domain in the `Issuer` of the certificate provided by your JWKS endpoint. Perform the same deploy and it should work.

**Observed result:**
Authorizer is not created.

**Expected result:**
Authorizer is created.

**Comment by sriram-mv** [comment]
I actually am not able to re-create this with both the HttpApiAuth properties that are mentioned in the issue.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunctionAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: Auth0Authorizer
        Authorizers:
          Auth0Authorizer:
            JwtConfiguration:
              issuer: "https://rd-paid.eu.auth0.com/"
              audience:
                - "https://api.auth.yoga"
          IdentitySource: "$request.header.Authorizer"
```


and

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunctionAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: Auth0Authorizer
        Authorizers:
          Auth0Authorizer:
            JwtConfiguration:
              issuer: "https://a0.auth.yoga/"
              audience:
                - "https://api.auth.yoga"
          IdentitySource: "$request.header.Authorizer"

```

![Screen Shot 2021-05-13 at 4 08 48 PM](https://user-images.githubusercontent.com/3770774/118198369-94d8bb80-b405-11eb-9303-0f8be672fa19.png)
![Screen Shot 2021-05-13 at 4 07 31 PM](https://user-images.githubusercontent.com/3770774/118198375-97d3ac00-b405-11eb-9a7a-c3b0b01a93bc.png)

Next up, I tried a completely made up issuer. 

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunctionAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: Auth0Authorizer
        Authorizers:
          Auth0Authorizer:
            JwtConfiguration:
              issuer: "https://myawesomeissuer.com/"
              audience:
                - "https://api.auth.yoga"
            IdentitySource: "$request.header.Authorizer"
```

Now this one does not show up, however the deployment goes through and succeeds.

Next up checking the native CFN on this.
