### ISSUE TITLE
EcsRunTaskPolicy should take ECS ARN, not task definition (family:revision)

### ISSUE THREAD

**Issue by smatsumt** [aws/serverless-application-model#1740]
**Description:**

"EcsRunTaskPolicy" policy template in [`policy_templates.json`](https://github.com/aws/serverless-application-model/blob/develop/samtranslator/policy_templates_data/policy_templates.json) takes one argument, `TaskDefinition`. It is assumed to be (family:revision), e.g. "EcsTaskName:1"

But `Ref` for `AWS::ECS::TaskDefinition` returns Task's ARN. So, following code would not work.

```yaml
Resources:
  SomeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - EcsRunTaskPolicy
           TaskDefinition: !Ref SomeECSTaskDefinition

  SomeECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
```

If `TaskDefinition` argument takes ARN format, the above code would work. We can refer ECS task definition in the CloudFormation template.

I think `TaskDefinition` should takes ARN format. How about it?
