### ISSUE TITLE
Functions can try to create EventBridgeRules with invalid target IDs

### ISSUE THREAD

**Issue by farski** [aws/serverless-application-model#1742]
**Description:**

When creating an Lambda function with inline `EventBridgeRule` events, the `target` property of the translated rules use an ID value of `self.logical_id + "LambdaTarget"`. Logical ID in this case is the logical ID of function itself, concat the name given to the event. So if those two things combine to more than ~52 characters, the attempt to create the rule will fail with an invalid id.

**Steps to reproduce the issue:**
1. Create a function with a resource name like `CdPipelineEventsTargetLambdaFunction`
2. Add an event with a name like `ActionsEventsRule`
3.

**Observed result:**

> 1 validation error detected: Value 'CdPipelineEventsTargetLambdaFunctionActionsEventsRuleLambdaTarget' at 'targets.1.member.id' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: d7368367-3408-45ba-a8d2-8117e4c5e771; Proxy: null)

**Expected result:**

Some sort of truncation, I guess, to ensure that the rule can be created

**Comment by hawflau** [comment]
Closing as PR is already merged and released in v1.29.0

**Comment by lobodpav** [comment]
Today I have deployed the lambda below using `aws-sam-cli v1.33.0`, and the same issue appeared. The same happens when the event type is `EventBridgeRule`.

### Lambda definition
```yaml
  SomeLambdaFunctionWithALongName:
    Type: AWS::Serverless::Function
    Properties:
      Description: SuperCoolLambdaFunction
      Handler: com.example.SuperCoolLambdaFunction::handleRequest
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        SuperCoolLambdaFunction:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - "aws.batch"
              detail-type:
                - "Batch Job State Change"
              detail:
                status:
                  - "FAILED"
                jobQueue:
                  - "Queue name"
```

### The error during `sam deploy`
```
CREATE_FAILED AWS::Events::Rule SomeLambdaFunctionWithALongNameSuperCoolLambdaFunction

1 validation error detected: Value 'SomeLambdaFunctionWithALongNameSuperCoolLambdaFunctionLambdaTarget' at 'targets.1.member.id' failed to satisfy constraint:
Member must have length less than or equal to 64 (Service: AmazonCloudWatchEvents;
Status Code: 400; Error Code: ValidationException;  
Request ID: d49015b6-1ae6-4746-b467-54a0dfdc8b98; Proxy: null)                                        
```
