### ISSUE TITLE
feature-request: Support multiple options in Function::CodeUri section

### ISSUE THREAD

**Issue by godrose** [aws/serverless-application-model#1746]
**Description:**

Need more options for specifying the code to be packaged before deployment

I have a case when there's certain replaceable part of the code which is required only for the certain configuration of the lambdas. I want to be able to omit if from the package so it never gets deployed.
This of course is relevant for the runtimes when there's no actual compilation artifacts, like `Node`

I was thinking about something like:

```yaml
Globals:
  Function:
    CodeUri: ./src |
      !./src/folder-i-want-to-omit
``` 

In short something like `.gitignore`. I would call this `.samignore` ;)
