### ISSUE TITLE
AWS::Serverless::Function AuthorizationScopes not being taken

### ISSUE THREAD

**Issue by elizeire** [aws/serverless-application-model#1752]
Issue: OAuth Scopes are empty at Method Request Settings using Cloudformation and AWS-SAM

Apparently there are a few places where I can declare my authorization scopes, if I got it right, I should declare all scopes at the authorizer and the ones I would like to specify per function at my Function template.

This is the template I am trying to fix:
```
MyServerlessFn
 Type: AWS::Serverless::Function
    Properties:
      FunctionName: helloWorldFn
      Description: my test using cognito.
      Handler: src/handlers/helloWorld.handler
      Runtime: nodejs12.x
      Events:
        ApplicationPostAPI:
          Type: Api
          Properties:
            Auth:
              AuthorizationScopes:
                - https://foobar.acme.net/full-api
            Method: POST
            Path: /hello/world
            RestApiId: !Ref MyServerlessApi
```

using sam cli I can validate, build and deploy this template but the oauthScopes are empty when I check it using AWS web console.

**Comment by sriram-mv** [comment]
Authorization Scopes will apply if you have an authorizer present. https://github.com/aws/serverless-application-model/blob/develop/tests/translator/input/api_with_auth_with_default_scopes.yaml has an example of when authorization scopes are set at function event source level.

**Comment by sriram-mv** [comment]
However, SAM can be more intelligent in this space and suggest a meaningful error message, so keeping it open for that.

**Comment by sukruavcuoglu** [comment]
> Authorization Scopes will apply if you have an authorizer present. https://github.com/aws/serverless-application-model/blob/develop/tests/translator/input/api_with_auth_with_default_scopes.yaml has an example of when authorization scopes are set at function event source level.

Trying to override the scopes with the similar implementation does not work either.

**Comment by igorassilva** [comment]
I have the same problem and I fix it just adding the `Authorizer` between `Auth` and `AuthorizationScope`, like this:

```yml
MyServerlessFn
 Type: AWS::Serverless::Function
    Properties:
      FunctionName: helloWorldFn
      Description: my test using cognito.
      Handler: src/handlers/helloWorld.handler
      Runtime: nodejs12.x
      Events:
        ApplicationPostAPI:
          Type: Api
          Properties:
            Auth:
              Authorizer:
                AuthorizationScopes:
                  - https://foobar.acme.net/full-api
            Method: POST
            Path: /hello/world
            RestApiId: !Ref MyServerlessApi
```

**Comment by MartijnKooij** [comment]
I'm facing the same issue on an API that has been deploying/working fine. Made a small change last Tuesday touching the "API gateway" part, since that deploy my scopes are no longer being applied to the paths.

All variants that I try cause Cloudformation deploy errors. So @igorassilva's version does not work for me, nor does the variant as listed in the unit/e2e tests: https://github.com/aws/serverless-application-model/blob/develop/tests/translator/input/api_with_auth_with_default_scopes_openapi.yaml.

We can configure it manually in API Gateway for now but that's of course not ideal.

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Serverless API

Parameters:
    Environment:
        Type: String
        AllowedValues:
            - dev
            - prod
        Description: Enter dev/prod

Mappings:
    EnvironmentMap:
        dev:
            domain: dev.mysite.com
        prod:
            domain: mysite.com

Resources:
    MyAppApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: prod
            Auth:
                Authorizers:
                    CognitoAuthorizer:
                        UserPoolArn: arn:aws:cognito-idp:eu-west-1:xxx
                        Type: COGNITO_USER_POOLS
                DefaultAuthorizer: CognitoAuthorizer
                AddDefaultAuthorizerToCorsPreflight: false
                ApiKeyRequired: false
            Domain:
                CertificateArn: arn:aws:acm:us-east-1:xxx:certificate/xxx
                DomainName:
                    !FindInMap [EnvironmentMap, !Ref Environment, domain]
                EndpointConfiguration: EDGE
                SecurityPolicy: TLS_1_2
                Route53:
                    HostedZoneId: XXX
            Cors:
                AllowMethods: "'OPTIONS, GET, PUT, POST, DELETE'"
                AllowHeaders: "'*'"
                AllowOrigin: "'*'"
    MyAppApiLambda:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ApiCatchAllEvent:
                    Type: Api
                    Properties:
                        Auth:
                            Authorizer: CognitoAuthorizer
                            AuthorizationScopes:
                                - MyApp.api
                        Path: /{data+}
                        Method: any
                        RestApiId:
                            Ref: MyAppApi
            FunctionName:
                Fn::Sub:
                    - MyApp-api-${Environment}
                    - Environment: !Ref Environment
            Handler: index.handler
            Runtime: nodejs18.x
            Architectures:
                - arm64
            Environment:
              Variables:
                NODE_ENV: production
                NODE_OPTIONS: --enable-source-maps
            CodeUri: ../dist
            Description: Serverless API function to interact with the MyApp DynamoDb data
            MemorySize: 512
            Timeout: 5
            ReservedConcurrentExecutions: 10
            Role: !GetAtt MyAppApiLambdaRole.Arn
    MyAppApiLambdaRole:
        Type: AWS::IAM::Role
        Properties:
            Path: '/'
            RoleName:
                Fn::Sub:
                    - MyApp-api-role-${Environment}
                    - Environment: !Ref Environment
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - lambda.amazonaws.com
                      Action: 'sts:AssumeRole'
            Policies:
                - PolicyName: MyAppApiPolicy
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Effect: Allow
                            Action:
                                - 'dynamodb:*'
                            Resource:
                                - arn:aws:dynamodb:eu-west-1:xxx
                          - Effect: Allow
                            Action:
                                - 's3:*'
                            Resource:
                                - arn:aws:s3:::xxx.com/*
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

```

**Comment by MartijnKooij** [comment]
Wait, sorry, I jumped to the wrong conclusion! It DOES work. During all of my attempts I also made another unrelated change (certificate ARN) that broke the deploy, and I judged the CFM fail too quickly assuming it was the same error.

So I think @igorassilva's solution would work, I'm using the style from the linked test now:
```yaml
ApiCatchAllEvent:
    Type: Api
    Properties:
        Auth:
            Authorizer: MyCognitoAuthorizer
            AuthorizationScopes:
            - my.api/my.api
        Path: /{data+}
        Method: any
        RestApiId:
            Ref: MyApi

```
