### ISSUE TITLE
Allow previously created Authorizer for AWS::Serverless::HttpApi

### ISSUE THREAD

**Issue by iRoachie** [aws/serverless-application-model#1785]
**Description:**

Currently, SAM Creates a new authorizer for `AWS::Serverless::HttpApi` when adding an Auth property. At our company, auth is managed in a central location with user pools, resource servers, user pool clients, and authorizers. This makes it easier to change permissions of app clients across different APIs without having to redeploy each application.

Ideally, I'd like to reference an already created Oauth2Authorizer to use in my sam template.

**Example Usage**

```yaml
Type: AWS::Serverless::HttpApi
Properties:
  Auth: 
    Authorizers:
      Authorizer: !Ref MyPreviouslyCreatedAuthorizer (Ref to AWS::ApiGatewayV2::Authorizer)
      AuthorizationScopes: ['users/read']
```

I'm willing to attempt implementing this if this features aligns with the project roadmap. Let me know 👋
