### ISSUE TITLE
RoleArn for AWS::Serverless::StateMachine EventSource/Schedule

### ISSUE THREAD

**Issue by vyazkov** [aws/serverless-application-model#1789]
**Description:**

For a Schedule under AWS::Serverless::StateMachine, it's not possible to specify my own Role. Instead, a new role is created.

**Steps to reproduce the issue:**

Specify in sam template  AWS::Serverless::StateMachine with a Schedule (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-schedule.html).
Run sam build && sam deploy

**Observed result:**

A new Role is automatically created

**Expected result:**

I'd like to provide my own RoleArn, like it's possible for AWS::Events::Rule

**Comment by wchengru** [comment]
Hi @vyazkov ! 
The property `Role` in `AWS::Serverless::StateMachine` will pass in a RoleArn according to the [document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-rolearn ). You can pass in your own RolaArn.
I have tried deploy with a sample template below with my RoleArn, no new Role is created. Can you please provide us a sample template you used to reproduce the issue?
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  StateMachine:
    Type: 'AWS::Serverless::StateMachine'
    Properties:
      Type: STANDARD
      Definition:
        Comment: An example ASL file for nested workflows
        StartAt: NestedStateOne
        States:
          NestedStateOne:
            Type: Pass
            Result:
              Value: 1
            Next: NestedStateTwo
          NestedStateTwo:
            Type: Pass
            Result:
              Value: 2
            End: True
      Role: arn:aws:iam::123456789:role/service-role/SampleRole
```
