### ISSUE TITLE
CodeUri overriding InlineCode 

### ISSUE THREAD

**Issue by dehli** [aws/serverless-application-model#1820]
**Description:**

**Steps to reproduce the issue:**
1. Create an `AWS::Serverless::Function` with both `InlineCode` and `CodeUri` properties set.

**Observed result:**
`CodeUri` is uploaded to the lambda function

```yml
Function:
  Type: AWS::Serverless::Function
  Properties:
    AutoPublishAlias: live
    Handler: index.handler
    Role:
      Fn::GetAtt:
      - Role
      - Arn
    Runtime: nodejs10.x
    InlineCode: "code"
    CodeUri: s3://...
```

is processed into:

```js
"Function": {
  "Type": "AWS::Lambda::Function",
  "Properties": {
    "Handler": "index.handler",
    "Code": {
      "S3Bucket": "bucket",
      "S3Key": "key"
    },
    "Role": {
      "Fn::GetAtt": [
        "Role",
        "Arn"
      ]
    },
    "Runtime": "nodejs10.x",
    "Tags": [
      {
        "Value": "SAM",
        "Key": "lambda:createdBy"
      }
    ]
  }
}
```

**Expected result:**
`InlineCode` is uploaded to the lambda function (this is the old behavior as of ~1-2 days ago).

```yml
Function:
  Type: AWS::Serverless::Function
  Properties:
    AutoPublishAlias: live
    Handler: index.handler
    Role:
      Fn::GetAtt:
      - Role
      - Arn
    Runtime: nodejs10.x
    InlineCode: "code"
    CodeUri: s3://...
```

is processed into:

```js
"Function": {
  "Type": "AWS::Lambda::Function",
  "Properties": {
    "Handler": "index.handler",
    "Code": {
      "ZipFile": "code"
    },
    "Role": {
      "Fn::GetAtt": [
        "Role",
        "Arn"
      ]
    },
    "Runtime": "nodejs10.x",
    "Tags": [
      {
        "Value": "SAM",
        "Key": "lambda:createdBy"
      }
    ]
  }
}
```

The reason I ran into this issue is that `aws cloudformation package` results in setting `CodeUri` even when having `InlineCode` set. This might be due to my specific version of the aws cli. I didn't realize this was the case until starting to look into this issue.

I think ideally this would throw an error rather than defaulting to `CodeUri`. Another option would be to revert back to the old behavior (where `InlineCode` takes precedence over `CodeUri`). Let me know if you need any more information! Thanks!

**Comment by zsaplan** [comment]
We are running into this same behavior

**Comment by dehli** [comment]
@zsaplan My workaround was to manually remove `CodeUri` after running `aws cloudformation package` for the resources that had them both set. This ensured that the code that would be deployed is `InlineCode`

**Comment by wchengru** [comment]
Hi @dehli and @zsaplan , can you please let me know how you generate the transformed template? I have tested the template below with SAM translator 1.31.1 and SAM CLI 1.11.0.
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - Role
        - Arn
      Runtime: nodejs10.x
      InlineCode: "code"
      CodeUri: s3://bucket/key
```
The transformed template is the expected one:
```
    "Function": {
      "Type": "AWS::Lambda::Function", 
      "Properties": {
        "Handler": "index.handler", 
        "Code": {
          "ZipFile": "code"
        }, 
        "Role": {
          "Fn::GetAtt": [
            "Role", 
            "Arn"
          ]
        }, 
        "Runtime": "nodejs10.x", 
        "Tags": [
          {
            "Value": "SAM", 
            "Key": "lambda:createdBy"
          }
        ]
      }
    }
```

**Comment by dehli** [comment]
Thanks @wchengru! I didn't manually generate the transformed template (I let CloudFormation handle that via `aws cloudformation deploy`). I determined my transform by clicking here: 

![image](https://user-images.githubusercontent.com/5856011/99850586-9c509380-2b4b-11eb-877b-48051c3601a0.png)

This is what my transform is set as (seems to be the same).

```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
```

Let me know if there's something else I can surface! Best.

**Comment by dehli** [comment]
So I was able to reproduce the issue with a minimal example. Simply run `aws cloudformation deploy` with the following template and you'll see that the processed template uses `CodeUri` rather than `InlineCode`.

```yml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      InlineCode: "foo"
      CodeUri: s3://bucket/key
```

**Comment by wchengru** [comment]
Thanks @dehli ! I can reproduce this issue with your example. We will investigate it, and work with cloudformation team on it.

**Comment by wchengru** [comment]
Also @dehli , `InlineCode` and `CodeUri` shouldn't appear together in the same template. Please remove one of them and try with the correct template.

**Comment by dehli** [comment]
Thanks! Ya, that's what I've done to fix the issue. I created this mostly because I didn't want it to result in a bug with other peoples code. In our case, we were unknowingly setting both keys (seems to be due to `aws cloudformation package`).

**Comment by quangvnm** [comment]
I second what @dehli has said, since long time ago (at least half a year ago based on old artifact), `aws cloudformation package` always force `CodeUri` property on resource `AWS::Serverless::Function` even if `InlineCode` is already defined.
This doesn't cause any issue till recently where Transform begins to take preference of `CodeUri` instead of `InlineCode` and it breaks every Inline function we have.

If I tried to do the transform manually with `bin/sam-translate.py`, the output-template is correct though. So maybe sam-translator is different?

**Comment by brewneaux** [comment]
Is https://github.com/aws/aws-sam-cli/issues/2388 also caused by this?

**Comment by jfuss** [comment]
We are rolling back some changes. Please give this about an hour to reflect. Sorry for the impact this might have caused.

@dehli @quangvnm @brewneaux

**Comment by quangvnm** [comment]
Thank @jfuss , it returns back to normal, even though the CodeUri still exists, I will fire a bug about this on aws-cli repo.

Could you tell us what has been changed and why the sam-translator behavior is different between AWS Cloudformation Service and manual execution of bin/sam-translate.py, please?

**Comment by dehli** [comment]
Thanks @jfuss! 👍 Also, I found https://github.com/aws/aws-cli/issues/3763 which seems to be the issue with the CLI @quangvnm

**Comment by sapessi** [comment]
> Thank @jfuss , it returns back to normal, even though the CodeUri still exists, I will fire a bug about this on aws-cli repo.
> 
> Could you tell us what has been changed and why the sam-translator behavior is different between AWS Cloudformation Service and manual execution of bin/sam-translate.py, please?

We were deploying an internal change that altered the way the SAM translator processes the `CodeUri`/`InlineCode` properties. The change caused the `CodeUri` to override the `InlineCode` property where both were specified. We have added an integration test to cover this edge case and ensure there are no regressions going forward.

**Comment by dehli** [comment]
Thanks for the transparency and quick turnaround! Just verified that the processed template is using `InlineCode` over `CodeUri` (see attached image). I'll go ahead and close this!
<img width="361" alt="Screen Shot 2020-11-21 at 07 06 58" src="https://user-images.githubusercontent.com/5856011/99876932-4ec63c00-2bc8-11eb-90bb-c9bc0c7527b7.png">

**Comment by divyeshramani** [comment]
If you deploy with template like below it works

```
Transform: AWS::Serverless-2016-10-31

Description: Lambda Deployment

Resources: 
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.11
      MemorySize: 128
      Handler: index.handler
      Policies: AmazonEC2FullAccess
      Timeout: 300
      InlineCode: |
        import boto3

        def handler(event, context):
          print(event)
```
