### ISSUE TITLE
Lambda Custom integration support

### ISSUE THREAD

**Issue by alikian** [aws/serverless-application-model#1841]
There are cases we want to remove certain values from http request header before calling lambda. For example we don't Lambda see API Key value, or other credential.

This is not possible using Lambda Proxy integration. We need some support for custom integration of Lambda so we can use request template to modify request.

The serverless framework currently support that, and  SAM missing this feature. It would be great if we can add following to lambda event type 
```
integration: lambda
          request:
            template:
              text/xhtml: '{ "stage" : "$context.stage" }'
              application/json: '{ "httpMethod" : "$context.httpMethod" }'
```

Thanks,
Ali
