### ISSUE TITLE
Removing autoscaled provisioned concurrency leaves provisioned concurrency behind

### ISSUE THREAD

**Issue by JackKelly-Bellroy** [aws/serverless-application-model#1846]
**Description:**

We temporarily deployed autoscaling to the ProvisionedConcurrency of a Lambda function deployed using SAM, and after removing the `AWS::ApplicationAutoScaling::ScalableTarget` and `AWS::ApplicationAutoScaling::ScalingPolicy`, the function is left with whatever provisioned concurrency the autoscaling set.

**Steps to reproduce the issue:**
1. Deploy an initial autoscaling stack:
  * An `AWS::Serverless::Function` with an `AutoPublishAlias` and (because of e.g., #1425, #1298, #1296) `DeploymentPreference: { Type: AllAtOnce }`;
  * an `AWS::ApplicationAutoScaling::ScalableTarget` scaling the `lambda:function:ProvisionedConcurrency` of the Lambda; and
  * an `AWS::ApplicationAutoScaling::ScalingPolicy` that will adjust the `ScalableTarget`.
2. Allow the stack to scale up the provisioned concurrency, either with scheduled scaling or by calling it enough times to trip the High alarm and make it grow.
3. Remove both `AWS::ApplicationAutoScaling` resources from the template.
4. Update the stack.

**Observed result:**

Any provisioned concurrency set by the autoscaling remains.

**Expected result:**

No provisioned concurrency is set on the function alias.

**Speculation:**

Once the autoscaling resources are removed from the stack, nothing seems to have any opinion about what the ProvisionedConcurrency of the function should be. Drift detection on the affected stack reports `IN_SYNC`.

**Other things tried:**

I tried setting `ProvisionedConcurrencyConfig: { ProvisonedConcurrentExecutions: 0 }` on the `AWS::Serverless::Function` after removing autoscaling, but `ProvisionedConcurrentExecutions` must be ≥1 and the stack fails to deploy with `Value '0' at 'provisionedConcurrentExecutions' failed to satisfy constraint: Member must have value greater than or equal to 1`. This seems wrong - how else can you turn off provisioned concurrency? Should it be reported somewhere?

**Comment by wynged** [comment]
I used the suggestion in this post to conditionally exclude the configuration.  https://blog.shikisoft.com/aws-cloudformation-no-value-pseudo-parameter/ 

Still didn't manage to get ProvisionedConcurrency up and running though, 😂 too many issues with getting alias and versions to update

**Comment by uehondor** [comment]
Hi @JackKelly-Bellroy @wynged 
I was able to solve this with the following:

```yaml
...
MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: function.handler
      ProvisionedConcurrencyConfig:
        !If
          - YourConditionHere
          -
            ProvisionedConcurrentExecutions: !Ref LambdaProvisionedConcurrency
          - !Ref "AWS::NoValue"
...
```

When `YourConditionHere` is false, `ProvisionedConcurrencyConfig` is set to `!Ref "AWS::NoValue"` which disables provisioned concurrency for the lambda completely.
You could also use `YourConditionHere` condition for the autoscaling policy definition so both autoscaling policy, target and provisioned concurrency on lambda are enabled/disabled together.

I hope this helps.
