### ISSUE TITLE
Cannot set HttpApi Event Type on AWS::Serverless::StateMachine

### ISSUE THREAD

**Issue by davingreen** [aws/serverless-application-model#1851]
I'm attempting to configure step functions to be triggered from an HttpApi (rather than a REST api). Here is my template:

```
  APIGatewayDeployment:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref pStage
    DefinitionBody:
        info:
          title: !Ref AWS::StackName
          version: "1.0"
        openapi: 3.0.1

  MyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachines/MyStateMachine.asl.json
      DefinitionSubstitutions:
        MyFunction: !GetAtt MyFunction.Arn
      Events:
        HttpAPIGateway:
          Type: HttpApi
          Properties:
            Path: /inbound
            Method: post
            ApiId: !Ref APIGatewayDeployment
      Policies: 
        - LambdaInvokePolicy:
            FunctionName: !Ref MyFunction
```

This builds, but fails validation or deployment with the following:
`Error: Failed to create changeset for the stack: , ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [MyStateMachine] is invalid. Event with id [HttpAPIGateway] is invalid. Resource dict has missing or invalid value for key Type. Event Type is: HttpApi.`

If I've done something wrong, let me know! I've been unable to find helpful documentation about using HTTP rather than REST with step functions.

**Comment by peterwmwong** [comment]
This would help our team aswell if `HttpApi` was a supported event source.
We tried to work around this by defining the necessary CloudFormation resources manually (extending the example above)...

```yaml
MyStateMachine:
  Type: AWS::Serverless::StateMachine
  # ... The State Machine configuration

MyStateMachineIntegrationRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: 2012-10-17
      Statement:
        - Sid: MyStateMachineIntegrationStartExecuteStateMachines
          Effect: Allow
          Principal:
            Service:
              - apigateway.amazonaws.com
          Action:
            - states:StartExecution

MyStateMachineIntegration:
  Type: AWS::ApiGatewayV2::Integration
  Properties:
    ApiId: !Ref HttpApiGateway
    IntegrationType: AWS_PROXY
    IntegrationSubtype: StepFunctions-StartExecution
    PayloadFormatVersion: 1.0
    CredentialsArn: !GetAtt MyStateMachineIntegrationRole.Arn
    RequestParameters:
      Input: "$request.body"
      StateMachineArn: !Ref MyStateMachine

MyStateMachineRoute:
  Type: AWS::ApiGatewayV2::Route
  DependsOn:
    - MyStateMachineIntegration
  Properties:
    ApiId: !Ref HttpApiGateway
    RouteKey: "POST /startMyStateMachine"
    AuthorizationType: NONE
    Target: !Join
      - /
      - - integrations
        - !Ref MyStateMachineIntegration
```

... Which worked for me, **BUT is not secure** as there doesn't seem to be a way to link the Authorizer created by SAM...

```yaml
HttpApiGateway:
  Type: AWS::Serverless::HttpApi
  Properties:
    # ... more configuration
    Auth:
      Authorizers:
        OAuth2Authorizer:  # <<<-- How do I reference the Authorizer ID created here in my `AWS::ApiGatewayV2::Route`
          # ...more configuration
```

Related: #1050

In the end, I've had to fall back to create a separate lambda (connected to the Http Api Gateway) that starts the state machine.  Alternatively, maybe I could have 
 defined another Authorizer with the same exact configuration as the one defined by SAM and reference that.  In either case, not ideal, and would love for this to just work™.
