### ISSUE TITLE
Intrinsic VPC and VPCE Whitelists and Blacklists should support all intrinsic functions

### ISSUE THREAD

**Issue by dinkzilla** [aws/serverless-application-model#1852]
**Description:**

The IntrinsicVpcWhitelist, InstrinsicVpcBlackList, IntrinsicVpceWhitelist, and IntrinsicVpceBlacklist currently only support the Ref function; however, allowing the use of the full suite of intrinsic functions would be useful. For example, ImportValue and Sub would allow you to get Vpc Ids from other stacks. 

Example:

```
     Auth:
        ResourcePolicy:
          IntrinsicVpcWhitelist:
            - Fn::ImportValue: !Sub ${BaseInfrastructureStack}-VpcId
```
