### ISSUE TITLE
StepFunctionsExecutionPolicy is resolved into unusable permission definition

### ISSUE THREAD

**Issue by TLaue** [aws/serverless-application-model#1855]
By using the default StepFunctionsExecutionPolicy in a SAM template using the following syntax:

```
...
   Type: 'AWS::Serverless::Function'
    Properties:
      Policies:
               - StepFunctionsExecutionPolicy:
                       StateMachineName: !Ref TestProcessStateMachine 
...
```
an unsable IAM policy document is created as the resource arn contains some duplicate parts:
        
```
"policies": [
    {
      "document": {
        "Statement": [
          {
            "Action": [
              "states:StartExecution"
            ],
            "Resource": "arn:aws:states:eu-central-1:123456789:stateMachine:arn:aws:states:eu-central-1:123456789:stateMachine:TestProcessStateMachine-RCRlxcyABTMF",
            "Effect": "Allow"
          }
        ]
      },
      "name": "TestRolePolicy0",
      "type": "inline"
    },
```

**Comment by chrisoverzero** [comment]
The problem is here, not in SAM:

```yaml
StateMachineName: !Ref TestProcessStateMachine 
```

Applying `!Ref` to a Step Functions State Machine [produces its ARN](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#aws-resource-stepfunctions-statemachine-return-values), as you can see in the output. You want this:

```yaml
Type: 'AWS::Serverless::Function'
Properties:
  Policies:
  - StepFunctionsExecutionPolicy:
    StateMachineName: !GetAtt TestProcessStateMachine.Name
```
