### ISSUE TITLE
Custom Event Bus with Schedule Event Type

### ISSUE THREAD

**Issue by cccassidy** [aws/serverless-application-model#1863]
**Description:**

Schedule event type does not support custom event bus
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-schedule.html

**Steps to reproduce the issue:**
1.  Tried to set EventBusName property with Schedule event and the transform failed to deploy

**Observed result:**
Deploy fails with 'property EventBusName not defined for resource of type Schedule'

**Expected result:**
Expected to be able to specify custom bus name with Schedule event (similar to the EventBridge rule type)

**Comment by mndeveci** [comment]
Hi @cccassidy ,

Can you provide an example template? And if you are using SAM CLI, can you provide the output of `sam validate --debug` as well?

Thanks

**Comment by cccassidy** [comment]
Hi @mndeveci,

I am using the 'Schedule' event type which works with the default bus:
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-schedule.html

I am looking to set the 'EventBusName' property which is available in the 'EventBridgeRule' type, however it doesn't appear to support cron-style expressions:
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-eventbridgerule.html

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.8
      InlineCode: |
        def handler(event, context):
          print("Hello, world!")
      Policies: AWSLambdaExecute
      Events:
        SampleEvent:
          Type: Schedule
          Properties:
            EventBusName: sample-bus
            Schedule: rate(1 minute)
```

sam deploy returns the following error:

`Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [SampleFunctionSampleEvent] is invalid. property EventBusName not defined for resource of type Schedule`

sam validate shows the following:

`Error: [InvalidResourceException('SampleFunctionSampleEvent', 'property EventBusName not defined for resource of type Schedule')] ('SampleFunctionSampleEvent', 'property EventBusName not defined for resource of type Schedule')`
