### ISSUE TITLE
ImageUri only does not work with AWS::Serverless-2016-10-31

### ISSUE THREAD

**Issue by JohnPreston** [aws/serverless-application-model#1900]
**Description:**

When creating a new Stack with AWS::Serverless::Function in it, and specifying only `ImageUri` in it, AWS get back the following error from AWS::Serverless transform 

```
Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [MacroLambdaFunction] is invalid. Only one of 'InlineCode' or 'CodeUri' can be set.
```

Here the template snippet 
```yaml
  MacroLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      Description: Lambda function to execute ECS Compose-X CFN Macro
      ImageUri: !Ref ECSComposeXMacroUri
      MemorySize: !Ref MemorySize
      Role: !GetAtt 'MacroFunctionRole.Arn'
      Timeout: 30
      FunctionName: !Sub "ecs-compose-x-macro-${AWS::Region}"
      Tags:
        Name: !Sub "ecs-compose-x-macro-${AWS::Region}"

```

Full template can be found [here](https://s3.amazonaws.com/files.compose-x.io/macro/macro-install.yaml)
Deploying the stack can be done by [clicking here](https://console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks/new?stackName=compose-x-macro&templateURL=https://s3.amazonaws.com/files.compose-x.io/macro/macro-install.yaml)
