### ISSUE TITLE
[sam validate] 'ImageUri' must be set

### ISSUE THREAD

**Issue by tuliocasagrande** [aws/serverless-application-model#1907]
**Description:**

I'm building a lambda function using the new container support and getting a linter/validation error with the absence of `ImageUri`.

`sam build & sam deploy` are working as expected, but `sam validate` is returning:

```
Error: [InvalidResourceException('rMyLambdaFunction', "'ImageUri' must be set.")] ('rMyLambdaFunction', "'ImageUri' must be set.")
```

Minimal template to reproduce:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  rMyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./my_lambda_image
      DockerTag: latest
```

Versions:
```
SAM CLI, version 1.15.0
aws-sam-translator        1.34.0
```
