### ISSUE TITLE
RDS::EventSubscription support for sam template?

### ISSUE THREAD

**Issue by durzo** [aws/serverless-application-model#1940]
Is it possible to create an RDS Event Subscription for my Lambda Function in SAM template?

The closest I can see is using EventBridge/CloudWatch Events but these are not exactly the same - the RDS Event Subscription allows you to define an Event category (e.g backup) along with the Source (e.g Instance) whereas EventBridge does not and the lambda will trigger on _all_ event categories.

RDS::EventSubscription has CloudFormation documentation here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-eventsubscription.html

**Comment by durzo** [comment]
I think I figured it out, for anyone curious this seems to be working:
```
      Events:
        BackupEvent:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.rds
              detail-type:
                - RDS DB Instance Event
              detail:
                EventCategories:
                  - backup
```
