### ISSUE TITLE
AWS::Serverless::HttpApi add default sigv4

### ISSUE THREAD

**Issue by DmytroMilashenko** [aws/serverless-application-model#1942]
### Describe your idea/feature/enhancement

Presently HttpApi supports IAM auth. https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-access-control-iam.html

### Proposal

When IAM is set via AWS Console and API is exported it generates:
```
components:
  securitySchemes:
    sigv4:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "awsSigv4"
```
So it is proposed to generate sigv4 by default, so that is can be referenced in lambda
```
Lambda:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        MyEvent:
          Type: HttpApi
          Properties:
            Auth:
              Authorizer: sigv4
```
Things to consider:

Please remember to add this information to documentation.
