### ISSUE TITLE
When using !Sub or !Ref in the 'Enabled' property in when 'Schedule' of AWS::Serverless::Function.

### ISSUE THREAD

**Issue by stanfan1992** [aws/serverless-application-model#1943]
### Description:

!Sub or !Ref in the 'Enabled' property in when 'Schedule' of AWS::Serverless::Function, it cannot be transformed correctly. The AWS::CloudWatch::Rule will always use 'ENABLED' for [State](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-state) property

### Steps to reproduce:
Launch the template below:
```yaml
Transform: AWS::Serverless-2016-10-31
Parameters:
  TriggerState:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
Resources:
  ExampleLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: example
      Handler: example
      Runtime: python3.8
      CodeUri:
        Bucket: myBucket
        Key: Lambda.py.zip
      Events:
        LambdaSchedule:
          Type: Schedule
          Properties:
          Name: lambda-trigger
          Schedule: cron(0 4 * * ? *)
          Description: description
          Enabled: !Sub ${TriggerState}
```

### Observed result:
After the template is transformed/launched with 'false' to 'TriggerState', the property [State](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-state) of AWS::CloudWatch::Rule will be 'ENABLED'

### Expected result:

As I passed 'false' for [Enabled](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-schedule.html#sam-function-schedule-enabled), the AWS::CloudWatch::Rule property [State](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-state) should be disabled. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.15.0
3. AWS region: us-east-1

`Add --debug flag to any SAM CLI commands you are running`

**Comment by stanfan1992** [comment]
These code could be the problematic part.
https://github.com/aws/serverless-application-model/blob/develop/samtranslator/model/eventsources/push.py#L120-L121

**Comment by stanfan1992** [comment]
#### Add a workaround: 
Since the issue is not successfully transforming the template with the intrinsic function we have workaround: 

Using `Fn::Transform` to call a AWS::Include transform. Use the `AWS::Include` transform, which is a macro hosted by AWS CloudFormation, to insert boilerplate content into your templates. The `AWS::Include` transform lets you create a reference to a template snippet in an Amazon S3 bucket.

Please check the below SAM template samples:
--- template.yml ---
```yaml
Transform: AWS::Serverless-2016-10-31
Parameters:
  S3Bucket: 
    Type: String 
  TriggerState:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
Resources:
  ExampleLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: example
      Handler: example
      Runtime: python3.8
      CodeUri:
        Bucket: fanhongy-customresource
        Key: Lambda.py.zip
      Events:
        LambdaSchedule:
          Fn::Transform :
            Name : AWS::Include
            Parameters :
              Location : 
                Fn::Sub: "s3://${S3Bucket}/${TriggerState}.yml"
```

--- true.yml ---
```yaml
Type: Schedule
Properties:
  Name: lambda-trigger
  Schedule: cron(0 4 * * ? *)
  Description: description
  Enabled: true
```

--- false.yml --- 
```yaml
Type: Schedule
Properties:
  Name: lambda-trigger
  Schedule: cron(0 4 * * ? *)
  Description: description
  Enabled: false
```

**Comment by MarcGuiselin** [comment]
I can reproduce this issue on v1.19.1 (via github actions)

Another workaround is to conditionally set the cron job to run on a past date like so:

````yaml
Events:
  Schedule:
    # https://docs.aws.amazon.com/eventbridge/latest/userguide/scheduled-events.html
    Type: Schedule
    Properties:
      Name: lambda-trigger
      # Workaround for disabling schedule
      Schedule: !If
        - TriggerState # Condition
        - cron(0 1 * * ? *) # 1:00 AM UTC or a custom schedule here
        - cron(0 1 1 1 ? 1970) # Never run
      Description: description
      Enabled: True
````
