### ISSUE TITLE
EventSource HttpApi silently fails to add path with trailing slash

### ISSUE THREAD

**Issue by bobk-fox** [aws/serverless-application-model#1949]
### Description:
When creating a Serverless Function with a trailing slash in it's Event Path the integration is created but the route is not. And no error is given

### Steps to reproduce:
If you create the following resource it will create an integration but no route.
```yaml
  EventsLambda:
    Type: AWS::Serverless::Function
    Properties:
      ...
      Events:
        GetRules:
          Type: HttpApi
          Properties:
            ApiId: !Ref APIGateway
            Path: /events/
            Method: GET
```

If you remove the slash behind events it does work:
```
            Path: /events
```

### Observed result:
No route created

### Expected result:
An error should be given because trailing slashes are not allowed by the HttpApi

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
Not relevant
