### ISSUE TITLE
domain already exists in stack

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws/serverless-application-model#1958]
### Description:

Seems it does not know when to create and when not to create.

### Steps to reproduce:

I created a custom domain with the following template:

```yaml
customDomainCert:
  Type: AWS::CertificateManager::Certificate
  Properties:
    DomainName: !Sub api-v1.domain.com
    ValidationMethod: DNS
mainBackendApi:
  Type: AWS::Serverless::Api
    EndpointConfiguration:
      Type: REGIONAL
    Domain:
      DomainName: !Sub api-v1.domain.com
      CertificateArn: !Ref customDomainCert
      BasePath:
        - !Ref Stage
      Route53:
        HostedZoneId: Z0450109WGLMG82TZFOY
```

Then deployed and it was successful, then I simply changed the code to the following

```diff
+Mappings:
+   stageVars:
+     dev:
+       basePath: "/dev"
+     production:
+       basePath: "/"

customDomainCert:
  Type: AWS::CertificateManager::Certificate
  Properties:
-   DomainName: !Sub api-v1.domain.com
+   DomainName: api-v1.domain.com
    ValidationMethod: DNS
mainBackendApi:
  Type: AWS::Serverless::Api
    EndpointConfiguration:
      Type: REGIONAL
    Domain:
-     DomainName: !Sub api-v1.domain.com
+     DomainName: api-v1.domain.com
      CertificateArn: !Ref customDomainCert
      BasePath:
-       - !Ref Stage
+         - !FindInMap
+           - stageVars
+           - !Ref Stage
+           - basePath
      Route53:
        HostedZoneId: Z0450109WGLMG82TZFOY
```

Then deployed, and I got this error:

<img width="727" alt="Screen Shot 2021-03-09 at 7 07 34 PM" src="https://user-images.githubusercontent.com/21032419/110463314-b9b26900-810c-11eb-9277-8b5050a5c4e2.png">

For some reason, it's trying to "create" again even though it shouldn't.

### Observed result:

Says create and then failed.

### Expected result:

It should not create again and it should not fail.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: N/A
2. If using SAM CLI, `sam --version`: 1.20.0
3. AWS region: ap-southeast-1

`Add --debug flag to any SAM CLI commands you are running`

**Comment by aprilmintacpineda** [comment]
I worked around this by deleting the custom domain properties, then deploy, then re-add then deploy, then I tried a test deployment where I simply added a test env variable to all my functions and that test deployment worked... I still seek to be enlightened on why I encountered this error.

**Comment by sriram-mv** [comment]
@aprilmintacpineda just to get some more information, did the transformed template reference to the same logical ids, and was the only change intrinsics? I'm trying to get a repro going, but wanted to ensure.

**Comment by aprilmintacpineda** [comment]
> @aprilmintacpineda just to get some more information, did the transformed template reference to the same logical ids, and was the only change intrinsics? I'm trying to get a repro going, but wanted to ensure.

Oh, I did not check the transformed template...

**Comment by prenx4x** [comment]
Can you provide complete template for a repro?

**Comment by denizoguz** [comment]
Hi,
I have the same issue and I really appreciate any help on this. I have defined stage as a parameter and I can deploy the same template.yaml file for different stages using different stack names. This creates different lambda, DynamoDB, GatewayAPI but domain part fails to deploy for different stages. I need to comment out it and manually add path mappings on the console and I need to delete these manually added path mappings before deleting the stack.

My goal is to access my Dev and Prod environments using different paths on the same domain, that is:
- mydomain.com/Prod for Prod Stage and 
- my domain.com/Dev for Dev stage.

When I try to deploy for Dev environment (Prod is still live) I get the following error.

`
CREATE_FAILED                              AWS::ApiGateway::DomainName                ApiGatewayDomainNamec022222222             mydomain.com already exists in    
                                                                                                                                 stack arn:aws:cloudformation:us-east-1:4 
                                                                                                                                 222222222:stack/RemindersCloudProd/2222222-2222-222-2222-22222222
`

Here is the domain name and API part of my template.yaml file. 

```

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS backend for issue reminders app.

#define parameters which can be referred within rest of the template file by using !Ref Stage
Parameters:
  Stage:
    Type: String
    Default: Prod
    AllowedValues:
      - Prod
      - Stage
      - Dev

Globals:
  Api: #Prevent unwanted "Stage" stage. https://github.com/aws/serverless-application-model/issues/191
    OpenApiVersion: 3.0.1

Resources:
  RemindersCloudApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage #Stage name comes from environment variable and defined in Parameters section
      Domain: 
        DomainName: mydomain.com
        BasePath: !Ref Stage # map mydomain.com/Prod to https://{random-api-path}/Prod. !Sub "/api/${Stage}" did not work!
        #we are required to manually create the certificate ourselves and specify it here. Otherwise, deploy fails.
        CertificateArn: arn:aws:acm:us-east-1:444444444:certificate/888888888888888888
        SecurityPolicy: TLS_1_2 #defaults to TLS 1.0 but TLS 1.2 is recommended
        Route53:
          HostedZoneId: Z1CLLL44444444
          EvaluateTargetHealth: true #when false Route53 records are not automatically created
      Auth:
        ApiKeyRequired: true
        UsagePlan: #Usage plan is required for API key to work, even if it doesn't block anything.
          CreateUsagePlan: SHARED
          Description: API Usage Plan for Reminders Cloud. It doesn't block anything but required to use API Keys.

```

**Comment by madeupname** [comment]
I have a very similar problem to denizoguz. I created a template.yaml with an Api StageName, function AutoPublishAlias, etc. all named Dev to test the concept.

Then I refactored to use a parameter like so:

```
Parameters:
  DeployEnvironment:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod
    Description: Enter Dev or Prod. Dev is the default.

Globals:
  Api:
    # This is only necessary to prevent SAM from creating an unnecessary stage named "Stage" that you have to delete later.
    OpenApiVersion: 3.0.1
  Function:
    Timeout: 20
    Runtime: java11
    Architectures:
      - x86_64

Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref DeployEnvironment
  LambdaZipFunction:
    Type: AWS::Serverless::Function 
    Properties:
      AutoPublishAlias: !Ref DeployEnvironment
# truncated
```
Deploying that gives me an error:

`CREATE_FAILED                                                     AWS::ApiGateway::Stage                                            RestApiStage                                                      <stage ID>|Dev already exists in stack
`

So it correctly substitutes the parameter name without recognizing there's no change. What strikes me as very strange is I've seen a few people suggest this approach, so it works for some (seems like an obvious best/common practice).

Any workaround? Just a note I reviewed the transformed template.yaml and it's basically the same but doesn't use the short form of Ref:

```
Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: DeployEnvironment
```
