### ISSUE TITLE
HTTP API Headers case mismatch between local and once deployed

### ISSUE THREAD

**Issue by mims92** [aws/serverless-application-model#1967]
### Description:
When testing locally with `sam local start-api` on an HTTP API, the headers are in upper-case.
Testing on AWS, the headers are lower-cased.
The PayloadFormatVersion is 2.0

### Steps to reproduce:
```
    ApiG:
        Type: AWS::Serverless::HttpApi
        Properties:
            CorsConfiguration:
                AllowHeaders: "*"
                AllowMethods:
                    - GET
                    - POST
                    - DELETE
                    - HEAD
                    - PUT
                    - PATCH
                AllowOrigins:
                    - '*'
            DisableExecuteApiEndpoint: True
            StageName: api


    APIServiceFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: api
            CodeUri: api/src/
            Handler: index.handler
            Runtime: nodejs12.x
            Events:
                API:
                    Type: HttpApi
                    Properties:
                        PayloadFormatVersion: "2.0"
                        Path: /api/{proxy+}
                        Method: any
                        ApiId: !Ref ApiG
```

### Observed result:
Called locally with `sam local start-api`

`console.log(JSON.stringify(event.headers))`:
```
{"Host":"127.0.0.1:3000","User-Agent":"curl/7.64.0","Accept":"*/*","Authorization":"Bearer 1","X-Forwarded-Proto":"http","X-Forwarded-Port":"3000"}
```

### Expected result:
Called from AWS console
```
{
    "accept": "*/*",
    "accept-encoding": "gzip, deflate, br",
    "authorization": "Bearer 1
    "content-length": "0",
    "host": "connect.release.koalaboox.com",
    "postman-token": "e4bfe83d-4594-4351-af83-4966a570d6ff",
    "user-agent": "PostmanRuntime/7.26.10",
    "x-forwarded-port": "443",
    "x-forwarded-proto": "https",
    [...]
}
```

Here the headers are in lower-case.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Debian 10
2. If using SAM CLI, `sam --version`: 1.21.1
3. AWS region: eu-central-1
