### ISSUE TITLE
AWS::ApiGatewayV2::Route and AWS::ApiGatewayV2::Integration resources are deleted from API Gateway upon stack update

### ISSUE THREAD

**Issue by bensie** [aws/serverless-application-model#1971]
### Description:
Route and Integration resources that are newly defined are created without issue. However, when certain parts of the template are updated, those resources are deleted from the API Gateway API even though they still exist in the template and are still resources visible to CloudFormation.

The only way to restore them is by removing them from the template (so CloudFormation registers it as a deleted resource), deploy, then add them back to the template and deploy again.

The template in the steps below has an explicitly defined `AWS::Serverless::HttpApi` resource and a `AWS::Serverless::Function` whose `Events` attribute references that API resource. There is an intentionally commented out event that we'll un-comment in the stack update to reproduce the issue.

Further below, there's a `AWS::ApiGatewayV2::Route` and `AWS::ApiGatewayV2::Integration` as a sample direct-to-SQS integration. This is the integration and route that disappears upon stack update.

### Steps to reproduce:

Create a stack with the following template. It will create without issue and the expected routes will exist.

```yml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: v1
      CorsConfiguration: true
  Func:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      PackageType: Zip
      InlineCode: |
        exports.handler = function(event, context) {
        }
      Handler: index.handler
      MemorySize: 128
      Events:
        HiGetEndpoint:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Path: /hi
            Method: GET
        # HiPostEndpoint:
        #   Type: HttpApi
        #   Properties:
        #     ApiId: !Ref Api
        #     Path: /hi
        #     Method: POST
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
  MyRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: POST /myroute
      Target: !Sub integrations/${MyRouteIntegration}
      AuthorizationType: NONE
  MyRouteIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref Api
      IntegrationType: AWS_PROXY
      IntegrationSubtype: SQS-SendMessage
      PayloadFormatVersion: "1.0"
      CredentialsArn: !GetAtt MyRouteRole.Arn
      RequestParameters:
        QueueUrl: !Ref Queue
        MessageBody: $request.body
  MyRouteRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: APIGWToSQS
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              Action: sqs:SendMessage
              Effect: Allow
              Resource: !GetAtt Queue.Arn
  Queue:
    Type: AWS::SQS::Queue
```

Open the API Gateway console and confirm the 2 expected routes exist.

<img width="318" alt="image" src="https://user-images.githubusercontent.com/4595/112553487-d3e17d80-8d81-11eb-9c29-8b1eb9621340.png">

Now, update the above template, un-commenting these 6 commented lines:

```yml
        # HiPostEndpoint:
        #   Type: HttpApi
        #   Properties:
        #     ApiId: !Ref Api
        #     Path: /hi
        #     Method: POST
```

Update the stack with the updated template, then head over to the API Gateway console. The added `POST /hi` exists but `POST /myroute` is gone.

<img width="333" alt="image" src="https://user-images.githubusercontent.com/4595/112553801-66821c80-8d82-11eb-949e-3adf68c000da.png">

### Observed result:

`POST /myroute` is gone from the API and results in a `404 Not Found` response when attempting to hit the URL.

### Expected result:

Resources that are defined in CloudFormation should not be deleted when they remain in the template and are valid resources listed in the stack.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
Tested in CloudFormation stacks in multiple accounts and in us-west-2 and us-east-1. It is environment-agnostic as the template provided can be directly run in the CloudFormation console.
