### ISSUE TITLE
AWS::Serverless::Api does not support DisableExecuteApiEndpoint

### ISSUE THREAD

**Issue by varming** [aws/serverless-application-model#1978]
### Description:
In https://github.com/aws/serverless-application-model/pull/1725 support for DisableExecuteApiEndpoint was added for AWS::Serverless::HttpApi, but AWS::Serverless::Api was omitted. It looks like CloudFormation for AWS::ApiGateway::RestApi supports DisableExecuteApiEndpoint, so it would be great to add support to AWS::Serverless::Api

### Steps to reproduce:
Create a CloudFormation stack with the template:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template with a simple API definition
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DisableExecuteApiEndpoint: True
      StageName: prod
  ApiFunction: # Adds a GET api endpoint at "/" to the ApiGatewayApi via an Api event
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
      Runtime: python3.7
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
            return {'body': 'Hello World!', 'statusCode': 200}
```

### Observed result:
Transform step fails:
```
Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [ApiGatewayApi] is invalid. property DisableExecuteApiEndpoint not defined for resource of type AWS::Serverless::Api
```

### Expected result:
The SAM transform would succeed.
