### ISSUE TITLE
Can not tag Functions

### ISSUE THREAD

**Issue by mrtj** [aws/serverless-application-model#1985]
### Description:
I found no way to tag a serverless function

### Steps to reproduce:
If I try the cloudformation tag formats:
```yaml
  MyFunction:
    Type: AWS::Serverless::Function
    Properties: ...
    Tags:
      - Key: foo
        Value: bar
```
then the `sam build` command fails with this error:
```
samcli.commands.validate.lib.exceptions.InvalidSamDocumentException: 
[InvalidResourceException('BootstrapperFunction', "Type of property 'Tags' is invalid.")] 
```

If I try the map style:
```yaml
  MyFunction:
    Type: AWS::Serverless::Function
    Properties: ...
    Tags:
      foo: bar
```
Then the `deploy` command fails with a CloudFormation error when it tries to propagate the tags to the role created for this function:
```
The following resource(s) failed to update: [MyFunctionRole].
Value of property Tags must be of type List
```

### Observed result:

No way to create function tags.

### Expected result:

Create function tags with a clean an documented way

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

`sam --version`: 1.20.0

**Comment by sriram-mv** [comment]
```
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Tags:
        mypropkey: mypropvalue
```

I tried it out with this format and tagging works as expected.

**Comment by mrtj** [comment]
Hello, sorry, my bad. I confused that I had also a custom IAM Role in my template, for which you should define the tags this way:
```yaml
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      # ...
      Tags:
        - Key: foo
          Value: bar
```
I might change the tags section together in the role and the sls function. It is a bit confusing though that you should define the tags in two different ways in the same template.
