### ISSUE TITLE
Cant use MethodSettings in AWS::Serverless::Api

### ISSUE THREAD

**Issue by AllanOricil** [aws/serverless-application-model#1988]
### Description:

Im trying to set ThrottlingBurstLimit to my api using the MethodSettings property but it is not working.

![image](https://user-images.githubusercontent.com/55927613/111890075-24518780-89de-11eb-8814-3111e77516f1.png)

I tried everything possible as it is saying here https://docs.aws.amazon.com/apigateway/api-reference/resource/stage/
and here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-stage-methodsetting.html and nothing worked

### Steps to reproduce:
Try to use MethodSettings for all your APIs in a Stage using `- /` or `- "/" ` or `- /* ` or `- "/*"` and verify that none of these entries is accepted.

![image](https://user-images.githubusercontent.com/55927613/111890120-89a57880-89de-11eb-9412-4f96fe4c4003.png)

### Observed result:
Method setting for every api route in a stage is not working.

### Expected result:
Method setting for "/" should work.

These are the props I want to configure

![image](https://user-images.githubusercontent.com/55927613/111890410-fe79b200-89e0-11eb-8cda-3b03324794cb.png)

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 20
2. `sam --version`:  SAM CLI, version 1.8.0
3. AWS region: eu-west-1

`Add --debug flag to command you are running`

**Comment by AllanOricil** [comment]
@jfuss I thought it was a list because of the name is in Plural and it also says it receives a list of MethodSetting which is the dictionary. Following your example how can I declare more then one Route setting? Could you place an example here, please

**Comment by AllanOricil** [comment]
@jfuss are you sure? because in the example in the link you sent it says it is a list of dictionary. It even has the "-" for the first entry

![image](https://user-images.githubusercontent.com/55927613/114594405-20cfba00-9c85-11eb-8920-5eae7e11e1f6.png)

**Comment by AllanOricil** [comment]
Would it be something like this?
````yaml
MethodSettings:
    - HttpMethod: '/route1'
      ThrottlingBurstLimit: 1000
    - HttpMethod: '/route2'
      ThrottlingBurstLimit: 1000
````

**Comment by AllanOricil** [comment]
When I read the doc I thought HttpMethod would be like POST, GET, PATCH, but it is actually the route I want to apply this setting to. Really weird name for the property.

**Comment by jfuss** [comment]
@AllanOricil You are correct, it is suppose to be a list. Sorry for additional confusion.

Your original definition is still incorrect because you have `/*` as a key, which is not valid. 

You can try that. It seems like there is a mix you can do. (I always get confused with this setting).

HttpMethod states: "The HTTP method. To apply settings to multiple resources and methods, specify an asterisk (*) for the HttpMethod and /* for the ResourcePath. "
Which seems to suggest you can apply this to multiple methods and ResourcePaths under HttpMethod only. 

The API Gateway docs do read like what you have in https://github.com/aws/serverless-application-model/issues/1988#issuecomment-818911317 is valid. I would give it a try.

**Comment by shrinathk** [comment]
The following is a working YAML definition.

```yaml
Resources:
  ApiGatewayRestApi:
    Type: AWS::Serverless::Api
    Properties:
      MethodSettings:
        - HttpMethod: '*'		# Mandatory
          ResourcePath: '/*'		# Mandatory
          LoggingLevel: ERROR
          DataTraceEnabled: true
          MetricsEnabled: true
```
For some reason, the template fails if `HttpMethod` and `ResourcePath` are not defined.
