### ISSUE TITLE
Lambda code must reside in the same region as where it's being deployed

### ISSUE THREAD

**Issue by nicollaas94** [aws/serverless-application-model#1993]
### Description:

When using AWS::Serverless::Function with code URI option, you first package the template, it will then generate a output template that you use to deploy the function. this is great and very handy, but unfortunately, you can only deploy it to the same region you packaged, otherwise you get this error:

> Error occurred while GetObject. S3 Error Code: PermanentRedirect. S3 Error Message: The bucket is in this region: eu-west-1. Please use this region to retry the request (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException...)

### Steps to reproduce:

- create a very basic js handler (helloWorld).
- Create a SAM template to deploy it:
*cfn-template.yaml*
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  SomeLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: "FunctionNameHere"
      Handler: handler.the_function_to_handle
      Runtime: nodejs14.x 
      Code: ./dist/to/where/handler/is
```
- package the template to some s3 in one region eg eu-west-1:
```
aws cloudformation package --template-file cfn-template.yaml --s3-bucket YOUR_BUCKET --output-template-file cfn-output.yaml --region eu-west-1
```
- use the *cfn-output.yaml* to deploy the cloudformation in the same region eg eu-west-1 *THIS WIL WORK*
```
aws cloudformation deploy --template-file cfn-output.yaml --capabilities CAPABILITY_NAMED_IAM --stack-name exampleStack --region eu-west-1
```
- use the *cfn-output.yaml* to deploy the cloudformation in ANOTHER region eg us-west-2 *THIS WIL NOT WORK*
```
aws cloudformation deploy --template-file cfn-output.yaml --capabilities CAPABILITY_NAMED_IAM --stack-name exampleStack --region us-west-2
```
### Observed result:

Error occurred while GetObject. S3 Error Code: PermanentRedirect. S3 Error Message: The bucket is in this region: eu-west-1. Please use this region to retry the request (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: SOME_GUID; Proxy: null)

### Expected result:

success to deploy

### Questions:
Why do not allow deploy with code from different region?
How to workaround?
Are there any documentation explaining it?
