### ISSUE TITLE
How to specify variable CORS endpoint 

### ISSUE THREAD

**Issue by KylePeterDavies** [aws/serverless-application-model#1994]
Hey, 

I am aware that you can specify CORS AllowOrigin as...
 
```yml
...
Cors: "'*'" # Take note of the '*'
```

However, how would you specify an endpoint here?

```yml
Cors: "'!Ref CORS_URL'" # doesn't seem to work
```
Also, how do I add "' to the start and end of the url? I have looked at !Sub, !Join 

I would like to achieve this with parameter instead of a hard coded value

```yml
Cors: "'http://some-endpoint'"
```

**Comment by jfuss** [comment]
@KylePeterDavies Moved to SAM's repo as this question does not relate to SAM CLI.

Your `Ref` example will not work because CloudFormation will assume that is a string. You need to use `Sub`.

Something like `! Sub "'${CORS_URL}'"` should be what you want, similar to this https://stackoverflow.com/questions/40292888/enable-cors-for-api-gateway-in-cloudformation-template

Closing

**Comment by KylePeterDavies** [comment]
For anyone reading

```yml
Parameters:
  CorsUrl:
    Type: String
    Default: http://localhost:3000
...
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Cors: !Sub "'${CorsUrl}'" # Take note of the quotation marks '
```
ineeds gets translated too 

```yml
Cors: 'http://localhost:3000'
``
Thanks @jfuss
