### ISSUE TITLE
Strings that contain an integer starting with 0 are converted into integers  

### ISSUE THREAD

**Issue by gaetanmorice** [aws/serverless-application-model#200]
For instance, if you have a parameter in your template with a value that is a string "012345" it is silently converted into the integer 012345 after aws cloudformation package action. 

This can raise issues:
- if the parameter is expecting a string as a value.
- if you use condition function to compare this value with other ones.
- if you use such a string as a key in a Mapping section (map keys have to be strings).

Type tags, such as !!str, are not preserved by the package action, so they cannot be used as a workaround.

**Comment by jfuss** [comment]
@gaetanmorice I have some clarifying questions for you.

1. Does this issue happen only when you run `aws cloudformation package`?  If you were to take the same template and manually run it in a stack on the console, does that work?
2. Could you provide a example we could use to repro this?

If this is only happening when you run the package command, it may be an issue in the awscli.

**Comment by jfuss** [comment]
Closing due to no response

**Comment by atharfaraz** [comment]
This is happening to us.
We have an account which starts with 0 and we tried to have mappings for specific accounts. Package converts the account number to integer by removing the quotes around it and the deploy complains that mapping has to be a string not integer. Package also seem to be sorting.

**Comment by keetonian** [comment]
@atharfaraz is this specifically happening at the `sam package` step?

**Comment by keetonian** [comment]
@atharfaraz could you provide the following information?
 
> 1. Does this issue happen only when you run `aws cloudformation package`?  If you were to take the same template and manually run it in a stack on the console, does that work?
> 2. Could you provide a example we could use to repro this?
> 
> If this is only happening when you run the package command, it may be an issue in the awscli.

**Comment by atharfaraz** [comment]
_1. Does this issue happen only when you run aws cloudformation package? If you were to take the same template and manually run it in a stack on the console, does that work?_
Ans: Yes, it happens with cloud formation as well.. Same template meaning the packaged template?

_2. Could you provide a example we could use to repro this?
Ans: Sure, here it is:
`AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: This template deploys the hi-fi lambda function and associated resources.
Parameters:
  Environment:
    Description: "The environment to create"
    Type: String 
Mappings:
  AmazingMapPerAcc:
    "0123457652": 
        Version: 12
    "23457651011":
        Version: 10
    "1234221768658":
        Version: 8
    "9252719167122":
         Version: 4
Resources:
  paymentMs:
    DependsOn: paymentMsRole
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: "dummy-ms"
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./lambdas/dummy-ms
      Description: ""
      MemorySize: 128
      Timeout: 15`

Since I couldn't copy paste my template coz it may contain information which should not be made public, the above is modified version. Please let me know if that helps. If not, I can spend a little more time on getting it identical.
Thanks!

**Comment by concordion2k** [comment]
This is also happening to me on a project im working on. AWS recommends using the account IDs for ALB found below to allow ALB to dump logs to some s3 bucket. the bucket policy is simple enough, but if you us the value for us-east-2, which has a leading zero, it will cause the account id to form an invalid value in scientific notation. 

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#enable-access-logging

**Comment by jcwhisman** [comment]
THis is also happening to us. Is there any progress/workarounds on this? We have our account ids in a map and referencing accounts that begin with '0' are being converted to scientific notation when using FindInMap.

We are using cloudformation package. It works when we run manually run the template

**Comment by keetonian** [comment]
I found that this happens from the CLI or console for strings:
* That start with '0' and end with '8' or '9'
* That exist in Mappings, Parameters, Environment.Variables, and potentially other areas
* Happens in SAM templates
* Happens in vanilla CFN templates (that do not use SAM at all)

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  FunctionNameParam:
    Type: String
    Default: "somename"
  AccId:
    Type: String
    Default: "012123123128" # converted

Conditions:
  TrueCondition:
    Fn::Equals: ["true", "true"]

Mappings:
  MyMap:
    a: 
      Version: "013566350540"
      Version2: "013566350541"
    b:
      Version: "330105517988"
      Version2: "013566350542"
    c:
      Version: "033010551798" # converted
      Version2: "013566350543"
    d:
      Version: "000999333888" # converted
      Version2: "013566350544"
    e:
      Version: "0121212121212"
      Version2: "013566350545"
    f:
      Version: "0121212121212"
      Version2: "013566350546"
    g:
      Version: "0121212121217"
      Version2: "013566350548" # converted
    h:
      Version: "0221212121219" # converted
      Version2: "033566350548" # converted
    i:
      Version: "0421212121218" # converted
      Version2: "003566350548" # converted

Resources:

  MyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      InlineCode: |
        print('hi')
      Handler: index.handler
      Runtime: python3.7
      Environment:
        Variables:
          a1: !FindInMap [MyMap, a, Version]
          b1: !FindInMap [MyMap, b, Version]
          c1: !FindInMap [MyMap, c, Version] # converted into a number
          d1: !FindInMap [MyMap, d, Version] # converted into a number
          e1: !FindInMap [MyMap, e, Version]
          f1: !Ref AccId # converted into a number
          g1: "012123123128" # converted into a number
          h1: "012123123121" # not converted to a number

Outputs:
  Number:
    Value: 08 # converted to number, expected
```
