### ISSUE TITLE
Replace Definition URI in AWS::Serverless::StateMachine with repo bucket

### ISSUE THREAD

**Issue by shreedharn** [aws/serverless-application-model#2000]
I have published a sam application and want to share publicly. The application contains a step function and couple of lambda functions. When I publish the application template file has following snippets for lambda and step function definitions:
```yaml
   MyFunction: 
   Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: <%REPO_BUCKET%>
```
```yaml
    MyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri:
        Bucket: my_bucket_name
        Key: v0_1_0/5622d7535a53de02c2fe8a15540abae8
```
Note: In the case of lambda function code uri refers to <%REPO_BUCKET%> which gets replaced as awsserverlessrepo-changesets-plntc6bfnfj during deployment. However in the case of StateMachine, Definition URI still points to my bucket instead of generic awsservlessrepo bucket.

My S3 bucket is blocked for public access and has the following policy

```yaml
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "serverlessrepo.amazonaws.com"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::<my_bucket_name>/*",
            "Condition": {
                "StringEquals": {
                    "aws:SourceAccount": "<my_account_no>"
                }
            }
        }
    ]
}
```
I have tested deploying my published sam applicaton from a different account. Lambda's are deployed correctly. However the cloudformation stack fails during the creation of State Machine with the error message: "Resource handler returned message: "Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied".

Is it a requirement to open my bucket to public read while publishing SAM application with Step functions? If so, why the rule is different from lambda?
