### ISSUE TITLE
http api not working together with lambda authorizer

### ISSUE THREAD

**Issue by pseidemann** [aws/serverless-application-model#2005]
### Description:

I'm trying to configure a lambda authorizer for my http api. when using rest api instead, everything works as expected.
I get an internal server error from api gateway but there are no further error messages when [configuring the gateway access log](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-troubleshooting-lambda.html) with additional fields like integration error (all error strings are "-" (dash) when this error happens).
the authentication lambda is not called when the bug happens.

### Steps to reproduce:

configure an http api to use a lambda authorizer:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: dummy

Parameters:
  AWSEnv:
    Type: String
    Default: AWS # AWS or AWS_SAM_LOCAL
  Stage:
    Type: String
    Default: dev
  Region:
    Type: String
    Default: eu-central-1

Globals:
  Function:
    Runtime: python3.8
    Handler: func.handler
    Timeout: 3
    Environment:
      Variables:
        AWS_ENV: !Ref AWSEnv
        STAGE: !Ref Stage
        REGION: !Ref Region

Resources:
  MessageApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Stage
      Auth:
        DefaultAuthorizer: MessageAuthorizer
        Authorizers:
          MessageAuthorizer:
            FunctionArn: !GetAtt MessageAuthFunction.Arn
            FunctionInvokeRole: !GetAtt MessageAuthFunctionRole.Arn
            Identity:
              Headers:
                - Authorization
              ReauthorizeEvery: 0 # disable caching
            AuthorizerPayloadFormatVersion: "2.0"
            EnableSimpleResponses: false

  MessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/message/
      Events:
        GetMessage:
          Type: HttpApi
          Properties:
            ApiId: !Ref MessageApi
            Path: /message
            Method: get
            PayloadFormatVersion: "2.0"

  MessageAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/auth/

  # attempt to fix the bug (not working)
  MessageAuthPermissionFix:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref MessageAuthFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MessageApi}/authorizers/*"

```

when using rest api instead, it works as expected:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: dummy

Parameters:
  AWSEnv:
    Type: String
    Default: AWS # AWS or AWS_SAM_LOCAL
  Stage:
    Type: String
    Default: dev
  Region:
    Type: String
    Default: eu-central-1

Globals:
  Function:
    Runtime: python3.8
    Handler: func.handler
    Timeout: 3
    Environment:
      Variables:
        AWS_ENV: !Ref AWSEnv
        STAGE: !Ref Stage
        REGION: !Ref Region

Resources:
  MessageApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Auth:
        DefaultAuthorizer: MessageAuthorizer
        Authorizers:
          MessageAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt MessageAuthFunction.Arn
            Identity:
              Headers:
                - Authorization
              ReauthorizeEvery: 0 # disable caching

  MessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/message/
      Events:
        GetMessage:
          Type: Api
          Properties:
            RestApiId: !Ref MessageApi
            Path: /message
            Method: get

  MessageAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/auth/

```

### Observed result:

`{"message":"Internal Server Error"}` from the `/message` api

### Expected result:

response from lambda (after authorization lambda allows request)

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: mac os big sur
2. If using SAM CLI, `sam --version`: 1.22.0
3. AWS region: eu-central-1
