### ISSUE TITLE
Allow users to add a "Policies" section under Globals -> Function in AWS SAM templates.

### ISSUE THREAD

**Issue by rts-rob** [aws/serverless-application-model#2009]
### Describe your idea/feature/enhancement

As a developer, I want to define IAM policies to be applied to every function in my application, so that I can grant access to resources that every function needs.

### Proposal

As serverless applications grow, so does the probability of performing operational tasks across all functions. For example, if you connect to a third-party API, you may need to provide access to an API key to every function using AWS Systems Manager Parameter Store. Currently, you must define policies for every function individually, which leads to copy/pasting and increases the likelihood of error.

A proposal is made to add a "Policies" stanza under "Globals -> Function" in AWS SAM templates. This section should be a map merged with the "Policies" section specified in individual functions, similar to how "Environment" is handled today. See example template under section [Additional Details](#additional-details) below.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model)

Yes, to [samtranslator/plugins/globals](https://github.com/aws/serverless-application-model/tree/579353c793b9c779c0f869f7bb7e4a16b16f8767/samtranslator/plugins/globals)

### Additional Details

Sample AWS SAM template today:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Resources:
  listStores:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/stores.list
      ...
      Policies:
        - AWSLambdaBasicExecutionRole
        - SSMParameterReadPolicy:
            ParameterName: MySecretAPIKey
        - DynamoDBReadPolicy:
            TableName: MyTable

  createStore:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/stores.create
      ...
      Policies:
        - AWSLambdaBasicExecutionRole
        - SSMParameterReadPolicy:
            ParameterName: MySecretAPIKey
        - DynamoDBWritePolicy:
            TableName: MyTable
```

Sample AWS SAM template after the proposal is implemented:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Globals:
  Functions:
    Policies:
      - AWSLambdaBasicExecutionRole
      - SSMParameterReadPolicy:
          ParameterName: MySecretAPIKey

Resources:
  listStores:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/stores.list
      ... 
      Policies:
        # This will be merged with the global policies
        - DynamoDBReadPolicy:
            TableName: MyTable

  createStore:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/stores.create
      ...
      Policies:
        # This will be merged with the global policies
        - DynamoDBWritePolicy:
            TableName: MyTable
```
