### ISSUE TITLE
I'm trying to map my websocket api to a custom domain, it is successful but can't connect to it

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws/serverless-application-model#2016]
### Description:

I have deployed a websocket api with cloudformation (because there is currently no aws-sam template available so I had to manually write everything), it was successful and I can connect to it and send messages. That's step 1.

Step 2 was to add a custom domain for my websocket. I was able to add the custom domain and the deployment was successful, however, when trying to connect to my api using the custom domain, I just can't connect to it.

Note that this is a React-Native app. I don't see any error messages to go on with so I decided to open an issue here. Here's the code for websocket:

```yaml
webSocket:
  Type: AWS::ApiGatewayV2::Api
  Properties:
    Name: !Join
      - '-'
      - - !Ref Stage
        - "my-app-webSocket"
    ProtocolType: WEBSOCKET
    RouteSelectionExpression: "$request.body.action"
    DisableExecuteApiEndpoint: true
webSocketDeployment:
  Type: AWS::ApiGatewayV2::Deployment
  DependsOn:
    - connectRoute
    - sendWebsocketMessageRoute
    - disconnectRoute
  Properties:
    ApiId: !Ref webSocket
webSocketStage:
  Type: AWS::ApiGatewayV2::Stage
  Properties:
    StageName: !Ref Stage
    DeploymentId: !Ref webSocketDeployment
    ApiId: !Ref webSocket
webSocketCustomDomainCert:
  Type: AWS::CertificateManager::Certificate
  Properties:
    DomainName: !Sub
      - ${webSocketSubDomain}.mydomain.com
      - webSocketSubDomain: !FindInMap
        - stageVars
        - !Ref Stage
        - webSocketSubDomain
    ValidationMethod: DNS
webSocketCustomDomain:
  Type: AWS::ApiGatewayV2::DomainName
  Properties:
    DomainName: !Sub
      - ${webSocketSubDomain}.mydomain.com
      - webSocketSubDomain: !FindInMap
        - stageVars
        - !Ref Stage
        - webSocketSubDomain
    DomainNameConfigurations:
      - CertificateArn: !Ref webSocketCustomDomainCert
webSocketCustomDomainMapping:
  Type: AWS::ApiGatewayV2::ApiMapping
  Properties:
    ApiId: !Ref webSocket
    DomainName: !Sub
      - ${webSocketSubDomain}.mydomain.com
      - webSocketSubDomain: !FindInMap
        - stageVars
        - !Ref Stage
        - webSocketSubDomain
    Stage: !Ref Stage
```

Here are the variables:

```yaml
Mappings:
  stageVars:
    dev:
      webSocketSubDomain: "websocketdev"
    prod:
      webSocketSubDomain: "websocket"
```

In line with this websocket api, I also have a rest api, but I don't see how that will cause this error, so I'm just going to leave it out. I did see the restrictions note in https://docs.aws.amazon.com/apigateway/latest/developerguide/websocket-api-mappings.html saying "You can't map WebSocket APIs to the same custom domain name as an HTTP API or REST API." but my rest api is mapped to `api.mydomain.com` and my websocket is `websocket.mydomain.com`

Note that despite not being able to connect to the websocket using the custom domain, I can still connect to it using the default domain.

### Steps to reproduce:

Deploy a websocket domain with similar code to the above.

### Observed result:

Cannot connect to the wesocket using custom domain.

### Expected result:

Should be able to connect to the websocket using custom domain.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Github Actions -- linux
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.23.0
3. AWS region: ap-southeast-1

`Add --debug flag to any SAM CLI commands you are running`

N/A
