### ISSUE TITLE
ANY Method not working for SAM Function events when using Auth in API

### ISSUE THREAD

**Issue by silverlord-consulting** [aws/serverless-application-model#2017]
### Description:
We are using SAM for our Lambdas and APIs. We do all routing within our lambdas and thus rely heavily on the ANY method and proxies. This has been working flawlessly for 1.5 years. However today when I deployed one of our stacks, it failed with the response:

```
Structure of the SAM template is invalid. Path '/' contains method 'x-amazon-apigateway-any-method' which is not a supported method ['OPTIONS', 'GET', 'HEAD', 'POST', 'PUT', 'DELETE', 'PATCH']
```
After some trial and error I think I have narrowed it down to the Auth property of the API. If I do not have the Auth property set, I can deploy my function with Method: ANY set. If I add the Auth property, it fails. This now applies to all my stacks which contain a SAM API, virtually blocking us from deploying anything in any environment

I have reproduced this with a minimal SAM template
This is abit of an inconvenience as we would otherwise need to add all the listed methods for each endpoint.

### Steps to reproduce:
I could reproduce this by first deploying the following template:

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template with a simple API definition
Resources:
  CognitoPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ANYMethodTest

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      MethodSettings:
        - ThrottlingBurstLimit: 20
          ThrottlingRateLimit: 20
          HttpMethod: "*"
          ResourcePath: "/*"
          LoggingLevel: INFO
          MetricsEnabled: true
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoPool.Arn

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId:
              Ref: ApiGatewayApi
      Runtime: python3.7
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
            return {'body': 'Hello World!', 'statusCode': 200}
```
That will fail. Then deploying the same template again but removing the following results in a successfull deploy:

```
Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoPool.Arn
```

### Observed result:

SAM resports the template as valid, both in CLI and AWS Console. But when deploying, results in:

![failed](https://user-images.githubusercontent.com/55580031/118142324-8ccf4a80-b40a-11eb-976a-df36974fe365.png)

### Expected result:
Successful deploy, an API resource with ANY method and the specified authorizer to be created

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux Mint
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.23.0 (But the same problem happens in the AWS GUI)
3. AWS region: eu-west-1

**Comment by Zwawoo** [comment]
+1 I have the same problem.

**Comment by epretha** [comment]
I have the same issue in Mac OS 10.15.4 and SAM CLI version 1.6.2

**Comment by lorilew** [comment]
I have the same issue, my work around was to copy the event resource that used ANY for each method ['OPTIONS', 'GET', 'HEAD', 'POST', 'PUT', 'DELETE', 'PATCH'] - a little verbose but works.

**Comment by silverlord-consulting** [comment]
We solved it temporarely by removing the "DefaultAuthorizer" on the API, and added the Auth explicitly on each API resource:

```
Mappings:
    Type: Api
    Properties:
        RestApiId: !Ref MappingManagerApi
        Method: ANY
        Path: /{proxy+}
        Auth:
            Authorizer: auth0authorizer
```

I would prefer being able to use the DefaultAuthorizer though, because that requires you to explicitly whitelist the endpoints that do not require authentication, rather than now "blacklisting" the endpoints that actually do (Thus, if you accidentally forget to add the authenticator, requests can pass through)
