### ISSUE TITLE
StateMachine Events should support ScheduleExpression

### ISSUE THREAD

**Issue by mrichman** [aws/serverless-application-model#2025]
Currently, the only way to execute a Step Function based on an EventBridge schedule is by using `AWS::Events::Rule`. It would be great to simplify this by specifying a `ScheduleExpression` directly under `Type: EventBridgeRule` like this:

```
MyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/mystatemachine.asl.json
      DefinitionSubstitutions:
        MyFunctionArn: !GetAtt MyFunction.Arn
      Events:
        EventBridgeRule:
          Type: EventBridgeRule
          Properties:
            Description: Run my Step Function every 10 mins
            ScheduleExpression: "rate(10 minutes)"
```

This should also spare me from having to create and wire up corresponding roles to grant perms like `states:StartExecution` to `events.amazonaws.com` and so forth.
