### ISSUE TITLE
Unable to perform Readonly operation in AWS Step function using sam policy template

### ISSUE THREAD

**Issue by ihalder1** [aws/serverless-application-model#2030]
Unable to perform Readonly operation in AWS Step function using sam policy template

https://github.com/aws/serverless-application-model/pull/2028#issuecomment-841739700

**Comment by qingchm** [comment]
Hi @ihalder1 we previously closed the contribution PR since there were no response to the review requests, if you are still looking for this feature please reopen the PR and address the issues ;) Looking forward to your response, if this is no longer a request I can also help you close the ticket!

**Comment by hoffa** [comment]
You can use a connector as such:

```yaml
MyConnector:
  Type: AWS::Serverless::Connector
  Properties:
    Source:
      Id: FunctionLogicalId
    Destination:
      Id: StateMachineLogicalId
    Permissions:
      - Read
```

It supports read-only permissions, see:

https://github.com/aws/serverless-application-model/blob/5e3741c05f0635135469b15db5a2feabdd263440/samtranslator/model/connector_profiles/profiles.json#L311-L333
