### ISSUE TITLE
Incorrect changeset created when updating Function API Event Methods

### ISSUE THREAD

**Issue by shrinathk** [aws/serverless-application-model#2047]
### Description:
SAM does not create the changeset correctly when we update the HTTP Methods in the `Events` section of a Lambda function.

### Steps to reproduce:
1. Define a SAM template (given below) that creates a Lambda function with one GET and one PUT method and associated API Gateway.
2. Deploy the SAM template. API Gateway correctly created with GET and PUT methods.
3. Update the SAM template by changing the PUT to PATCH.
4. Redeploy the SAM template.

### Observed result:
The new PATCH method is added to the API Gateway but the old PUT method is not deleted.

### Expected result:
The new PATCH method should be added **_AND the old PUT method should be deleted_**.

#### SAM Template
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample Function

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "My API"
      StageName: prod

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: my-function
      Description: My Function
      Handler: io.micronaut.function.aws.proxy.MicronautLambdaHandler
      Runtime: java11
      CodeUri: s3://my-bucket/my-function.jar
      Events:
        MyGetAPI:
          Type: Api
          Properties:
            Method: get
            Path: /hello
            RestApiId:
              Ref: MyApi
        MyPutAPI:
          Type: Api
          Properties:
            Method: put
            Path: /update
            RestApiId:
              Ref: MyApi
```

#### Deployment Commands
Package - `sam package --template-file sam-template.yml --s3-bucket s3://my-bucket --output-template-file sam-template-packaged.yml`

Deploy - `sam deploy --region us-east-1 --template-file sam-template-packaged.yml --stack-name sample-stack --capabilities CAPABILITY_IAM --confirm-changeset`

#### Cloudformation stack changeset (initial run)
```
----------------------------------------------------------------------------------
Operation LogicalResourceId                ResourceType                Replacement                             
----------------------------------------------------------------------------------
+ Add     MyApiDeploymenth77a1567sj        AWS::ApiGateway::Deployment N/A                                     
+ Add     MyApiprodStage                   AWS::ApiGateway::Stage      N/A                                     
+ Add     MyApi                            AWS::ApiGateway::RestApi    N/A                                     
+ Add     MyFunctionMyGetAPIPermissionprod AWS::Lambda::Permission     N/A                                     
+ Add     MyFunctionMyPutAPIPermissionprod AWS::Lambda::Permission     N/A                                     
+ Add     MyFunctionRole                   AWS::IAM::Role              N/A                                     
+ Add     MyFunction                       AWS::Lambda::Function       N/A                                     
-----------------------------------------------------------------------------------
```
#### SAM Template Update
Changed MyPutAPI to MyPatchAPI as follows:

```yaml
MyPatchAPI:
  Type: Api
  Properties:
    Method: patch
    Path: /update
    RestApiId:
      Ref: MyApi
```

#### Cloudformation stack changeset (after PUT to PATCH update)
```
------------------------------------------------------------------------------------
Operation LogicalResourceId  		     ResourceType                Replacement                                   
------------------------------------------------------------------------------------
+ Add     MyApiDeployment7jy3kq9vf8          AWS::ApiGateway::Deployment N/A                                           
+ Add     MyFunctionMyPatchAPIPermissionprod AWS::Lambda::Permission     N/A                                           
* Modify  MyApiprodStage                     AWS::ApiGateway::Stage      False                                         
* Modify  MyApi                              AWS::ApiGateway::RestApi    False                                         
- Delete  MyApiDeploymente38a0754fd          AWS::ApiGateway::Deployment N/A                                           
- Delete  MyFunctionMyPutAPIPermissionprod   AWS::Lambda::Permission     N/A                                           
------------------------------------------------------------------------------------
```

#### APIGateway after initial deployment
![Before](https://user-images.githubusercontent.com/8599144/119618875-0579d200-be21-11eb-90ed-d0deaddc842e.png)

#### APIGateway after update deployment
![After](https://user-images.githubusercontent.com/8599144/119618888-0ad71c80-be21-11eb-9dac-396d6e8ed3b2.png)

**Comment by shrinathk** [comment]
Looks like this is not supported by `AWS::Serverless::Api` yet. 

As an alternative (if you plan to use `CloudFormation RestApi` instead of `Serverless Api`) there is a property called `Mode` in `AWS::ApiGateway::RestApi` which determines how API Gateway handles resource updates. The modes are `overwrite` and `merge`.

[Source](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html#cfn-apigateway-restapi-mode)

**Comment by c2tarun** [comment]
Hi @shrinathk,

I am not able to reproduce the issue. I used following template:

```
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "My Api"
      StageName: Prod
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        HelloWorldGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref ServerlessRestApi 
        HelloWorldPut:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /update
            Method: put
            RestApiId: !Ref ServerlessRestApi 

```

When I first deployed the template and run curl I got following response:
```
❯ curl --location --request PUT 'https://abcdefghi.execute-api.us-east-1.amazonaws.com/Prod/update/'
{"message":{"msg":"Hello World 2","method":"PUT"}}%
```

Then I changed put to patch in second event and ran these commands:

```
❯ curl --location --request PUT 'https://abcdefghi.execute-api.us-east-1.amazonaws.com/Prod/update/'
{"message":"Missing Authentication Token"}%
❯ curl --location --request PATCH 'https://abcdefghi.execute-api.us-east-1.amazonaws.com/Prod/update/'
{"message":{"msg":"Hello World 2","method":"PATCH"}}%
```

I also checked in console and my PUT method is removed

![Screen Shot 2021-06-03 at 2 56 40 PM](https://user-images.githubusercontent.com/1129670/120717160-eb24a180-c47b-11eb-9ba4-da750f8fc29b.png)

Can you please try one more time on a clean stack? Just trying to isolate if the problem is in something that is not captured in the added template.

Thanks
