### ISSUE TITLE
Ability to customize CloudWatch LogGroups for Lambda Functions

### ISSUE THREAD

**Issue by esteban1983cl** [aws/serverless-application-model#2057]
### Describe your idea/feature/enhancement

Provide a clear description.

Provide definition to configure cloudwatch log grups in SAM Template
Example: 

```yaml
Resources:
  DevOpsTaggerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../../tagger_function
      Handler: tagger/app.lambda_handler
      Runtime: python3.8
      CloudWatchLogGroup:
         Retention: 30d
         Name: CustomName
         Tags:
         - Key: Key1
            Value: Value1
```

Things to consider:
[x] The [SAM documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification.html) will need to be updated

**Comment by hawflau** [comment]
Hi @esteban1983cl , can you elaborate more about what you want to achieve?

Logs for a Lambda Function are pushed to the log group with name `/aws/lambda/<function name>`. It does not seem possible to specify which log group to push logs to from Lambda's perspective.

If you just want to change the retention period of the log group that the Lambda function pushes logs to, you can do something like this:
```
Resources:
  ServerlessFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ../../tagger_function
      Handler: tagger/app.lambda_handler
      Runtime: python3.8
      Role:
        Fn::GetAtt:
        - LambdaRole
        - Arn

  ServerlessFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ServerlessFunction}"
      RetentionInDays: 300

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
          Action:
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource:
          - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${ServerlessFunction}"
          - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${ServerlessFunction}:*"
          - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${ServerlessFunction}:*:*"


```

**Comment by grahamlyons** [comment]
It would be really nice to be able to set the log group expiration without having to define an extra resource. It's OK for a stack with one function but with more than that it gets annoying. A global option would be very useful.

**Comment by SamStephens** [comment]
In addition to this, there's a race condition that cannot be avoided unless you explicitly set the name of your Lambda. In [the example provided above](https://github.com/aws/serverless-application-model/issues/2057#issuecomment-863377830), it's possible for the Lambda function to be created first and called before the log group resource is created, which means the log group creation will then fail because the group already exists.

If you try and use DependsOn to ensure the log group is created first:

```
Resources:
  ServerlessFunction:
    DependsOn: ServerlessFunctionLogGroup
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ../../tagger_function
      Handler: tagger/app.lambda_handler
      Runtime: python3.8
      Role:
        Fn::GetAtt:
        - LambdaRole
        - Arn

  ServerlessFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ServerlessFunction}"
      RetentionInDays: 300
```

This template will fail because of the circular reference between ServerlessFunction and ServerlessFunctionLogGroup. You have to use an explicit function name to break this circular reference:

```
Resources:
  ServerlessFunction:
    DependsOn: ServerlessFunctionLogGroup
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Sub "serverless-function-${AWS::AccountId}-${AWS::Region}"
      CodeUri: ../../tagger_function
      Handler: tagger/app.lambda_handler
      Runtime: python3.8
      Role:
        Fn::GetAtt:
        - LambdaRole
        - Arn

  ServerlessFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/serverless-function-${AWS::AccountId}-${AWS::Region}"
      RetentionInDays: 300
```

So there's no way to cleanly and reliably set the retention period without support from the SAM framework. This is important to expose from a cost management perspective. No one should be creating production lambda code without setting the log retention period.

As has been pointed out, there's no way to customize the log group name. But something similar to the originally suggested syntax works if you remove the Name parameter:

```
Resources:
  DevOpsTaggerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../../tagger_function
      Handler: tagger/app.lambda_handler
      Runtime: python3.8
      CloudWatchLogGroup:
         Retention: 30d
         Tags:
         - Key: Key1
            Value: Value1
```
