### ISSUE TITLE
Openapi template cannot be transformed because of the size limitation of AWS::Include & Fn::Transform.

### ISSUE THREAD

**Issue by FirosStuart** [aws/serverless-application-model#2058]
Hi,
I'm trying to use `openapi.yml` as the definition of **RestApi** in SAM template. 
For some  reasons, the `openapi.yml` became very large (180KB, 6300 lines), 
and I got the following errors while trying to read the api definition from S3 using `DefinitionBody` and `AWS::Include && Fn::Transform`.
```
Error: Failed to create changeset for the stack: xxx-xxx-web-api, 
ex: Waiter ChangeSetCreateComplete failed: 
Waiter encountered a terminal failure state: 
For expression "Status" we matched expected path: "FAILED" 
Status: FAILED. 
Reason: Transform AWS::Serverless-2016-10-31 returned fragment exceeding 1000000 bytes
```

This is the part of `template.yml` that I am using.

```yaml
Resources:
  XXXXAPI:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: !Sub s3://${BucketName}/openapi.yml
      StageName: !Sub ${StageName}
```

I have tried using `DefinitionUri` and although it can be deployed, 
it can't read the resource name in `template.yml`, as this issue #305 said. 
And the conclusion of this issue is to recommend the use of `DefinitionBody`.

Should I split `openapi.yml` into several small files? And is there any other possible solution?
