### ISSUE TITLE
AWS::Serverless::Api always creates a stage named "Stage"

### ISSUE THREAD

**Issue by forzagreen** [aws/serverless-application-model#2077]
### Description:

`AWS::Serverless::Api` always creates an extra stage called "**Stage**", alongside the requested stage.

### Steps to reproduce:

I took the simplest example from [AWS::Serverless::Api](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html) docs.
I want the `StageName` to be called `Gamma`

My `template.yaml` file:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template with a simple API definition
Resources:
  MyTestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Gamma  # <-- Here is my stage name
  MyTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: MyTestApi
      Runtime: python3.8
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
            return {'body': 'Hello World!', 'statusCode': 200}
```

I deployed with `sam deploy --guided` , etc...

### Observed result:

The API Gateway is created with 2 stages: "**Gamma**" and "**Stage**".

<img src="https://user-images.githubusercontent.com/8544289/124616424-5811c980-de76-11eb-8123-0ba6410a189d.png" width="40%">

In CloudFormation stack, there is only one resource of type `AWS::ApiGateway::Stage` , which is `MyTestApiGammaStage` (Physical ID is `Gamma`).

The stage "**Stage**" is only deployed the first time. If I delete it manually, then run `sam deploy`, it's not redeployed.

### Expected result:
There should be only the stage "**Gamma**". The stage "**Stage**" must not be created.

### Additional environment details

1. Mac OS
2. SAM CLI version: 1.25.0
3. AWS region: eu-west-1

**Comment by CoshUS** [comment]
I was able to reproduce this behavior. Current workaround is to add `OpenApiVersion: 3.0.1` in the Api Propreties.
```
  MyTestApi:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: 3.0.1
      StageName: Gamma
```

Root cause is from the line below. Auto created deployment always uses the stage "Stage" instead of respecting the one specified in Api Properties.
https://github.com/aws/serverless-application-model/blob/c39d0a09623ea5eb47231682e20c97b7468ac481/samtranslator/model/api/api_generator.py#L335
