### ISSUE TITLE
Invalid value for 'RequestParameters' property - error in sam deploy cli

### ISSUE THREAD

**Issue by paolobenini** [aws/serverless-application-model#2109]
### Description:
After running "sam build" and "sam package", further "sam deploy" command fails, apparently due to an "Invalid Serverless Application Specification document". In reality the document is perfectly valid and generated by "sam build".
The error is: 
"Error: Failed to create changeset for the stack: chefwizard-api, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [ChefWizardApi] is invalid. Event with id [UpdateOrder] is invalid. Invalid value for 'RequestParameters' property. Keys must be in the format 'method.request.[querystring|path|header].{value}', e.g 'method.request.header.Authorization'."

### Steps to reproduce:
Command: "sam deploy --template-file template_generated.yaml --stack-name chefwizard-api --capabilities CAPABILITY_IAM"
I believe it can be reproduced just with the template_generated.yaml as it clearly is a template processing error.

[template_generated.zip](https://github.com/aws/serverless-application-model/files/6904917/template_generated.zip)

### Observed result:
"Error: Failed to create changeset for the stack: chefwizard-api, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [ChefWizardApi] is invalid. Event with id [UpdateOrder] is invalid. Invalid value for 'RequestParameters' property. Keys must be in the format 'method.request.[querystring|path|header].{value}', e.g 'method.request.header.Authorization'.

### Expected result:
Success

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
sam cli runs on Windows 10 power shell.

1. OS: Windows 10
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.27.1
3. AWS region: ap-southeast-2

`Add --debug flag to any SAM CLI commands you are running`

**Comment by paolobenini** [comment]
It appears to be some sort of limit in the number of Events. In fact, if I remove "UpdateOrder" from the template, I still get the same error on the next event.

**Comment by sriram-mv** [comment]
Looks like the RequestParameters need to be set in different format, as specified here: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-requestparameter.html

```
        FetchUser:
          Type: Api
          Properties:
            Path: /users/{user_id}
            Method: GET
            RequestParameters:
            - method.request.querystring.user_id:
                Required: true
                Caching: false

```

I set it in this format and it worked. Does that help in your case?

**Comment by paolobenini** [comment]
> Looks like the RequestParameters need to be set in different format, as specified here: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-requestparameter.html
> 
> ```
>         FetchUser:
>           Type: Api
>           Properties:
>             Path: /users/{user_id}
>             Method: GET
>             RequestParameters:
>             - method.request.querystring.user_id:
>                 Required: true
>                 Caching: false
> ```
> 
> I set it in this format and it worked. Does that help in your case?

Thanks for your test and comment and for taking the time to investigate.

[template.zip](https://github.com/aws/serverless-application-model/files/6910479/template.zip)

Sorry but it doesn't work on my side.
This is the error again:
"Error: Failed to create changeset for the stack: chefwizard-api, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [ChefWizardApi] is invalid. Event with id [FetchUser] is invalid. Invalid value for 'RequestParameters' property. Keys must be in the format 'method.request.[querystring|path|header].{value}', e.g 'method.request.header.Authorization'."
Attached my template.
What's the next step?

**Comment by chrisoverzero** [comment]
@paolobenini 

The template as written is malformed, which is why the generated template is incorrect. This input:

```yaml
# Written, original
RequestParameters:
  - method.request.querystring.user_id:
    Required: true
    Caching: false
```

…is producing this output:

```yaml
# Generated
RequestParameters:
- method.request.querystring.user_id: null
  Required: true
  Caching: false
```

…because the properties in the written template aren't indented correctly. It should look like this, where `Required` and `Caching` are each one indentation deeper.

```yaml
# Written, corrected
RequestParameters:
  - method.request.querystring.user_id:
      Required: true
      Caching: false
```

Using tools such as [cfn-lint][] can catch this sort of thing, and more – it's how I noticed the problem in my editor.

[cfn-lint]: https://github.com/aws-cloudformation/cfn-lint

**Comment by sriram-mv** [comment]
@paolobenini : @chrisoverzero has a good explanation. Closing this issue, feel free to re-open another issue if you are still seeing the same issue.

**Comment by paolobenini** [comment]
> @paolobenini
> 
> The template as written is malformed, which is why the generated template is incorrect. This input:
> 
> ```yaml
> # Written, original
> RequestParameters:
>   - method.request.querystring.user_id:
>     Required: true
>     Caching: false
> ```
> 
> …is producing this output:
> 
> ```yaml
> # Generated
> RequestParameters:
> - method.request.querystring.user_id: null
>   Required: true
>   Caching: false
> ```
> 
> …because the properties in the written template aren't indented correctly. It should look like this, where `Required` and `Caching` are each one indentation deeper.
> 
> ```yaml
> # Written, corrected
> RequestParameters:
>   - method.request.querystring.user_id:
>       Required: true
>       Caching: false
> ```
> 
> Using tools such as [cfn-lint](https://github.com/aws-cloudformation/cfn-lint) can catch this sort of thing, and more – it's how I noticed the problem in my editor.

Thanks a lot for your reply. I tried what you said and it worked! I've also installed cfn-lint and can now clearly see the error. Unfortunately there's a lack of documentation about it on AWS. Very few and basic examples.

**Comment by XXChester** [comment]
Hello, I am having a similar issue where my template builds and validates fine if I only have 1 request parameter but as soon as I add a second one, I start to get "Event with id [Write] is invalid. Invalid value for 'RequestParameters' property. Values must be an object,".

Here is the problematic portion of the SAM template:

```
WriteLeaderboardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: write_leaderboard.lambda_handler
      Runtime: python3.9
      ReservedConcurrentExecutions: 1
      MemorySize: 256
      Architectures:
        - x86_64
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref BucketName
      Events:
        Write:
          Type: Api 
          Properties:
            RestApiId: !Ref apis
            Path: /leaderboard
            Method: put
            Auth:
              ApiKeyRequired: true
            RequestParameters:
              - method.request.querystring.score:
                type: integer
                minimum: 0
                required: true
              - method.request.querystring.name:
                type: string
                minLength: 1
                maxLength: 25
                required: true
```
I've been banging my head on this all night and cannot figure it out. My indentation is correct based on rainbow colors plugin. Any help would be great. Thanks.
