### ISSUE TITLE
Cannot Add S3 Triggers to Lambda

### ISSUE THREAD

**Issue by omersi** [aws/serverless-application-model#2113]
### Description:
I had a long session with a support team representative who asked me to open a new issue, which relates to https://github.com/aws/serverless-application-model/issues/300

I need my lambda to be triggered by `s3:ObjectCreated:Put` event. 
I could get the function created, but the triggers weren't.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM template to deploy lambda functions

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    

# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-s3.html

Resources:
  MyTestingFunctionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: my_testing_function_sam
      CodeUri: my_code_path/
      Handler: app.lambda_handler
      PackageType: Zip
      DeploymentPreference: 
        Type: Canary10Percent10Minutes
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: files/

  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt MyTestingFunctionFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: 's3.amazonaws.com'
      SourceAccount: !Sub ${AWS::AccountId}
      SourceArn: !GetAtt Bucket1.Arn
  
  Bucket1:
    Type: 'AWS::S3::Bucket'
    proerties:
      BucketName: myBucket
```

In this [tutorial](https://medium.com/build-succeeded/subscribe-an-aws-lambda-function-to-an-s3-bucket-event-using-cloudformation-and-sam-80f979675f96), the composer is able to create a trigger, BUT, he's monitoring the same bucket that SAM uses for storing the deployment package.

### Steps to reproduce:
1. Run `sam build`
2. Run `sam deploy`
3. Check the lambda configuration and you'll see that the function was created without the triggers.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu Linux 20.04
2. SAM CLI version: 1.27.2
3. AWS region: us-east-1

**Comment by jfuss** [comment]
For S3, the "triggers" are not on lambda (`aws lambda list-function-event-invoke-configs`) but is viewed on the S3 bucket itself (`aws s3api get-bucket-notification-configuration`).

I deployed this app (which is a fully working version of the above)
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM template to deploy lambda functions

Globals:
  Function:
    Timeout: 300
    MemorySize: 512

Resources:
  MyTestingFunctionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: my_testing_function_sam
      CodeUri: hello_world/
      Handler: app.lambda_handler
      PackageType: Zip
      Runtime: python3.8
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: files/
  
  Bucket1:
    Type: 'AWS::S3::Bucket'
    proerties:
      BucketName: myBucket
```

This created the bucket notifications which are found on S3:
```
aws s3api get-bucket-notification-configuration --bucket testing-2113-bucket1-6jkpzi9ixg01
{
    "LambdaFunctionConfigurations": [
        {
            "Id": "d0f4d80c-c9a4-48c5-9e5f-bd26ce2a5ab2",
            "LambdaFunctionArn": "arn:aws:lambda:us-east-1:007174592951:function:my_testing_function_sam",
            "Events": [
                "s3:ObjectCreated:Put"
            ],
            "Filter": {
                "Key": {
                    "FilterRules": [
                        {
                            "Name": "Prefix",
                            "Value": "files/"
                        }
                    ]
                }
            }
        }
    ]
}
```

Are you not seeing the configuration on your bucket?
