### ISSUE TITLE
GetAtt ARN on SimpleTable returns bogus ARN

### ISSUE THREAD

**Issue by jasonmk** [aws/serverless-application-model#2123]
### Description:
When creating a SimpleTable resource in a sam template, GetAtt TableResource.ARN returns an invalid ARN.

### Steps to reproduce:
```yaml
  # resource in template.yaml
  TableResource:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey: 
        Name: id
        Type: String
      TableName: example-table
```

### Observed result:
Calling `!GetAtt TableResource.ARN` returns `arn:aws:lambda:us-east-1:123456789012:function:TableResource`.

Note that the ARN literally contains the account ID 123456789012.  That is NOT a placeholder for this example.

### Expected result:
Expect it to return something like `arn:aws:dynamodb:us-east-1:xxxxxxxxxxxx:table/example-table`.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: N/A
2. If using SAM CLI, `sam --version`: 1.27.2
3. AWS region: us-east-1
