### ISSUE TITLE
Add builtin policy template for synchronous StepFunction execution

### ISSUE THREAD

**Issue by eyalroth** [aws/serverless-application-model#2130]
**Description:**

Please add a builtin policy template for _synchronous_ StepFunction execution.

The current [StepFunctionsExecutionPolicy](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html#stepfunctions-execution-policy) adds permissions only for asynchronous executions, but not for asynchronous ones which require additional `states:` and `events:` policies (see https://docs.aws.amazon.com/step-functions/latest/dg/stepfunctions-iam.html).

Also see [this SO question](https://stackoverflow.com/questions/60612853/nested-step-function-in-a-step-function-unknown-error-not-authorized-to-cr).

**Comment by aahung** [comment]
Thanks for the suggestion @eyalroth

**Comment by hoffa** [comment]
[Connectors](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/managing-permissions-connectors.html) support Lambda functions executing state machines, and state machines executing state machines.

Use as such:

```yaml
MyConnector:
  Type: AWS::Serverless::Connector
  Properties:
    Source:
      Id: FunctionLogicalId
    Destination:
      Id: StateMachineLogicalId
    Permissions:
      - Write
```

For reference, function-to-state machine permissions:

https://github.com/aws/serverless-application-model/blob/5e3741c05f0635135469b15db5a2feabdd263440/samtranslator/model/connector_profiles/profiles.json#L288-L310

And state machine-to-state machine permissions:

https://github.com/aws/serverless-application-model/blob/5e3741c05f0635135469b15db5a2feabdd263440/samtranslator/model/connector_profiles/profiles.json#L647-L678
