### ISSUE TITLE
Bug In Sending Multiple $request values from a AWS::Serverless::HttpApi to a AWS::Serverless::StateMachine

### ISSUE THREAD

**Issue by NickLiffen** [aws/serverless-application-model#2138]
### Description:

In the following: `AWS::Serverless::HttpApi`, whenever I try and send multiple values from the `$request` to the Step Functions State Machine, it doesn't allow it and it breaks the build. I have it set to fail the build on `FailOnWarnings: True`. 

What do I mean? Basically, I would like to send multiple `$request` values to my step functions to be processed. I would like to send the `$request.body` and the `$request.headers.X`. 

However, you are only able to specify **ONE** input from the request. You can only specify `$request.body` OR `$request.headers.X`. Not both. 

I need to send both, as I need information from the headers but also the body. I have tried **so many** different combinations, but no luck. 

I tried writing a [Stack Overflow](https://stackoverflow.com/questions/69045453/aws-http-api-integration-with-aws-step-functions-send-multiple-values-in-the) post, but still no response. 

I think this is a bug. Step Functions can take multiple inputs, I just don't know why I can't send multiple values from a HTTP API down to a State Machine. 

Below I have some examples of` IaC` where it WORKS. However, if you change the  `Input: "$request.body"` to something like `Input: "$request" or:

```yaml
Input:
  $request.body
  $request.header.X-Hub-Signature-256 
```

It breaks. I just need to be able to send multiple values. 

### Steps to reproduce:

Deploy the following `AWS::Serverless::HttpApi` API: 

```yaml
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      FailOnWarnings: True
      DefinitionBody:
        info:
          version: '1.0'
          title:
            Ref: AWS::StackName
        paths:
          "/github/secret":
            post:
              responses: 
                default:
                  description: "Default response for POST /"
              x-amazon-apigateway-integration:
                integrationSubtype: "StepFunctions-StartExecution"
                credentials:
                  Fn::GetAtt: [StepFunctionsApiRole, Arn]
                requestParameters:
                  Input: "$request.body"
                  StateMachineArn: !Ref SecretScannerStateMachine
                payloadFormatVersion: "1.0"
                type: "aws_proxy"
                connectionType: "INTERNET"
                timeoutInMillis: 30000
        openapi: 3.0.1
        x-amazon-apigateway-importexport-version: "1.0"
```

Deploy the following `'AWS::IAM::Role`: 

```yaml
  StepFunctionsApiRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
      - PolicyName: AllowSFNExec
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "states:StartExecution"
              Resource: !Ref SecretScannerStateMachine
```

Finally, the `AWS::Serverless::StateMachine`:

```yaml
  SecretScannerStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: stepfunctions/secretscanner.yml
      Type: EXPRESS
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt SecretScannerStateMachineLogGroup.Arn
        IncludeExecutionData: true
        Level: ALL
```

Change the `Input: "$request.body"` value from the `AWS::Serverless::HttpApi` to try and send multiple values, or even `$request`. It will break and not work. 

### Observed result:

The observed output is a fail in the cloud formation deployment. However, if you try and put it onto an object with multiple values in and stringify it, it will deploy, but when you hit the HTTP API and it tries to connect to the Step Functions it will break and return a `400` HTTP Status. 

### Expected result:

- I can pass both the `$request.body` and `request.header.x` down to my step function for processing. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: 
2. If using SAM CLI, `sam --version`:
3. AWS region: `us-east-1`

`Add --debug flag to any SAM CLI commands you are running`
