### ISSUE TITLE
Conditional event attachment

### ISSUE THREAD

**Issue by glenveegee** [aws/serverless-application-model#214]
If conditional resource creation is eventually supported you might also have to support conditional events as in the following example where in some environments a bucket might not already exist and so it can be created and the event attached to the lambda. While in other environments the bucket may already exist and the trigger needs to be manually defined because cloudformation doesn't yet use existing resources.

***For example***

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Lambda that responds to S3 events

Parameters:
    PreExistingBucket:
        Description: "Does an existing bucket exist (not managed by cloudformation)"
        Type: String
        Default: 'no'
        AllowedValues:
            - 'yes'
            - 'no'
        ConstraintDescription: must specify yes or no.

Conditions:
  NeedsSomeBucket: !Equals [ !Ref PreExistingBucket, 'no' ]

Resources:
    BucketEventConsumer:
        Type: AWS::Serverless::Function
        Properties:
            Handler: BucketEventConsumer.main.lambda_handler
            Runtime: python3.6
            CodeUri: bundle.zip
            Events:
                CreateMetaEvent:
                    Condition: NeedsSomeBucket
                    Type: S3
                    Properties:
                        Bucket: !Ref SomeBucket
                        Events: "s3:ObjectCreated:*"
                        Filter:
                            S3Key:
                                Rules:
                                    -
                                        Name: suffix
                                        Value: meta.json
    SomeBucket:
        Condition: NeedsSomeBucket
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: 'some-bucket-somewhere'
        DeletionPolicy: Retain
```
I'd like to draw your attention to the following crucial lines:

```yaml
                CreateMetaEvent:
                    Condition: NeedsSomeBucket
```

> Can this already be acheived using Fn::If?

**Comment by brettstack** [comment]
Closing in favor of #142

**Comment by jaypadia-frame** [comment]
This one was created as a new Feature-Request based on the discussion in #142 . 

> @ glenveegee That is an interesting thought and idea! Would you mind create a new issue with this use case? It will help us prioritize this in the future and will ensure it does not get lost or forgotten about in this issue (since they are slightly different).

Closing this in favor of #142 doesn't make sense. Both of these are separate and useful features.

**Comment by glenak1911** [comment]
Any update on this? I've run into a similar use case and would like to use this feature as well.

**Comment by brettstack** [comment]
There are currently higher priority items we are focusing on. I've increased the priority label for visibility during planning and hope to get to this one along with #142 soon

**Comment by glenak1911** [comment]
Thanks for the feedback @brettstack !

**Comment by made2591-eb** [comment]
@brettstack Any update on this? I would like to conditionally enable or disable the event rule. I tried also using mapping but it seems it doesn't work either... so I'm wondering which kind of *intrinsic* functions (see [doc](https://github.com/awslabs/serverless-application-model/blob/develop/docs/cloudformation_compatibility.rst#events-properties)) are supported for real inside SAM template. Is there any other way to conditionally enable events? Thank you!

**Comment by keetonian** [comment]
@made2591-eb We have passed this along to our product team for possible prioritization. Please +1 on the feature to help with prioritization.

**Comment by takeshi4126** [comment]
+1 
I appreciate if you prioritise this issue. I have the exactly same issue as #1229 and have to manually disable a CloudWatch event once it is deployed in a staging environment. Thank you!

**Comment by kyletechspert** [comment]
Ran across this with an AWS::Serverless::Function using EventSource - unable to conditionally apply it. Would be great to see.

**Comment by andrescastillol** [comment]
+1

**Comment by jiminkk** [comment]
+1
This will help lessen a lot of cost savings and manual maintenance in dev stages.

**Comment by Catastropha** [comment]
Issue was opened in 2017
Soon 2021 arrives
Can you prioritize a bit more?

**Comment by RichDavis1** [comment]
+1

**Comment by jiojanen** [comment]
+1

**Comment by sleekmountaincat** [comment]
+1

**Comment by tniemann** [comment]
+1

**Comment by tniemann** [comment]
As a workaround, you can use AWS::Events::Rule

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#aws-resource-events-rule-syntax.yaml

**Comment by navigator3** [comment]
+1

**Comment by rickard-andersson-wcar** [comment]
+1

**Comment by decewei** [comment]
+1
One common use case is we use existing API gateway in production but we can't do it using SAM, so we end up having to remove API event on serverless function during production. We do like SAM's local testing ability and want to keep it there during dev.

**Comment by dave-kennedy** [comment]
> As a workaround, you can use AWS::Events::Rule
> 
> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#aws-resource-events-rule-syntax.yaml

How do you add an `AWS::Events::Rule` to an `AWS::Serverless::Function`?

**Comment by chrisoverzero** [comment]
@dave-kennedy 

It's the other way around. As one of the `Targets` of the `AWS::Events::Rule`, specify the Lambda Function.

```yaml
ExampleRule:
  Type: AWS::Events::Rule
  Properties:
    EventBusName: !Ref ExampleEventBus
    EventPattern: # the pattern to match, or use `ScheduleExpression` instead
    Targets:
    - Arn: !GetAtt ExampleFunction.Arn
      Id: Example # But use a unique value, natch.
```

And it's there in the resource that one can specify optionality. Either by `Condition` at the top level or something like `!If` on the `Targets` property.

**Comment by dave-kennedy** [comment]
@chrisoverzero if the event emitter is an SNS topic, is there any difference between creating an AWS::SNS::Subscription between the topic and the function as opposed to using AWS::Events::Rule?

**Comment by chrisoverzero** [comment]
I'm afraid I must not understand your question correctly. Are you asking whether you can use a rule to subscribe to a topic? SNS doesn't emit messages onto EventBridge buses, EventBridge does. An `AWS::Events::Rule` won't react to messages in SNS topics.

**Comment by Jacco** [comment]
Not entirely sure but can this request not already be solved:

```yaml
Resources:
    BucketEventConsumer:
        Type: AWS::Serverless::Function
        Properties:
            Handler: BucketEventConsumer.main.lambda_handler
            Runtime: python3.6
            CodeUri: bundle.zip
            Events:
                !If
                    - NeedsSomeBucket
                    - 
                        CreateMetaEvent:
                            Condition: NeedsSomeBucket
                            Type: S3
                            Properties:
                                Bucket: !Ref SomeBucket
                                Events: "s3:ObjectCreated:*"
                                Filter:
                                    S3Key:
                                        Rules:
                                            -
                                                Name: suffix
                                                Value: meta.json
                    - !Ref "AWS::NoValue"
```

The yaml is a little uggly. But is is similar to `example 4` here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html

**Comment by mluypaert** [comment]
> Not entirely sure but can this request not already be solved:
> 
> ```yaml
> Resources:
>     BucketEventConsumer:
>         Type: AWS::Serverless::Function
>         Properties:
>             Handler: BucketEventConsumer.main.lambda_handler
>             Runtime: python3.6
>             CodeUri: bundle.zip
>             Events:
>                 !If
>                     - NeedsSomeBucket
>                     - 
>                         CreateMetaEvent:
>                             Condition: NeedsSomeBucket
>                             Type: S3
>                             Properties:
>                                 Bucket: !Ref SomeBucket
>                                 Events: "s3:ObjectCreated:*"
>                                 Filter:
>                                     S3Key:
>                                         Rules:
>                                             -
>                                                 Name: suffix
>                                                 Value: meta.json
>                     - !Ref "AWS::NoValue"
> ```
> 
> The yaml is a little uggly. But is is similar to `example 4` here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html
> 
> Haven't testes this yet. The way described above could be syntactic sugar then.

Using the `!If` statement within the `Events` block does not work, as doing so throws the validation off. Having such a conditional in your template results in `sam validate` returning you an error like `Event with id [Fn::If:] is invalid. 'list' object has no attribute 'get'`.

@aws: It's been more than 4.5 years since this feature was requested. Please implement a solution for this!

**Comment by hoffa** [comment]
This is now doable.

Save the following as `template.yaml`:

```yaml
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Parameters:
  NeedBucket:
    Type: String

Conditions:
  NeedBucketCondition: !Equals [!Ref NeedBucket, "yes"]

Resources:
  MyBucket:
    Condition: NeedBucketCondition
    Type: AWS::S3::Bucket

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      Handler: foo
      InlineCode: bar
      Events:
        S3Event:
          Fn::If:
            - NeedBucketCondition
            - Type: S3
              Properties:
                Bucket: !Ref MyBucket
                Events: s3:ObjectCreated:*
            - !Ref AWS::NoValue
```

Then deploy with the S3 event:

```
sam deploy --region us-west-2 --resolve-s3 --capabilities CAPABILITY_IAM --stack-name test-214 --template template.yaml --parameter-overrides NeedBucket=yes
```

Or without the S3 event:

```
sam deploy --region us-west-2 --resolve-s3 --capabilities CAPABILITY_IAM --stack-name test-214 --template template.yaml --parameter-overrides NeedBucket=no
```

Adding `AWS::LanguageExtensions` ensures intrinsic functions that are known before deployed (such as the above) are resolved; see #2533.
