### ISSUE TITLE
Base policy for all functions in the "globals" section of the template

### ISSUE THREAD

**Issue by selcukcihan** [aws/serverless-application-model#2145]
### Describe your idea/feature/enhancement

I wish AWS SAM would allow me to declare shared policies in the "globals" section, to be applied to all the functions in the template.

### Proposal

```yaml
Globals:
  Function:
    Runtime: python3.7
    Policies:
       - CloudWatchPutMetricPolicy: {}
```
