### ISSUE TITLE
AWS::Serverless::Api does not expose DomainName or ApiKey properties

### ISSUE THREAD

**Issue by sarahpads** [aws/serverless-application-model#2151]
### Description:
According to the documentation, AWS::Serverless::Api will generate specific resources under-the-hood when certain attributes are set (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources-api.html#sam-specification-generated-resources-api-domain-name). I have set the UseagePlan property in my template, but I am unable to reference the ApiKey property within my template. I receive the error: `Template error: every Fn::GetAtt object requires two non-empty parameters, the resource name and the resource attribute`. In my case, I'm trying to stand CloudFront in front of ApiGateway and use the ApiKey as a required header to block requests that aren't coming from CloudFront. To do this, I am configuring CloudFront to set the ApiKey that is created by AWS::Serverless::Api as a custom header. Here are some of the things I've tried:
- Include ApiGateway inside CloudFront's DependsOn list
- Include the logical id for the generated ApiKey inside CloudFront's DependsOn list

During this process, I also noticed that the DomainName property isn't available when specifying the Domain.DomainName property in the template for AWS::Serverless::Api, though I do not have a version of my template to demonstrate.

Here's my template:

```
Transform:
- AWS::Serverless-2016-10-31

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: GatewayAuthorization

  CloudFrontDistro:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - ApiGateway
      - ApiGateway.ApiKey
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: <redacted>
            ID: !Ref ApiGateway
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: [ "TLSv1", "TLSv1.1", "TLSv1.2" ]
            CustomOriginHeaders:
              - HeaderName: "x-api-key"
                HeaderValue: !GetAtt ApiGateway.ApiKey # this doesn't work
        Enabled: true
        HttpVersion: http2
        DefaultCacheBehavior:
          AllowedMethods:
            - HEAD
            - GET
          Compress: true
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 0
          ForwardedValues:
            QueryString: true
          TargetOriginId: ApiGateway
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        Restrictions:
          GeoRestriction:
            Locations:
              - CA
            RestrictionType: whitelist

```

### Observed result:
```
Waiting for changeset to be created..
2021-09-16 16:07:40,482 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': <redacted>, 'installationId': <redacted>, 'sessionId': <redacted>, 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.12', 'samcliVersion': '1.31.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': 'ca-central-1', 'commandName': 'sam deploy', 'duration': 17974, 'exitReason': 'ChangeSetError', 'exitCode': 1}}]}
2021-09-16 16:07:41,157 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Failed to create changeset for the stack: <redacted>, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Template error: every Fn::GetAtt object requires two non-empty parameters, the resource name and the resource attribute
```
When removing the references to the ApiKey by commenting out the OriginCustomHeaders block and omitting the DependsOn list, the changeset is successfully created.

### Expected result:
The ApiKey value would be present, which would allow the changeset creation to succeed.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: mac
2. If using SAM CLI, `sam --version`: 1.31.0
3. AWS region: ca-central-1

Happy to provide any additional information or try out any suggestions. My apologies if there is something incorrect with my configuration or if I have misunderstood the documentation; any help is welcome and appreciated!

**Comment by hoffa** [comment]
Can you try using `!Ref` instead of `!GetAtt`?

[`!GetAtt`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html) requires an attribute that's returned by the resource, but [`AWS::Serverless::Api` has no attribute `ApiKey`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-resource-api-return-values). `ApiGateway.ApiKey` is the generated `AWS::ApiGateway::ApiKey` resource, which you can access like a regular logical ID.

Full example:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template with a simple API definition
Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Auth:
        UsagePlan:
          CreateUsagePlan: PER_API
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref ApiGateway
      Runtime: python3.9
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
            return {'foo': 'bar'}
Outputs:
  ApiKey1:
    Value: !Ref ApiGateway.ApiKey
  ApiKey2:
    Value: !GetAtt ApiGateway.ApiKey.APIKeyId
```

Which returns the expected outputs:

```
------------------------------------
Outputs                                                                                                                                                                                         
------------------------------------
Key                 ApiKey2                                                                                                                                                                     
Description         -                                                                                                                                                                           
Value               3990pnqf1k                                                                                                                                                                  

Key                 ApiKey1                                                                                                                                                                     
Description         -                                                                                                                                                                           
Value               3990pnqf1k                                                                                                                                                                  
------------------------------------
```

**Comment by sarahpads** [comment]
@hoffa I just gave that a shot and it worked! Thank you so so much for your help; I really appreciate it. The next thing I ran into is that this returns the logical id, but doesn't provide a way to get the value itself (which is what I need to send in the header). From what I've read, the actual ApiKey value isn't made available within cloudformation. This an entirely separate, unrelated problem with my approach itself. I'll close this ticket as this works as intended. If you have any recommendations around how to approach this next piece I'm all ears!

For posterity, here is the working template:
```
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration:
        Type: REGIONAL
      StageName: Dev
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: GatewayAuthorization

  CloudFrontDistro:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Join
            - ''
            - - !Ref ApiGateway
              - '.execute-api.'
              - !Ref AWS::Region
              - '.amazonaws.com'
            Id: !Ref ApiGateway
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: [ "TLSv1", "TLSv1.1", "TLSv1.2" ]
            OriginCustomHeaders:
              - HeaderName: "x-api-key"
                HeaderValue: !Ref ApiGateway.ApiKey # this DOES work!
        Enabled: true
        HttpVersion: http2
        DefaultCacheBehavior:
          AllowedMethods:
            - HEAD
            - GET
          Compress: true
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 0
          ForwardedValues:
            QueryString: true
          TargetOriginId: !Ref ApiGateway
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        Restrictions:
          GeoRestriction:
            Locations:
              - CA
            RestrictionType: whitelist

```

Thank you again!
