### ISSUE TITLE
HttpAPI properties are ignored when CorsConfiguration is not specified

### ISSUE THREAD

**Issue by FieryCod** [aws/serverless-application-model#2152]
### Description:

Let's take as an example the following `template.yml`:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 2048
  Environment:
    Type: String
    Default: staging

Globals:
  Function:
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize

Resources:
  ExampleOfHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      Description: "Some description"
      DisableExecuteApiEndpoint: True

  LambdaFunctionExample:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "ec2:CreateNetworkInterface"
              - "ec2:DeleteNetworkInterface"
              - "ec2:DescribeNetworkInterfaces"
              - "ec2:DetachNetworkInterface"
            Resource: "*"
      VpcConfig:
        SecurityGroupIds:
          - "sg-0022f72578ac5b373"
        SubnetIds:
          - "subnet-09e403ca9d13578df"
          - "subnet-00eb630443da8fc42"
          - "subnet-0833fa017fa879075"
      FunctionName: !Sub "LambdaFunctionExample-${Environment}"
      PackageType: Image
      Events:
        HttpProxyEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ExampleOfHttpApi
            Path: /{proxy+}
            Method: ANY
    Metadata:
      DockerTag: v1
      DockerContext: .
      Dockerfile: Dockerfile
```

This is perfectly valid template. What I found surprising is that the following properties are ignored:
- HttpApi::Description
- HttpApi::StageName
- HttpApi::DisableExecuteApiEndpoint

Hovewer after adding `CorsConfiguration` the above specified properties works.

### Steps to reproduce:

1. Modify the template

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 2048
  Environment:
    Type: String
    Default: staging

Globals:
  Function:
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize

Resources:
  ExampleOfHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      Description: "Some description"
      DisableExecuteApiEndpoint: True

  LambdaFunctionExample:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "ec2:CreateNetworkInterface"
              - "ec2:DeleteNetworkInterface"
              - "ec2:DescribeNetworkInterfaces"
              - "ec2:DetachNetworkInterface"
            Resource: "*"
      VpcConfig:
        SecurityGroupIds:
          - "sg-0022f72578ac5b373"
        SubnetIds:
          - "subnet-09e403ca9d13578df"
          - "subnet-00eb630443da8fc42"
          - "subnet-0833fa017fa879075"
      FunctionName: !Sub "LambdaFunctionExample-${Environment}"
      PackageType: Image
      Events:
        HttpProxyEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ExampleOfHttpApi
            Path: /{proxy+}
            Method: ANY
    Metadata:
      DockerTag: v1
      DockerContext: .
      Dockerfile: Dockerfile
```

2. Run `sam build`
3. Run `sam deploy --guided`

### Expected result:
I would expect that CorsConfiguration would not be required as it's specified in the documentation.
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html#sam-httpapi-corsconfiguration

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux
2. `sam --version`: 1.31.0
3. AWS region: eu-central-1

**Comment by hoffa** [comment]
Can't reproduce with `PackageType: Image` either:

```bash
sam init --name sam-app --package-type Image --base-image amazon/nodejs14.x-base
cd sam-app
```

With following template:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 2048
  Environment:
    Type: String
    Default: staging

Globals:
  Function:
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize

Resources:
  ExampleOfHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      Description: "Some description"
      DisableExecuteApiEndpoint: True

  LambdaFunctionExample:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "ec2:CreateNetworkInterface"
              - "ec2:DeleteNetworkInterface"
              - "ec2:DescribeNetworkInterfaces"
              - "ec2:DetachNetworkInterface"
            Resource: "*"
      FunctionName: !Sub "LambdaFunctionExample-${Environment}"
      PackageType: Image
      Events:
        HttpProxyEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ExampleOfHttpApi
            Path: /{proxy+}
            Method: ANY
    Metadata:
      DockerTag: v1
      DockerContext: ./hello-world
      Dockerfile: Dockerfile
```

Only differences with your template is the lack of `VpcConfig`, and using `./hello-world` for `DockerContext`.

Just to clarify, by

> the following properties are ignored

do you mean that the default values are used?

**Comment by FieryCod** [comment]
@hoffa My bad. Please try this:
```
sam init --name sam-app --package-type Image --base-image amazon/nodejs14.x-base
cd sam-app
```
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
Parameters:
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 2048
  Environment:
    Type: String
    Default: staging

Globals:
  Function:
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize

Resources:
  ServerlessHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      Description: "Some description"
      DisableExecuteApiEndpoint: True

  LambdaFunctionExample:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "ec2:CreateNetworkInterface"
              - "ec2:DeleteNetworkInterface"
              - "ec2:DescribeNetworkInterfaces"
              - "ec2:DetachNetworkInterface"
            Resource: "*"
      FunctionName: !Sub "LambdaFunctionExample-${Environment}"
      PackageType: Image
      Events:
        HttpProxyEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerlessHttpApi
            Path: /{proxy+}
            Method: ANY
    Metadata:
      DockerTag: v1
      DockerContext: ./hello-world
      Dockerfile: Dockerfile
```

![image](https://user-images.githubusercontent.com/14275210/133879966-f0dbc506-5803-4905-bb21-51477145c070.png)
