### ISSUE TITLE
SAM policy template - S3FullAccessPolicy

### ISSUE THREAD

**Issue by gadavis2** [aws/serverless-application-model#2154]
### Describe your idea/feature/enhancement

I would like the ability to list and delete all object versions in an S3 bucket.

### Proposal

Add the IAM policy actions ListBucketVersions and DeleteObjectVersion to the S3FullAccessPolicy.

Things to consider:
[ ] The [SAM documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification.html) will need to be updated

### Additional Details

https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectVersions.html
https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html

**Comment by CoshUS** [comment]
Thanks for the feedback. I'll bring this up with the team and see whether we can take this in without breaking existing use cases.

**Comment by baguilarq** [comment]
Any status?

**Comment by hoffa** [comment]
You can use a [connector](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/managing-permissions-connectors.html) as such:

```yaml
MyConnector:
  Type: AWS::Serverless::Connector
  Properties:
    Source:
      Id: FunctionLogicalId
    Destination:
      Id: BucketLogicalId
    Permissions:
      - Read
      - Write
```
