### ISSUE TITLE
!Sub & !Ref functions inside AWS::Serverless::Function API Paths fail

### ISSUE THREAD

**Issue by zero4573** [aws/serverless-application-model#2157]
The !Sub or !Ref functions don't seem to work when used inside the AWS::Serverless::Function, specifically for API paths.

Example:
```
  LambdaFunc:
    Type: AWS::Serverless::Function
    Properties:
      ...
      Events: 
        SomeEvent:
          Type: API
          Properties:
            Path: !Sub "${APIBasepath}/health"
      ...
```

**Outcome**

When running something like `sam local start-api` I get an error like:
```
Error: [InvalidResourceException('LambdaFunc', "Event with id [SomeEvent] is invalid. Api Event must have a String specified for 'Path'.")] ('LambdaFunc', "Event with id [SomeEvent] is invalid. Api Event must have a String specified for 'Path'.")
```

Bringing this back up since I didn't see anyone else bring it up apart from the comment [here](https://github.com/aws/serverless-application-model/issues/190) at the end of #190 apologies if I had missed someone else's ticket/resolution/discussion on this.
