### ISSUE TITLE
Different architecture support for Lambda functions

### ISSUE THREAD

**Issue by zachjonesnoel** [aws/serverless-application-model#2166]
### Describe your idea/feature/enhancement

Provide a clear description.

AWS Lambda recently announced about [Lambda functions powered by AWS Graviton2 processor](https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/) where it's mentioned that AWS SAM would also support the different architectures for the Lambda function. So that it's easier to deploy with `SAM build` CLI command.
Just searched for the options currently there was none and didn't find in the issue list so raising it. 

### Proposal

A new parameter on AWS SAM should be able define different architectures - 
+ arm64 (Recently announced)
+ x86_64 

```yaml
  Parameters:
     LambdaArchitecture:
        Type: String
        Default: x86_64
        AllowedValues:
             - x86_64
             - arm64
    Description: Lambda function Architecture type.
```
Sample parameter **Architecture** which accepts either **x86_64** or **arm64**
```yaml
        Type: AWS::Serverless::Function
        Properties:
              Architecture : !Ref LambdaArchitecture
```
Add details on how to add this to the product.

Things to consider:

- [x]  The [SAM documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification.html) will need to be updated
