### ISSUE TITLE
Sharing a single API dns name across varying base path names that represent API extensions

### ISSUE THREAD

**Issue by bmckinle** [aws/serverless-application-model#2175]
### Describe your idea/feature/enhancement

We need a way to extend an API across different repositories by creating a new base path name for an existing, shared API DNS name.  For example:

api.mycompany.com/service1  created in template1.yaml using a single API Gateway and Serverless Function resources.
api.mycompany.com/service2 created in template2.yaml using the template1.yaml API Gateway and different Serverless Function resources.  

### Proposal

Our understanding is that is a limitation of SAM but using a combination of CloudFormation and SAM can achieve automation that would achieve a shared api domain goal that supports extensions via basename changes only.  This should be supportable via SAM itself.

Things to consider:

Sharing API elements across SAM templates.  We are primarily looking ways to simplify maintaining a growing API over time without resorting to creating a unique domain name for each API extension that emerges from collaborating teams over time.  Ostensibly,
service1.mycompany.com
service2.mycompany.com 
...
is not as valuable as 
api.mycompany.com/service1
api.mycompany.com/service2
...

### Additional Details

AWS Support suggested we create this issue as the limitation of sharing a single API domain across SAM templates is a known limitation.

**Comment by troycampano** [comment]
@bmckinle I've been able to achieve this URL format using multiple SAM projects:
```
api.mycompany.com/service1
api.mycompany.com/service2
```
I used `AWS::ApiGateway::BasePathMapping` to associate various paths to my custom domain used in API Gateway. It looks like this:

```yml
  Microservice02Mapping:
    Type: 'AWS::ApiGateway::BasePathMapping'
    Properties:
      BasePath: 'app02'
      DomainName: api.hostname.com
      RestApiId: !Ref ApiGatewayApi
      Stage: Prod
```

I have mappings like this in each of my SAM projects. In the API Gateway console, under "Custom domain names", the "API mappings" tab looks like this:

![Screenshot 2022-12-06 220123](https://user-images.githubusercontent.com/10110352/206078038-e4137e3f-111e-4a1e-9673-0604515c9233.jpg)

I posted more details here: https://github.com/aws/serverless-application-model/discussions/2703#discussioncomment-4328858

**Comment by ricott** [comment]
@troycampano We use this approach extensively and it works ok. We use it for the HTTP API Gateway. It took a session with an AWS serverless specialist SA to come up with the solution a year ago when we adopted the pattern.
```
  ApiGatewayMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    DependsOn: Gateway
    Properties:
      ApiId: !Ref Gateway
      ApiMappingKey: !If [IsFeatureDeployment, !Sub '${AWS::StackName}/users', 'users']
      DomainName: !FindInMap [DeploymentEnvironment, !Ref Environment, DomainName]
      Stage: !Ref Gateway.Stage
```

You get a lot of API Gateways but at least it solves the _very_ basic problem of being forced to build a single monolithic API stack. With this approach, you can build and deploy multiple stacks independently and still use the same custom domain name, e.g. api.mycompany.com.

There is a problem though with paths. Imagine you have a users endpoint as per the example above. Gateway path mapping points to `/users`. Since users is now part of base path there is a problem with the path property of the individual serverless functions. If you want to expose a get with `/users/{user_id}` and a get with `/users` where you for instance want to allow a lookup via email - then this is not possible using this approach.

This works
```
      Events:
        GetUser:
          Type: HttpApi
          Properties:
            ApiId: !Ref Gateway
            Method: get
            Path: /{user_id}
            Auth:
              Authorizer: OAuth2Authorizer
              AuthorizationScopes:
                - "read:users"

```

This works but looks awful since the path has to be `/users/?email=abc@xyz.se` with the ending /.
```
        GetUsers:
          Type: HttpApi
          Properties:
            ApiId: !Ref Gateway
            Method: get
            Path: /
            Auth:
              Authorizer: OAuth2Authorizer
              AuthorizationScopes:
                - "read:users"
```

This means you have to add some artificial API mapping path like this, which we currently use
`ApiMappingKey: !If [IsFeatureDeployment, !Sub '${AWS::StackName}/u/v1', 'u/v1']`

Then for the serverless endpoints, you can use 
`Path: /users/{user_id}` and `/users`

Which results in these endpoints
```
get api.mycompany.com/u/v1/users/{user_id}
get api.mycompany.com/u/v1/users?email=
```

If we could import and share an API Gateway instance instead and only attach the serverless functions we wouldn't have this problem. My understanding is that the [serverless framework](https://www.serverless.com/framework/docs/providers/aws/events/apigateway#share-api-gateway-and-api-resources) supports this but I have gotten around to trying it yet.
