### ISSUE TITLE
Cannot use multiple Authorizers in AWS::Serverless::Function

### ISSUE THREAD

**Issue by pfeyssaguet** [aws/serverless-application-model#2192]
### Description:
I'm trying to use 2 different authorizers with API gateway, and so far it doesn't seem to work.

### Steps to reproduce:
This is part of my API gateway:

```yaml
MyApi:
  Type: AWS::Serverless::Api
  Properties:
    Name: MyApi
    StageName: prod
    Auth:
      DefaultAuthorizer: MyAuthorizerV1
      Authorizers:
        MyAuthorizerV1:
          UserPoolArn: !Ref CognitoUserPoolArn
        MyAuthorizerV2:
          UserPoolArn: !Ref CognitoUserPoolArn
          AuthorizationScopes:
            - 'aws.cognito.signin.user.admin'
```

This is my function with 2 distinct events, each one using a different path and a different authorizer:
```yaml
MyFunction:
  Type: 'AWS::Serverless::Function'
  Properties:
    FunctionName: my.function
    Handler: my.handler
    Events:
      MyEventV1:
        Type: Api
        Properties:
          RestApiId: !Ref MyApi
          Path: /test
          Method: get
          Auth:
            Authorizer: MyAuthorizerV1
      MyEventV2:
        Type: Api
        Properties:
          RestApiId: !Ref MyApi
          Path: /v2/test
          Method: get
          Auth:
            Authorizer: MyAuthorizerV2
```

### Observed result:
Both API gateway endpoints are using `MyAuthorizerV1`.
If I remove the `DefaultAuthorizer`, then both endpoints are using `NONE` as an Authorizer.

### Expected result:
The endpoint `/test` should be using `MyAuthorizerV1` and the endpoint `/v2/test` should be using `MyAuthorizerV2`.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS or Linux
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.23.0
3. AWS region: eu-west-1

Just to be more specific let me explain exactly what I'm trying to achieve here:
I already have live endpoints using my Cognito authorizer with `id_token`. I want to migrate and start using `access_token` instead. If I'm right, this is possible but I need to add `AuthorizationScopes` to my Authorizer.

Since I have clients already using the `id_token`, I can't just migrate without some kind of transition, which is why I wanted to create new endpoints prefixed by `/v2` and migrate the clients smoothly.

So far the only way I'm thinking of is duplicate the whole API part, which will generated another API gateway URL, and use CloudFront to cloak both API gateway domains under a single domain. Maybe there's a different technique to achieve this, in this case I'm open to suggestions.

**Comment by marcoblos** [comment]
Hi guys. Any updates on it? I'm trying to create 2 JWT authorizers and just the first one is created.

**Comment by GavinZZ** [comment]
Hi there, I did some investigation into this issues and I believe we now support multiple authorizers in SAM Function. Following your example, this is the complete template I tried:
```
Transform: AWS::Serverless-2016-10-31

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyAuthorizerV1
        Authorizers:
          MyAuthorizerV1:
            UserPoolArn: !GetAtt  MyCognitoUserPool.Arn
          MyAuthorizerV2:
            UserPoolArn: !GetAtt  MyCognitoUserPool.Arn
            AuthorizationScopes:
              - 'aws.cognito.signin.user.admin'

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      InlineCode: |
        exports.handler = async (event, context, callback) => {
          return {
            statusCode: 200,
            body: 'Success'
          }
        }
      Events:
        MyEventV1:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /test
            Method: get
            Auth:
              Authorizer: MyAuthorizerV1
        MyEventV2:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /v2/test
            Method: get
            Auth:
              Authorizer: MyAuthorizerV2

  MyCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: MyCognitoUserPoolRandomName


  MyCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: MyCognitoUserPool
      ClientName: MyCognitoUserPoolClient
      GenerateSecret: false

  MyFirstApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
    - MyUsagePlan
    Properties:
      Enabled: true
      StageKeys:
      - RestApiId:
          Ref: MyApi
        StageName:
          Ref: MyApi.Stage

  MyUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
    - MyApi
    Properties:
      ApiStages:
      - ApiId:
          Ref: MyApi
        Stage:
          Ref: MyApi.Stage

  MyUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId:
        Ref: MyFirstApiKey
      UsagePlanId:
        Ref: MyUsagePlan
      KeyType: API_KEY
```

In this template, I have one SAM Function that specified two API events, each using a different cognito authorizer. I am able to deploy this successfully and verified that `endpoint /test should be using MyAuthorizerV1 and the endpoint /v2/test should be using MyAuthorizerV2`.

Closing this issue as it's now supported.
