### ISSUE TITLE
Unable to update CloudFormation stack using the 'Use current template' option as the 'AWS::Serverless::Function' resource as the CodeUri values are hard-coded

### ISSUE THREAD

**Issue by sawalanipawan** [aws/serverless-application-model#2217]
### Description:

Updating a Serverless Function in a CloudFormation stack using the "Use current template" option from console, with some new parameter value, referencing a change to "CodeUri" property of "AWS::Serverless::Function" resource fails every time. The change set created by CloudFormation does not detect any changes.

Why does SAM hard-code the values for `CodeUri` section when using `AutoPublishAlias: Live`?

### Steps to reproduce:

Please find below steps to reproduce the issue:
1. Copy the below CFN template and save it on your local machine.

```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Test serverless function

Parameters:
  s3bucket:
    Type: String
  s3path:
    Type: String
  s3keyversion:
    Type: String

Resources:
  testServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      AutoPublishAlias: Live
      CodeUri:
        Bucket: !Ref s3bucket
        Key: !Sub ${s3path}/test.zip
        Version: !Ref s3keyversion
```
2. Navigate to AWS CloudFormation Console: https://eu-west-1.console.aws.amazon.com/cloudformation/home?region=eu-west-1#
3. Click on 'Create Stack' -> 'With new resources (Standard)' -> 'Upload template file'. Upload the above saved file.
4. Click 'Next' and then fill out parameter values for s3bucket, s3path and s3keyversion. These three parameters point to the lambda function zip file in your s3 bucket.
5. Click 'Next' -> 'Next' -> 'Create stack'

Once the stack is created, check the processed template, you will see that the `AWS::Lambda::Function` resource has hard-coded values for S3Bucket, S3Key and S3ObjectVersion. Below is the snippet:

```
    "testServerlessFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Handler": "lambda_function.lambda_handler",
        "Code": {
          "S3Bucket": "sawapawa-test",
          "S3Key": {
            "Fn::Sub": "mykey/test.zip"
          },
          "S3ObjectVersion": "yWZIx3FFztUHmHGSyfrdAL8fPdrr5ScL"
        },
        "Role": {
          "Fn::GetAtt": [
            "testServerlessFunctionRole",
            "Arn"
          ]
        },
        "Runtime": "python3.9",
        "Tags": [
          {
            "Value": "SAM",
            "Key": "lambda:createdBy"
          }
        ]
      }
    }
```
Now, if update the above deployed stack using the 'Use current template' option -> Click 'Next' -> change the value for the s3bucket parameter -> Click 'Next' -> Click 'Next'.
In the 'Change set preview' section you will see that CFN did not detect the change in s3bucket parameter because the AWS::Serverless Transform hard-coded the values.

### Observed result:

When using `AutoPublishAlias: Live`, the `CodeUri` values are hard-coded. But when you remove the AutoPublishAlias, the values are not hard-coded.

Below is the processed template snippet without `AutoPublishAlias: Live`

```
    "testServerlessFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Handler": "lambda_function.lambda_handler",
        "Code": {
          "S3Bucket": {
            "Ref": "s3bucket"
          },
          "S3Key": {
            "Fn::Sub": "${s3path}/test.zip"
          },
          "S3ObjectVersion": {
            "Ref": "s3keyversion"
          }
        },
        "Role": {
          "Fn::GetAtt": [
            "testServerlessFunctionRole",
            "Arn"
          ]
        },
        "Runtime": "python3.9",
        "Tags": [
          {
            "Value": "SAM",
            "Key": "lambda:createdBy"
          }
        ]
      }
    }
  }
```

### Expected result:

It is expected that CodeUri values will not be hard-coded.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

AWS region: eu-west-1
