### ISSUE TITLE
AWS::Serverless::Api Auth requires DefinitionBody but ignores DefinitionUri

### ISSUE THREAD

**Issue by eugene-bright** [aws/serverless-application-model#2228]
### Description:

`sam validate` treat mixture of properties `Auth` and `DefinitionUri` as invalid for resource `AWS::Serverless::Api`.

### Steps to reproduce:

```yaml
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: Test
      Auth: ...
      StageName: Test
      DefinitionUri: openapi.yaml
```

### Observed result:

`sam validate` warns:

```log
"Auth works only with inline Swagger specified in 'DefinitionBody' property."
```

### Expected result:

`DefinitionUri` should be treated as a valid equivalent of `DefinitionBody` when `Auth` is set.
The problem is critical as `Fn::Transform` doesn't seem to work in the `DefinitionBody` context.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Debian GNU/Linux 11
2. `sam --version`: SAM CLI, version 1.33.0
3. AWS region: us-east-1
