### ISSUE TITLE
How to specify handler for each function when using a custom Docker image

### ISSUE THREAD

**Issue by troyswanson** [aws/serverless-application-model#2244]
Hello all. I'm trying to discover how to specify the `CMD` for an individual function in a SAM project.

Generally when you are a Docker image in Lambda, you can include a line that looks like this:

```dockerfile
CMD [ "app.hello_world" ]
```

This will execute the function located at `app.hello_world`. This works great if you only have one function.

However, I have a single Dockerfile that I would like to use for multiple Lambda functions. Given that, I'm having difficulty locating where I would go to specify the handler for each function in my `template.yaml` file.

Thanks in advance for your help!

**Comment by troyswanson** [comment]
The `AWS::Serverless::Function` object type has a property called `ImageConfig`, which is itself an object that contains a property called `Command`. Using this, you can specify the command that should be run in the Docker container.

Example:

```yaml
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig: 
        Command:
          - app.hello_world
      Architectures:
        - x86_64
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: hello_world-v1
```
