### ISSUE TITLE
Error calling ECS tasks. AccessDeniedException due iam:PassRole action

### ISSUE THREAD

**Issue by apsergithub** [aws/serverless-application-model#2247]
### Description:
I have created a Lambda funtion that execute a ECS tasks using run_task from boto3
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.run_task

The policy inside my template look like this:

```yaml
      Policies:
        - EcsRunTaskPolicy:
            TaskDefinition: sample-batch-job:*

```
### Observed result:

I get an AccessDeniedException

> "errorMessage": "An error occurred (AccessDeniedException) when calling the RunTask operation: User: arn:aws:sts::123456789:assumed-role/[role]/[function] is not authorized to perform: iam:PassRole on resource: arn:aws:iam::123456789:role/ecsTaskExecutionRole because no identity-based policy allows the iam:PassRole action"

### Expected result:

EcsRunTaskPolicy should be enough to execute a ECS task, otherwise some documentation should be added to the development guide.

I think that something like this must be added automatically with EcsRunTaskPolicy

```json
  {
            "Effect": "Allow",
            "Action": [
                "iam:PassRole"
            ],
            "Resource": [
                "arn:aws:iam::************:role/ecsTaskExecutionRole"
            ]
  }
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. If using SAM CLI, `sam --version`: 1.36.0
3. AWS region: eu-west-1

`Add --debug flag to any SAM CLI commands you are running`

**Comment by torresxb1** [comment]
Hi @apsergithub, could you a sample template and handler, or steps to reproduce this?

**Comment by apsergithub** [comment]
Template
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ECSCallFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ecs_call/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Policies:
        - EcsRunTaskPolicy:
            TaskDefinition: sample-batch-job:*

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ECSCallFunction:
    Description: "ECS call Lambda Function ARN"
    Value: !GetAtt ECSCallFunction.Arn
  ECSCallFunctionIamRole:
    Description: "Implicit IAM Role created for ECS call function"
    Value: !GetAtt ECSCallFunctionRole.Arn
```

Handler

```
import json
import boto3

def lambda_handler(event,context):
  client = boto3.client('ecs')
  response = client.run_task(
    capacityProviderStrategy=[
        {
            'capacityProvider': 'FARGATE_SPOT'
        },
    ],

  cluster='foobar', 
  #launchType = 'FARGATE',
  taskDefinition='sample-batch-job:1',
  count = 1,
  platformVersion='LATEST',
  networkConfiguration={
        'awsvpcConfiguration': {
            'subnets': [
                'subnet-0933a9a24a0888df6',
                'subnet-013be239a14c81b3d',
                'subnet-0cb6036951ec13541'
            ],
            'assignPublicIp': 'ENABLED'
        }
    })
  return str(response)

```
