### ISSUE TITLE
 Reuse AWS::Lambda::Permission across multiple serverless functions for resource-based policies. 

### ISSUE THREAD

**Issue by MattLish** [aws/serverless-application-model#2249]
### Describe your idea/feature/enhancement

Often, we will have multiple serverless functions that need the same resource-based policies.
An example of this is when we have multiple lambdas to support the same resource, such as AWS Connect.
Each of these serverless functions requires an `AWS::Lambda::Permission` to give access to AWS Connect.
Currently, each resource-based policy requires a `FunctionName`.
This is fine with a small number but as the number increases in a single `template.yaml`, there is a lot of duplicated code.

e.g.

```yaml
Resources:
  Func1ConnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: connect.amazonaws.com
      FunctionName: !GetAtt Func1.Arn
      SourceArn: arn:aws:connect:eu-central-123:instance/123

  Func1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Func1
      Runtime: nodejs14.x
      FunctionName: Func1
      Policies:
        - LambdaInvokePolicy
        - Func1ConnectPermission

  Func2ConnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: connect.amazonaws.com
      FunctionName: !GetAtt Func2.Arn
      SourceArn: arn:aws:connect:eu-central-123:instance/123

  Func2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Func2
      Runtime: nodejs14.x
      FunctionName: Func2
      Policies:
        - LambdaInvokePolicy
        - Func2ConnectPermission

...etc

```

This isn't very DRY and will grow to be quite unmaintainable.

### Proposal

Support passing a `FunctionName` as a parameter to a permission.

e.g. something like

```yaml
Resources:
  ConnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: connect.amazonaws.com
      SourceArn: arn:aws:connect:eu-central-123:instance/123

  Func1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Func1
      Runtime: nodejs14.x
      FunctionName: Func1
      Policies:
        - LambdaInvokePolicy
        - ConnectPermission:
            FunctionName: !GetAtt Func1.Arn
  
  Func2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Func2
      Runtime: nodejs14.x
      FunctionName: Func2
      Policies:
        - LambdaInvokePolicy
        - ConnectPermission:
            FunctionName: !GetAtt Func1.Arn
```

This would allow the code to be a lot more DRY.

### Other things I have tried

- Using yaml anchors, but they aren't supported by AWS SAM
- Using [yq](https://github.com/mikefarah/yq) to support yaml anchors, but that gets messy quickly.
- Adding a new role in the template and attaching a policy to that role. IAM roles cannot have resource based policies attached in this way, unless I am missing something.

Things to consider:
[ ] The [SAM documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification.html) will need to be updated

### Additional Details

My knowledge of AWS permissions is fairly lacking, so if there is a more suitable way to achieve this then I will be more than willing to accept that.
