### ISSUE TITLE
Do I need to define PostTrafficLambdaFunction using "Traffic shifting using CodeDeploy"?

### ISSUE THREAD

**Issue by kenlee0305** [aws/serverless-application-model#2264]
Situation:
I am studying safe_lambda_deployments.rst in the docs directory.
[https://github.com/aws/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst](url)

Question:
I am confused about whether i need to define ```PostTrafficLambdaFunction``` using "Traffic shifting using CodeDeploy".
The docs are not clear enough to let people know this answer. 

Opinion:
If yes, please update the sample template to include it.
If no, please explicitly state it.

Thank you.

**Comment by awood45** [comment]
To be exactly clear, what are you trying to do? The pre/post traffic hooks are optional, but if you don't have either hooks or alarms then a traffic shifting deployment is not very helpful. So it's not strictly required but can be a useful part of a traffic shifting deployment design.

**Comment by awood45** [comment]
For what it's worth, the [documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-deploymentpreference.html) does clearly state that this parameter is not required.

**Comment by kenlee0305** [comment]
What i am doing is to find a way using sam template to shift my traffic in case  i will update my lambda function in the future.
That's what lead me to [https://github.com/aws/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst](url)

So my question is asking whether i need to define ```PostTrafficLambdaFunction``` in the template in the case of the session "Traffic shifting using CodeDeploy" in the link above, but not a general question asking whether this parameter is required in ```DeploymentPreference```.

To be short, i am asking in a specific case( please see the link i provide), not a general simple question.

**Comment by kenlee0305** [comment]
I have also mentioned in the topic that 'using "Traffic shifting using CodeDeploy"' and provided the relevant link [(https://github.com/aws/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst)](https://github.com/aws/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst) to clarify my situation.

**Comment by kenlee0305** [comment]
> To be exactly clear, what are you trying to do? The pre/post traffic hooks are optional, but if you don't have either hooks or alarms then a traffic shifting deployment is not very helpful. So it's not strictly required but can be a useful part of a traffic shifting deployment design.

What i am doing is to find a way using sam template to shift my traffic in case i will update my lambda function in the future.
That's what lead me to https://github.com/aws/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst

So my question is asking whether i need to define PostTrafficLambdaFunction in the template in the case of the session "Traffic shifting using CodeDeploy" in the link above, but not a general question asking whether this parameter is required in DeploymentPreference.

To be short, i am asking in a specific case( please see the link i provide), not a general simple question.

**Comment by kenlee0305** [comment]
> To be exactly clear, what are you trying to do? The pre/post traffic hooks are optional, but if you don't have either hooks or alarms then a traffic shifting deployment is not very helpful. So it's not strictly required but can be a useful part of a traffic shifting deployment design.

I have also mentioned in the topic that 'using "Traffic shifting using CodeDeploy"' and provided the relevant link (https://github.com/aws/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst) to clarify my situation.

**Comment by kenlee0305** [comment]
> To be exactly clear, what are you trying to do? The pre/post traffic hooks are optional, but if you don't have either hooks or alarms then a traffic shifting deployment is not very helpful. So it's not strictly required but can be a useful part of a traffic shifting deployment design.

In [this link](https://github.com/aws/serverless-application-model/blob/develop/docs/safe_lambda_deployments.rst), there is a example telling people how to shift traffic from old to new lambda function using CodeDeploy. 
What i want to do is exactly what the example do,including to shift traffic from old one to new one, and to create alarms.

The example in the link above is as follow.
```
MyLambdaFunction:
  Type: AWS::Serverless::Function
  Properties:
    Handler: index.handler
    Runtime: nodejs12.x
    AutoPublishAlias: live
    DeploymentPreference:
      Type: Linear10PercentEvery10Minutes
      Alarms:
        # A list of alarms that you want to monitor
        - !Ref AliasErrorMetricGreaterThanZeroAlarm
        - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm
      Hooks:
        # Validation Lambda functions that are run before & after traffic shifting
        PreTraffic: !Ref PreTrafficLambdaFunction
        PostTraffic: !Ref PostTrafficLambdaFunction
      # Provide a custom role for CodeDeploy traffic shifting here, if you don't supply one
      # SAM will create one for you with default permissions
      Role: !Ref IAMRoleForCodeDeploy # Parameter example, you can pass an IAM ARN

AliasErrorMetricGreaterThanZeroAlarm:
  Type: "AWS::CloudWatch::Alarm"
  Properties:
    AlarmDescription: Lambda Function Error > 0
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
      - Name: Resource
        Value: !Sub "${MyLambdaFunction}:live"
      - Name: FunctionName
        Value: !Ref MyLambdaFunction
    EvaluationPeriods: 2
    MetricName: Errors
    Namespace: AWS/Lambda
    Period: 60
    Statistic: Sum
    Threshold: 0

LatestVersionErrorMetricGreaterThanZeroAlarm:
  Type: "AWS::CloudWatch::Alarm"
  Properties:
    AlarmDescription: Lambda Function Error > 0
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
      - Name: Resource
        Value: !Sub "${MyLambdaFunction}:live"
      - Name: FunctionName
        Value: !Ref MyLambdaFunction
      - Name: ExecutedVersion
        Value: !GetAtt MyLambdaFunction.Version.Version
    EvaluationPeriods: 2
    MetricName: Errors
    Namespace: AWS/Lambda
    Period: 60
    Statistic: Sum
    Threshold: 0

PreTrafficLambdaFunction:
  Type: AWS::Serverless::Function
  Properties:
    Handler: preTrafficHook.handler
    Policies:
      - Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Action:
            - "codedeploy:PutLifecycleEventHookExecutionStatus"
          Resource:
            !Sub 'arn:${AWS::Partition}:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
      - Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
          Resource: !GetAtt MyLambdaFunction.Arn
    Runtime: nodejs12.x
    FunctionName: 'CodeDeployHook_preTrafficHook'
    DeploymentPreference:
      Enabled: False
      Role: ""
    Environment:
      Variables:
        CurrentVersion: !Ref MyLambdaFunction.Version
```

But the example does not include to define ```PostTrafficLambdaFunction```. 

So my question is whether i need to define  ```PostTrafficLambdaFunction```, or  ```PostTrafficLambdaFunction``` will be created automatically using the example template?
