### ISSUE TITLE
"Value null at 'stateMachineArn' failed to satisfy constraint" when using API even source for Step Functions

### ISSUE THREAD

**Issue by nmoutschen** [aws/serverless-application-model#2269]
### Description:

I am trying to define an integration between Amazon API Gateway REST API and AWS Step Functions using the [`AWS::Serverless::StateMachine` resource type](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html) and [Api Event](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-statemachineapi.html)

The stack deploys correctly, but when I try to invoke the endpoint, I get the following error message:

```
{"__type":"com.amazon.coral.validate#ValidationException","message":"1 validation error detected: Value null at 'stateMachineArn' failed to satisfy constraint: Member must not be null"}%
```

### Steps to reproduce:

1. Create a simple SAM template with a resource like this one:
```yaml
  PutStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: stepfunctions.asl.yaml
      DefinitionSubstitutions:
        TableName: !Ref Table
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /sfn/{id}
            Method: put
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref Table
      Type: EXPRESS
```
2. Deploy using `sam deploy -g`
3. Call the API endpoint using curl: `curl -X PUT <ENDPOINT>/sfn/123 -d '{"hello": "world"}'`

### Observed result:

The following error message:

```
{"__type":"com.amazon.coral.validate#ValidationException","message":"1 validation error detected: Value null at 'stateMachineArn' failed to satisfy constraint: Member must not be null"}%
```

### Expected result:

API Gateway is able to call the Step Functions directly.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS
2. If using SAM CLI, `sam --version`: 1.35.0
3. AWS region: eu-west-1

`Add --debug flag to any SAM CLI commands you are running`
