### ISSUE TITLE
Top level array Type Model fails validation

### ISSUE THREAD

**Issue by stevehogdahl** [aws/serverless-application-model#2278]
Setting the top level type of a Request Model fails validation with this error `Models schema is missing properties`. This shouldn't fail this validation because an array doesn't have named variables listed in the `properties` attribute. The array should be able to have an empty properties attribute.

### Steps to reproduce:
The following Model defines an array of user objects to be accepted by the API.
```
Users:
  type: array
  items:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
      name:
        type: string
```

### Observed result:
The model above fails validation with the following error.
`Models schema is missing properties`

### Expected result:
An array of User objects Model is created and used for validation.

**Comment by mildaniel** [comment]
Thanks for reporting the issue we will be investigating it further. Please watch this channel for more updates, and feel free to reach out.

**Comment by qingchm** [comment]
Unfortunately this is an expected behaviour, our SAM expects the Users array to not only have type but also properties, which is missing here
```
Users:
  type: array
  properties:
    some properties
  items:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
      name:
        type: string
```
This would be an example of a template that we accept and pass validation. Hope this unblocks you and please let us know if you have any further questions!
