### ISSUE TITLE
Hyphens are stripped from API mapping paths

### ISSUE THREAD

**Issue by AndrewKvalheim** [aws/serverless-application-model#2279]
### Description:

The template transform incorrectly [strips hyphens](https://github.com/aws/serverless-application-model/blob/ab6943a340a3f489af62b8c70c1366242b2887fe/samtranslator/model/api/api_generator.py#L503) from API mapping paths.

This was previously reported [in a comment](https://github.com/aws/serverless-application-model/issues/1456#issuecomment-652779157) on a related bug but was never addressed.

### Steps to reproduce:

Specify an API mapping path containing a hyphen:

```yaml
Globals:
  Api:
    Domain:
      BasePath: foo-bar
```

### Observed result:

The transformed path is missing the hyphen:

```json
{
  "Type": "AWS::ApiGateway::BasePathMapping",
  "Properties": {
    "BasePath": "foobar"
  }
}
```

### Expected result:

Hyphens are not removed, e.g. `foo-bar`.

### Additional environment details

- SAM CLI 1.35.0
- NixOS 21.11

**Comment by AndrewKvalheim** [comment]
Workaround:

```yaml
Resources:
  Issue2279BasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      RestApiId: !Ref ServerlessRestApi
      Stage: !Ref ServerlessRestApiProdStage
      DomainName: !Ref ServerlessRestApi.DomainName
      BasePath: foo-bar
```
