### ISSUE TITLE
Api Gateway integration extensions don't get added to OpenAPI definitions when they're included from an external file

### ISSUE THREAD

**Issue by Bouldersky** [aws/serverless-application-model#2282]
### Description:
Hi, I'm new to SAM so there's a good chance this is just user error, but it sure isn't obvious to me what I'm doing wrong. For some reason the `x-amazon-apigateway-integration` is not being added to a path that I defined in an openAPI DefinitionBody that's being included from an external yaml file for an Api resource. [Here's my complete example project](https://github.com/Bouldersky/sam-swagger-example), but I think the relevant sections are the resources section of the sam template:

```yaml
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: swagger.yml
  CreateUser:
    Type: AWS::Serverless::Function
    Properties:
      ...
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /user
            Method: post
            RestApiId: !Ref Api
```

and the corresponding `/user` path defined in the OpenAPI file: 

```yaml
paths:
  /user:
    post:
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
```

When I build & deploy this, sam isn't adding a `x-amazon-apigateway-integration` section to the /user path in the swagger file before uploading it to S3. Based on [these docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-definitionbody) and [this test case I found](https://github.com/aws/serverless-application-model/blob/ab6943a340a3f489af62b8c70c1366242b2887fe/tests/openapi/test_openapi.py#L258) it sure seems like this should work. It's particularly strange since the DefinitionUri documentation explicitly including an external file a supported pattern:

> Intrinsic functions are not supported in external OpenApi files referenced by DefinitionUri. **Use instead the DefinitionBody property with the Include Transform to import an OpenApi definition into the template.**

### Steps to reproduce:
1. clone [the linked repo](https://github.com/Bouldersky/sam-swagger-example)
2. run `sam build -t sam.yml && sam deploy -t sam.yml --resolve-s3`

### Observed result:
The ApiGateway resource fails to create with a `No integration defined for method` error. I downloaded the OpenAPI file that SAM uploaded to S3 (and referenced from the generated template), and I found that the /user path did not get a `x-amazon-apigateway-integration` section added to it. Here's file that SAM uploaded:

```yaml
openapi: '3.0.2'
info:
  title: Test API
  version: '1.0'
servers:
  - url: "https://3sp6l92kgf.execute-api.us-east-1.amazonaws.com/{basePath}"
    variables:
      basePath:
        default: "Prod"

components:
  schemas:
    user:
      type: object
      properties:
        userid:
          type: string
paths:
  /user:
    post:
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
```

### Additional environment details

1. OS: Linux
2. `sam --version`: SAM CLI, version 1.37.0
3. AWS region: us-east-1
