### ISSUE TITLE
SmSConfiguration property not possible for a Cogninto User Pool

### ISSUE THREAD

**Issue by dbenader** [aws/serverless-application-model#2283]
### Description:

When defining a Cognito user pool in the sam template, validation fails if you try to configure sms. This is unfortunate because sms is used so heavily today for mfa/user onboarding and should be available to use in sam apps. This issue is essentially the same as [#1252](https://github.com/aws/serverless-application-model/issues/1252) but unfortunately, no action was taken to resolve the issue (its been over 2 years)

### Steps to reproduce:
Add a Cognito user pool resource that includes an sms configuration:
```yaml
Resources:
  Users:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: users
        UsernameConfiguration:
           CaseSensitive: false
        AliasAttributes:
          - email
          - phone
        DeviceConfiguration:
          ChallengeRequiredOnNewDevice: true
        MfaConfiguration: OPTIONAL
        EnabledMfas:
          - SMS_MFA
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 2
            - Name: verified_phone_number
              Priority: 1
        AutoVerifiedAttributes:
          - email
          - phone_number
        EmailConfiguration:
          EmailSendingAccount: DEVELOPER
          From: <email>
          SourceArn:<arn>
        EmailVerificationSubject: Confirm your email
        EmailVerificationMessage: verification code  {####}
        SmsVerificationMessage: Your verification code {####}
        SmsConfiguration:  # CAUSE OF PROBLEM
          SnsCallerArn: !GetAtt UserPoolRole.Arn
          ExternalId: !Ref ExternalId
        Schema:
          - AttributeDataType: String
            Mutable: false
            Name: given_name
            Required: true
       ... 
       ...
       ...
```

### Observed result:
```bash
sam validate --debug
```

Template provided at 'path\to\template\template.yaml' was invalid SAM Template.
2022-01-09 15:01:38,141 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '169e7e14-4594-4067-a4d0-224a62a87238', 'installationId': '23f27017-025f-4435-8737-e14280c8cced', 'sessionId': '01ff58d0-679c-4b71-9ba3-48dd0563ee1b', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.36.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam validate', 'duration': 1665, 'exitReason': 'InvalidSamTemplateException', 'exitCode': 1}}]}
2022-01-09 15:01:38,541 | Telemetry response: 200
Error: [InvalidResourceException('Users', "Type of property 'SmsConfiguration' is invalid.")] ('Users', "Type of property 'SmsConfiguration' is invalid.")

### Expected result:
path\to\template.yaml is a valid SAM Template
2022-01-09 15:05:54,286 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '45a885d7-17aa-4bf8-a1f3-28ee8301f9a9', 'installationId': '23f27017-025f-4435-8737-e14280c8cced', 'sessionId': '370d4dca-ad80-4c71-92ba-de2c069541c1', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.36.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam validate', 'duration': 1591, 'exitReason': 'success', 'exitCode': 0}}]}
2022-01-09 15:05:54,667 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: windows 10
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.36.0
3. AWS region: us-east-2
