### ISSUE TITLE
Lambda Authorizer httpApi openapi.yaml not created

### ISSUE THREAD

**Issue by FedericoBorra** [aws/serverless-application-model#2290]
### Description:
Good morning,
i am trying to implement a lambda authorizer for an httpapi in apigateway. All my resources are created using cloudformation using a template.yaml file and an openapi.yaml file where the routes are defined.
The securitySchemes are also defined in the openapi.yaml file using the x-amazon-apigateway-authorizer tag. My problem is that the authorizer is not created in api gateway when I deploy the stack.

### Steps to reproduce:
This is my template.yaml file 
```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description:

Resources:
  # API ----------------------------------------------------------------------------------------------------------------
  APILogRole:
    Type: AWS::IAM::Role
    Properties:
      Description: 'IAM role for API Gateway Logging'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [apigateway.amazonaws.com]
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'

  APIGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt APILogRole.Arn

  BackendHttpAPI:
    Type: AWS::Serverless::HttpApi
    DependsOn:
      - AuthorizerLambda
      - AuthorizerInvokationRole
    Properties:
      StageName: !Ref Stage
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: openapi.yaml

  # Authorizer

  AuthorizerLambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: 'Authorizer for AudioMatch API'
      CodeUri: ./authorizer
      Handler: handler.handler
      Runtime: python3.7
      Timeout: 10
      MemorySize: 128
      Layers:
        - !Ref LibrariesLayer
      VpcConfig:
        SecurityGroupIds:
          - !Ref NoIngressSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB

  AuthorizerInvokationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
  LambdaInvocationPolicy:
    Type: AWS::IAM::Policy
    DependsOn: [AuthorizerInvokationRole]
    Properties:
      PolicyName: LambdaInvocationPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource: !GetAtt AuthorizerLambda.Arn
      Roles:
        - !Ref AuthorizerInvokationRole

  LibrariesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: python3.7
    Properties:
      Description: 'Dependencies for Lambda functions'
      RetentionPolicy: Delete
      ContentUri: libs/
      CompatibleRuntimes:
        - python3.7
```

This is the openapi.yaml file
```
openapi: 3.0.1

components:
  securitySchemes:
    LambdaAuth:
      type: "http"
      scheme: "bearer"
      bearerFormat: "JWT"
      x-amazon-apigateway-authorizer:
        type: "request"
        identitySource: "$request.header.Authorization"
        authorizerCredentials:
          Fn::GetAtt: [AuthorizerInvokationRole,Arn]
        authorizerUri:
          Fn::Join:
            - ""
            - - "arn:aws:apigateway:"
              - Ref: AWS::Region
              - ":lambda:path/2015-03-31/functions/"
              - Fn::GetAtt: [AuthorizerLambda,Arn]
              - "/invocations"
        authorizerPayloadFormatVersion: "2.0"
        enableSimpleResponses: true
        authorizerResultTtlInSeconds: 3600
```
This is the command used to build and deploy the stack:
`
sam build --use-container && sam deploy 
`

### Observed result:
Both `sam build` and `sam deploy` compile successfully

### Expected result:
LambdaAuth should be visible under Authorization->Manage authorizers in the API Gateway GUI

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Big Sur
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.37.0
3. AWS region: eu-central-1

**Comment by mildaniel** [comment]
Thanks for reporting the issue, we will be investigating it further. Please watch this channel for more updates, and feel free to reach out.

**Comment by hawflau** [comment]
When you use `AWS::Include` to include the `openapi.yml`, SAM (the service) does not have access to `openapi.yml`. So it could not read and modify what's inside the file. As a result, it could not add the authorizer into the open api definition. 

The only workaround is to embed your open api definition directly into `template.yaml` under `DefinitionBody`.

I understand it's a pain. We will discuss internally to see if there's anything we can do about this limitation.

**Comment by FedericoBorra** [comment]
Thanks @hawflau for the reply. 
After some tests I saw that the problem was in the definition of the securityScheme. In fact, by replacing this 
```
LambdaAuth:
  type: "http"
  scheme: "bearer"
  bearerFormat: "JWT"
  x-amazon-apigateway-authorizer:
    type: "request"
    identitySource: "$request.header.Authorization"
    authorizerCredentials:
      Fn::GetAtt: [AuthorizerInvokationRole,Arn]
    authorizerUri:
      Fn::Join:
        - ""
        - - "arn:aws:apigateway:"
          - Ref: AWS::Region
          - ":lambda:path/2015-03-31/functions/"
          - Fn::GetAtt: [AuthorizerLambda,Arn]
          - "/invocations"
    authorizerPayloadFormatVersion: "2.0"
    enableSimpleResponses: true
    authorizerResultTtlInSeconds: 3600
```
with this 
```
LambdaAuth:
  type: "apiKey"
  name: "Authorization"
  in: "header"
  x-amazon-apigateway-authtype: "custom"
  x-amazon-apigateway-authorizer:
    type: "request"
    identitySource: "$request.header.Authorization"
    authorizerCredentials:
      Fn::GetAtt: [AuthorizerInvokationRole,Arn]
    authorizerUri:
      Fn::Join:
        - ""
        - - "arn:aws:apigateway:"
          - Ref: AWS::Region
          - ":lambda:path/2015-03-31/functions/"
          - Fn::GetAtt: [AuthorizerLambda,Arn]
          - "/invocations"
    authorizerPayloadFormatVersion: "2.0"
    enableSimpleResponses: true
    authorizerResultTtlInSeconds: 3600
```


the resource was created even though defined in an external openapi.yaml.
