### ISSUE TITLE
FailOnWarnings Enabled with $default Stage on HTTP API Produces an Error

### ISSUE THREAD

**Issue by jessedoyle** [aws/serverless-application-model#2297]
### Description:

Hi there! I believe I've stumbled on a bug with a recent version release of `aws-sam-cli`.

My template hasn't changed at all, and it used to deploy the stack in the past without issue. 

After updating SAM CLI to version `1.37.0`, I'm now seeing an error when deploying the stack. 

It appears to occur because I've enabled the `FailOnWarnings` option in my HTTP API resource. 

I think the SAM CLI may be generating some configuration that produces warnings by default in the `AmazonApiGatewayV2` service.

### Steps to reproduce:

I'm able to reproduce the issue with a template that looks like this:

```yml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  AppApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      FailOnWarnings: true
      StageName: $default
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        AppHandler:
          Type: HttpApi
          Properties:
            ApiId: !Ref AppApi
```

### Observed result:

When deploying the stack I see the following error event in CloudFormation:

```
AppApi - Create Failed

Warnings found during import: Parse issue: attribute paths. 

Resource $default should start with / (Service: AmazonApiGatewayV2; Status Code: 400; 
Error Code: BadRequestException; Request ID: 1234; Proxy: null) (Service: null; Status Code: 404; Error Code: BadRequestException; Request ID: null; Proxy: null)
```

### Expected result:

The stack should deploy without issue.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS 12.1
2. `sam --version`: SAM CLI, version 1.37.0
3. AWS region: us-west-2
