### ISSUE TITLE
ResourceConflictException | function is currently in the following state: 'Pending'. StateReasonCode: 'Creating'

### ISSUE THREAD

**Issue by ognitio-technologies** [aws/serverless-application-model#2356]
### Description:
Nextjs project deployment error using serverless framework 

serverless.yml
```
coolncare:
  useDotenv: true
  component: "@sls-next/serverless-component@1.18.0"
  inputs:
    cloudfront:
      distributionId: "${env.AWS_CLOUDFRONT_ID}"
    bucketName: "${env.AWS_BUCKET_NAME}"
    bucketRegion: "ap-south-1"
    memory:
      defaultLambda: 512
      apiLambda: 512
    name:
      defaultLambda: "${env.APP_NAME}DefaultLambda"
```

Error:
 ResourceConflictException: The operation cannot be performed at this time. The resource arn:aws:lambda:us-east-1:403848688600:function:coolncare is currently in the following state: 'Pending'. StateReasonCode: 'Creating'

Expected result:
Deployment success with cloudfront url

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MAC
2. If using SAM CLI, `sam --version`: No
3. AWS region: ap-south-1
<img width="921" alt="Screenshot 2022-03-19 at 1 24 30 PM" src="https://user-images.githubusercontent.com/72864567/159112895-f009927b-27c7-4518-8c48-5f09029e7940.png">
