### ISSUE TITLE
Add AWS::Serverless::Function.EphemeralStorage

### ISSUE THREAD

**Issue by aidansteele** [aws/serverless-application-model#2361]
The `AWS::Lambda::Function` resource now supports a [`EphemeralStorage`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-ephemeralstorage) property.  `AWS::Serverless::Function` should also support this property. Today this does not work:

```
Resources:
  Regular:
    Type: AWS::Serverless::Function
    Properties:
      # other props
      EphemeralStorage:
        Size: 10240
```

The following error is returned:

> Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [Regular] is invalid. property EphemeralStorage not defined for resource of type AWS::Serverless::Function
