### ISSUE TITLE
Getting cors error when api gateway deployed using SAM template

### ISSUE THREAD

**Issue by sk-dotnetcoder** [aws/serverless-application-model#2372]
I have developed lambda functions in node.js and trying to deploy to api gateway with proxy integration using SAM templates. my lambda functions are returning headers as mentioned in AWS documentation

```
const response = {
       statusCode: 200,
       headers: {
           "Access-Control-Allow-Headers" : "Content-Type",
           "Access-Control-Allow-Origin": "https://www.example.com",
           "Access-Control-Allow-Methods": "OPTIONS,POST,GET"
       },
       body: JSON.stringify('Hello from Lambda!'),
   };

```
**template.yaml code part:**

```
GetClientFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: functions/GetClient/
        Handler: index.handler
        Runtime: nodejs14.x
      Events:
        GetClientCustomFieldMap:
          Type: Api
          Properties:
            RestApiId: !Ref ClientApi # this is api with authorizer configured
            Path: api/Client/GetClient/{name}   
            Method: get
```
It is creating all resources which mentioned in the path like 'api', 'Client', 'GetClient' but not with Options method, also getting cors error. Tried multiple ways from stackoverflow but could not resolve it. Followed this url as well [How to enable CORS with AWS SAM](https://stackoverflow.com/questions/67065130/how-to-enable-cors-with-aws-sam)

1. OS: Windows
2. `sam --version`: 1.40.1
3. AWS region: us-east-1
