### ISSUE TITLE
Models schema - array list not parsing

### ISSUE THREAD

**Issue by phenri00** [aws/serverless-application-model#2374]
### Description:

Trying to declare following: 

```
   Properties:
      Name: My AWS Serverless API
      Models: 
        myModel: 
          $schema: "http://json-schema.org/draft-04/schema#"
          properties: 
            foo: 
              type:
                - string
                - 'null'
```

I need a type which can be both string and null, this is possible to do manually do through the console. But does not work when defined in template.yaml, the type will be dropped.

OS: Mac 12.2.1
SAM: 1.45.0
AWS region: eu-north-1
