### ISSUE TITLE
Function ScheduledEvent error: "Parameter ScheduleExpression is not valid"

### ISSUE THREAD

**Issue by labarilem** [aws/serverless-application-model#2392]
### Description:

I'm trying to setup an EventBridge Scheduled Event for my Lambda Function using the SAM CLI.

My desired cron expression is:
`cron(0 0 * * ? *)`

But I get an error that causes a rollback when I try to deploy the stack.

I've tried setting the cron expression on the AWS console and it's considered valid.

I've tried these other expressions in my template.yml file:

```
cron(0 0 * * ? *)
cron(0 0 * * * *)
cron(0 0 ? * * *)
cron(0 1 * * ? *)
cron(1 1 * * ? *)
0 0 * * ? *
```

but they always return the same error when I try to deploy the stack.

I've also created a question on stackoverflow:
https://stackoverflow.com/questions/72118664/aws-sam-scheduledevent-error-parameter-scheduleexpression-is-not-valid

### Steps to reproduce:

Add this function in the `template.yml` file:
```
MyFun:
  Type: AWS::Serverless::Function
  Metadata:
    BuildMethod: makefile
  Properties:
    FunctionName: !Ref MyFunName
    Handler: dist/handlers/my-fun.handler
    Runtime: nodejs14.x
    MemorySize: 128
    Timeout: 10
    Environment:
      Variables:
        NODE_ENV: !Ref MyFunEnvNODEENV
    Layers:
      - !Ref RuntimeDependenciesLayer
    # EventBridge schedule config
    Events:
      ScheduledEvent:
        Type: Schedule
        Properties:
          # Every day at 0:00
          Schedule: cron(0 0 * * ? *)
    # Policies will be appended to the default role of this function
    Policies: []
    Tags:
      project: !Ref Project
        env: !Ref Env
```

Then deploy with `sam deploy`

### Observed result:

I get an error:
```
CREATE_FAILED                                            AWS::Events::Rule
Parameter ScheduleExpression is not valid. (Service:   
AmazonCloudWatchEvents; Status Code: 400; Error Code:       
ValidationException; Request ID:                            
fd2e61e6-2945-40fa-96d7-a86973f99f0d; Proxy: null)
```

### Expected result:

Stack deployed successfully.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.48.0
3. AWS region: eu-west-1

`Add --debug flag to any SAM CLI commands you are running`

**Comment by jfuss** [comment]
@labarilem That error is coming from the service not SAM-T. I did a check through the cli by doing `aws events put-rule --schedule-expression "cron(0 0 * * ? *)" --name MyRule1` and that worked as expected. 

Can you try again? I wonder if this was a transient error on the Service.

**Comment by labarilem** [comment]
Thanks @jfuss for the help. I've tried again and I got the same error.
`Parameter ScheduleExpression is not valid. (Service:  AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: e7a4ed31-99d7-4ecf-aaac-48725184af31; Proxy: null)`

**Comment by jfuss** [comment]
@labarilem 

I was able to deploy the following:

```
HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            # Every day at 0:00
            Schedule: "cron(0 0 * * ? *)"
```

So you are defining something wrong with your template.

**Comment by labarilem** [comment]
@jfuss 

This is my whole template file:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  # Global params
  Project:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - staging
      - prod
  # Lambda params
  StartExperiencesFunName:
    Type: String
  StartExperiencesFunEnvNODEENV:
    Type: String
  StartExperiencesFunEnvDATABASEURL:
    Type: String

Resources:
  StartExperiencesFun:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: !Ref StartExperiencesFunName
      Handler: dist/handlers/start-experiences.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          NODE_ENV: !Ref StartExperiencesFunEnvNODEENV
          DATABASE_URL: !Ref StartExperiencesFunEnvDATABASEURL
      Layers:
        - !Ref RuntimeDependenciesLayer
      # EventBridge schedule config
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            # Every day at 0:00
            Schedule: "cron(0 0 * * ? *)"
      # Policies will be appended to the default role of this function
      Policies: []
      Tags:
        project: !Ref Project
        env: !Ref Env

  # Shared layer with nodejs runtime dependencies
  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      LayerName: myproj-scheduled-functions-dependencies
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Delete

Outputs:
  StartExperiencesFunName:
    Value: !GetAtt StartExperiencesFun.Arn
  StartExperiencesFunRole:
    Value: !GetAtt StartExperiencesFunRole.Arn
```

The differences between this one and the other functions I've deployed are names and the event schedule.
Is there a way to get more info about the reported error? I've already tried with the `--debug` option.
