### ISSUE TITLE
DisableExecuteApiEndpoint not working with OpenApiVersion>=3.x.x

### ISSUE THREAD

**Issue by forzagreen** [aws/serverless-application-model#2396]
### Description:
`DisableExecuteApiEndpoint: True` is not working (i.e. the default endpoint is not disabled) when `OpenApiVersion` is set to 3.x.x versions (tested with `3.0.1` and `3.0.3`).

It works correctly when `OpenApiVersion: "2.0"`.

My resource:
```yaml
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: MyStage
      OpenApiVersion: "3.0.3"
      DisableExecuteApiEndpoint: True
```

When deployed, the processed template contains:
```json
"openapi": "3.0.3",
"x-amazon-apigateway-endpoint-configuration": {
  "disableExecuteApiEndpoint": true
}
```
But still the API Gateway default endpoint is not disabled.

I think this is a CloudFormation bug.

### Workaround: `OpenApiVersion: "2.0"`
It works in these 2 cases:
- When I set `OpenApiVersion: "2.0"`
- If I don't add `OpenApiVersion` at all. The translated JSON template gets `"swagger": "2.0"`.
  - But I need to pass `OpenApiVersion` to prevent SAM from creating a default stage `Stage` (cf. https://github.com/aws/serverless-application-model/issues/2077 and https://github.com/aws/serverless-application-model/issues/191) 

The processed template with `OpenApiVersion: "2.0" has:
```json
"swagger": "2.0",
"x-amazon-apigateway-endpoint-configuration": {
  "disableExecuteApiEndpoint": true
}
```

### Packages versions:
```
aws-lambda-builders==1.16.0
aws-sam-cli==1.49.0
aws-sam-translator==1.45.0
```
