### ISSUE TITLE
APIGW REST query string validation does not work

### ISSUE THREAD

**Issue by ymwjbxxq** [aws/serverless-application-model#2404]
### Description:
In the console, you have 4 options in the request validator:
- NONE
- body-only
- Validate body, query string parameters, and headers
- Validate query string parameters and headers

With the implicit API Definition, it is not possible to set "Validate query string parameters and headers"

### Steps to reproduce:
Create an Amazon API Gateway REST API with request validation.

```
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
....
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /mypath
            Method: GET
            RestApiId: !Ref MyApi
            RequestModel:
              Model: MyModel #you can omit this, because it is only for POST
              Required: true
              ValidateParameters: true
            RequestParameters:
              - method.request.querystring.id:
                  Required: true

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Models:
        MyModel:
          type: object
          required: 
            - id
          properties:
            id:
              type: string
```

### Observed result:
I have found the following issues:

- it is possible to omit a required parameter Model: MyModel
- With or without the model, the "request validator" will be set to "NONE"

### Expected result:
GIVEN Method: GET 
           and ValidateBody: false
           and ValidateParameters: true
WHEN deploy 
THEN request validator is "Validate query string parameters and headers"

GIVEN Method: GET 
           and ValidateBody: false
           and ValidateParameters: true
WHEN deploy 
THEN RequestModel.Model is not a required parameter.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. If using SAM CLI, `sam --version`: 1.48.0
3. AWS region: eu-central-1

**Comment by gantonopoulos** [comment]
What I have found by experimentation (AWS documentation is unfortunately not clear on that) is the following:

Just by setting 

``` yaml
RequestParameters:
    - method.request.querystring.id:
         Required: true
```

has no effect on the parameter's validation.

Once you define the RequestModel with ```ValidateParameters: true```, it gets "activated". 

The weird thing is that in order for the parameters to be validated, the model has to contain the "queryStringParameters" entry.

```
Models:
        MyModel:
          type: object
             required:
               - queryStringParameters
             properties:
                 queryStringParameters:
                    type: object
                    required:
                       - Id
```
Then it works.

What I haven't gotten to work is to validate Body AND QueryStringParameters. If I add a "Body" entry (following the same logic as the queryStringParameters) then both body and parameter validation don't work.

**Comment by gantonopoulos** [comment]
In the case of Serverless and Lambda Integration (as is I think the case you describe), the validation options in the console are the following:
a) None
b) body-and-params
c) body-only
d) params-only

Are you sure you are not confusing the context?

In version 1.50.0, I achieve validation working as expected. 
If I omit the ```Model```, deployment fails. 
If I reference any model schema and set 

``` yaml

           RequestModel:
              Model: MyModel
              Required: true
              ValidateParameters: true

```
then all parameters marked as ```Required: True``` under ```RequestParameters``` get validated (this setting seems to get ignored without RequestModel present). 

It appears that the model schema doesn't have to do anything with the parameter validation, maybe because [for basic validation, API Gateqway only validates the presence/emptyness of the parameters and not their content.](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-method-request-validation.html)

By setting the boolean on ```ValidateParameters``` and ```ValidateBody``` accordingly, I can achieve all available validation options.
