### ISSUE TITLE
Bug: Serverless::StateMachine EventBridgeRule Pattern not matching when bucket name is supplied

### ISSUE THREAD

**Issue by dominicfarr** [aws/serverless-application-model#2406]
### Description:
When creating a SAM with resource type of AWS::Serverless::StateMachine, for an EventBridge Rule that includes a Pattern for S3 Create Object for a **specific bucket**, when the create event happens the expected rule doesn't match and not event is triggered.

Supplying bucket name seems to only work via console. 

I have confirmed the following.

- If an identical rule is added via the console the rule triggered as expected. 
- If I remove the bucket name from the pattern in SAM the rule is triggered as expected
- If I open the rule in the console after SAM has created it, and simple re-create the same pattern via the console, the rule triggered as expected.

### Steps to reproduce:
This is a slightly modified version of the SAM quick starter stock pick step functions template. Modifying the event from schedule to S3 EventBridge
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  steps-tutorial

  Sample SAM Template for steps-tutorial

Parameters:
  BucketName:
    Type: String
    Description: The name of the test bucket this template creates

Resources:
  StockTradingStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/stock_trader.asl.json
      DefinitionSubstitutions:
        StockCheckerFunctionArn: !GetAtt StockCheckerFunction.Arn
        StockSellerFunctionArn: !GetAtt StockSellerFunction.Arn
        StockBuyerFunctionArn: !GetAtt StockBuyerFunction.Arn
        DDBPutItem: !Sub arn:${AWS::Partition}:states:::dynamodb:putItem
        DDBTable: !Ref TransactionTable
      Events:
        S3Trigger:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.s3
              detail-type:
                - 'Object Created'
              details:
                bucket:
                  name:
                    - !Ref BucketName
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref StockCheckerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref StockSellerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref StockBuyerFunction
        - DynamoDBWritePolicy:
            TableName: !Ref TransactionTable

  StockCheckerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/stock-checker/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  StockSellerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/stock-seller/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  StockBuyerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/stock-buyer/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

  TransactionTable:
    Type: AWS::Serverless::SimpleTable # More info about SimpleTable Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - HEAD
            AllowedOrigins:
              - '*'

Outputs:
  # StockTradingStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  StockTradingStateMachineArn:
    Description: 'Stock Trading state machine ARN'
    Value: !Ref StockTradingStateMachine
  StockTradingStateMachineRole:
    Description: 'IAM Role created for Stock Trading state machine based on the specified SAM Policy Templates'
    Value: !GetAtt StockTradingStateMachineRole.Arn
```

This template creates all the required resources successfully, and the Event pattern as follows.

```json
{
  "source": ["aws.s3"],
  "detail-type": ["Object Created"],
  "detail": {
    "bucket": {
      "name": ["stock-step-app"]
    }
  }
}
```

Creating another rule exclusively via the console, using all the same resources as used by the SAM, it creates this pattern.

```json
{
  "source": ["aws.s3"],
  "detail-type": ["Object Created"],
  "detail": {
    "bucket": {
      "name": ["stock-step-app"]
    }
  }
}
```
When editing the SAM event pattern via the console the output is this. [That is, the same as the two json above]
```json
{
  "source": ["aws.s3"],
  "detail-type": ["Object Created"],
  "detail": {
    "bucket": {
      "name": ["stock-step-app"]
    }
  }
}
```

### Observed result:
The pattern is created as expected in the rule for the default event bus, but does not trigger when S3 event occurs on configured bucket.

If I remove the bucket name from the SAM template the event is triggered as expected.

```yaml
Events:
        S3Trigger:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.s3
              detail-type:
                - 'Object Created'
```

### Expected result:
When S3 create object in the bucket name configured via SAM template  an event is triggered

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS
2. SAM CLI, version 1.33.0
3. AWS region: eu-west-2

`Add --debug flag to any SAM CLI commands you are running`

**Comment by mingkun2020** [comment]
Thanks @dominicfarr for reporting the issue, we will be investigating it further. Please watch this channel for more updates, and feel free to reach out.

**Comment by chrisoverzero** [comment]
```yaml

      Events:
        S3Trigger:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.s3
              detail-type:
                - 'Object Created'
              details: # here
                bucket:
                  name:
                    - !Ref BucketName

```

You have written `details`, not `detail`.
