### ISSUE TITLE
AutoPublishAlias is not triggered for timeout changes

### ISSUE THREAD

**Issue by tdmalone** [aws/serverless-application-model#2418]
### Description:
Changing the timeout for a function does not cause a new version to be published when using `AutoPublishAlias`.

### Steps to reproduce:
1. Deploy a SAM template with an `AWS::Serverless::Function` resource, with `AutoPublishAlias` set, and specifying any valid value for `Timeout`.
2. Change the `Timeout` value to another valid value, and redeploy.

### Observed result:
The `Timeout` value changes on `$LATEST`, but a new version is not created.

### Expected result:
A new version to be created, with the updated configuration.

### See also
Similar to https://github.com/aws/serverless-application-model/issues/1305, in particular note https://github.com/aws/serverless-application-model/issues/1305#issuecomment-562692061 which implies that relevant properties could be added to the hash used to determine if a new version is needed.

**Comment by mildaniel** [comment]
Hey @tdmalone, thanks for bringing this up. Since resolving this would be considered a backwards incompatible change, we are considering this as a candidate for when we version bump SAM.

**Comment by hoffa** [comment]
There's been a few similar requests (e.g. https://github.com/aws/serverless-application-model/issues/413). We can't update the most straightforward way as it would be a backward incompatible change (would cause many redeployments).

We could however consider an opt-in approach. Something like this (just rough idea):

```yaml
MyFunction:
  Type: AWS::Serverless::Function
  Properties:
    Timeout: 10
    AutoPublishAlias: live
    AutoPublishAdditionalProperties:
      - Timeout
    ...
```
