### ISSUE TITLE
Feature request: Packaging source bundles of Elastic Beanstalk

### ISSUE THREAD

**Issue by binchoo** [aws/serverless-application-model#2423]
### Packaging and uploading Elastic Beanstalk's source bundles
Hi, I am trying to package and upload a source bundle for my Elastic Beanstalk application via SAM CLI.

I thought this idea was possible because `sam package --help` said it could package the `AWS::ElasticBeanstalk::ApplicationVersion::SourceBundle`.
```bash
$ sam package --help

 The following resources and their property locations are supported.
 ...
 Resource : AWS::ElasticBeanstalk::ApplicationVersion | Location : SourceBundle
 ...
```

Below is the template that I used.
```yaml
Resources:
  ...
  MyApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref MyApplication
      SourceBundle: !Sub ./.aws-sam/build/${AWS::StackName}-${ArchiveVersion}.jar
```

`sam deploy` with this template caused an exception complaining about the value of the SourceBundle.
[The specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-beanstalk-sourcebundle.html) defines `S3Bucket` and `S3Key` properties in `SoureceBundle`, but mine has none of them.
```
Value of property SourceBundle must be an object.
The following resource(s) failed to create: [MyApplicationRole, MyApplicationVersion]. 
Rollback requested by user.
```

I doubt that `sam deploy` can package a source bundle without a capability to point to local source files.

If packaging for Elastic Beanstalk is already possible, I'd like to know some docs or tutorials relating to it.
If not, I hope this feature is supported by SAM CLI.
