### ISSUE TITLE
Bug: DisableExecuteApiEndpoint causes deployment warning in AWS::Serverless::HttpApi

### ISSUE THREAD

**Issue by dominickpastore** [aws/serverless-application-model#2424]
### Description:

When deploying an AWS::Serverless::HttpApi resource with `DisableExecuteApiEndpoint: true`, the deployment raises a warning that attribute `.servers.url` is missing. If `FailOnWarnings: true` is specified, this causes deployment to fail.

There is an existing issue open for `DisableExecuteApiEndpoint` at #2396, but it appears to be a different bug.

### Steps to reproduce:

This is the resource configuration I am using:

```
  WwwHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DisableExecuteApiEndpoint: true
      FailOnWarnings: true
      AccessLogSettings:
        DestinationArn: !GetAtt AccessLogs.Arn
        Format: $context.requestId
      DefaultRouteSettings:
        ThrottlingBurstLimit: 100
      RouteSettings:
        "GET /test":      
          ThrottlingBurstLimit: 100
```

Then I run `sam build` and `sam deploy`.

### Observed result:

```
-------------------------------------------------------------------------------------------------
ResourceStatus           ResourceType             LogicalResourceId        ResourceStatusReason   
-------------------------------------------------------------------------------------------------
UPDATE_IN_PROGRESS       AWS::ApiGatewayV2::Api   WwwHttpApi               -                      
UPDATE_FAILED            AWS::ApiGatewayV2::Api   WwwHttpApi               Warnings found during  
                                                                           import:         Parse  
                                                                           issue: attribute       
                                                                           .servers.url is        
                                                                           missing (Service:      
                                                                           AmazonApiGatewayV2;    
                                                                           Status Code: 400;      
                                                                           Error Code:            
                                                                           BadRequestException;   
                                                                           Request ID: 837734ce-e 
                                                                           82a-462b-90b0-df533638 
                                                                           e456; Proxy: null)     
                                                                           (Service: null; Status 
                                                                           Code: 404; Error Code: 
                                                                           BadRequestException;   
                                                                           Request ID: null;      
                                                                           Proxy: null)           
UPDATE_ROLLBACK_IN_PRO   AWS::CloudFormation::S   dcpx-org                 The following          
GRESS                    tack                                              resource(s) failed to  
                                                                           update: [WwwHttpApi].  
```

### Expected result:

Successful deployment with no warnings

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 20.04
2. If using SAM CLI, `sam --version`: `SAM CLI, version 1.52.0`
3. AWS region: us-east-1

**Comment by jfuss** [comment]
@dominickpastore This is an issue with your OpenApi. `DisableExecuteApiEndpoint` only add the configuration for telling API Gateway you don't want to use the `execute-api` endpoint. The warning is telling saying you need `.servers.url`, which given the warning I assume you are not putting that into your OpenApi spec.

**Comment by dominickpastore** [comment]
My goal here is something like the last example ("HttpApi with configuration settings") on the [documentation page for AWS::Serverless::HttpApi](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html). That example didn't contain an explicit OpenApi spec, so I figured I could allow SAM to generate it in my case as well. The main difference is that in my case, I wanted to use a custom domain name instead of the default endpoint, which sounds like exactly the situation `DisableExecuteApiEndpoint` is intended for:

> Specifies whether clients can invoke your HTTP API by using the default `execute-api` endpoint `https://{api_id}.execute-api.{region}.amazonaws.com`. By default, clients can invoke your API with the default endpoint. To require that clients only use a custom domain name to invoke your API, disable the default endpoint.

To that end, I did originally have a `Domain` property attached to the HttpApi also, but I took that off when trying to narrow down what was causing the issue, so that's why it's not in the resource configuration above. But here is the configuration I was originally using (and the Function resource as well), which is based on that documentation example, but also uses `DisableExecuteApiEndpoint` and `Domain` to try and replace the default endpoint with a custom domain:

```
  WwwHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DisableExecuteApiEndpoint: true
      FailOnWarnings: true
      Domain:
        CertificateArn: !Ref Certificate
        DomainName: www.dcpx.org
      AccessLogSettings:
        DestinationArn: !GetAtt AccessLogs.Arn
        Format: $context.requestId
      DefaultRouteSettings:
        ThrottlingBurstLimit: 100
      RouteSettings:
        "GET /test":      
          ThrottlingBurstLimit: 100

  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: provided.al2
      Handler: bootstrap.is.the.handler
      Architectures:
        - x86_64
      MemorySize: 128
      CodeUri: .
      Events:
        Test:
          Type: HttpApi
          Properties:
            ApiId: !Ref WwwHttpApi
            Path: /test
            Method: GET
```

So is the problem here that the `Domain` property isn't sufficient to establish an alternative endpoint when the default one is disabled?
