### ISSUE TITLE
AWS::Serverless::HttpApi's authorizers are missing AuthorizerResultTtlInSeconds field

### ISSUE THREAD

**Issue by andresmiguel** [aws/serverless-application-model#2447]
I've created an HTTP Api Gateway using `AWS::Serverless::HttpApi`. I've also created an **Authorizer** using the `Auth` property. However, there is no `AuthorizerResultTtlInSeconds` to cache the Authorizer's result as in `AWS::ApiGatewayV2::Authorizer`.
This is the link to the documentacion: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-httpapi-lambdaauthorizer.html.
And this is the relevant part from my SAM template:
```yaml
  MyHttpApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        DefaultAuthorizer: RESTRequestAuthorizer
        Authorizers:
          RESTRequestAuthorizer:
            FunctionArn: !GetAtt RESTAuthorizerFunction.Arn
            AuthorizerPayloadFormatVersion: 2.0
            EnableSimpleResponses: true
```

**Comment by jfuss** [comment]
@andresmiguel You want to use `ReauthorizeEvery` Property: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-httpapi-lambdaauthorizationidentity.html#sam-httpapi-lambdaauthorizationidentity-reauthorizeevery

This get placed into the OpenApi spec that we generate: https://github.com/aws/serverless-application-model/blob/67c2358907cc8477771de81ae4b8d48410464e39/samtranslator/model/apigatewayv2.py#L235

**Comment by andresmiguel** [comment]
@jfuss Yes indeed! Thanks a lot!

**Comment by skand888** [comment]
The solution worked for me as well, but it is somewhat disappointing when a reference example from the [documentation ](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-controlling-access-to-apis-lambda-authorizer.html#serverless-controlling-access-to-apis-lambda-authorizer-httpapi) does not work.

I suggest updating the documentation to include `ReauthorizeEvery`. Also `AuthorizerPayloadFormatVersion` is a string and should be in quotes. 

```
Resources:
  MyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyLambdaRequestAuthorizer
        Authorizers:
          MyLambdaRequestAuthorizer:
            FunctionArn: !GetAtt MyAuthFunction.Arn
            FunctionInvokeRole: !GetAtt MyAuthFunctionRole.Arn
            Identity:
              Headers:
                - Authorization
              ReauthorizeEvery: 30
            AuthorizerPayloadFormatVersion: "2.0"
            EnableSimpleResponses: true
```
