### ISSUE TITLE
Resource Type evaluated before conditions in SAR CFN template

### ISSUE THREAD

**Issue by rachit-shah** [aws/serverless-application-model#2448]
### Description
We use a single CFN template that deploys to our multi-region service. We use conditions for resources we don't want to deploy to a region or stage. 

We are trying to add new regions to our service. One of the regions is af-south-1 (CPT), however Serverless Application Repository (SAR) is not supported in the region: https://docs.aws.amazon.com/general/latest/gr/serverlessrepo.html

### Issue

To not deploy to the unsupported region, we added a condition similar to below:
```
AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"
Conditions:
  isNotSARUnsupportedRegion:
    'Fn::Not':
      - 'Fn::Equals':
          - Ref: 'AWS::Region'
          - af-south-1
Resources:
  LambdaJanitorServerlessApplication:
    Condition: isNotSARUnsupportedRegion
    Type: 'AWS::Serverless::Application'
    Properties:
      Location:
        ApplicationId: >-
          arn:aws:serverlessrepo:us-east-1:374852340823:applications/lambda-janitor
        SemanticVersion: 1.6.0
      Parameters:
        VersionsToKeep: 5
```

However, the deployment to CPT still fails because of error:
```
Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [LambdaJanitorServerlessApplication] is invalid. Serverless Application Repository is not available in this region.
```

**Expected**: CFN to evaluate condition before the resource type so that we don't deploy to the region at all.

**Actual**: CFN checks for resource type before the condition and fails because it is unsupported

Is there a way for us to keep using the SAR in our other regions but not deploy to CPT from the same template?
