### ISSUE TITLE
Removing the Alarms property from the serverless function DeploymentPreference does not remove the alarms from the created deployment group

### ISSUE THREAD

**Issue by moelasmar** [aws/serverless-application-model#2452]
### Description:
When in a SAM template, Alarms are removed from DeploymentPreference it doesn't not remove Alarm value on CodeDeploy Deployment Group console.

### Steps to reproduce:
1- deploy the following SAM Template
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: Simple Hello World Example

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
       Handler: HelloWorld.handler_aws
       CodeUri: ./
       Runtime: python3.9
       AutoPublishAlias: test
       DeploymentPreference:
          Enabled: true
          Type: Canary10Percent10Minutes
          Alarms:
            - Ref: AliasErrorMetricGreaterThanZeroAlarm
  AliasErrorMetricGreaterThanZeroAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: AliasErrorMetricGreaterThanZeroAlarm
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      EvaluationPeriods: 1
      Metrics:
      - Expression: ANOMALY_DETECTION_BAND(m1, 2)
        Id: ad1
      - Id: m1
        MetricStat:
          Metric:
            MetricName: Invocations
            Namespace: AWS/Lambda
          Period: !!int 86400
          Stat: Sum
      ThresholdMetricId: ad1
      TreatMissingData: breaching
```
2- check the created Deployment Group instance, and make sure that the alarms configuration is there.
3- update the created stack using the following SAM template:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: Simple Hello World Example

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
       Handler: HelloWorld.handler_aws
       CodeUri: ./
       Runtime: python3.9
       AutoPublishAlias: test
       DeploymentPreference:
          Enabled: true
          Type: Canary10Percent10Minutes
```
4- check the deployment group again. You will find the alarms is still there, although the expectation is it should be removed.

The issue is the generated CFN template after removing the Alarm configuration is as following:
```
HelloWorldFunctionDeploymentGroup:
    Properties:
      ApplicationName:
        Ref: ServerlessDeploymentApplication
      AutoRollbackConfiguration:
         ....
    Type: AWS::CodeDeploy::DeploymentGroup
```

Although it should be as following:
```
HelloWorldFunctionDeploymentGroup:
    Properties:
      ApplicationName:
        Ref: ServerlessDeploymentApplication
      AlarmConfiguration:
        Alarms: []
        Enabled: False
      .....
    Type: AWS::CodeDeploy::DeploymentGroup
```
to force CFN to update the deployment group, and to remove the alarms configuration from it.
