### ISSUE TITLE
Bug: SAM Templates don't produce valid Open API Specification Files after deployment to API Gateway

### ISSUE THREAD

**Issue by normand1** [aws/serverless-application-model#2459]
### Description:
I don't see a way to produce a valid Open API specification from a SAM template because there is no way to define the response models in the SAM template. Running through the Hello World sample SAM application demonstrates this behavior. After deploying to API gateway and then exporting the Open API spec the Open API Validator throws the following error:

```
Structural error at paths./hello.get
should have required property 'responses'
missingProperty: responses
```

I don't see any options for updating the response model for a function so I'm not sure how to resolve this error:
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html

### Steps to reproduce:
1. Follow Hello World Sam Deployment (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html)
2. Deploy to API Gateway: `sam deploy --guided`
3. Go to API Gateway and export the Open API specification for the Hello World API: (https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-export-api.html)
```
openapi: "3.0.1"
info:
  title: "sam-app"
  version: "1.0"
servers:
- url: "https://myexample.execute-api.us-west-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/Stage"
paths:
  /hello:
    get: {}
components: {}
```
 4. paste the exported open api spec to a swagger / OAS editor and view the error (https://editor.swagger.io/)

### Observed result:
```
Structural error at paths./hello.get
should have required property 'responses'
missingProperty: responses
Jump to line 11
```

### Expected result:
Expected API Gateway export schemas to pass validation.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS
5. If using SAM CLI, `sam --version`: SAM CLI, version 1.50.0
6. AWS region: us-west-1

**Comment by normand1** [comment]
Yes, it’s a valid SAM template, but the Open API Spec produced is not valid. Here is a screenshot of the error that the OAS Validator throws for the HelloWorld spec produced by API Gateway.
<img width="1680" alt="182476706-c444a9bc-c8ee-4012-bb24-793f9495db1c" src="https://user-images.githubusercontent.com/1393261/182477856-023172c5-c864-4cba-a228-cb29baa20acc.png">

```

Structural error at paths./hello.get
should have required property ‘responses’
missingProperty: responses
Jump to line 11
```

I can fix this invalid spec manually by including a default response like so:

> Valid Open API Spec
```
openapi: “3.0.1"
info:
  title: “sam-app”
  version: “1.0"
servers:
- url: “[https://myexample.execute-api.us-west-1.amazonaws.com/{basePath}](https://myexample.execute-api.us-west-1.amazonaws.com/%7BbasePath%7D)”
  variables:
    basePath:
      default: “/Stage”
paths:
  /hello:
    get:
      responses:
        default:
          description: “”
components: {}
```

I thought I'd be able to modify the sam template to produce a valid Open API spec export in API Gateway by using `AWS::Include` to include a valid open API Spec with a default response definition like so:

> template.yaml
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-test-app

  Sample SAM Template for sam-test-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: './api.yaml'
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref HelloWorldApi

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${HelloWorldApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
```

> api.yaml
```
openapi: "3.0.1"
info:
  title: "sam-test-app"
  version: "1.0"
paths:
  /hello:
    get:
      responses:
          default:
            description: ""
      x-amazon-apigateway-integration:
        type: aws
        httpMethod: GET
        uri : "arn:aws:apigateway:us-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-1:xxx:function:sam-test-app-HelloWorldFunction-xxx/invocations"
```

I'm able to build and deploy this, but now I'm getting an `internal server error` thrown from the HelloWorld Api and the exported Open API spec still doesn't include a response.

Any help is appreciated, thanks

**Comment by jfuss** [comment]
So the way we determine "valid" is by deploying to API Gateway. So if it is accepted by API Gateway it is a valid config (both yaml and OpenApi Spec). 

> I'm able to build and deploy this, but now I'm getting an internal server error thrown from the HelloWorld Api and the exported Open API spec still doesn't include a response.

Can you provide an example with code that shows this? This can be caused by a number of things (Lambda code, something not getting translated correctly, service issues with Lambda or Api Gateway, etc).

**Comment by normand1** [comment]
Sure, thanks for taking a look. I am using the default SAM hello world app just to keep things simple. I haven't modified any of the code though. I can actually fix the issue by just removing the `DefinitionBody` definition with the Include function so I think the issue is related to either my api.yaml definition or the template.yaml, but like you said they are valid and are able to be deployed...

> app.py
```
import json

# import requests


def lambda_handler(event, context):
    """Sample pure Lambda function

    Parameters
    ----------
    event: dict, required
        API Gateway Lambda Proxy Input Format

        Event doc: https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format

    context: object, required
        Lambda Context runtime methods and attributes

        Context doc: https://docs.aws.amazon.com/lambda/latest/dg/python-context-object.html

    Returns
    ------
    API Gateway Lambda Proxy Output Format: dict

        Return doc: https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html
    """

    # try:
    #     ip = requests.get("http://checkip.amazonaws.com/")
    # except requests.RequestException as e:
    #     # Send some context about this error to Lambda Logs
    #     print(e)

    #     raise e

    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "hello world",
            # "location": ip.text.replace("\n", "")
        }),
    }
```

**Comment by jfuss** [comment]
@normand1 I missed this before. You are using `AWS::include`, which will not work as you expect. The way CloudFormation works with include, means the file you are referencing will not be available to SAM (as `AWS::Include` will run after SAM does). This explains both why this failed and why it passes when you remove the `DefinitionBody`. You cannot mix the Events and providing the OpenApi Spec.

I would suggest if you want to use the Event structure in `AWS::Serverless::Function` to let SAM generate and not provide the `DefinitionBody` property at all.

**Comment by normand1** [comment]
Ok, yes that does make sense that you can't mix Events and an OpenApi Spec. However, if I try removing the Events definition and keeping the OpenAPI spec api definition then I'm still receiving an `internal server error` when trying to invoke the Hello World API from API gateway even though I'm able to deploy the SAM and Template file. Is there a good way to debug that issue because I'm not seeing any invocations of the function appear in cloud watch still.

Current files:
> Template.yml
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-test-app

  Sample SAM Template for sam-test-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: './api.yaml'
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${HelloWorldApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
```

> Api.yaml
```
openapi: "3.0.1"
info:
  title: "sam-test-app"
  version: "1.0"
paths:
  /hello:
    get:
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-1:<redacted>:function:sam-test-app-HelloWorldFunction-<redacted>/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws"
components: {}
```

**Comment by jfuss** [comment]
@normand1 Because you are wiring these up manually, you need `AWS::Lambda::Permission` resources to allow API Gateway to call Lambda. Otherwise there is no access allowed. Here is an example: https://github.com/aws/serverless-application-model/blob/develop/tests/translator/output/implicit_api.json#L35

**Comment by normand1** [comment]
Thanks for that suggestion, that did appear to be part of the problem. I've also discovered that I can view the API gateway logs directly and troubleshoot that way more efficiently too. So I was seeing an error related to Lambda Invocation permissions. 

However, now that that has been fixed I'm seeing a new error in API Gateway:
```
Execution failed due to configuration error: No match for output mapping and no default output mapping configured. Endpoint Response Status Code: 200
```

Is there a simple working example of a SAM Template using Open API that I can look at as a reference? I feel like I may just be missing something fundamental at this point...

Here are my current files I'm using for `sam build` / `sam deploy`:

> template.yaml
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-test-app

  Sample SAM Template for sam-test-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: './api.yaml'

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

  permissionForURLInvoke:
     Type: AWS::Lambda::Permission
     Properties:
       FunctionName: !Ref HelloWorldFunction
       Action: lambda:InvokeFunction
       Principal: '*'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${HelloWorldApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
```

> Api.yaml
```
openapi: 3.0.1
info:
  title: sam-hello-world
  version: '1.0'
servers:
  - url: 'https://tw10nn7pih.execute-api.us-east-1.amazonaws.com/{basePath}'
    variables:
      basePath:
        default: /Stage
paths:
  /hello:
    post:
      responses:
        default:
          description: 'test'
      x-amazon-apigateway-integration:
        httpMethod: POST
        uri: 'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:<redacted>:function:sam-hello-world-HelloWorldFunction-66iXZYWVPBuH/invocations'
        type: aws_proxy
```
