### ISSUE TITLE
Add State Property to Schedule EventSource in StateMachine

### ISSUE THREAD

**Issue by konoui** [aws/serverless-application-model#2467]
### Describe your idea/feature/enhancement

AWS::Serverless::StateMachine should support State property for Schedule EventSource as well as AWS::Serverless::Function does https://github.com/aws/serverless-application-model/issues/1329.
https://github.com/aws/serverless-application-model/pull/1666 does not fix AWS::Serverless::StateMachine.

### Proposal

We would like to use conditional logic for schedule event.

```
Resources:
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      (snip)
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            State:
              Fn::If:
              - IsDev
              - DISABLED
              - ENABLED
```
