### ISSUE TITLE
Lambda Function URL local development

### ISSUE THREAD

**Issue by slaphead** [aws/serverless-application-model#2472]
How do I run a lambda locally that has a lambda function url configured? I tried searching and could not find any documentation around this.
`sam local start-lambda` and `sam local start-api` do not appear to expose a lambda function url.

Is this supported and if so, how would this be achieved please?

Here is an extract of the configured lambda:
```
Resources:
  validator:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.validator
      AutoPublishAlias: live
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'
          AllowMethods:
            - POST
          AllowHeaders:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
            - workspace
            - network
```
