### ISSUE TITLE
SAM policy template "DynamoDBStreamReadPolicy" generates IAM role with incorrect resource ARN

### ISSUE THREAD

**Issue by jleatherwood** [aws/serverless-application-model#2476]
### Environment

aws-sam-cli v1.52.0

### Steps to reproduce

1. Create a SAM template containing a Function resource.
2. Attach to the "DynamoDBStreamReadPolicy" SAM Policy Template to the Function, specifying the Stream Name as an ISO 8601 date time string (as is used in the stream's corresponding ARN).
3. Deploy the SAM template.

[ExampleSAMTemplate.yml.txt](https://github.com/aws/aws-sam-cli/files/9403755/ExampleSAMTemplate.yml.txt)

### Expected

The SAM template generates an IAM role and attaches it to the deployed Lambda function. The IAM role contains an inline policy granting access to the DynamoDB stream.

### Actual

The SAM template generates an IAM role and attaches it to the deployed Lambda function. The IAM role contains an inline policy with an invalid ARN for the DynamoDB stream. Instead of ending with an ISO 8601 date time string like "2022-08-23T12:34:56.789", the policy ARN is like "2022-08-23 12:34:56.789000".

[GeneratedInlinePolicy.json.txt](https://github.com/aws/aws-sam-cli/files/9403754/GeneratedInlinePolicy.json.txt)

### Impact

Lambda functions deployed using a valid SAM template are unable to access DynamoDB streams.

**Comment by jfuss** [comment]
@jleatherwood Thanks for the report. We should be using whatever is in the template so somewhere the serialization is getting messed up. Which can be either CloudFormation or SAM. I would need to do a deeper dive to know which one is what, but this may have compatibility concerns if the behavior changes.

What happens if you explicitly define `StreamName: "2022-08-23T12:34:56.789"` instead of letting yaml do "yaml magic". My expectation would this would work and force the serialization to treat it as a string and not a date.

**Comment by aahung** [comment]
I did a quick test with this template:
```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: s3://a/b
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBStreamReadPolicy:
            TableName: mytable
            StreamName: 2022-08-23T12:34:56.789
```

after `sam build`, the output template looks like

```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://a/b
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Policies:
      - AWSLambdaBasicExecutionRole
      - DynamoDBStreamReadPolicy:
          TableName: mytable
          StreamName: 2022-08-23 12:34:56.789000
```

Moving this issue to SAM CLI repo. 

For our policy generator, there is no scenario that we expect the policy parameters to be a date. SAM CLI can raise an error in build stage.
