### ISSUE TITLE
Bug: HttpApi not exposing header

### ISSUE THREAD

**Issue by NWBY** [aws/serverless-application-model#2478]
### Description:
The `ExposeHeaders` option on the HTTP API CORS configuration isn't returning the `Access-Control-Expose-Headers` in preflight requests.

### Steps to reproduce:
Using a standard Python3.9 project with the following HTTP API configuration:
```yaml
  IveHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: 'prod'
      CorsConfiguration:
        AllowCredentials: true
        AllowMethods:
          - OPTIONS
          - GET
          - POST
        AllowHeaders:
          - 'x-apigateway-header'
          - 'content-type'
          - 'Authorization'
          - 'x-ive-token'
        AllowOrigins:
          - 'http://localhost:5173'
        ExposeHeaders:
          - 'x-ive-token'
          - 'Authorization'
```

### Observed result:
Screenshot from browser response:
<img width="601" alt="Screenshot 2022-08-24 at 20 54 47" src="https://user-images.githubusercontent.com/25590354/186510907-e067d71e-e025-4228-ac65-08c3f9e60895.png">

Response from cURL:
<img width="774" alt="Screenshot 2022-08-24 at 20 55 50" src="https://user-images.githubusercontent.com/25590354/186511093-f279cbd1-6cff-462a-b379-35ebfe701827.png">

### Expected result:

I would expect to see the following header: `Access-Control-Expose-Headers: x-ive-token,Authorization` in the response in the browser and cURL.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. If using SAM CLI, `sam --version`: 1.55.0
3. AWS region: eu-west-2
