### ISSUE TITLE
BUG: UserAttributeUpdateSettings not defined for resource of type AWS::Cognito::UserPool

### ISSUE THREAD

**Issue by alexandermjames** [aws/serverless-application-model#2496]
### Description:
It appears that the sam translator does not recognize or understand the following property for Cognito User Pools supported by CloudFormation. I created a Cognito User Pool with the following SAM template and it failed with this error:

Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 3. Resource with id [CognitoUserPool] is invalid. property UserAttributeUpdateSettings not defined for resource of type AWS::Cognito::UserPool Resource with id [CognitoUserPool] is invalid. property UserAttributeUpdateSettings not defined for resource of type AWS::Cognito::UserPool Resource with id [CognitoUserPool] is invalid. property UserAttributeUpdateSettings not defined for resource of type AWS::Cognito::UserPool

See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-userattributeupdatesettings for CloudFormation support.

### Steps to reproduce:

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM template

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          TemporaryPasswordValidityDays: 7
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: true
        DeviceOnlyRememberedOnUserPrompt: true
      EmailConfiguration:
        ConfigurationSet: ...
        EmailSendingAccount: DEVELOPER
        From: ...
        ReplyToEmailAddress: ...
        SourceArn: ...
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      UsernameAttributes:
        - email
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate: 
          - email
      UsernameConfiguration:
        CaseSensitive: false
      MfaConfiguration: "OFF"
      UserPoolName: !Sub ${AWS::StackName}-userpool
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
```

### Observed result:

Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 3. Resource with id [CognitoUserPool] is invalid. property UserAttributeUpdateSettings not defined for resource of type AWS::Cognito::UserPool Resource with id [CognitoUserPool] is invalid. property UserAttributeUpdateSettings not defined for resource of type AWS::Cognito::UserPool Resource with id [CognitoUserPool] is invalid. property UserAttributeUpdateSettings not defined for resource of type AWS::Cognito::UserPool

### Expected result:
Should have been successful.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.56.1
3. AWS region: us-east-2
