### ISSUE TITLE
Bug: AWS::ApiGateway::GatewayResponse header doesn't work

### ISSUE THREAD

**Issue by mehimanshupatil** [aws/serverless-application-model#2498]
### Description:
For timeout errors (504) since I am getting CORS error i have added `AWS::ApiGateway::GatewayResponse` as mentioned in [docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-controlling-access-to-apis-customize-response.html). but i am still getting CORS error.

### Steps to reproduce:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  aws-sam

Globals:
  Function:
    Runtime: nodejs16.x
    CodeUri: .
    Architectures:
      - arm64
    Timeout: 120
    MemorySize: 1024

Resources:
  GatewayResponseDefault5XX:
    Type: 'AWS::ApiGateway::GatewayResponse'
    Properties:
      ResponseParameters:
         gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
         gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      ResponseType: DEFAULT_5XX
      RestApiId:
        Ref: 'ApiGatewayApi'
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: staging
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'POST, OPTIONS'"
        AllowHeaders: "'*'"
  lambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: lambdaFn
      Handler: src/handlers/lambdaFn.handler
      Events:
        PublicFunctionCreate:
          Type: Api
          Properties:
            Path: /public/create
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
```
### Observed result:
since my lambda function takes more than 30sec to complete 
the API gateway returns 504 error but headers mentioned in Template are missing due to which CORS error is thrown

### Expected result:
API gateway returns 504 error with mentioned headers in template
