### ISSUE TITLE
BasePathMapping deployment error: Invalid stage identifier specified

### ISSUE THREAD

**Issue by yaminir** [aws/serverless-application-model#2499]
Based on the link below this should have been fixed by adding a `DependsOn` to `<api‑LogicalId><stage‑name>Stage` (as documented in this link: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources-api.html)

Template format error: Unresolved resource dependencies [RestAPIGatewaydevelopmentStage] in the Resources block of the template

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  APIStageName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: The name of the stage to deploy the API to.
    Default: /account/environment
Resources:    
  RestAPIGateway:
    Type: AWS::ApiGateway::RestApi
...
  APICustomDomainMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: 
     - RestAPIGatewaydevelopmentStage
    Properties:
      DomainName: !Ref APICustomDomain
      RestApiId: !Ref RestAPIGateway
      Stage: !Ref APIStageName
```

It is hard to believe that this issue has not been addressed after almost 5 years. It seems that adding an explicit dependson on the stage generated during translation should fix this. We got this to work by adding a `WaitConditionHandle` on the suggested stage name. Not clear why this does not work directly on the `DependsOn`, but in case it matters we are using AWS CLI 2.0 from CodeBuild project using `aws/codebuild/standard:5.0` image.

```yaml
  StageCreated:
    Type: AWS::CloudFormation::WaitConditionHandle
    Metadata:
      Created: !Sub RestAPIGateway${APIStageName}Stage

  APICustomDomainMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: 
     - StageCreated
```

The impact of this issue is that since it's a timing issue it some times work, so imagine it works in dev/test environments and it happens to fail in the production deployment, that would be a very bad experience.  think the difference is that we're using a `RestApi` vs `Api` and maybe that's why the workaround doesn't work for us.

**Comment by moelasmar** [comment]
Thanks @yaminir for raising this issue. 

I want to double check my understanding with you. You have a template that contains a RestAPiGateway resource of type `AWS::ApiGateway::RestApi` or this is a typo and you are creating it of type `AWS::Serverless::Api`

**Comment by moelasmar** [comment]
I was able to add some resource that depend on the generated stage resource, and the template got deployed successfully
```
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: hello-world
      Runtime: go1.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: RestAPIGateway
  RestAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: development
  TestWaitOnDependency:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: hello-world
      Runtime: go1.x
    DependsOn:
     - RestAPIGatewaydevelopmentStage
```
So I think you may use `AWS::ApiGateway::RestApi` as a resource type by mistake, or I may miss understand your issue.

**Comment by hoffa** [comment]
I was also unable to reproduce:

```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: foo
      Handler: bar
      Runtime: nodejs16.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref RestAPIGateway

  RestAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: development

  MyQueue:
    Type: AWS::SQS::Queue
    DependsOn: RestAPIGatewaydevelopmentStage
```

Deploy:

```
sam deploy --region us-west-2 --resolve-s3 --capabilities CAPABILITY_IAM --stack-name test-2499 --template template.yaml
```

Closing; let us know if there's something we're missing.
