### ISSUE TITLE
Bug: BatchSize on event source mapping does not get updated

### ISSUE THREAD

**Issue by andreas-trvlk** [aws/serverless-application-model#2504]
### Description:

We are creating several Lambda function using SAM that are triggered by SQS. We have configured the `EventSourceMapping` in the SAM. Initially, we set the value of `BatchSize` as 1. Later, we decided to increase to 5/10, but the size stays as 1 after deployment.

### Steps to reproduce:

1. Define event source mapping to SQS in SAM, eg
    ```yaml
    Parameters:
      SqsBatchSize:
        Type: Number
        Default: 1
      # ...
    Resources:
       FunctionA:
        Type: AWS::Serverless::Function
        Properties:
          # ...
          Events:
            FunctionSQS:
              Type: SQS
              Properties:
                Queue: !Ref SqsArn
                BatchSize: !Ref SqsBatchSize
                FunctionResponseTypes:
                  - ReportBatchItemFailures
     ```
2. Deploy the changes
3. Increase the `SqsBatchSize` value. eg
    ```yaml
    Parameters:
      SqsBatchSize:
        Type: Number
        Default: 5 # new value
      # ...
    Resources:
       FunctionA:
        Type: AWS::Serverless::Function
        Properties:
          # ...
          Events:
            FunctionSQS:
              Type: SQS
              Properties:
                Queue: !Ref SqsArn
                BatchSize: !Ref SqsBatchSize
                FunctionResponseTypes:
                  - ReportBatchItemFailures
     ```
4. Redeploy it.

### Observed result:

The BatchSize stays as old value, ie 1.

### Expected result:

The BatchSize is updated to the new value, ie 5.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. If using SAM CLI, `sam --version`:
3. AWS region:

`Add --debug flag to any SAM CLI commands you are running`
