### ISSUE TITLE
Bug: AWS Glue Triggers, not working with crawler

### ISSUE THREAD

**Issue by kumarahul98** [aws/serverless-application-model#2506]
### Description:

 I am deploying AWS Glue Jobs and Crawler using SAM. Creating a `AWS::Glue::Trigger` with this config
```
MyJobTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: "MyJobTrigger"
      Type: "CONDITIONAL"
      StartOnCreation: true
      Description: "Description for a conditional job trigger"
      Actions:
        - JobName: !Ref GlueJob1
      Predicate:
        Conditions:
          - LogicalOperator: EQUALS
            CrawlerName: !Ref DataCrawler
            CrawlState: SUCCEEDED
```
The scheduled crawler runs as expected, but the glue job is never triggered.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: mac OS
2. SAM CLI, version 1.53.0
3. AWS region: ap-southeast-1
