### ISSUE TITLE
Feature request: Allow Name property to be set for EventBridgeRule event source

### ISSUE THREAD

**Issue by sliedig** [aws/serverless-application-model#2508]
### Describe your idea/feature/enhancement
Today, when you create a function using an EventBridgeRule event source, SAM creates a rule with the name of the cfn logical id. This is not very manageable and difficult to work with.

![image](https://user-images.githubusercontent.com/597073/191643486-9baf1515-b7ce-4c74-83d0-4665f70db651.png)

I wish the SAM Translator would allow me to set the name of the rule so I can apply my own naming conventions to EventBride rule naming, rather than using the generated name. 

### Proposal

Add `Name` or `RuleName` property to event source definition.

```
      Events:
        StatusChangedEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: UnicornEventBus
            RuleName: unicorn.properties.ContractStatusChanged.HandlerApp
            Pattern:
              source:
                - unicorn.contracts
              detail-type:
                - ContractStatusChanged
```
Things to consider:
[x] The [SAM documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification.html) will need to be updated

### Additional Details
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-name
