### ISSUE TITLE
Websocket API deployment error

### ISSUE THREAD

**Issue by lindsaycode05** [aws/serverless-application-model#2512]
Hi, I'm using a SAM template and when trying to deploy my websocket API (and 3 lambdas for each route) to API Gateway, I'm getting this error: `At least one route is required before deploying the Api`
![SCR-20220922-rjb](https://user-images.githubusercontent.com/88434441/191811986-9172566b-ab64-4a9f-ae91-e4d97df4f32b.png)

The thing is that I already have defined 3 routes ($connect, $disconnect, message) in my template file

Here is my whole template:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: school-stack websocket api and lamdba functions for the support centre

Parameters:
  StackName:
    Description: The name of the application.
    Type: String
  NodeDependenciesLayer:
    Type: String
    Description: The ARN of NodeDependenciesLayer
  PrismaLayer:
    Type: String
    Description: The ARN of PrismaLayer
  SlackReportingLayer:
    Type: String
  PrismaDatabaseUrl:
    Type: String
    NoEcho: True

Resources:
  # WebSocket Infrastructure
  # apiId, apiName, routeSelectionExpression, stageName, stageDescription, [FunctionNames]
  #===========================
  # API ($request.body.action)
  #===========================
  SupportCentreWebsocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: ws-support-centre-2
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: '$request.body.action'

  # Route
  #===========================
  #  Key: $connect route handler
  #  Handler: onConnect
  #===========================
  onConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SupportCentreWebsocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      RouteResponseSelectionExpression: $default
      OperationName: onConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref onConnectInteg

  onConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SupportCentreWebsocketApi
      Description: onConnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${onConnect.Arn}/invocations

  onConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - SupportCentreWebsocketApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref onConnect
      Principal: apigateway.amazonaws.com

  # Route
  #===========================
  #  Key: $disconnect route handler
  #  Handler: onDisconnect
  #===========================
  onDisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SupportCentreWebsocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: onDisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref onDisconnectInteg

  onDisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SupportCentreWebsocketApi
      Description: onDisconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${onDisconnect.Arn}/invocations

  onDisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - SupportCentreWebsocketApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref onDisconnect
      Principal: apigateway.amazonaws.com

  # Route
  #===========================
  #  Key: message route handler
  #  Handler: onMessage
  #===========================
  onMessageRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SupportCentreWebsocketApi
      RouteKey: message
      AuthorizationType: NONE
      OperationName: onMessageRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref onMessageInteg

  onMessageInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SupportCentreWebsocketApi
      Description: onMessage Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${onMessage.Arn}/invocations

  onMessagePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - SupportCentreWebsocketApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref onMessage
      Principal: apigateway.amazonaws.com

  #===========================
  # Deployment
  #===========================
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref SupportCentreWebsocketApi
      Description: Initial deployment

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: prod
      Description: Version 1 of the api
      DeploymentId: !Ref Deployment
      ApiId: !Ref SupportCentreWebsocketApi

  onConnect:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.default
      Timeout: 30
      Runtime: nodejs14.x
      CodeUri: ../lambdas/node/user/supportCentreChat/onConnect
      Architectures:
        - x86_64
      MemorySize: 1024
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/SampleLambdaRole-${AWS::Region}-${AWS::AccountId}-${Stage}
      Environment:
        Variables:
          DATABASE_URL: !Ref PrismaDatabaseUrl
      Layers:
        - !Ref NodeDependenciesLayer
        - !Ref PrismaLayer
        - !Ref SlackReportingLayer

  onDisconnect:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.default
      Timeout: 30
      Runtime: nodejs14.x
      CodeUri: ../lambdas/node/user/supportCentreChat/onDisconnect
      Architectures:
        - x86_64
      MemorySize: 1024
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/SampleLambdaRole-${AWS::Region}-${AWS::AccountId}-${Stage}
      Environment:
        Variables:
          DATABASE_URL: !Ref PrismaDatabaseUrl
      Layers:
        - !Ref NodeDependenciesLayer
        - !Ref PrismaLayer
        - !Ref SlackReportingLayer

  onMessage:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.default
      Timeout: 30
      Runtime: nodejs14.x
      CodeUri: ../lambdas/node/user/supportCentreChat/onMessage
      Architectures:
        - x86_64
      MemorySize: 1024
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/SampleLambdaRole-${AWS::Region}-${AWS::AccountId}-${Stage}
      Environment:
        Variables:
          DATABASE_URL: !Ref PrismaDatabaseUrl
      Layers:
        - !Ref NodeDependenciesLayer
        - !Ref PrismaLayer
        - !Ref SlackReportingLayer
```

Would appreciate any help, thanks

**Comment by RNavaneethKumar** [comment]
@lindsaycode05 - Did you find a solution for this? I'm stuck with the same problem.

**Comment by lindsaycode05** [comment]
Hey mate, yes I solved that issue then, I will try to remember to my max on how I solved this issue back then, it's quite a time ago and unfortunately and don't work in that company anymore so I don't have access to the file/repo :/

I think firstly I would recommend to install "cfn-lint" extension if you haven't already, I think it played a role actually in solving this or another issue with the SAM template. It's a YAML template validator. Here it is - https://github.com/aws-cloudformation/cfn-lint

And I used this package to generate this whole SAM template (no, I didn't write it myself :) ) - https://github.com/dsandor/aws-websocket-sam-helper

But unfortunately I don't exactly remember what I did to solve the error `At least one route is required before deploying the Api` ;(

If I recall I think I played a bit with adding and removing `DependsOn` field in the `Deployment` declaration, like this:

```
 Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref SupportCentreWebsocketApi
      Description: Initial deployment
    DependsOn: // add this block
      - onConnectRoute
      - onDisconnectRoute
      - onMessageRoute
```

and then `cfn-lint` extension would start to error out because of circular dependency so I removed the `!Ref` that would cause the error from `onMessageRoute`, `onDisconnectRoute` and `onConnectRoute`

I mean cloudformation can't find the the routes because they aren't declared somewhere, but I don't remember exactly what I did. That's why I'd suggest you to try to add that `DependsOn` in the `Deployment` block


https://www.google.com/search?q=dependson+sam+template (this might give some explanation just in case you need)
