### ISSUE TITLE
Feature request: Documentation update showing how to use ReportBatchItemFailures with SQS

### ISSUE THREAD

**Issue by timpugh** [aws/serverless-application-model#2515]
Hello,

Can we get an update to the documentation located here: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-sqs.html

that shows how someone could enable `FunctionResponseTypes` (also known as partial batch failure reporting)?

It technically works (example below):
```
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Enabled: true
            FunctionResponseTypes:
              - ReportBatchItemFailures
            Queue: !GetAtt MySqsQueue.Arn
            BatchSize: 10
```

but just isn't documented.

If by chance (not necessary for this one) an example could be written in Python and provided on this documentation link: https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html#sqs-batchfailurereporting-syntax

That would be really great as well! The reason why for this Python example is because our documentation for DynamoDB + Kinesis ( https://docs.aws.amazon.com/lambda/latest/dg/with-ddb.html#streams-batchfailurereporting-bisect and https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis.html#streams-batchfailurereporting-bisect) have examples in Java and Python, so it'd be good if our SQS documentation had parity:
