### ISSUE TITLE
SimpleTable Improvements

### ISSUE THREAD

**Issue by sanathkr** [aws/serverless-application-model#252]
Parent tracking Issue for improvements to `AWS::Serverless::SimpleTable`:

- [x] TableName
- [x] Tagging 
- [ ] Stream

Feel free to add more things as you see fit

**Comment by sanathkr** [comment]
`TableName` and `Tags` are now available. Checkout [Release Notes](https://github.com/awslabs/serverless-application-model/releases/tag/1.4.0)

**Comment by revmischa** [comment]
Great! How can I use the new version?

**Comment by Nr18** [comment]
@revmischa just use it in your CFN Template as described [here](https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md#awsserverlesssimpletable). SAM runs as part of CloudFormation so the translation will happen before your stack will be created or updated so the latest version of SAM will be applied by AWS.

**Comment by revmischa** [comment]
I added:
```
  Message:
    Type: AWS::Serverless::SimpleTable
    TableName: 'qanda.message'
    PrimaryKey:
      Name: id
      Type: String
```
to my template.yml in my CodeStar project. it created a table named awscodestar-qanda-lambda-MessageTable-1NKRNP43YJQHR. what am I doing wrong?

**Comment by jfuss** [comment]
@revmischa You are not defining `Properties` making your template invalid.

SimpleTable Docs: https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md#awsserverlesssimpletable 
Note they can improved due to omitting the Type and LogicalId. So the full resource from the example in docs would be:

```
LogiclaIdForSimpleTable:
  Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: my-table
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        Department: Engineering
        AppType: Serverless
```
