### ISSUE TITLE
Bug: SAM translator produces an invalid AWS::Lambda::EventSourceMapping for SelfManagedKafka event sources with ConsumerGroupId

### ISSUE THREAD

**Issue by wayne-folkes** [aws/serverless-application-model#2546]
### Description:

When creating a  `AWS::Serverless::Function` with a `SelfManagedKafka` event source that specifies a `ConsumerGroupId` that the SAM translator produces an invalid `AWS::Lambda::EventSourceMapping`
with an extraneous field `SelfManagedKafkaConfig` instead of `SelfManagedKafkaEventSourceConfig`

### Steps to reproduce:
Create a `AWS::Serverless::Function` with a `SelfManagedKafka` event source that specifies a `ConsumerGroupId`

### Observed result:

When you run `sam validate --debug` you will see a generated template that has an `AWS::Lambda::EventSourceMapping` that contains a `SelfManagedKafkaConfig` field
```
  KafkaConsumerFunctionSelfManagedKafka:
    Properties:
      BatchSize:
        Fn::FindInMap:
        - Config
        - Ref: Stage
        - KafkaBatchSize
      Enabled: true
      FunctionName:
        Ref: KafkaConsumerFunction
      SelfManagedEventSource:
        Endpoints:
          KafkaBootstrapServers:
            Fn::FindInMap:
            - Config
            - Ref: Stage
            - KafkaBootstrapServers
      SelfManagedKafkaConfig:
        ConsumerGroupId: foo-bar
      SourceAccessConfigurations:
      - Type: VPC_SUBNET
        URI:
          Fn::Join:
          - ':'
          - - subnet
            - Fn::Select:
              - 0
              - Fn::Split:
                - ','
                - Fn::ImportValue: shared-vpc-private-subnet-ids
      - Type: VPC_SUBNET
        URI:
          Fn::Join:
          - ':'
          - - subnet
            - Fn::Select:
              - 1
              - Fn::Split:
                - ','
                - Fn::ImportValue: shared-vpc-private-subnet-ids
      - Type: VPC_SUBNET
        URI:
          Fn::Join:
          - ':'
          - - subnet
            - Fn::Select:
              - 2
              - Fn::Split:
                - ','
                - Fn::ImportValue: shared-vpc-private-subnet-ids
      - Type: VPC_SECURITY_GROUP
        URI:
          Fn::Join:
          - ':'
          - - security_group
            - Fn::ImportValue: shared-vpc-codebuild-default-sg-id
      StartingPosition: TRIM_HORIZON
      Topics:
      - Ref: KafkaTopicName
    Type: AWS::Lambda::EventSourceMapping
```

When you deploy this you will get the following error from Cloudformation

```
Resource handler returned message: "Model validation failed (#: extraneous key [SelfManagedKafkaConfig] is not permitted)" (RequestToken: 487b08a0-b613-4412-62e1-5e6a2106d6ee, HandlerErrorCode: InvalidRequest)
```
### Expected result:
The expected result is a template that has a `AWS::Lambda::EventSourceMapping` with a `SelfManagedKafkaEventSourceConfig` field instead of `SelfManagedKafkaConfig`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.60.0
3. AWS region: us-east-1

`Add --debug flag to any SAM CLI commands you are running`
