### ISSUE TITLE
Transform fails when `DeletionProtection` specified in `AWS::Cognito::UserPool` with Cognito event

### ISSUE THREAD

**Issue by jjaimez** [aws/serverless-application-model#2581]
### Describe your idea/feature/enhancement
 I wish the SAM Translator would support [DeletionProtection](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-deletionprotection) in Cognito User Pool definition.

### Proposal

```
MyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      DeletionProtection: ACTIVE
```

Things to consider:

### Additional Details
I tried to do it and i got the following error.  
`property DeletionProtection not defined for resource of type AWS::cognito::UserPool`

**Comment by xazhao** [comment]
Thanks for the feature request. I will discuss this with the team and post updates here.

**Comment by ssenchenko** [comment]
`DeletionProtection` seems to be quite a fresh feature. [The blog](https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-cognito-console-user-pool-deletion-protection/) which mentions it, is dated of Oct 2022.
It explains why `DeletionProtection` is not currently supported by CloudFormation https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-deletionprotection
We can add it after CloudFormation starts supporting it.

**Comment by ssenchenko** [comment]
Feel free to reopen this issue if you notice that CloudFormation has started to support this property

**Comment by JP-tech-sh** [comment]
I'm using SAM CLI to version 1.76.0, I identified that according to [Cloud formation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-deletionprotection) this feature should be supported. However, if you don't use the Ref build in cloud formation function to refer to the cognito user pool anywhere in the template, it'll work fine. Surprisingly, if you add at least one instance of Ref to a cognito user pool with DeletionProtection enabled, it will show this error. In my case, I'm using cognito events on lambda resources that need a reference to a cognito user pool in the template.  If using this particular configuration, it will fail with the error mentioned above. I guess is a very similar use case for the other devs reporting this issue. Please let me know if I can provide additional details or if you recommend that I open a separated issue for this. As a temporary solution, I removed the DeletionProtection from my user pool, but this is risky on a production scenario.

**Comment by hoffa** [comment]
@jjaimez @benconnito Could you clarify what the ask is?

`AWS::Cognito::UserPool` supports `DeletionProtection`:

```yaml
Transform: AWS::Serverless-2016-10-31
Parameters:
  DeletionProtection:
    Type: String
    Default: ACTIVE
Resources:
  MyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      DeletionProtection: !Ref DeletionProtection
```

Deploy:

```bash
sam deploy --region us-west-2 --resolve-s3 --capabilities CAPABILITY_IAM --stack-name test-deletion-protection --template template.yaml
```

**Comment by hoffa** [comment]
@JP-tech-sh Would you be able to provide a template reproducing the issue?

**Comment by JP-tech-sh** [comment]
@hoffa Yes, I'll provide a minimal working template reproducing the issue, so you can test it. I'll try to have it ready for today.

**Comment by benconnito** [comment]
i am actually unable to get NEW cognito domains (wether initially inactive or active) to have the issue. however updating an existing cognito domain (created BEFORE the deletion protection feature) to have deletion protection seems to fail

**Comment by JP-tech-sh** [comment]
Hello, this is the example sam project showing the error, sorry about the delay. https://github.com/JP-tech-sh/deletion-protection-sam-error
To run the project.
`sam build --beta-features --cached`
`sam deploy --guided`

**Comment by hoffa** [comment]
> Hello, this is the example sam project showing the error, sorry about the delay. https://github.com/JP-tech-sh/deletion-protection-sam-error To run the project. `sam build --beta-features --cached` `sam deploy --guided`

Thanks a lot for this, I was able to reproduce.

Here's a minimal example. Save as `template.yaml`:

```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  MyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      DeletionProtection: ACTIVE

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      InlineCode: foo
      Handler: bar
      Events:
        CognitoEvent:
          Type: Cognito
          Properties:
            Trigger: {}
            UserPool: !Ref MyUserPool
```

Creating the change set will fail with:

> Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [MyFunctionCognitoEvent] is invalid. Type of property 'Trigger' is invalid.

If you remove the Cognito event, it succeeds:

```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  MyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      DeletionProtection: ACTIVE

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      InlineCode: foo
      Handler: bar
```
