### ISSUE TITLE
Resource metadata is removed when converting 'AWS::Serverless::Function' to 'AWS::Lambda::Function'

### ISSUE THREAD

**Issue by sunnyone** [aws/serverless-application-model#264]
"Metadata" in AWS::Serverless::Function is removed when it's converted to AWS::Lambda::Function.
```
  MyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cloudformation:DescribeStackResource
              Resource: (...ARN...)
    Metadata:  # <--- REMOVED!!!
      CustomData: ABC
      ImageConvertFunctionArn: !ImportValue OtherFunctionArn
```

Resource metadata is useful to customize behaviors in a function on Lambda@Edge since it does not support environmental variables of Lambda.
