### ISSUE TITLE
AWS::ServerLess::HttpApi "Auth" property does not create authorizer

### ISSUE THREAD

**Issue by baxterjo** [aws/serverless-application-model#2689]
I am attempting to secure my serverless application using AWS Cognito as a JWT issuer. When I use the built in `Auth` property as shown below, no authorizer resource is made.
```yaml
HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          CognitoAuthorizer:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              Audience:
                - !Ref UserPoolClient
              Issuer: !GetAtt CognitoUserPool.ProviderURL
        DefaultAuthorizer: CognitoAuthorizer
``` 
When this builds and deploys using AWS SAM after changing any of the settings, there are no logs to communicate that the gateway is being changed, and the authorizer does not appear in the list of authorizers attached to the API in the AWS console. I instead have to manually create the authorizer using the underlying resource of the `Serverless::HttpApi`, the `AWS::ApiGatewayV2::Authorizer` as shown below:
```yaml
HttpApi:
    Type: AWS::Serverless::HttpApi
      DefaultRouteSettings:
        ThrottlingBurstLimit: 200
      StageName: 
        !If 
          - ProdEnvironment
          - prod
          - !If
            - StageEnvironment
            - stage
            - dev

  CognitoAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties: 
      ApiId: !Ref HttpApi
      AuthorizerType: JWT
      IdentitySource: 
        - "$request.header.Authorization"
      JwtConfiguration: 
        Audience: 
        - !Ref UserPoolClient
        Issuer: !GetAtt CognitoUserPool.ProviderURL
      Name: CognitoAuthorizer
```
This successfully creates the authorizer under the API. I have not attempted to attach this to any routes, but this in itself is an issue that should prompt an investigation into the authorizer deployment process in SAM.
