### ISSUE TITLE
Add the states:StartSyncExecution action to the StepFunctionsExecutionPolicy policy template

### ISSUE THREAD

**Issue by apopa57** [aws/serverless-application-model#2717]
### Description
The `StepFunctionsExecutionPolicy` policy template only includes the `states:StartExecution` action, so it cannot be used to start synchronous executions.

**Comment by GavinZZ** [comment]
An alternative while waiting for this change to get approved and released is to use [AWS::Serverless::Connector](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-connector.html). 

Assuming you want to use a lambda function to start state machine sync execution. Here is an example on how `AWS::Serverless::Connector` can help:

```
MyFunction:
  Type: AWS::Serverless::Function
  Properties:
    ...

MyStateMachine:
  Type: AWS::Serverless::StateMachine
  Properties:
    ...

MyConnector:
  Type: AWS::Serverless::Connector
  Properties:
    Source:
      Id: MyFunction
    Destination:
      Id: MyStateMachine
    Permissions:
    - Write
```
MyConnector will be transformed into a `AWS::IAM::ManagedPolicy` that contains the following policy document
```
"PolicyDocument": {
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "states:StartExecution",
        "states:StartSyncExecution"
      ],
    },
    {
      "Effect": "Allow",
      "Action": [
        "states:StopExecution"
      ],
    }
  ]
},
```
