### ISSUE TITLE
AT_TIMESTAMP value for StartingPosition is now supported in CloudFormation

### ISSUE THREAD

**Issue by baxterjo** [aws/serverless-application-model#2754]
### Description

`AT_TIMESTAMP` value was previously not supported in Cloudformation event source mapping and it looks like the support in SAM was removed [here](https://github.com/aws/serverless-application-model/issues/1741). But looking at the latest cloudformation documentation for `AWS::Lambda::EventSourceMapping` it seems as though [support was added](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html#cfn-lambda-eventsourcemapping-startingposition).

Requesting to re-add support for `AT_TIMESTAMP` in the `Kinesis` and `DynamoDB` event sources. As well as add support for `StartingPositionTimestamp` as a conditionally required parameter to go with this starting position.

### Steps to reproduce

In `AWS::Serverless::Function` resource, when defining the stream event, use `AT_TIMESTAMP` for `StartingPosition` and any unix seconds time for `StartingPositionTimestamp`

Abbreviated Kinesis event example
```yaml
Type: AWS::Serverless::Function
Properties:
  Events:
    KinesisRule:
      Type: Kinesis
        Properties:
          Stream: !GetAtt stream.Arn
          StartingPosition: AT_TIMESTAMP
          StartingPositionTimestamp: 1671489395
```

### Observed result

```bash
Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [KinesisRule] is invalid. property StartingPositionTimestamp not defined for resource of type Kinesis
```

### Expected result

These two parameters should pass through to the `AWS::Lambda::EventSourceMapping` and deploy the event source with the correct starting position.

### Additional environment details

1. OS: Docker with circle ci convenience image `cimg/python:3.8.13`
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: SAM CLI, version 1.67.0
3. AWS region: us-west-2
