### ISSUE TITLE
FN::ImportValue of ARN fails with 'Partition "" is not valid for resource...'

### ISSUE THREAD

**Issue by mslattery** [aws/serverless-application-model#2766]
### Description
Stack fails when importing an ARN from another stack for use in a AWS::Serverless::Connector Destination.

### Steps to reproduce

NOTE: YAML

1. In another stack, in the outputs section export a ARN of the resource you need access to.

Outputs:
  SQSqueueARN:
    Value: !GetAtt AccountWorkQueue.Arn
    Export:  
      Name: !Sub "${AWS::StackName}-SQSqueueARN"

2. Use Fn::ImportValue to bring this in as a parameter in your template e.g.

Parameters:
  AccountWorkQueueARN:
    Type: String
    Default: Fn::ImportValue 'APP-AD-Audit-EventBridgeSchedulerToLambda-SQSqueueARN'

### Observed result
During stack execution received the following CREATE_FAILED

Partition "" is not valid for resource "arn::ImportValue 'APP-AD-Audit-EventBridgeSchedulerToLambda-SQSqueueARN':*:*:*". (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 21ba6cc3-fad4-46c0-aff4-f33b68a83094; Proxy: null)

### Expected result
Expected connector to allow the use of this imported ARN.

### Additional environment details

1. OS: via CodePipeline built from AWS Pipeline Init aws/codebuild/amazonlinux2-x86_64-standard:3.0
4. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), SAM CLI, version 1.67.0
5. AWS region: us-east-1

**Comment by mslattery** [comment]
Related? https://github.com/aws/serverless-application-model/issues/768

**Comment by GavinZZ** [comment]
Hi @mslattery, thanks for reporting this issue. I tried out `AWS::Serverless::Connector` with exported and imported values. It's working as expected for me. Here is my simple example:

Exported Stack:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs14.x
      Handler: index.handler
      InlineCode: |
        const AWS = require('aws-sdk');
        exports.handler = async (event) => {
          console.log(JSON.stringify(event));
        };

Outputs:
  MyFunctionArn:
    Value: !Ref MyFunction
    Export:
      Name: !Sub "${AWS::StackName}-FunctionArn"
```
I deployed the stack and named it `LambdaFunctionStack`.

Imported Stack:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  LambdaFunctionStack:
    Type: String
    Default: LambdaFunctionStack

Resources:
  MyTopic:
    Type: AWS::SNS::Topic

  TopicToLambdaHardcoded:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: MyTopic
      Destination:
        Type: AWS::Lambda::Function
        Arn: !ImportValue
          'Fn::Sub': '${LambdaFunctionStack}-FunctionArn'
      Permissions:
      - Write
```

Looking at your error message, `Partition "" is not valid for resource "arn::ImportValue 'APP-AD-Audit-EventBridgeSchedulerToLambda-SQSqueueARN':::*". `, it seems that the arn isn't valid. My hypothesis is that you didn't use the [`Fn::Sub`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html) like I did  here `'Fn::Sub': '${LambdaFunctionStack}-FunctionArn'`.

If that's not the issue, would you be able to provide your template (or a portion of it) so that I can deep dive into this problem for you?
