### ISSUE TITLE
LanguageExtensions  and Serverless-2016-10-31 conflicts

### ISSUE THREAD

**Issue by blade2005** [aws/serverless-application-model#2778]
### Description
In my SAM template I'm deploying a dynamo table and api gateway mappings along with normal things like lambdas and the api gateway itself.

The `AWS::ApiGateway::BasePathMapping` depends on the `resApiGatewayStage` which is created during the transform. So by the end of the transform when it goes to validate the template it's all good.

When I add in a `DeletionPolicy` on the `AWS::DynamoDB::Table` to set it to `Retain` for prod and add `AWS::LanguageExtensions` to the top of the transforms I get an error.

What I believe is happening is that after `AWS::LanguageExtensions` is done transforming things it validates the template but because I have a reference to `resApiGatewayStage` which doesn't exist (yet) then it fails.

```
  resAPIBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Condition: conditionBuildBasePath
    DependsOn: resApiGatewayStage
    Properties:
      BasePath: !If
        - conditionNotFeatureBranch
        - !Sub "${paramServiceName}"
        - !Sub "${paramServiceName}-${paramFeatureBranch}"
      DomainName:
        Fn::ImportValue: !Sub export-environment-domain-${paramEnvironment}
      RestApiId: !Ref resApiGateway
      Stage: !Ref paramEnvironment
```

### Steps to reproduce

Have a template which has 
1. a resource with a deletion policy with an intrisnic function.
2. a resource which depends on resources created during the SAM transformation.
```
Conditions:
  conditionIsProd: !Equals [!Ref paramEnvironment, prod]

  DynamoTable:
    Type: AWS::DynamoDB::Table
    # DeletionPolicy: "Retain"
    DeletionPolicy: !If
      - conditionIsProd
      - Retain
      - Delete
```

### Observed result
Change set created fails with
> Template format error: Unresolved resource dependencies [resApiGatewayStage] in the Resources block of the template

### Expected result
Successful deployment

### Additional environment details
WSL2, Ubuntu
Ubuntu
MacOSX
```
SAM CLI, version 1.66.0
```

1. OS:
3. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`:
4. AWS region:

**Comment by GavinZZ** [comment]
Hi there, thanks for reporting this issue. I'll take a look at this problem and get back to you.

**Comment by GavinZZ** [comment]
Short version: 
I built a template that satisfied the requirement you mentioned but wasn't able to reproduce this problem. Are you able to provide me with a sanitized template you used that failed the deployment? Can you make sure `resApiGatewayStage` matches the generated resource `AWS::ApiGateway::Stage` name from your template?


Long version:
I have written a simple template that satisfies the requirement: I have a resource with a deletion policy with an intrinsic function (`DynamoTable`) and I have a resource which depends on resources created during the SAM transformation (`MyApiBaseMapping` dependsOn `MyApiProdStage` which is generated by SAM resource `MyApi`.
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Parameters:
  conditionIsProdVar:
    Default: prod
    Type: String

Conditions:
  conditionIsProd: !Equals [!Ref conditionIsProdVar, prod]

Resources:
  Certificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: example.mydomain-GavinZZ-testing.com

  DomainName:
    Type: 'AWS::ApiGateway::DomainName'
    Properties:
      CertificateArn: !Ref Certificate
      DomainName: example.mydomain-GavinZZ-testing.com

  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: Id
        AttributeType: S
      KeySchema:
      - AttributeName: Id
        KeyType: HASH
    DeletionPolicy: !If
      - conditionIsProd
      - Retain
      - Delete

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        exports.handler = async (event) => {
          const response = {
            statusCode: 200,
            body: JSON.stringify('Hello from Lambda!'),
          };
          return response;
        };
      Handler: index.handler
      Runtime: nodejs14.x
      Events:
        Fetch:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Method: Get
            Path: /get

  MyApiBaseMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: MyApiProdStage
    Properties:
      BasePath: "basepath"
      DomainName: !Ref DomainName
      RestApiId: !Ref MyApi

  DNS: 
    Type: "AWS::Route53::HostedZone"
    Properties: 
      Name: example.mydomain-GavinZZ-testing.com

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: 3.0.1
      StageName: Prod
      Domain:
        DomainName:
          Ref: DomainName
        CertificateArn:
          Ref: Certificate
        EndpointConfiguration: EDGE
        BasePath:
        - /get
        Route53:
          HostedZoneId:
            Ref: DNS
          IpV6: true
```

I'm using `AWS::LanguageExtensions` in the Transform section and I was able to deploy this template to my CFN stack without any issue. Here is the processed/transformed CFN templates
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Parameters": {
    "conditionIsProdVar": {
      "Default": "prod",
      "Type": "String"
    }
  },
  "Resources": {
    "MyFunction": {
      "Type": "AWS::Lambda::Function",
      "Metadata": {
        "SamResourceId": "MyFunction"
      },
      "Properties": {
        "Code": {
          "ZipFile": "exports.handler = async (event) => {\n  const response = {\n    statusCode: 200,\n    body: JSON.stringify('Hello from Lambda!'),\n  };\n  return response;\n};\n"
        },
        "Handler": "index.handler",
        "Role": {
          "Fn::GetAtt": [
            "MyFunctionRole",
            "Arn"
          ]
        },
        "Runtime": "nodejs14.x",
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ]
      }
    },
    "DynamoTable": {
      "Type": "AWS::DynamoDB::Table",
      "DeletionPolicy": "Retain",
      "Metadata": {
        "SamResourceId": "DynamoTable"
      },
      "Properties": {
        "BillingMode": "PAY_PER_REQUEST",
        "AttributeDefinitions": [
          {
            "AttributeName": "Id",
            "AttributeType": "S"
          }
        ],
        "KeySchema": [
          {
            "AttributeName": "Id",
            "KeyType": "HASH"
          }
        ]
      }
    },
    "ApiGatewayDomainName60ef7d66a0": {
      "Type": "AWS::ApiGateway::DomainName",
      "Properties": {
        "DomainName": {
          "Ref": "DomainName"
        },
        "EndpointConfiguration": {
          "Types": [
            "EDGE"
          ]
        },
        "CertificateArn": {
          "Ref": "Certificate"
        }
      }
    },
    "Certificate": {
      "Type": "AWS::CertificateManager::Certificate",
      "Metadata": {
        "SamResourceId": "Certificate"
      },
      "Properties": {
        "DomainName": "example.mydomain-yuanhaoz-testing.com"
      }
    },
    "DomainName": {
      "Type": "AWS::ApiGateway::DomainName",
      "Metadata": {
        "SamResourceId": "DomainName"
      },
      "Properties": {
        "CertificateArn": {
          "Ref": "Certificate"
        },
        "DomainName": "example.mydomain-yuanhaoz-testing.com"
      }
    },
    "RecordSetGroup5aaaf19b98": {
      "Type": "AWS::Route53::RecordSetGroup",
      "Properties": {
        "HostedZoneId": {
          "Ref": "DNS"
        },
        "RecordSets": [
          {
            "Name": {
              "Ref": "DomainName"
            },
            "Type": "A",
            "AliasTarget": {
              "HostedZoneId": "Z2FDTNDATAQYW2",
              "DNSName": {
                "Fn::GetAtt": [
                  "ApiGatewayDomainName60ef7d66a0",
                  "DistributionDomainName"
                ]
              }
            }
          },
          {
            "Name": {
              "Ref": "DomainName"
            },
            "Type": "AAAA",
            "AliasTarget": {
              "HostedZoneId": "Z2FDTNDATAQYW2",
              "DNSName": {
                "Fn::GetAtt": [
                  "ApiGatewayDomainName60ef7d66a0",
                  "DistributionDomainName"
                ]
              }
            }
          }
        ]
      }
    },
    "MyFunctionRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              }
            }
          ]
        },
        "ManagedPolicyArns": [
          "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        ],
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ]
      }
    },
    "MyApigetBasePathMapping": {
      "Type": "AWS::ApiGateway::BasePathMapping",
      "Properties": {
        "BasePath": "get",
        "DomainName": {
          "Ref": "ApiGatewayDomainName60ef7d66a0"
        },
        "RestApiId": {
          "Ref": "MyApi"
        },
        "Stage": {
          "Ref": "MyApiProdStage"
        }
      }
    },
    "MyApi": {
      "Type": "AWS::ApiGateway::RestApi",
      "Metadata": {
        "SamResourceId": "MyApi"
      },
      "Properties": {
        "Body": {
          "info": {
            "version": "1.0",
            "title": {
              "Ref": "AWS::StackName"
            }
          },
          "paths": {
            "/get": {
              "get": {
                "x-amazon-apigateway-integration": {
                  "httpMethod": "POST",
                  "type": "aws_proxy",
                  "uri": {
                    "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyFunction.Arn}/invocations"
                  }
                },
                "responses": {}
              }
            }
          },
          "openapi": "3.0.1"
        }
      }
    },
    "DNS": {
      "Type": "AWS::Route53::HostedZone",
      "Metadata": {
        "SamResourceId": "DNS"
      },
      "Properties": {
        "Name": "example.mydomain-yuanhaoz-testing.com"
      }
    },
    "MyFunctionFetchPermissionProd": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "Action": "lambda:InvokeFunction",
        "FunctionName": {
          "Ref": "MyFunction"
        },
        "Principal": "apigateway.amazonaws.com",
        "SourceArn": {
          "Fn::Sub": [
            "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/GET/get",
            {
              "__ApiId__": {
                "Ref": "MyApi"
              },
              "__Stage__": "*"
            }
          ]
        }
      }
    },
    "MyApiProdStage": {
      "Type": "AWS::ApiGateway::Stage",
      "Properties": {
        "DeploymentId": {
          "Ref": "MyApiDeployment16df2c571c"
        },
        "RestApiId": {
          "Ref": "MyApi"
        },
        "StageName": "Prod"
      }
    },
    "MyApiDeployment16df2c571c": {
      "Type": "AWS::ApiGateway::Deployment",
      "Properties": {
        "Description": "RestApi deployment id: 16df2c571c891adbc115b37ef4fd494eba0f8cb0",
        "RestApiId": {
          "Ref": "MyApi"
        }
      }
    },
    "MyApiBaseMapping": {
      "Type": "AWS::ApiGateway::BasePathMapping",
      "Metadata": {
        "SamResourceId": "MyApiBaseMapping"
      },
      "DependsOn": "MyApiProdStage",
      "Properties": {
        "BasePath": "basepath",
        "DomainName": {
          "Ref": "DomainName"
        },
        "RestApiId": {
          "Ref": "MyApi"
        }
      }
    }
  },
  "Conditions": {
    "conditionIsProd": {
      "Fn::Equals": [
        "prod",
        "prod"
      ]
    }
  }
}
```

**Comment by blade2005** [comment]
The example code you provided looks correct. The generated api stage resource is named correctly as `resApiGatewayStage`. This is not a new project and it's been working fine without using language extensions with `resApiGatewayStage`. 

I decided to write out the shortest example I could and while reading through your example I realized I had made the test solution more complicated than it needed to be by using the api gateway mapping so in my example i'm going to use usage plans and keys.

This fails
```
AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Parameters:
  paramEnvironment:
    Type: String
    Description: Which environment do you want to deploy to? (local,dev,stage, or prod)
    AllowedValues:
      - local
      - dev
      - stage
      - prod
    Default: local
Conditions:
  conditionIsProd: !Equals [!Ref paramEnvironment, prod]
Resources:
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: Id
        AttributeType: S
      KeySchema:
      - AttributeName: Id
        KeyType: HASH
    DeletionPolicy: !If
      - conditionIsProd
      - Retain
      - Delete
  resApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: 3.0.1
      StageName: !Ref paramEnvironment
  resUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: resApiGatewayStage
    Properties:
      Description: Unlimited usage plan
      ApiStages:
        - ApiId: !Ref resApiGateway
          Stage: !Ref paramEnvironment
  resApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn: resApiGateway
    Properties:
      Description: !Sub "Access to specific endpoints in API ${paramEnvironment}"
      Enabled: true
  resUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref resApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref resUsagePlan
```

Specifically this fails with
> Template format error: Unresolved resource dependencies [resApiGatewayStage] in the Resources block of the template

If I remove the deletion policy and change the `Transform` key to `Transform: AWS::Serverless-2016-10-31` it works.

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Parameters:
  paramEnvironment:
    Type: String
    Description: Which environment do you want to deploy to? (local,dev,stage, or prod)
    AllowedValues:
      - local
      - dev
      - stage
      - prod
    Default: local
Conditions:
  conditionIsProd: !Equals [!Ref paramEnvironment, prod]
Resources:
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: Id
        AttributeType: S
      KeySchema:
      - AttributeName: Id
        KeyType: HASH
  resApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: 3.0.1
      StageName: !Ref paramEnvironment
  resUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: resApiGatewayStage
    Properties:
      Description: Unlimited usage plan
      ApiStages:
        - ApiId: !Ref resApiGateway
          Stage: !Ref paramEnvironment
  resApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn: resApiGateway
    Properties:
      Description: !Sub "Access to specific endpoints in API ${paramEnvironment}"
      Enabled: true
  resUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref resApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref resUsagePlan
```

**Comment by blade2005** [comment]
I think I see what I missed from your example compared to my running code.

```
  resAPIBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: resApiGatewayStage
    Properties:
      BasePath: "basepath"
      DomainName: !Ref DomainName
      RestApiId: !Ref resApiGateway
      Stage: !Ref paramEnvironment
```
Tying in the Stage to the base path mapping.

**Comment by GavinZZ** [comment]
> I think I see what I missed from your example compared to my running code.
> 
> ```
>   resAPIBasePathMapping:
>     Type: AWS::ApiGateway::BasePathMapping
>     DependsOn: resApiGatewayStage
>     Properties:
>       BasePath: "basepath"
>       DomainName: !Ref DomainName
>       RestApiId: !Ref resApiGateway
>       Stage: !Ref paramEnvironment
> ```
> 
> Tying in the Stage to the base path mapping.

Thanks for the replies. Were you able to figure out the problem? 

By looking at your templates, it does seem like there is a conflict between the two transform extensions. I'll confirm with the team about it. Though I highly doubt there is anything SAM can do because it's `AWS::LanguageExtensions` doing the verification.

**Comment by blade2005** [comment]
I agree I think the issue is more on `AWS::LanguageExtensions` side, is there a way to reach out to the team regarding this issue?

I wish that as part of cloudformation processing transformations that it skips validation between each transform and just validates at the end before attempting to launching cloudformation.

**Comment by blade2005** [comment]
Another thing is is it possible to avoid having the reference to the gateway stage or to have it defined but overridden by the transformation?

**Comment by GavinZZ** [comment]
AFAIK I don't think there is a way for you to reach out to them. What I can do is to create an issue and cut to their team internally and I can give you periodic update on the status once they reply to me.

**Comment by GavinZZ** [comment]
> Another thing is is it possible to avoid having the reference to the gateway stage or to have it defined but overridden by the transformation?


I don't know your exact use case. However, looking at the original problem, one thing that you can do is instead of defining `AWS::ApiGateway::BasePathMapping` manually, SAM allows you to define [BasePath](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-domainconfiguration.html#sam-api-domainconfiguration-basepath) property and you don't have to manually add a DependsOn in this case.

**Comment by blade2005** [comment]
@GavinZZ thanks for opening the ticket.

Using the BasePath property would solve one of the issues but I'm not seeing a way to handle the creation of `AWS::ApiGateway::UsagePlan` without that depends.

**Comment by GavinZZ** [comment]
SAM also supports the creation of `AWS::ApiGateway::UsagePlan`. For more detail, please look at this [documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-apiauth.html#sam-api-apiauth-usageplan)

**Comment by blade2005** [comment]
I looked deeper into how the `AWS::ApiGateway::BasePathMapping` is being generated and I don't think it will work for my current project. The domain name is static and uses the mapping for custom domains for different dev environments. Think `https://example.com/projectprefixticketnumber/get`

However I can't provide `Domain.DomainName` without it creating a new `AWS::ApiGateway::DomainName` which already exists.

Is there a way that I've overlooked in the translater to create the `AWS::ApiGateway::BasePathMapping`  without creating a new  `AWS::ApiGateway::DomainName`?

**Comment by GavinZZ** [comment]
```
AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Parameters:
  paramEnvironment:
    Type: String
    Description: Which environment do you want to deploy to? (local,dev,stage, or prod)
    AllowedValues:
      - local
      - dev
      - stage
      - prod
    Default: local
Resources:
  resApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: 3.0.1
      StageName: !Ref paramEnvironment
```

It appears that if `AWS::LanguageExtensions` is removed, `paramEnvironment` is treated as an intrinsic function, then the `AWS::ApiGateway::Stage` resource gets correct generated with the name `resApiGatewayStage`.
However, if we add `AWS::LanguageExtensions`, `paramEnvironment` is a fixed value after `AWS::LanguageExtensions` transform, then the resource name for ApiGateway Stage becomes `resApiGatewaylocalStage`.
Code for the above logic can be found [here]( https://github.com/aws/serverless-application-model/blob/develop/samtranslator/model/api/api_generator.py#L402)

One of the alternative is to use intrinsic function in `DependsOn`, however, it turned out to be NOT supported by `AWS::LanguageExtensions`. I have asked their team to see if they could support intrinsic function in `DependsOn` but haven't gotten an answer yet.
