### ISSUE TITLE
New connector support for Location Search

### ISSUE THREAD

**Issue by dylan8902** [aws/serverless-application-model#2781]
### Describe your idea/feature/enhancement

A new policy template to allow lambda functions to make use of the AWS Location Service

### Proposal

Add new policy `LocationSearchPolicy` based on the example provided here: https://docs.aws.amazon.com/location/latest/developerguide/security_iam_id-based-policy-examples.html#security_iam_id-based-policy-examples-search-for-place

**Comment by aahung** [comment]
Proposing to add it to serverless connector:

```
  Connector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: SomeFunction
      Destination:
        Arn: "arn:aws:geo:us-west-2:account-id:place-index/PlaceIndex"
        Type: AWS::Location::PlaceIndex
      Permissions:
      - Read
```
