### ISSUE TITLE
Openapi integration extention does not dereference $ref

### ISSUE THREAD

**Issue by brandonryan** [aws/serverless-application-model#2785]
### Description:

I am trying to define my lambda integration in the openapi document using the [openapi aws extentions](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-integration.html). It works when I use `x-amazon-apigateway-integration` inline and define the integration, but when I try to use a $ref to the components section it does not resolve the $ref. See [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-extensions-integrations.html) for example.

### Steps to reproduce:

Create template with a integration $ref:
```yaml
/testpath:
  get:
    summary: test path
    x-amazon-apigateway-integration:
      $ref: '#/components/x-amazon-apigateway-integrations/testIntegration'
```
Create integration in the components section:
```yaml
x-amazon-apigateway-integrations:
  testIntegration:
    type: aws_proxy
    httpMethod: POST
    uri: !Sub ${testLambda.Arn}
    passthroughBehavior: when_no_match
    payloadFormatVersion: 2.0
```
### Observed result:

`Lambda function integration not found in Swagger document at path='/testpath' method='get'`

### Expected result:

Lambda mounted at /testpath endpoint

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`: SAM CLI, version 1.23.0
3. AWS region: us-east-1
