### ISSUE TITLE
Feature: Add !GetAtt support for AWS::MSK::Cluster's BootstrapServers

### ISSUE THREAD

**Issue by mattyboy84** [aws/serverless-application-model#2809]
Currently the only supported return values for `AWS::MSK::Cluster` are !Ref & !GetAtt cluster.Arn. Adding !GetAtt cluster.BootstrapServers would be used in a `AWS::KafkaConnect::Connector` resource to link it to the cluster
```yaml
cluster:
  Type: AWS::MSK::Cluster
  Properties: 
    ClusterName: example-cluster
 
connector:
  Type: AWS::KafkaConnect::Connector
  Properties:
    ConnectorName: example-connector
    KafkaCluster:
      ApacheKafkaCluster:
        BootstrapServers: !GetAtt cluster.BootstrapServers
        Vpc:
          SecurityGroups:
            - !Ref securityGroup
          Subnets:
            - !Ref subnetB
            - !Ref subnetC

```
!GetAtt cluster.BootstrapServers would return a string like:
b-1.example-cluster.irmtd9.c3.kafka.REGION.amazonaws.com:9094,b-2.example-cluster.irmtd9.c3.kafka.REGION.amazonaws.com:9094
