### ISSUE TITLE
`AWS::Serverless::Api` resource dependency does not apply for the child resources like `AWS::ApiGateway::Stage`

### ISSUE THREAD

**Issue by prasanthnarasimha** [aws/serverless-application-model#2830]
### Description:
I'm not sure if this is the case with all SAM resources but when you `!Ref` a `AWS::Serverless::Api` in another resource `B` (or add `DependsOn`), creation of resource `B` does not wait until all child resources for `AWS::Serverless::Api` like  `AWS::ApiGateway::Deployment` and `AWS::ApiGateway::Stage` are created . It only waits until `AWS::ApiGateway::RestApi` resource is created. This affects the ability to deploy resources like `AWS::WAFv2::WebACLAssociation` in the same stack as `AWS::Serverless::Api` as it relies on `AWS::ApiGateway::Stage` to be created. Workaround is to depoly `AWS::Serverless::Api` first and then perform a stack update after adding  `AWS::WAFv2::WebACLAssociation`.

### Steps to reproduce:
Use the following template 
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  ApiStageName:
    Type: String
    Default: prod
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Auth:
        DefaultAuthorizer: AWS_IAM
      StageName: !Ref ApiStageName
      MethodSettings:
        - ResourcePath: /get_t/{tes}
          HttpMethod: GET
          CachingEnabled: true
          CacheTtlInSeconds: 300
  WebACL:
    Type: 'AWS::WAFv2::WebACL'
    Properties:
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: apig-wafv2
        SampledRequestsEnabled: true
  ApiWebAclAssociations:
    Type: AWS::WAFv2::WebACLAssociation
    DependsOn:
      - "ApiGatewayApi"
    Properties: 
      ResourceArn: !Sub "arn:aws:apigateway:${AWS::Region}::/restapis/${ApiGatewayApi}/stages/${ApiStageName}"
      WebACLArn: !GetAtt WebACL.Arn
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /get_t/{tes}
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
      Runtime: python3.9
      Handler: index.handler
      InlineCode: |
        import json
        def handler(event, context):
            return {'body': json.dumps({"text": "hello world", "event": event}), 'statusCode': 200}
```

### Observed result:

`ApiWebAclAssociations` fails with the following `NotFound` error because the creation of this resource starts as soon as `AWS::ApiGateway::RestApi` child resource creation is complete but it requires `AWS::ApiGateway::Stage` to be created.

```
ApiWebAclAssociations | CREATE_FAILED | Resource handler returned message: "AWS WAF couldn?t perform the operation because your resource doesn?t exist. (Service: Wafv2, Status Code: 400, Request ID: xxx, Extended Request ID: null)" (RequestToken: xxx, HandlerErrorCode: NotFound)
```

### Expected result:
I would expect it to respect `DependsOn` attribute (or the reference in !Sub statement for `ResourceArn` property) and wait until all child resources for `ApiGatewayApi` are created before `ApiWebAclAssociations` creation so it can successfully refer to the API stage and create successfully.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

```
 sam --info
{
  "version": "1.71.0",
  "system": {
    "python": "3.8.10",
    "os": "Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29"
  }
}
```
