### ISSUE TITLE
CodeDeploy error resulting in inconsistent state

### ISSUE THREAD

**Issue by jarreds** [aws/serverless-application-model#291]
### Observations

We were receiving notifications that one of our SAM stacks was failing CloudFormation updates. Looking back through the event logs, we noticed that this was our first error that seems to have broken the stack:

```
16:58:19 UTC-0800 UPDATE_FAILED	AWS::Lambda::Alias	GetAllContactAliaslive	A conflicting deployment is in progress
```

After this error occurred, subsequent updates of this stack began failing within CodeDeploy with the following error. Note: it takes about 30 minutes for this stack to rollback on failure, so it seems like there is a timeout thing going on too.

```
Error:
Instance ID is Missing.

Deployment Failed:
The deployment failed because the AppSpec file that specifies the AWS Lambda deployment configuration is missing or has an invalid configuration. The Lambda function alias version does not match the current version in AppSpec file. (Error code: INVALID_LAMBDA_CONFIGURATION)
```

We were stumped. Looking at the sam.yaml configuration we noticed we had one potential configuration that could cause the CodeDeploy conflicting deployment for the `GetAllContactAliaslive` function:

```yaml
  GetOneContact:
    Type: AWS::Serverless::Function
    Properties:
      Handler: consumer.GetContact::handleRequest
      Runtime: java8
      CodeUri: ../consumer/getContact/deploy.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 20
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /v3.0/consumer/contact/{contact_id}
            Method: get
            RestApiId: !Sub ${API}

  GetAllContact:
    Type: AWS::Serverless::Function
    Properties:
      Handler: consumer.GetContact::handleRequest
      Runtime: java8
      CodeUri: ../consumer/getContact/lambda_deploy.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 20
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /v3.0/consumer/contact
            Method: get
            RestApiId: !Sub ${API}
```

These are two separate lambda functions that are identical with the exception of the events that trigger them. It seems possible that this is what's tripping CodeDeploy up.

We're going to change to the following with one lambda definition and multiple events to see if the conflict goes away:

```yaml
  GetContact:
    Type: AWS::Serverless::Function
    Properties:
      Handler: consumer.GetContact::handleRequest
      Runtime: java8
      CodeUri: ../consumer/getContact/lambda_deploy.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 20
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        GetAllApi:
          Type: Api
          Properties:
            Path: /v3.0/consumer/contact
            Method: get
            RestApiId: !Sub ${API}
        GetOneApi:
          Type: Api
          Properties:
            Path: /v3.0/consumer/contact/{contact_id}
            Method: get
            RestApiId: !Sub ${API}
```
### Questions

* Is it possible that the `A conflicting deployment is in progress` error from CodeDeploy is triggering because the former configuration? If so, this seems like a configuration that should succeed.
* The 30 minute CloudFormation rollback seems like a bug.
* It appears that the inconsistent state the stack is left in after the rollback is a bug as well.

**Comment by sanathkr** [comment]
The two functions are entirely different from CodeDeploy's perspective because they will have different Arns. So this doesn't matter.

Can you give me a bit more details to dive deep:
* AWS Region this happened
* When this happened? 
* Did this start happening after you added deployment preference?

**Comment by jarreds** [comment]
> AWS Region this happened

us-west-2

> When this happened?

The conflict error occurred for the first time on 16:58:19 UTC-0800 Feb-07-18.

> Did this start happening after you added deployment preference?

No, this stack was originally created with this DeploymentPreference.

> Did you happened to create Lambda versions outside of the stack using API/CLI/Console?

No, we did not. All updates are done via CloudFormation.

**Comment by sanathkr** [comment]
@jarreds Let's take this offline. Can you shoot me an email sanathkr [at] amazon.com?

**Comment by jarreds** [comment]
On it.

**Comment by vinkris** [comment]
@sanathkr @jarreds 

I was seeing this same issue, more than twice last week. 
Getting following errors when trying to deploy SAM stack using CF:

```
...
20:06:41 UTC-0700 | UPDATE_FAILED | AWS::Lambda::Alias | UserLogoutAliaslive | Already chained. Call unchain() to get rid of the previous chaining.
-- | -- | -- | -- | --
  | 20:03:48 UTC-0700 | UPDATE_FAILED | AWS::Lambda::Alias | UserReturnAliaslive | Already chained. Call unchain() to get rid of the previous chaining.
  | 20:03:29 UTC-0700 | UPDATE_FAILED | AWS::Lambda::Alias | DisconnectAliaslive | Already chained. Call unchain() to get rid of the previous chaining.
  | 19:38:09 UTC-0700 | UPDATE_FAILED | AWS::Lambda::Alias | KinesisScalingAliaslive | Resource update cancelled
19:38:06 UTC-0700 | UPDATE_FAILED | AWS::Lambda::Alias | AdminReturnAliaslive | A conflicting deployment is in progress
...

```
This doesn't happen all the time. However, once it reaches this state, new updates would not succeed anymore. Had to delete and recreate the stack. 

We have about 13 lambdas in the SAM template, with a global setting like this:

```

Globals:
  Function:
    Runtime: nodejs6.10
    MemorySize: 256
    Timeout: 10
    AutoPublishAlias: live
    DeploymentPreference:
      Type: AllAtOnce

AdminReturn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-${EnvName}-adminreturn
      CodeUri:
        Bucket: !Ref BootstrapS3Bucket
        Key: !Ref AzureADFunctionCodeS3Key
      Handler: handler.adminReturn
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref TenantsTable
        - KMSDecryptPolicy:
            KeyId: !Ref AzureADKMSKeyId
      VpcConfig:
        SubnetIds: 
          !Split
            - ','
            - 'Fn::If': [ GentooConsumer, !Sub "${AzureADFunctionSubnetsIds}", 'Fn::ImportValue': !Sub "${BaseVPCStackName}-${EnvName}-SubnetsPrivateAppIds"]
        SecurityGroupIds:
          !Split
            - ','
            - 'Fn::If': [ GentooConsumer, !Sub "${AzureADFunctionSecurityGroupIds}", 'Fn::ImportValue': !Sub "${BaseVPCStackName}-${EnvName}-AzureAdSG"]
      Environment:
        Variables:
          TENANTSTATE_TABLE: !Ref TenantsTable
          DEP_ENVIRONMENT: !Ref EnvName
          ESS_URL: !Ref AzureADESSUrl
          CLIENT_ID: !Ref AzureADMSClientId
          CLIENT_SECRET: !Ref AzureADMSClientSecret
      Events:
        Consent:
          Type: Api
          Properties:
            Path: /adminreturn
            Method: get
            RestApiId:
              !Ref AzureADSyncAPI

```

Did we find the root cause for this? Any help here would be appreciated. Thanks!
