### ISSUE TITLE
AWS::Serverless::Function: Adding multiple event source of the same type results to an error

### ISSUE THREAD

**Issue by jsunico** [aws/serverless-application-model#2927]
### Description
When creating a serverless function with multiple event sources of the same type, an error is thrown in Cloudformation.

Error: Multiple IAM policies have the same policy name: [SamAutoGeneratedAMQPolicy]. Specify a unique name for each policy and run the stack operation again.

![image](https://user-images.githubusercontent.com/65151494/220558205-54cb1c54-f3f6-48b1-88b0-25218734623c.png)

### Steps to reproduce
Create a resource with the following definition:

```
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Test
      CodeUri: path-to-code/
      Handler: app.handler
      Runtime: nodejs18.x
      MemorySize: 256
      Architectures:
        - x86_64
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroup
        SubnetIds: !Ref SubnetIds
      Events:
        BrokerOne:
            Type: MQ
            Properties:
              Broker: !Ref Broker1
              BatchSize: 1
              Queues:
                - MyQueue
              SourceAccessConfigurations:
                - Type: BASIC_AUTH
                  URI: !Ref BrokerSecret
        BrokerTwo:
            Type: MQ
            Properties:
              Broker: !Ref Broker2
              BatchSize: 1
              Queues:
                - MyQueue
              SourceAccessConfigurations:
                - Type: BASIC_AUTH
                  URI: !Ref BrokerSecret
        BrokerThree:
            Type: MQ
            Properties:
              Broker: !Ref Broker3
              BatchSize: 1
              Queues:
                - MyQueue
              SourceAccessConfigurations:
                - Type: BASIC_AUTH
                  URI: !Ref BrokerSecret
```

### Observed result
Error in Cloudformation is thrown:

Multiple IAM policies have the same policy name: [SamAutoGeneratedAMQPolicy]. Specify a unique name for each policy and run the stack operation again.

### Expected result
Lambda functions are created with multiple source mapping of the same type.

### Additional environment details

1. OS: WSL Ubuntu 20.04.5 LTS
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: SAM CLI, version 1.73.0
3. AWS region: eu-west-1
