### ISSUE TITLE
X-Ray cannot be enabled on API Gateway event source

### ISSUE THREAD

**Issue by lorchda** [aws/serverless-application-model#2939]
### Description

Given:

- A `AWS::Serverless::Function`
- An API Event Source

then it is no possible to enable X-Ray tracing on the API Event Source.

### Steps to reproduce

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Wild Rydes Asynchronous Messaging Workshop - Lab 2
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    Runtime: python3.9
    Tags:
      project: wild-rydes
      workshop: asynchronous-messaging-workshop
      author: aws

Resources:
  SubmitRideCompletionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: unicorn-management-service/
      Handler: app.lambda_handler
      Tracing: Active
      Events:
        WildRydes:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /submit-ride-completion
            Method: post
```

Full source code: https://github.com/aws-samples/asynchronous-messaging-workshop/blob/master/code/lab-2/template.yaml

### Observed result

With `Tracing: Active` set on the `AWS::Serverless::Function`, the Lambda function has X-Ray tracing enabled.

But the generated API Gateway does not have X-Ray tracing enabled. It is not possible to enable X-Ray tracing on the API Gateway event source, as there is no corresponding parameter for it available.

<img width="1363" alt="Screenshot 2023-02-24 at 10 54 53" src="https://user-images.githubusercontent.com/98748454/221148708-da583c94-b87e-4400-a567-76af0c467325.png">

### Expected result

Suggestions:
1. Provide a `Tracing` parameter to allow enabling X-Ray for the API Gateway event source
2. Given that I have enabled tracing on the Lambda function, SAM could infer that I also want it enabled on my event sources and could auto-enable X-Ray tracing on the API Gateway.

### Additional environment details

1. OS: macOS Monterey 12.6.3
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: SAM CLI, version 1.53.0
4. AWS region: eu-central-1

**Comment by lorchda** [comment]
We found out that X-Ray tracing needs to be enabled on the respective *stage*. The corresponding code would look like the one below.

However, this overrides the automatically created stages `Prod` and `Stage`, so might not be the ideal solution.

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Wild Rydes Asynchronous Messaging Workshop - Lab 2
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    Runtime: python3.9
    Tags:
      project: wild-rydes
      workshop: asynchronous-messaging-workshop
      author: aws

Resources:
  SubmitRideCompletionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: unicorn-management-service/
      Handler: app.lambda_handler
      Environment:
        Variables:
          TABLE_NAME: !Ref RidesTable
          TOPIC_ARN: !Ref RideCompletionTopic
      Policies:
        - DynamoDBCrudPolicy: # https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/policy_templates_data/policy_templates.json
            TableName: !Ref RidesTable
        - SNSPublishMessagePolicy: # https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/policy_templates_data/policy_templates.json
            TopicName: !GetAtt RideCompletionTopic.TopicName
      Tracing: Active
      Events:
        WildRydes:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /submit-ride-completion
            Method: post
            RestApiId: !Ref SubmitRideCompletionApi

  SubmitRideCompletionApi:
    Type: AWS::Serverless::Api
    Properties:
      TracingEnabled: true
      StageName: Prod
```
