### ISSUE TITLE
Deployment Error for generated EB Rules due to long name

### ISSUE THREAD

**Issue by hawflau** [aws/serverless-application-model#2941]
### Description
we got an error `QueryForAvailabilityWithUserExceptionQueryForAvailabilityWithUserExceptionEventLambdaTarget' at 'targets.1.member.id' failed to satisfy constraint: Member must have length less than or equal to 64 when deploying a changeset`. It was resulted from have a long Function Logical ID and a long Event key:

As discussed, the fix would be to: when generating the rule name, if it's longer than its max length, generate a shorter name. This should avoid any breaking change as it doesn't change any generated rule name if its length is within 64 characters.

### Steps to reproduce

```yml
QueryForAvailabilityWithUserException:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.query_for_command_availability_with_user_exception
      CodeUri: telemetry
      Role:
        Fn::GetAtt:
        - DefaultRole
        - Arn
      Events:
        QueryForAvailabilityWithUserExceptionEvent:
          Type: Schedule
          Properties:
            Schedule: cron(05 12 * * ? *)
```

### Observed result

Error seen: `QueryForAvailabilityWithUserExceptionQueryForAvailabilityWithUserExceptionEventLambdaTarget' at 'targets.1.member.id' failed to satisfy constraint: Member must have length less than or equal to 64 when deploying a changeset`

### Expected result

Deployment succeeds

### Additional environment details

1. OS:
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`:
3. AWS region:
