### ISSUE TITLE
Cannot add DefaultAuthorizer to API Gateway

### ISSUE THREAD

**Issue by tobi5775** [aws/serverless-application-model#2960]
### Description
I cannot add a DefaultAuthorizer to the API Gateway via AWS SAM template.

### Steps to reproduce
Add `AWS::Serverless::Api` to `template.yaml` with `Authorizers` and `DefaultAuthorizer`.
```
AWSTemplateFormatVersion: 2010-09-09

Transform:
  - AWS::Serverless-2016-10-31
 
Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: True
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Parameters:
  AuthorizerFunctionArn:
    Type: String
    Description: Arn of the AuthorizerFunction

Resources:
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: AWS Api Gateway
      Auth:
        DefaultAuthorizer: BasicAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          BasicAuthorizer:
            FunctionPayloadType: TOKEN
            FunctionArn: !Ref AuthorizerFunctionArn
            Identity:
              Header: Authorization
              ValidationExpression: ^[Bb]earer [-0-9a-zA-z\.]*$
              ReauthorizeEvery: 0
```

### Observed result
No Authorizer is added to the API Gateway as you can see here:
<img width="1415" alt="Bildschirmfoto 2023-02-27 um 12 20 19" src="https://user-images.githubusercontent.com/50146675/221550726-2b5a61b4-2d27-4940-9100-ed85f2cd5049.png">

No Authorizer is added to method.
<img width="383" alt="Bildschirmfoto 2023-02-27 um 12 24 01" src="https://user-images.githubusercontent.com/50146675/221551500-86f1b5ca-98a0-496b-b956-d1bda53b4420.png">

`AuthorizerFunctionArn` is a valid Arn.
<img width="813" alt="Bildschirmfoto 2023-02-27 um 12 22 44" src="https://user-images.githubusercontent.com/50146675/221551220-8992819e-ab05-4ef6-b671-daa2a8ef7417.png">

### Expected result
API Gateway has an authorizer and all methods are using the default authorizer.
Is there something missing in my template or something else blocking the authorizer creation?

### Additional environment details

1. OS: MacOS 12.1
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: SAM CLI, version 1.74.0
3. AWS region: eu-central-1
