### ISSUE TITLE
Feature request: Add resource names to destination linkages

### ISSUE THREAD

**Issue by allanchua101** [aws/serverless-application-model#3035]
### Describe your idea/feature/enhancement

In order to ease SAM connector's integration to storage resources as destinations (DynamoDBs, SQS Queues and Secrets), it will be really cool to add support to their names. This will make cross cloud formation stack integration much easier.

### Proposal

I wish SAM connectors could be defined such as:

```yaml
  StripePayoutInitiatorCron:
    Type: AWS::Serverless::Function
    Connectors:
      ReadConnectors:
        Properties:
          Destination:
            - Name: !Sub "${Environment}-${Version}-stripe-trail-queue" # SQS
            - Name: !Sub "${Environment}-${Version}-stripe-api-key" # Secrets manager
            - Name: !Sub "${Environment}-${Version}-stripe-payouts-db" # DynamoDB
```
