### ISSUE TITLE
New properties in `AWS::Cognito::UserPool` cannot be used with Cognito event

### ISSUE THREAD

**Issue by hoffa** [aws/serverless-application-model#3042]
### Description

See https://github.com/aws/serverless-application-model/issues/2581 for original issue.

### Steps to reproduce

```bash
git clone https://github.com/aws/serverless-application-model.git
cd serverless-application-model
python3 -m venv .venv && source .venv/bin/activate && make init
```

Save as `template.yaml`:

```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  MyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      SomeUnknownProperty: SomeUnknownValue

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      InlineCode: foo
      Handler: bar
      Events:
        CognitoEvent:
          Type: Cognito
          Properties:
            Trigger: CustomMessage
            UserPool: !Ref MyUserPool
```

Transform:

```bash
bin/sam-translate.py --template-file template.yaml
```

Which fails:

> ERROR:__main__:Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [MyUserPool] is invalid. property SomeUnknownProperty not defined for resource of type AWS::Cognito::UserPool
ERROR:__main__:<map object at 0x10d0772b0>

### Thoughts

`from_dict()` in `Resource` is the entry point:

https://github.com/aws/serverless-application-model/blob/f6b8794306ec8ffaf99a50ceea0a4ca33a4ee678/samtranslator/model/eventsources/push.py#L1203

https://github.com/aws/serverless-application-model/blob/f6b8794306ec8ffaf99a50ceea0a4ca33a4ee678/samtranslator/model/__init__.py#L169

It stores the properties as object attributes, and does validation when storing:

https://github.com/aws/serverless-application-model/blob/f6b8794306ec8ffaf99a50ceea0a4ca33a4ee678/samtranslator/model/__init__.py#L316-L317

And retrieving them:

https://github.com/aws/serverless-application-model/blob/f6b8794306ec8ffaf99a50ceea0a4ca33a4ee678/samtranslator/model/__init__.py#L298-L302

We could either add the unknown properties as attributes like usual, or perhaps better, store the initial resource dictionary, and in `to_dict()` merge, failing in case of conflict (to ensure it doesn't silently overwrite properties from customer template).

Also... does this affect any other resources? Maybe ones that use `from_dict()` as well?
