### ISSUE TITLE
Latest version of lambda not being used for lambda@edge

### ISSUE THREAD

**Issue by peejayess** [aws/serverless-application-model#3079]
### Description:
I'm running a stack in eu-west-1 and I'm creating a lambda@edge function in us-east-1 using a StackSet.  I'm setting an SSM parameter in eu-west-1 with the lambda version (i.e. using `AutoPublishAlias: live` on the function) so I can retrieve it in the eu-west-1 lambda.  The Issue I'm having is that the parameter is getting written with the previous version of the lambda and not the latest version

### Steps to reproduce:
My code:
```
EdgeRoutingLambda:
  Type: AWS::Serverless::Function
  DeletionPolicy : Retain
  Properties:
    Handler: index.handler
    Description: CloudFront edge routing for SalesDesk.app
    Role: !Ref EdgeRoutingLambdaRoleArn
    AutoPublishAlias: live
    Runtime: nodejs14.x
    InlineCode:  <lambda@edge handler code>

CallSaveEdgeRoutingLambdaArnToSSMParam:
  Type: AWS::CloudFormation::CustomResource  
  Properties:
    ServiceToken: !Ref SetSSMParamLambdaArn
    Name: !Ref SSMParameter
    Value: !Ref EdgeRoutingLambda.Version
```

### Observed result:
The `!Ref EdgeRoutingLambda.Version` is providing the Arn for the previous version of the lambda and not the latest

If I change the `<lambda@edge handler code>` and redeploy I can see that a new version of the lambda is being created but the parameter in SSM refers to the previous version and not the latest.  I have done this up to version 6 of the lambda yet I still get the version 5 Arn put in the SSM parameter.  It's almost as if the `CallSaveEdgeRoutingLambdaArnToSSMParam` dependency is running once the underlying aws::lambda::function has been created but before the underlying AWS::Lambda::Version has been created so its picking up the previous version

### Expected result:
I would expect the `!Ref EdgeRoutingLambda.Version` to provide the latest version of the lambda

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
{
  "version": "1.76.0",
  "system": {
    "python": "3.8.13",
    "os": "macOS-13.2.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.23",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}
