### ISSUE TITLE
AWS::Serverless::Api EndpointConfiguration doesn't support Types? expected type: String, found: JSONObject

### ISSUE THREAD

**Issue by Jun711** [aws/serverless-application-model#3089]
### Description

I was trying to use !FindInMap to set different API type for different API stages 
but it failed to pass the properties validation with this error.
I referred to this AWS Documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html for EndpointConfiguration syntax

```
Properties validation failed for resource ApiName with message:   
#/Parameters: #: no subschema matched out of the total 2 subschemas   
#/Parameters/endpointConfigurationTypes: expected type: String, found: JSONObject   
#/Parameters: expected type: String, found: JSONObject 
#/EndpointConfiguration/Types/0: expected type: String, found: JSONObject. 
```

I got it working eventually by removing types and set it directly at EndpointConfiguration 
```
EndpointConfiguration: !FindInMap [StageToName, ApiType, !Ref Stage]
``` 

### Steps to reproduce

```
Mappings: 
  StageToName: 
    ApiType: 
      test: REGIONAL
      prod: EDGE
Resources:
  ApiName:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub '${Stage}'
      EndpointConfiguration:   
        Types:
          - !FindInMap [StageToName, ApiType, !Ref Stage]
```

### Observed result

CREATED_FAILED with this error message

```
Properties validation failed for resource ApiName with message:   
#/Parameters: #: no subschema matched out of the total 2 subschemas   
#/Parameters/endpointConfigurationTypes: expected type: String, found: JSONObject   
#/Parameters: expected type: String, found: JSONObject 
#/EndpointConfiguration/Types/0: expected type: String, found: JSONObject. 
```

On CloudFormation, the transformed template looks like this:
```
EndpointConfiguration:
        Types:
        - Fn::FindInMap:
          - StageToName
          - apiType
          - Ref: Stage
```

This is processed template section that caused this error:
```
"Parameters": {
          "endpointConfigurationTypes": {
            "Types": [
              "REGIONAL"
            ]
          }
        },
        "EndpointConfiguration": {
          "Types": [
            {
              "Types": [
                "REGIONAL"
              ]
            }
          ]
        }
      }
```

### Expected result

Expected it to be able to build different types of API using !FindInMap intrinsic function

### Additional environment details

1. OS:
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: SAM CLI, version 1.78.0
3. AWS region: us-east-1
