### ISSUE TITLE
Not creating New Lambda Version on every deployment when package type for lambda is Image

### ISSUE THREAD

**Issue by jay-patel-simformsolutions** [aws/serverless-application-model#3103]
### Description
**What I am trying to achieve:** I want to have a blue green deployment strategy for my backend deployment. That means that 2 versions of my back-end APIs should co-exist at the same time. That versioning should happen through API Gateway stages. and each stage should point to a different alias of a lambda function and each alias should point to a different Lambda version. I have tried using AutoPublishAlias attribute of AWS::Serverless::Function. But it was not persisting the previous Aliases. So according to https://github.com/aws/serverless-application-model/issues/304 I specified AWS::Lambda::Version and AWS::Lambda::Alias explicitly
But again this created an issue that it was not creating a new Lambda Version. Some more context: My lambdas are using PackageType Image.

### Expected result
I want that every new deployment should create a new API Gateway stage, new Lambda Version and a new Lambda Alias and persist the old ones. And once I feel confident about the new API Stage working correctly I can migrate my traffic to new stage and delete the old one manually or using aws cli

### Additional environment details

1. OS:
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: SAM CLI, version 1.72.0
3. AWS region: eu-central-1

Adding Code Sample
```yaml
  APILambda:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Sub "${Env}-api"
      MemorySize: 128
      Timeout: 15
      ImageUri: apilambda:api
      Environment:
        Variables:
          ENV: !Sub "${Env}"
          AWS_SECRET_REGION: !Ref AWS::Region
          ENCRYPTION_KEY: !Ref EncryptionKey
          S3_BUCKET_NAME: !Sub "${Env}-artifacts"
          NOTIFICATION_QUEUE_URL: !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${Env}-notification-queue"
          FRONT_END_DOMAIN: !Ref FrontendURL
          S3_BUCKET_NAME: !Sub "${Env}-artifacts"
    Metadata:
      DockerTag: api
      DockerContext: .
      Dockerfile: Dockerfile
  
  APILambdaVersion:
    Type: AWS::Lambda::Version
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties: 
      Description: !Sub "Version for ${BackendVersion}"
      FunctionName: !Sub "${Env}-api"

  APILambdaAlias:
    Type: AWS::Lambda::Alias
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties: 
      Description: !Sub "Alias for ${BackendVersion}"
      FunctionName: !Sub "${Env}-api"
      FunctionVersion: !Select [7, !Split [ ":", !Ref APILambdaVersion]]
      Name: !Ref BackendVersion
```
