### ISSUE TITLE
AWS::Scheduler::Schedule fails on creation when using same template on multiple stacks

### ISSUE THREAD

**Issue by cignuz-jp** [aws/serverless-application-model#3109]
### Description

When creating a new stack from a template that has `AWS::Serverless::Function` using the `ScheduleV2` Event source type, change set execution fails with error: `<function-event> already exists in stack arn:aws:cloudformation:us-east-2:************:stack/firstScheduler/d4db7f60-dccb-11ed-aaac-02795b774f1e`

The [documentation page](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-schedulev2.html#sam-function-schedulev2-name) for `Name` property of the `ScheduleV2` event type mentions: 
>The name of the schedule. If you don't specify a name, AWS SAM generates a name in the format Function-Logical-IDEvent-Source-Name and uses that ID for the schedule name. 

From above statement it can be concluded that if the template is used on more than one stack the Name for the Event will not be unique which will lead to the error. 

 

### Steps to reproduce

1. Create a SAM application that has an AWS::Serverless::Function resource with an Event of type `ScheduleV2`. The following is a change I've made to the a SAM application based on the `quick-start-cloudwatch-events` template.

```yaml
  ScheduledEventLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that logs the payload of messages sent to an associated SQS queue.
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Handler: src/handlers/scheduled-event-logger.scheduledEventLoggerHandler
      Events:
        EventBridgeScheduler:
          Type: ScheduleV2
          Properties:
            Description: scheduler to consume notifications
            ScheduleExpression: 'cron(0 0 ? * 2 *)'
            ScheduleExpressionTimezone: America/Los_Angeles
            FlexibleTimeWindow:
              Mode: 'OFF'
      MemorySize: 128
      Timeout: 100
```

2. Build and deploy the sam application to a new stack (e.g: firstScheduler)
3. Deploy the sam application to a different stack (e.g: secondScheduler).
### Observed result

The SAM application fails to deploy on 3rd step showing the error referencing the resource exists in the stack deployed on step 2.

### Expected result

The SAM application to be successfully deployed.

### Additional environment details

1. OS: MacOS Monterrey (12.6.1) on M1 chip
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: SAM CLI, version 1.79.0
4. AWS region: us-east-2
