### ISSUE TITLE
Can't call methods from other files in handler

### ISSUE THREAD

**Issue by brandon-burciaga** [aws/serverless-application-model#3122]
### Description

I have an HTTP GET request Lambda set up via my `template.yml` file. My handler calls another method (not another Lambda) that's exported in another file. 

When including this method call in my code, I get the error below. When I comment it out, I no longer receive the error. The issue is that I am  unable to call methods in other files from my handler for some reason. This was not happening before a couple days ago, and I have no idea what changed.

It is a GET, so there is no body to parse, which would usually cause this error.

It also never reaches my first line of code, before the method call., to log the event. So simply including the `myFunctionCall()` is 
causing the error...

template.yml snippet
```
  GetHealthCheckFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/health-check.getHealthCheckHandler
      Description: Health Check Endpoint.
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AmazonSSMReadOnlyAccess
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref BaseApi
            Path: /health-check
            Method: GET
```
My code:

```
import { myFunctionCall } from '../my-service'

export class GetHealthCheckLambda{
  async run(event: ApiGatewayEvent): Promise<ApiGatewayResponse> {
    console.log(
      'GetTestLambda began processing a request...',
      event
    ) // <-- never even logs here, just fails when loading this file I think
    const resp = await myFunctionCall()
}
```

Error upon hitting my Lambda endpoint with Postman:
```
START RequestId: b1ea29fe-3429-4115-a056-cdff6ee7d77e Version: $LATEST                                        2023-04-23T17:30:01.117Z        undefined       ERROR   Uncaught Exception      {"errorType":"Runtime.UserCodeSyntaxError","errorMessage":"SyntaxError: Unexpected token { in JSON at position 1","stack":["Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token { in JSON at position 1","    at _loadUserApp (file:///var/runtime/index.mjs:994:17)","    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1032:21)","    at async start (file:///var/runtime/index.mjs:1195:23)","    at async file:///var/runtime/index.mjs:1201:1"]}                                                                                                   23 Apr 2023 17:30:01,127 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 129 InvokeID=  
```

### Steps to reproduce

1. Set up new Lambda via API Gateway in SAM template.yml
2. Set up Lambda handler code as above
3. Start the local API with `sam local start-api --warm-containers LAZY --env-vars env.json --debug`
4. Hit the endpoint that has a handler that uses a method call from another file
5. Receive error

### Observed result

Lambda does not execute but fails when invoking with an unhelpful message.

### Expected result

The lambda to be successfully invoked and at least log something.

### Additional environment details

1. OS: Windows 10 running on WSL 2 with Ubuntu
6. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: `1.78.0`
7. AWS region: us-east
