### ISSUE TITLE
Feature request: Support DisableExecuteApiEndpoint for Serverless::HttpApi with DefinitionUri

### ISSUE THREAD

**Issue by CloudedThings** [aws/serverless-application-model#3128]
Support `DisableExecuteApiEndpoint: true` when creating AWS::Serverless::HttpApi with DefinitionUri.

### Proposal

When running `sam validate` on a template with resource Serverless::HttpApi with DefinitionUri property allow disabling the execute API endpoint. 

> template.yaml

```
HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
        DefinitionUri:
            Bucket: !Ref Bucket
            Key: 'openapi.yaml'
        DisableExecuteApiEndpoint: true
```

That raises error: `[InvalidResourceException('HttpApi', "DisableExecuteApiEndpoint works only within 'DefinitionBody' property.")]

The alternative way with 'DefinitionBody' property doesn't solve the problem instead leads to another one. When trying to create HttpApi with:

> template.yaml

```
HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
        DefinitionBody:
            'Fn::Transform':
                Name: 'AWS::Include'
                Parameters:
                    Location: './openapi.yaml'
        DisableExecuteApiEndpoint: true
```
Another error is being raised: [InvalidTemplateException("Invalid OpenApi document. Invalid values or missing keys for 'openapi' or 'paths' in 'DefinitionBody'.")] 

> openapi.yaml

```
openapi: 3.0.1
info:
    title: 'api'
    version: '1.0'
    description: test
paths:
    /hello:
        get:
...
```

### Additional Details
SAM CLI, version 1.81.0
