### ISSUE TITLE
Cannot pass Dynamic path to a nested application using !Sub or !Ref intrinsic functions

### ISSUE THREAD

**Issue by jay-patel-simformsolutions** [aws/serverless-application-model#3144]
parent-application.yaml
```
ChildApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: resources/child1-application.yaml
      Parameters:
        Env: !Ref Env
```
And consider we have child1-application.yaml and child2-application.yaml in the resource directory so a static location path `resource/child1-application.yaml` works fine but `!Sub resource/${Env}-applicaion.yaml` does not work where Env is a command-line argument that is passed child1. It gives an error that the applicationId is missing, but the same error does not occur when I use static  `resources/child1-application.yaml`

**Comment by awood45** [comment]
I don't quite follow some of the explanation - can you perhaps give me a minimal set of reproducing steps for this?

**Comment by jay-patel-simformsolutions** [comment]
Sure, Basically I want to create 2 stacks 1 is parent stack and the other one is child stack, I want the child stack to be dynamic. To be very specific the child stack contains database. Now I want that for each env a database is created with a different specification, for eg. the prd, stg, uat must have a aurora-postgresql instance and the dev, test, playground and other short living environments should have simple RDS with postgresql instance to reduce the cost.

Code level example:
Our folder tree is something like this:
parent-stack.yaml
resources/
     - some-nested-stack.yaml
     - some-nested-stack2.yaml
     - prd-database.yaml
     - stg-database.yaml
     - dev-database.yaml


parent-stack.yaml
```
.
.
.
DatabaseStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: resources/prd-database.yaml
      Parameters:
        Env: !Ref Env
```

So the above code example works perfectly fine because it is a static path in the template.yaml file itself. But what I am trying to achieve is I take a command line argument and make the Location Property for DatabaseStack dynamic. For e.g.
parent-stack.yaml
```
Parameter:
    Env:
         Type: String
         Description: Specifies the Environment that we want to deploy

.
.
.
    DatabaseStack:
        Type: AWS::Serverless::Application
        Properties:
            Location: !Sub resources/${Env}-database.yaml
            Parameters:
                   Env: !Ref Env
```

This gives me an error that the ApplicationId is required, Where as a static path was working correctly

I hope this gives more clarity
