### ISSUE TITLE
Invalid RequestParameters when more than 1 querystring parameter defined

### ISSUE THREAD

**Issue by XXChester** [aws/serverless-application-model#3146]
### Description
I am trying to deploy an API with 2 query string parameters with validation for fail fast functionality in API Gateway. If I only put one query string parameter under the RequestParameters section, it works properly but as soon as I add 2 or more, sam validate complains with the following error:
> Error: [InvalidResourceException('WriteLeaderboardFunctionWrite', "Type of property 'RequestParameters' is invalid.")] ('WriteLeaderboardFunctionWrite', "Type of property 'RequestParameters' is invalid.")

### Steps to reproduce
run sam validate on a template with multiple RequestParameters preesnt.
```yaml
WriteLeaderboardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: write_leaderboard.lambda_handler
      Runtime: python3.9
      ReservedConcurrentExecutions: 1
      MemorySize: 256
      Architectures:
        - x86_64
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref BucketName
      Events:
        Write:
          Type: Api
          Properties:
            RestApiId: !Ref apis
            Path: /leaderboard
            Method: put
            Auth:
              ApiKeyRequired: true
            RequestParameters:
              method.request.querystring.score:
                type: integer
                minimum: 0
                required: true
              method.request.querystring.name:
                type: string
                minLength: 3
                maxLength: 25
                required: true
```

### Observed result
> Error: [InvalidResourceException('WriteLeaderboardFunctionWrite', "Type of property 'RequestParameters' is invalid.")] ('WriteLeaderboardFunctionWrite', "Type of property 'RequestParameters' is invalid.")

### Expected result
The template should be valid and allow deployment to AWS with 2 query parameter validations set.

### Additional environment details

1. OS: Windows
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`:  1.64.0
3. AWS region: us-east-1

To remove the question about whitespace and indentation here is a screenshot of the template with rainbow color indentation.
![image](https://user-images.githubusercontent.com/12719018/236550847-dda386ca-7c41-4a6e-bfc0-160a1ec1c824.png)

Thank you.

**Comment by hoffa** [comment]
For posterity, see perhaps relevant issue: https://github.com/aws/serverless-application-model/issues/2109

**Comment by aahung** [comment]
[Our doc](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-api.html#sam-function-api-requestparameters) is outdated. 
<img width="870" alt="image" src="https://github.com/aws/serverless-application-model/assets/3804518/40109805-d6d3-4c98-b53e-738f594393bd">

The type of `RequestParameters` should be `List[String | RequestParameter]` and supported format can be found in #2109 brought up by @hoffa:

```
            RequestParameters:
            - method.request.querystring.xxx:
                Required: true
                Caching: false
```

Note the only `Required` and `Caching` are [valid properties](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-requestparameter.html). I am curious about where the `type` and `minLength` in your template come from.
