### ISSUE TITLE
Transform rejects CloudFormation dynamic references in `Policies` field

### ISSUE THREAD

**Issue by JackKelly-Bellroy** [aws/serverless-application-model#3152]
### Description

It is no longer possible to use `{{resolve:...}}` syntax ([CloudFormation Dynamic References](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html)) in the `Policies:` field of (at least) `AWS::Serverless::Function`. To attach certain (Terraform-provisioned) IAM Policies to our Functions' execution roles, we have been using dynamic references to SSM Parameters which provide the Policy ARNs. Our deploys are now failing because Serverless Transform is rejecting the CloudFormation Template.

### Steps to reproduce

1. Create an IAM Policy
2. Create an SSM Parameter (string type) whose value is the ARN of the policy from step (1).
3. Declare an `AWS::Serverless::Function` which lists the policy via `{{resolve}}`:
    ```yaml
    ExampleFunction:
      Type: AWS::Serverless::Function
      # Other fields omitted
      Policies:
        - AWSLambdaBasicExecutionRole
        - "{{resolve:ssm:/name_of_parameter_from_step_2}}"
    ```
4. Attempt to deploy.

### Observed result

```
Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [ExampleFunction] is invalid. Invalid policy '{{resolve:ssm:/name_of_parameter_from_step_2}}'; make sure the value is a valid AWS managed policy ARN.
```

[Judging by the error message](https://github.com/aws/serverless-application-model/pull/3132/files#diff-16692ef20ff9927de4284790d5378a7a0a7dc29870fca48be5231de8d2171b7dR152), I suspect this was introduced by #3132.

### Expected result

Serverless Transform would not inspect the string, and pass it through unchanged to be substituted by CloudFormation.
