### ISSUE TITLE
Query string validator support

### ISSUE THREAD

**Issue by XXChester** [aws/serverless-application-model#3161]
I've been searching the internet all day and looking through PR's here for adding support for body and request parameters but query string and header support has been left out from what I can tell.

For instance in the example function below, the Score comes in through an query string parameter. I would love to be able to validate this which currently I seem to only be able to do it via changing the UI setting manually. Why did we not support all 4 validators when we added support for body and request params?

```yaml
GetLeaderboardFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:"GetLeaderboard"
      CodeUri: app/
      Handler: read_leaderboard.lambda_handler
      Runtime: python3.9
      MemorySize: 512
      Architectures:
        - x86_64
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref BucketName
      Events:
        Read:
          Type: Api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /leaderboard
            Method: get
            Auth:
              ApiKeyRequired: true
            RequestParameters:
              - method.request.querystring.score:
                  Required: true
                  Caching: false
            RequestModel:
              Model: Score
              Required: true
              ValidateBody: false
              ValidateParameters: false
              ValidateQueryString: true
              ValidateHeaders: true
```

I don't really care what the fields are called, I would just like to be able to assign the UI field via my SAM template. 

To clarify, this setting should be set to query-string-and-header or something similar:
![image](https://github.com/aws/serverless-application-model/assets/12719018/f2c6b395-ad3a-4f6d-a3cb-1bcaa5dcbfd4)

Thanks.

**Comment by hoffa** [comment]
I think supporting this makes sense. Do you happen to know how you would enable this in regular CloudFormation?

I had a quick look at the code and this seems to be the relevant part for body and parameters validation:

https://github.com/aws/serverless-application-model/blob/c2d7e2164038c79715707ec5a7e67e050ab691f6/samtranslator/swagger/swagger.py#L798-L803

Which seems to correspond to https://docs.aws.amazon.com/apigateway/latest/api/API_RequestValidator.html. However it doesn't mention query parameters specifically.

**Comment by hoffa** [comment]
I gave it a shot, and I'm unable to reproduce.

It looks like enabling `ValidateParameters` validates both headers and query strings, which is consistent with the [SAM docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-requestmodel.html#sam-function-requestmodel-validateparameters).

I saved the following as `template.yaml`:

```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      AlwaysDeploy: true
      StageName: prod
      Models:
        mybody:
          type: object
          properties:
            myprop:
              type: string
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
          return {"statusCode": 200, "body": "hi"}
      Events:
        MyEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref MyApi
            RequestParameters:
              - method.request.querystring.myquerystring:
                  Required: true
              - method.request.header.myheader:
                  Required: true
            RequestModel:
              Model: mybody
              ValidateBody: false
              ValidateParameters: true
Outputs:
  ApiEndpoint:
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/prod/"
```

Then deployed:

```bash
sam deploy --region eu-west-1 --resolve-s3 --capabilities CAPABILITY_IAM --stack-name test-10 --template template.yaml
```

Then `curl`ed the endpoint. It only works if I pass both `myquerystring` and `myheader`:

```bash
curl -H "myheader: foo" 'https://<api-id>.execute-api.eu-west-1.amazonaws.com/prod/?myquerystring=bar'
```
