### ISSUE TITLE
SAM deploy doesn't modify uploaded `CodeUri` if `!Sub` is used even with AWS::LanguageExtensions

### ISSUE THREAD

**Issue by garretwilson** [aws/serverless-application-model#3197]
I'm using SAM 1.84.0 on Windows 10.

Let's say I'm deploying some lambda function I built with Maven:

```yaml
Resources:
  FooFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/foo-bar-functions-1.2.3.jar
      Handler: com.example.FooBar::foo
```

SAM recognizes that `CodeUri` points to a local file, so it uploads JAR file to S3 and also uploads the template itself to S3. But _first it modifies the template_ to reference the new JAR file location. The template uploaded windws up looking like this:

```yaml
Resources:
  FooFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-…/…
      Handler: com.example.FooBar::foo
```

Obviously I don't want to hard-code the version `1.2.3` in my SAM template. In pure CloudFormation it is no problem for me to simply pass in a `Ver` parameter from the command line, indicating the version to use (e.g. the latest Maven version, or some version in the past, or whatever):

```yaml
Resources:
  FooFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: !Sub "target/foo-bar-functions-${Ver}.jar"
      Handler: com.example.FooBar::foo
```

But because of this bug, SAM gives me an error:

> `'CodeUri' requires Bucket and Key properties to be specified.`

This general problem has been discussed in #2533. It seems that SAM gets all confused if there are functions used in the values that SAM needs right away. So the workaround noted in #2533 was to add `AWS::LanguageExtensions`.

```
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
```

That gets me a little further: SAM will at least upload my JAR to the S3 bucket. But then when it fails with:

> `'CodeUri' is not a valid S3 Uri of the form 's3://bucket/key' with optional versionId query parameter.`

The template uploaded has:

```yaml
      CodeUri:
        Fn::Sub: target/foo-bar-functions-${Ver}.jar
```

I believe this is not simply the same as #2533 ; rather, it would seem to be a SAM bug. If SAM with `AWS::LanguageExtensions` can figure out the JAR file that `!Sub "target/foo-bar-functions-${Ver}.jar"` and be able to upload it, it should be able to realize that the value for `CodeUri` should be updated, just as if it were a literal string.

In other words, this is not just a problem of not having values available at the time of deployment. As you can see, with `AWS::LanguageExtensions` _SAM already knows what the correct value is for `CodeUri`_, because it found the JAR file. The problem is that when SAM then uploads the template to S3, it doesn't realize that the `CodeUri` still needs updating. **It knows what the value should be because it just uploaded the JAR file!** Something about using `!Sub` with `CodeUri` is preventing SAM from replacing the local reference as it would if the value were a literal string.

(I would guess that somewhere in the code there is an erroneous "sanity-check" line that say something like "if (`CodeUri` is a literal string and `CodeUri` points to a local value) {update `CodeUri` value to S3 form}". This bug fix may be a simple as removing the erroneous "`CodeUri` is a literal string" check. This is all just a guess based upon behavior; I haven't looked at the code.)
