### ISSUE TITLE
Validation fails when using `Name` property in `EventBridgeRule`

### ISSUE THREAD

**Issue by davidjb** [aws/serverless-application-model#3215]
### Description

`sam validate` fails when defining an `EventBridgeRule` with a `Name` property, as per the SAM API docs at https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-statemachineeventbridgerule.html.

Originally described in #3086, the fix PR #3087 doesn't actually solve the validation issue. The  error described in #3086 and below occurs at this point:

https://github.com/aws/serverless-application-model/blob/develop/samtranslator/model/__init__.py#L325

and the `self` Resource object is a `samtranslator.model.stepfunctions.events.EventBridgeRule`. This class [extends from `CloudWatchEvent`](https://github.com/aws/serverless-application-model/blob/develop/samtranslator/model/stepfunctions/events.py#L279), which is expecting `Name` to be defined as `RuleName` (https://github.com/aws/serverless-application-model/blob/develop/samtranslator/model/stepfunctions/events.py#L199) which causes the validation failure.

Changing `Name` to `RuleName` in `template.yaml` allows validation to pass, but creates a non-standard configuration. 

Because the `EventBridgeRule` class extends `CloudWatchEvent`, this also allows configs with `State`, a property that's not defined in the [EventBridgeRule docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-statemachineeventbridgerule.html), to pass.

### Steps to reproduce

1. Create a proejct: `sam init --name sam-eventbridgerule --runtime python3.9`
2. Change the SFN in `template.yaml`:

   ```yml
   Resources:
     StockTradingStateMachine:
       Type: AWS::Serverless::StateMachine
       # snip
       Properties:
         # snip
         Events:
          MyEvent:
            Type: EventBridgeRule
            Properties:
              Name: foobar
              Pattern:
                detail-type: ["Object Created"]
   ```
3. Run `sam validate` and observe error.

### Observed result

```sh
E0001 Error transforming template: Resource with id [StockTradingStateMachineMyEvent] is invalid. property Name not defined for resource of type EventBridgeRule
/Users/davidjb/sam-eventbridgerule/template.yaml:1:1

Error: Linting failed. At least one linting rule was matched to the provided template.
```

### Expected result
Template validation to succeed with `Name` and to fail when using `State` properties on `EventBridgeRule`.

### Additional environment details

1. OS: macOS
4. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: `v1.87.0`
5. AWS region: `us-east-1`
