### ISSUE TITLE
AWS::Serverless::Api not applying Tags to all generated resources, PropagateTags not defined.

### ISSUE THREAD

**Issue by cheriejw** [aws/serverless-application-model#3246]
### Description

I am using the `AWS::Serverless::Api` resource and attempting to have it tag the generated `AWS::ApiGateway::RestApi` resource. Currently only the generated `AWS::ApiGateway::Stage` resource receives the `Tags` provided in the `template.yaml`.

I looked at the [documentation page for AWS::Serverless::Api](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html) and it looks like there is a `PropagateTags` property that can be set, that sounds like it will do what I want. I set the property, but I get a `InvalidResourceException` error.

### Steps to reproduce

Set `template.yaml` to:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

Globals:
  Function:
    Tags: &tags
      source: 2uinc/ai-chatbot-backend
      portfolio: service-experience
      product: chatbot-backend
      businessunit: degrees
      group: ai-services
      env: testerstagename

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /helloWorld
            Method: get
        HttpPost:
          Type: Api
          Properties:
            RestApiId: !Ref QueryApi
            Path: /zendesk/query
            Method: post

  QueryApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: testerstagename
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
      PropagateTags: True
      Tags: *tags

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
```
_Note: This configuration is valid without the added `PropagateTags` value._

Run `sam validate` or `sam deploy`.

### Observed result

`Error: [InvalidResourceException('QueryApi', 'property PropagateTags not defined for resource of type AWS::Serverless::Api')] ('QueryApi', 'property PropagateTags not defined for resource of type AWS::Serverless::Api')`

### Expected result

I expect `PropagateTags` to be a valid property for `AWS::Serverless::Api` definition.

If it is not supported, then I **do not expect** to see it in the [documentation page for AWS::Serverless::Api](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-propagatetags).
![Screenshot 2023-07-07 at 8 13 18 AM](https://github.com/aws/serverless-application-model/assets/14297171/d952d100-bba2-4aff-a025-38d98e823c0c)

### Additional environment details

1. OS: macOS Ventura - Version 13.4
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli)
    `sam --version`: `SAM CLI, version 1.89.0`
    `aws --version`: `aws-cli/2.12.4 Python/3.11.4 Darwin/22.5.0 source/arm64 prompt/off`
3. AWS region: `us-west-1`
