### ISSUE TITLE
`EventBridgeRule` breaks with `Fn::Sub`: "Name not defined for resource of type EventBridgeRule"

### ISSUE THREAD

**Issue by garretwilson** [aws/serverless-application-model#3260]
I had a very straightforward CloudFormation template, containing a Lambda that listened to EventBridge events with the detail type "FooBar". It looked like this

```yaml
  MyEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: my-event-bus

  MyFunction:
    Type: AWS::Lambda::Function

…

  MyEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${AWS::StackName}-my-rule"
      EventBusName: !Ref MyEventBus
      EventPattern:
        detail-type: ["FooBar"]
      Targets:
        - Id: !Ref MyFunction
          Arn: !GetAtt MyFunction.Arn
```

"Use SAM," they said. "SAM will make things easier." So I converted it to SAM. I put the magic stuff at the top:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
```

Then I "simplified" the function definition (except for the `CodeUri` stuff, which I had to turn into a kludge to work around aws/serverless-application-model#3264):

```yaml
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      …
      Events:
        Trigger:
          Type: EventBridgeRule
          Properties:
            Name: !Sub "${AWS::StackName}-my-rule"
            EventBusName: !Ref MyEventBus
            Pattern:
              detail-type: ["FooBar"]
            Target:
              Id: !Ref MyFUnction
```

We are truly far from rocket science at this point. But SAM doesn't like that. I do a `sam deploy` and get this:

> `Error: Failed to create changeset for the stack: my-stack, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [MyFunctionTrigger] is invalid. property Name not defined for resource of type EventBridgeRule`

Please tell me this is not (again!) what I think it is. Please tell me I am making some mistake and I have screwed up the conversion. Please tell me I'm being slow this morning and have made a typo or something. Please tell me this is not SAM again making things "simple" for me and wasting my day to file bugs.

Please, I want the mistake to be mine. I would welcome it.

**Comment by ssenchenko** [comment]
It seems like you wanted to use `AWS::Serverless::Function`. `AWS::Lambda::Function` doesn't have all those extensions. So once you change the type, I suppose everything will work.

**Comment by garretwilson** [comment]
> It seems like you wanted to use `AWS::Serverless::Function`. `AWS::Lambda::Function` doesn't have all those extensions.

That was a typo. I will fix it now.

> So once you change the type, I suppose everything will work.

I suppose you haven't tested it.

**Comment by aaythapa** [comment]
Hi @garretwilson thanks for reporting this issue. Turns out it was an error in our docs. The property is called `RuleName` not `Name` and thats what was causing your deployment to fail. Sorry about this.

I tested with the following template and it deployed fine. 

```
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Resources:
  
  MyEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: my-event-bus

  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      InlineCode: ...
      Events:
        Trigger:
          Type: EventBridgeRule
          Properties:
            RuleName: !Sub "${AWS::StackName}-my-rule"
            EventBusName: !Ref MyEventBus
            Pattern:
              detail-type: ["FooBar"]
```
We'll be updating the docs asap. Let us know if this fixes your error or if it persists. Thanks again.
