### ISSUE TITLE
AWS::Serverless::Api AuthorizationScopes not being taken

### ISSUE THREAD

**Issue by pedrofurlanetto90** [aws/serverless-application-model#3325]
### Description
`AWS::Serverless::Api` is not validating the JWT token scopes.

### Steps to reproduce

Configure the `AWS::Serverless::Api` Lambda authorizer with the following configuration and send a token without a scope or with a scope not present in the `AuthorizationScopes` list
```yaml
      Auth:
        Authorizers:
          LambdaAuthorizer:
            FunctionPayloadType: TOKEN
            FunctionArn: <lambda ARN>
            AuthorizationScopes:
            - a
            - b
            - c
            Identity:
              ValidationExpression: ^(Bearer )[a-zA-Z0-9\-_]+?\.[a-zA-Z0-9\-_]+?\.([a-zA-Z0-9\-_]+)$
```

### Observed result

The request is being routed to the Authorizer Lambda and lambda is trying to validate the token

### Expected result

The request should be blocked by API Gateway and lambda authorizer should not be called (same behavior when the token does not follow the regex configured in `ValidationExpression`)

### Additional environment details

1. OS:
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`:
3. AWS region: us-east-1
