### ISSUE TITLE
Feature request: Support InputTransformer under EventBridgeRule for `AWS::Serverless::StateMachine`

### ISSUE THREAD

**Issue by ljacobsson** [aws/serverless-application-model#3333]
As a user of SAM I would expect to be able to use `InputTransformer` in an EventBridgeRule on `AWS::Serverless::StateMachine` in the same way as I can on `AWS::Serverless::Function`, which was just released (see issue #2666):

```
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${AWS::StackName}-StateMachine
      DefinitionUri: statemachine.yaml
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: default
            Pattern:
              source:
                - aws.s3
              detail-type:
                - Object Created
              detail:
                bucket:
                  name:
                    - abc
                object:
                  key:
                    - xyz
            InputTransformer: 
              InputPathsMap: 
                bucket: "$.detail.bucket.name"
                key: "$.detail.object.key"
              InputTemplate: '{"bucket": <bucket>, "key": <key>}'
```
