### ISSUE TITLE
Suddenly getting traceback: AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by garretwilson** [aws/serverless-application-model#3361]
I'm on Windows 10. A day or two ago I updated to SAM CLI, version 1.97.0. I don't know for sure if it's related to the upgrade, but now deploying a very simple template gives me:

```
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1686, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\_utils\options.py", line 170, in artifact_callback
    for _template_artifact in get_template_artifacts_format(template_file=template_file)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\_utils\template.py", line 301, in get_template_artifacts_format
    for _, resource in template_dict.get("Resources", {}).items():
AttributeError: 'NoneType' object has no attribute 'items'
```

Why?!

**Comment by GavinZZ** [comment]
Hi there, would you mind sharing that simple template so that I can investigate?

**Comment by garretwilson** [comment]
I stress that this was _not_ happening before. I've never seen this before. And the template is dirt simple:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Description:
  Foo service.

Parameters:
  Env:
    Description: The token identifying the deployment environment, such as "dev", "dev3", or "dev-jdoe".
    Type: String
    AllowedPattern: '\w[\w-]*'
    ConstraintDescription: The development environment identifier must only use word characters and dashes.

Globals:
  Function:
    Runtime: java17
    Architectures: [x86_64]
    MemorySize: 800
    Timeout: 4 #4 s

Resources:
  LambdaHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "foo-${Env}-LambdaHandler"
      CodeUri: !Sub "s3://foo-${Env}-staging/foo-aws-lambda.zip"
      Handler: com.example.LambdaHandler::handleRequest
```

This is being invoked from Git Bash using the following command:

```bash
        sam deploy \
            --profile $awsProfile \
            --template-file "$samTemplateFile" \
            --stack-name $stackName \
            --s3-bucket $stagingBucketName \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides Env=$env
```

Note that there is _no_ SAM config file. I shouldn't need one—everything is being passed on the command line. Furthermore, as I mentioned, it worked fine before.

**Comment by GavinZZ** [comment]
Unfortunately I'm unable to reproduce the issue you described. Here is my full log. I used the same template you provided, except updating the `CodeUri` to point to my own s3 bucket URI. 

Here is the template I used:
```
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Description:
  Foo service.

Parameters:
  Env:
    Description: The token identifying the deployment environment, such as "dev", "dev3", or "dev-jdoe".
    Type: String
    AllowedPattern: '\w[\w-]*'
    ConstraintDescription: The development environment identifier must only use word characters and dashes.

Globals:
  Function:
    Runtime: java17
    Architectures: [x86_64]
    MemorySize: 800
    Timeout: 4 #4 s

Resources:
  LambdaHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "foo-${Env}-LambdaHandler"
      CodeUri: !Sub s3://deployment-bucket-${Env}-name-123/helloworld.app.zip # I changed this to point to my own bucket
      Handler: com.example.LambdaHandler::handleRequest
```

Here is the log of my deployment process:
```
➜  SAMPlayGround sam --version      
SAM CLI, version 1.97.0 # note that I am also on latest version


➜  SAMPlayGround sam build    
The resource AWS::Serverless::Function 'LambdaHandler' has specified S3 location for CodeUri. It will not be built and SAM CLI does not support invoking it locally.                                                  

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Validate SAM template: sam validate
[*] Invoke Function: sam local invoke
[*] Test Function in the Cloud: sam sync --stack-name {{stack-name}} --watch
[*] Deploy: sam deploy --guided
➜  SAMPlayGround sam deploy --guided

Configuring SAM deploy
======================

        Looking for config file [samconfig.toml] :  Found
        Reading default arguments  :  Success

        Setting default arguments for 'sam deploy'
        =========================================
        Stack Name [reprofailedtemplatewithcodeuri]: reprofailedcustomertemplate
        AWS Region [us-west-2]: 
        Parameter Env [random]: 
        #Shows you resources changes to be deployed and require a 'Y' to initiate deploy
        Confirm changes before deploy [y/N]: 
        #SAM needs permission to be able to create roles to connect to the resources in your template
        Allow SAM CLI IAM role creation [Y/n]: 
        #Preserves the state of previously provisioned resources when an operation fails
        Disable rollback [y/N]: 
The resource AWS::Serverless::Function 'LambdaHandler' has specified S3 location for CodeUri. It will not be built and SAM CLI does not support invoking it locally.                                                  
        Save arguments to configuration file [Y/n]: 
        SAM configuration file [samconfig.toml]: 
        SAM configuration environment [default]: 

        Looking for resources needed for deployment:

        Managed S3 bucket: aws-sam-cli-managed-default-samclisourcebucket-6wfg4pcf3im2
        A different default S3 bucket can be set in samconfig.toml and auto resolution of buckets turned off by setting resolve_s3=False

        Saved arguments to config file
        Running 'sam deploy' for future deployments will use the parameters saved above.
        The above parameters can be changed by modifying samconfig.toml
        Learn more about samconfig.toml syntax at 
        https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html


        Deploying with following values
        ===============================
        Stack name                   : reprofailedcustomertemplate
        Region                       : us-west-2
        Confirm changeset            : False
        Disable rollback             : False
        Deployment s3 bucket         : aws-sam-cli-managed-default-samclisourcebucket-6wfg4pcf3im2
        Capabilities                 : ["CAPABILITY_IAM"]
        Parameter overrides          : {"Env": "random"}
        Signing Profiles             : {}

Initiating deployment
=====================

        Uploading to reprofailedcustomertemplate/06b0a337a8379afbe58db2ced40be68b.template  866 / 866  (100.00%)


Waiting for changeset to be created..

CloudFormation stack changeset
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Operation                                            LogicalResourceId                                    ResourceType                                         Replacement                                        
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
+ Add                                                LambdaHandlerRole                                    AWS::IAM::Role                                       N/A                                                
+ Add                                                LambdaHandler                                        AWS::Lambda::Function                                N/A                                                
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Changeset created successfully. arn:aws:cloudformation:us-west-2:649563674902:changeSet/samcli-deploy1696017816/12d780de-3384-47df-8559-6dbb907343d8


2023-09-29 13:03:47 - Waiting for stack create/update to complete

CloudFormation events from stack operations (refresh every 5.0 seconds)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ResourceStatus                                       ResourceType                                         LogicalResourceId                                    ResourceStatusReason                               
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE_IN_PROGRESS                                   AWS::CloudFormation::Stack                           reprofailedcustomertemplate                          User Initiated                                     
CREATE_IN_PROGRESS                                   AWS::IAM::Role                                       LambdaHandlerRole                                    -                                                  
CREATE_IN_PROGRESS                                   AWS::IAM::Role                                       LambdaHandlerRole                                    Resource creation Initiated                        
CREATE_COMPLETE                                      AWS::IAM::Role                                       LambdaHandlerRole                                    -                                                  
CREATE_IN_PROGRESS                                   AWS::Lambda::Function                                LambdaHandler                                        -                                                  
CREATE_IN_PROGRESS                                   AWS::Lambda::Function                                LambdaHandler                                        Resource creation Initiated                        
CREATE_COMPLETE                                      AWS::Lambda::Function                                LambdaHandler                                        -                                                  
CREATE_COMPLETE                                      AWS::CloudFormation::Stack                           reprofailedcustomertemplate                          -                                                  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Successfully created/updated stack - reprofailedcustomertemplate in us-west-2
```
