### ISSUE TITLE
Possible Issue with CloudFormation on conditions

### ISSUE THREAD

**Issue by georgettica** [aws/serverless-application-model#3364]
### Description

I have a cloudformation and I am using https://github.com/aws/serverless-application-model/raw/develop/samtranslator/validator/sam_schema/schema.json as the yaml lang server source
I am getting a purely linting error:
```
Incorrect type. Expected "object"
```

on my cloudformation although other fields are ok.

### Steps to reproduce

1- Use the Cloudformation with the section

```
# yaml-language-server: $schema=https://github.com/aws/serverless-application-model/raw/develop/samtranslator/validator/sam_schema/schema.json
# also read https://github.com/redhat-developer/vscode-yaml/issues/669 in order to make most of the warning disappear
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
   sam-cloudformation-template
Parameters:
  foo:
    Type: String
Conditions:
  IsBar: !Equals
    - !Ref foo
    - bar
 ```

### Observed result

```
Incorrect type. Expected "object"
```

### Expected result

that the cloudformation will be valid

### Additional environment details

1. OS: N/A
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: N/A
3. AWS region: us-east-1
4. vscode version: 1.82.3
5. yaml plugin verision: v1.14.0
