### ISSUE TITLE
Sam Deploy Fails When Using Multiple Api Authorization Override Endpoints  (yet, a single one succeeds)

### ISSUE THREAD

**Issue by bmckinle** [aws/serverless-application-model#3366]
### Description
OverrideApiAuth with cognito authorizer per lambda event endpoint fails on sam deploy with an esoteric error when using more than one or other than one GET event.

### Steps to reproduce
Using the following template.yaml (sam) section for one (GET) endpoint, per [@GavinZZ's suggestion],(https://github.com/aws/serverless-application-model/issues/3356) allows resolving a cognito endpoint authorization issue. A sam deploy succeeds and authorization honored and visible on console.  i.e., Positive and negative tests work for cognito token and no valid cognito token, respectively.

```
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        CreateEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref "SlaterApiGateway"
            Path: /resource
            Method: POST
            Auth: 
               Authorizer: CognitoAuthorizer  # defined via AWS::Cognito::UserPool elsewhere in template.yaml
               OverrideApiAuth: true  # new property we introduced to fix no cognito security on each endpoint
```

But, using the same section for multiple GET, POST, PUT, etc endpoints leads to the following sam deploy error.

### Observed result
```Waiting for changeset to be created..
Error: Failed to create changeset for the stack: slater-stack, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Structure of the SAM template is invalid. Value of '/ipsanddnsnames' path must be a dictionary according to Swagger spec.
So we can make one endpoint work, but multiple endpoints across different methods do not. We validate all yaml and use sam validate on openapi_bundled.yaml. We are trying just GETters with two and then more incrementally to see if we can isolate the problem. Can you suggest how we can scale the single-endpoint-working solution up to an arbitrary number of endpoints (uri/methods) across a large API? 
```

### Expected result
Successful sam deploy with cognito authorizer assigned to each endpoint on the console.  Both positive and negative cognito tests, as described earlier, demonstrate endpoints are secured.

### Additional environment details

1. OS: Linux
2. SAM CLI, version 1.91.0
3. AWS region: us-east-1

**Comment by bmckinle** [comment]
@GavinZZ I'm reviewing your working code in the referring issue](https://github.com/aws/serverless-application-model/issues/3356) to see if it is possible to adapt it to our approach.  Two notable differences are:

1. template.yaml's use of  x-amazon-apigateway-integration in AWS::Serverless::Api Paths occurs in openapi_bundled.yaml in our coding approach; and
2. MyLambdaRequestAuth does not appear in our Auth section in AWS::Serverless::Api. <== This is of particular interest.

**Comment by bmckinle** [comment]
@GavinZZ The following openapi_bundled.yaml defines our authorizer.  Note that the corresponding template.yaml does not contain two sections in the Authorizers section in the api gateway definition, namely, MyLambdaRequestAuth and DefaultAuthorizer.

openapi_bundled.yaml:
```
...
components:
  securitySchemes:
    slater-auth1:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
      x-amazon-apigateway-authorizer:
        providerARNs:
          - Fn::GetAtt: [ UserPool, Arn ]
        type: "cognito_user_pools"
```

template.yaml:
```
  ...
  SlaterApiGateway:
    DependsOn: UserPool
    Type: AWS::Serverless::Api
    Properties:
      StageName: !FindInMap [Accounts, !Ref "AWS::AccountId", StageName]
      DefinitionBody:
        Transform:
          Name: LargeInclude
          Parameters:
            BucketPrefix: "prsn-code-artifacts-us-east-1-"
            Key: "slater/temporary_openapi/openapi_bundled.yaml"
      EndpointConfiguration: REGIONAL
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt "UserPool.Arn"
# This is referenced (defined) in openapi_bundled.yaml but only with function arn and nothing else (see openapi_bundled.yaml snippet above)
#          MyLambdaRequestAuth:  
#            FunctionPayloadType: REQUEST
#            FunctionArn:
#              Fn::GetAtt: MyLambdaAuthFunction.Arn
#            Identity:  # we don't have this
#              QueryStrings:
#                - authorization
#          DefaultAuthorizer: MyLambdaRequestAuth. # we dont have this
      BinaryMediaTypes:
        - multipart/form-data
 ...
      Events:
        GetAccountsApi:
          Type: Api
          Properties:
            RestApiId: !Ref "SlaterApiGateway"
            Path: /accounts
            Method: GET
            Auth:
               Authorizer: CognitoAuthorizer
                OverrideApiAuth: true  # new property we introduced to fix no cognito security on each endpoint
         ...70+ other GET, POST, DELETE, etc other endpoint defintions
```
