### ISSUE TITLE
ARN SESBulkTemplatedCrudPolicy_v2 is not valid policy

### ISSUE THREAD

**Issue by akksa** [aws/serverless-application-model#3375]
### Description
When I am attaching the policy SESBulkTemplatedCrudPolicy_v2 to send email from the lambda function, AWS sam fails to deploy this and throws the following error.

ARN SESBulkTemplatedCrudPolicy_v2 
is not valid. (Service:           
AmazonIdentityManagement; Status  Code: 400; 
Error Code:InvalidInput; 
Request ID: 9da1d05 f-fd8e-4ba2-9e29-56b850ec14d2;    
Proxy: null)  

Just add the policy SESBulkTemplatedCrudPolicy_v2 the template.yaml and build and deploy.
and it failed to deploy the SAM model

### Expected result
It should get deployed and should be able to send email from lambda.

### Additional environment details

1. OS: Ubuntu 22.04
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: SAM CLI, version 1.97.0
3. AWS region: us-east-1a

Please let me know if any more details needed.

**Comment by aaythapa** [comment]
Hi @akksa, thanks for reporting this. Do you have a template that I could use to re-produce the issue?

**Comment by sidhujus** [comment]
Hi @akksa I was able to reproduce your error using this template 

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

Resources:
  OnePolicyTemplate:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: bar
      Handler: hello.handler
      Runtime: python3.9
      Policies: SESBulkTemplatedCrudPolicy_v2
```

The issue with the above template is that the `SESBulkTemplatedCrudPolicy_v2` is being passed a string but per https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html when using a SAM policy template it needs to be an object with the required keys, or empty if there are none.

To fix the issue above adding the two required parameters `identityName` and `templateName` should fix the issue

Working example
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

Resources:
  OnePolicyTemplate:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: bar
      Handler: hello.handler
      Runtime: python3.9
      Policies:
        SESBulkTemplatedCrudPolicy_v2:
          IdentityName: name
          TemplateName: template_name
```

Closing for now, please re-open if the issue isn't fixed.
