### ISSUE TITLE
Invalid permissions on Lambda function

### ISSUE THREAD

**Issue by nowtryz** [aws/serverless-application-model#3393]
### Description

When creating a SAM stack with a custom API, which is required to configure the CORS setting of the gateway, the permission generated for lambda integrations (`AWS::Serverless::Function`) uses the logical id of the custom gateway instead of its real id. As a consequence, the integration cannot be called by the gateway.

### Steps to reproduce

Deploy the following template
```yaml
Resources:
  CustomAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.lambda_handler
      InlineCode: >
        def lambda_handler(_, __):
            return {
                "statusCode": 200,
                "body": "hello world",
            }
      Runtime: python3.11
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: CustomAPI
            Path: /hello
            Method: get
```

### Observed result

On the lambda permissions I see the condition ARN :
```
{
 "ArnLike": {
  "AWS:SourceArn": "arn:aws:execute-api:us-east-1:{account id}:CustomAPI/*/GET/hello"
 }
}
```
Whereas, from what I understand going through the [documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/arn-format-reference.html#apigateway-execute-api-arns), I should get the following:
```
{
 "ArnLike": {
  "AWS:SourceArn": "arn:aws:execute-api:us-east-1:{account id}:49hnwkgcp9/*/GET/hello"
 }
}
```
Where `49hnwkgcp9` is the ID of the deployed gateway (created for the purpose of this issue, deleted since)

#### Current workaround
At first, I thought it was a duplicate of #59, so I used the solution from @uclaeagit's [comment](https://github.com/aws/serverless-application-model/issues/59#issuecomment-532031247), which solved the issue by adding a custom permission to the lambda:
```yaml
  HelloWorldFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref HelloWorldFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${CustomAPI}/*/GET/hello
```

#### /hello - GET method test results (testing the integration through API Gateway console)
| Request | Latency   | Status |
|-|-|-|
| `/hello` | 21 | 500 |

##### Response body
```
{"message": "Internal server error"}
```

#####  Response headers
```
{
  "x-amzn-ErrorType": "InternalServerErrorException"
}
```

##### Log
```
Execution log for request c929fde4-f5b6-4c0d-9f14-d7d3516f21f2
Sun Oct 29 18:51:06 UTC 2023 : Starting execution for request: c929fde4-f5b6-4c0d-9f14-d7d3516f21f2
Sun Oct 29 18:51:06 UTC 2023 : HTTP Method: GET, Resource Path: /hello
Sun Oct 29 18:51:06 UTC 2023 : Method request path: {}
Sun Oct 29 18:51:06 UTC 2023 : Method request query string: {}
Sun Oct 29 18:51:06 UTC 2023 : Method request headers: {}
Sun Oct 29 18:51:06 UTC 2023 : Method request body before transformations: 
Sun Oct 29 18:51:06 UTC 2023 : Endpoint request URI: https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/arn:aws:lambda:us-east-1:611600784962:function:sam-issue-HelloWorldFunction-xS8OsmWWS0LO/invocations
Sun Oct 29 18:51:06 UTC 2023 : Endpoint request headers: {X-Amz-Date=20231029T185106Z, x-amzn-apigateway-api-id=49hnwkgcp9, Accept=application/json, User-Agent=AmazonAPIGateway_49hnwkgcp9, Host=lambda.us-east-1.amazonaws.com, X-Amz-Content-Sha256=b4840eb6275636dc74218c1c22baefdf51e7c73fc2a41ffcf6199dc38d0d3571, X-Amzn-Trace-Id=Root=1-653ea99a-d20bba9c7fc7c4ebe93c7766, x-amzn-lambda-integration-tag=c929fde4-f5b6-4c0d-9f14-d7d3516f21f2, Authorization=*********************************************************************************************************************************************************************************************************************************************************************************************************************************************c7cfc2, X-Amz-Source-Arn=arn:aws:execute-api:us-east-1:611600784962:49hnwkgcp9/test-invoke-stage/GET/hello, X-Amz-Security-Token=******************* [TRUNCATED]
Sun Oct 29 18:51:06 UTC 2023 : Endpoint request body after transformations: {"resource":"/hello","path":"/hello","httpMethod":"GET","headers":null,"multiValueHeaders":null,"queryStringParameters":null,"multiValueQueryStringParameters":null,"pathParameters":null,"stageVariables":null,"requestContext":{"resourceId":"dw2180","resourcePath":"/hello","httpMethod":"GET","extendedRequestId":"Nk9wIGFMoAMFtEw=","requestTime":"29/Oct/2023:18:51:06 +0000","path":"/hello","accountId":"*****************","protocol":"HTTP/1.1","stage":"test-invoke-stage","domainPrefix":"testPrefix","requestTimeEpoch":1698605466154,"requestId":"c929fde4-f5b6-4c0d-9f14-d7d3516f21f2","identity":{"cognitoIdentityPoolId":null,"cognitoIdentityId":null,"apiKey":"test-invoke-api-key","principalOrgId":null,"cognitoAuthenticationType":null,"userArn":"******************************","apiKeyId":"test-invoke-api-key-id","userAgent":"****** [TRUNCATED]
Sun Oct 29 18:51:06 UTC 2023 : Sending request to https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/arn:aws:lambda:us-east-1:611600784962:function:sam-issue-HelloWorldFunction-xS8OsmWWS0LO/invocations
Sun Oct 29 18:51:06 UTC 2023 : Execution failed due to configuration error: Invalid permissions on Lambda function
Sun Oct 29 18:51:06 UTC 2023 : Method completed with status: 500
```
> **Note the line:** `Execution failed due to configuration error: Invalid permissions on Lambda function`

### Expected result

The SAM should generate a valid lambda permission (`<function-logical-id><api-name>Permission<stage-name>` as per #70) for the gateway with its real arn.

### Additional environment details

1. OS: Windows 10
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: SAM CLI, version 1.99.0
3. AWS region: experienced on eu-west-3 and us-east-1
