### ISSUE TITLE
Error: The template contains unsupported resource types. [AWS::Lambda::Url]

### ISSUE THREAD

**Issue by nicolasochem** [aws/serverless-application-model#3402]
Hi,
I'm trying to publish to SAR.

I have the following resources:

```
  Signer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: signer/
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Role: !GetAtt ConsensusSignerRole.Arn
      Environment:
        Variables:
          BAKER_AUTHORIZED_KEY: !Ref BakerAuthorizedKey
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
          KMS_KEY_ID: !GetAtt TezosConsensusKey.Arn
          CONSENSUS_PUBLIC_KEY: !GetAtt SignerLambdaEnv.publicKey
          CONSENSUS_PUBLIC_KEY_HASH: !GetAtt SignerLambdaEnv.publicKeyHash
          SECRET_URL_PATH: !GetAtt SignerLambdaEnv.randomString

  SignerUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt Signer.Arn

  SignerUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunctionUrl
      FunctionName: !Ref Signer
      Principal: "*"
      FunctionUrlAuthType: NONE
```

and the following output:

```
Outputs:
  SignerURL:
    Description: "Signer Secret URL"
    Value: !Sub "${SignerUrl.FunctionUrl}${SignerLambdaEnv.randomString}"
```

The package works, but when I try to publish it, it fails with: `Error: The template contains unsupported resource types. [AWS::Lambda::Url]`

I can work around the issue by removing the SignerUrl, but then I can't get it as output:

```
 # SignerUrl:
  #   Type: AWS::Lambda::Url
  #   Properties:
  #     AuthType: NONE
  #     TargetFunctionArn: !GetAtt Signer.Arn

  SignerUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunctionUrl
      FunctionName: !Ref Signer
      Principal: "*"
      FunctionUrlAuthType: NONE

Outputs:
  # SignerURL:
  #   Description: "Signer Secret URL"
  #   Value: !Sub "${SignerUrl.FunctionUrl}${SignerLambdaEnv.randomString}"
  SignerURLPath:
    Description: "Signer Secret URL path (get the URL from lambda console)"
    Value: !GetAtt SignerLambdaEnv.randomString
```

Indeed, `AWS::Lambda::Url` is not in the supported AWS resource list:

https://docs.aws.amazon.com/serverlessrepo/latest/devguide/list-supported-resources.html

I don't see a problem with adding it to the supported resources list, since it's already possible to create a URL, just impossible to get it as output.

The doc says to open a support ticket, but I can't, so I am opening an issue here. Thanks in advance!
