### ISSUE TITLE
Cannot publish app with SSMParameterWithSlashPrefixReadPolicy policy

### ISSUE THREAD

**Issue by kamilturek** [aws/serverless-application-model#3412]
### Description
When trying to publish a SAM application with the `SSMParameterWithSlashPrefixReadPolicy` policy to Serverless Application Repository (SAR), an error is raised saying that the policy is invalid.

```
Error: Invalid Serverless Application Specification document. Number of errors found: 1. Errors: Resource with id [HelloWorldFunction] is invalid. Policy at index 0 in the 'Policies' property is not valid
Please follow the instructions in https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-applications.html
```

The application can be built and deployed successfully. The permission works correctly. It's only publishing to SAR that fails.

### Steps to reproduce
1. Initialize SAM application (`sam init`).
2. Create a `template.yaml` file with such content:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Description: Test SAM App
    Name: test-sam-app
    Author: Developer
    ReadmeUrl: README.md
    SemanticVersion: 0.1.0

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName: /test/parameter
```
3. Run `sam package`.
```sh
sam package --output-template-file packaged.yaml
```
4. Run `sam publish`.
```sh
sam publish --template packaged.yaml
``` 

### Observed result
```sh
$ sam publish --template packaged.yaml
Publish Failed
Error: Invalid Serverless Application Specification document. Number of errors found: 1. Errors: Resource with id [HelloWorldFunction] is invalid. Policy at index 0 in the 'Policies' property is not valid
Please follow the instructions in https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-applications.html
```

### Expected result
The application should be successfully published.

### Additional environment details

1. OS: macOS 14.0
5. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: 1.95.0
6. AWS region: `eu-central-1`, `eu-west-1`
