### ISSUE TITLE
AutoPublishAlias not updating version when using FindInMap function in CodeUri.Key

### ISSUE THREAD

**Issue by smathez** [aws/serverless-application-model#3414]
### Description
The alias/version won't update when using  lambda code packaged as zip files stored on an S3 bucket, and use FindInMap function for CodeUri.Key. (For greater readability of our templates, the versions are defined in Mappings, and we refer to them using the FindInMap function.)

Example of template:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform:
    - AWS::Serverless-2016-10-31
Description: XXX
Mappings:
    Lambdas:
        authorizer:
            package: ecs-commons-lambda-authorizer-1.3.0
        mpf:
            package: ecs-mpf-lambda-1.2.4
...
Globals:
    Function:
        Runtime: nodejs18.x
        AutoPublishAlias: live
        Tracing: Active
        CodeUri:
            Bucket: !Ref lambdaS3Bucket
...
    MpfTriggerFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            CodeUri:
                Key: !FindInMap [Lambdas, mpf, package]
            FunctionName: 'xxx-eventTrigger'
            Events:
                MpfEvent:
                    Type: EventBridgeRule
                    Properties:
                        EventBusName: eventBusXXX
                        Pattern:
                            detail-type:
                                - prefix: 'XXX/'
```

If I change the package in the mapping, lambda function is updated but not my alias/version, so the event rule is always pointing to the previous version :
```
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Operation                               LogicalResourceId                       ResourceType                            Replacement                           
-------------------------------------------------------------------------------------------------------------------------------------------------------------
* Modify                                MpfTriggerFunctionRole                  AWS::IAM::Role                          False                                 
* Modify                                MpfTriggerFunction                      AWS::Lambda::Function                   False                                 
-------------------------------------------------------------------------------------------------------------------------------------------------------------
```

But if I don't use the mapping anymore and update the `CodeUri.Key `part like that, everything is working fine : 
```yaml
    MpfTriggerFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            CodeUri:
                Key: ecs-mpf-lambda-1.2.5
```

```
CloudFormation stack changeset
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Operation                               LogicalResourceId                       ResourceType                            Replacement                           
-------------------------------------------------------------------------------------------------------------------------------------------------------------
+ Add                                   MpfTriggerFunctionVersione5e43cd2e8     AWS::Lambda::Version                    N/A                                   
* Modify                                MpfTriggerFunctionAliaslive             AWS::Lambda::Alias                      False                                 
* Modify                                MpfTriggerFunction                      AWS::Lambda::Function                   False                                 
- Delete                                MpfTriggerFunctionVersion5a618a3a55     AWS::Lambda::Version                    N/A                                   
-------------------------------------------------------------------------------------------------------------------------------------------------------------
```

### Additional environment details

1. OS: Linux
2. SAM CLI 1.101.0
3. AWS region: eu-west-1
