### ISSUE TITLE
Feature Request: Add SQS Redrive option to SNS event

### ISSUE THREAD

**Issue by conao3** [aws/serverless-application-model#3444]
#854 makes it easy to build SNS->SQS->Lambda configurations.

When I looked at the documentation, it was not clear whether the RedrivePolicy was for SNS or SQS.
From the actual behavior, I can guess that this seems to be a RedrivePolicy for SNS.

The failure of the SNS->SQS integration does not need to be taken into account by the average user, and in fact, a Redrive due to an error in the SQS->Lambda integration is required.

Perhaps adding a new key like SqsRedrivePolicy or instructing SAM to automatically create the required SQS when specifying an object in SqsSubscription, like the traditional true, would fulfill the requirement.

## Option1: Adding `SqsRedrivePolicy`

```yaml
Type: SNS
Properties:
  Topic: arn:aws:sns:us-east-1:123456789012:my_topic
  SqsSubscription: true
  RedrivePolicy:
    deadLetterTargetArn: !GetAtt QueueSNSDlq.Arn
  SqsRedrivePolicy:  # <----- New key for SQS redrive policy
    deadLetterTargetArn: !GetAtt QueueFunctionDlq.Arn
    maxReceiveCount: 1
```

Using this option requires validation of the reciprocal relationship that `SqsSubscription` must be specified when using `SqsRedrivePolicy`.

## Option2: Support `RedrivePolicy` on `SqsSubscriptionObject`

```yaml
Type: SNS
Properties:
  Topic: arn:aws:sns:us-east-1:123456789012:my_topic
  RedrivePolicy:
    deadLetterTargetArn: !GetAtt QueueSNSDlq.Arn
  SqsSubscription:
    QueueArn: !Ref TopicFunction
    RedrivePolicy:  # <----- New key for SQS redrive policy
      deadLetterTargetArn: !GetAtt QueueFunctionDlq.Arn
      maxReceiveCount: 1
```

Using this option requires the SQS to be explicitly created by the user.
(This is a potential issue to be resolved by a separate feature request).

**Comment by conao3** [comment]
Related Documents:
- [AWS::Serverless::Function](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html)
  - [EventSource](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-eventsource.html) / [SNS](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-sns.html)
    - [SqsSubscriptionObject](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-sqssubscriptionobject.html)

**Comment by ConnorRobertson** [comment]
Hello @conao3 
If you need to have custom properties (i.e. RedrivePolicy, VisibilityTimeout, etc) set on the SNS->SQS->Lambda generated `AWS::SQS::Queue` please define a custom SQS Queue. Then in the 'SNS' Event on the `AWS::Serverless::Function` reference the `AWS::SQS::Queue` in the `SqsSubscription:` like below. Please respond if you have any questions, or if this does not work for what you are trying to do. 
```
Resources:
  Topic:
    Type: AWS::SNS::Topic

  MyFunctionTopicEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy: 
        deadLetterTargetArn: 
          Fn::GetAtt: 
            - "MyDeadLetterQueue"
            - "Arn"
        maxReceiveCount: 5

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucket/key
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 60
      Events:
        TopicEvent:
          Type: SNS
          Properties:
            Topic: !Ref Topic
            RedrivePolicy:
                deadLetterTargetArn: !GetAtt QueueSNSDlq.Arn
            SqsSubscription:
              QueueArn: 
                Fn::GetAtt: 
                  - MyFunctionTopicEventQueue
                  - "Arn"
              QueueUrl: !Ref MyFunctionTopicEventQueue
```
