### ISSUE TITLE
Set Visibility timeout of the SQS with reference to the timeout of the function

### ISSUE THREAD

**Issue by conao3** [aws/serverless-application-model#3445]
### Description

I deploy SNS->SQS->Lambda configuration by `SqsSubscription: true`.

The SQS automatically created by this specification is deployed with an empty configuration, so the visibility timeout is fixed at 30 seconds, regardless of the timeout of the associated function.

Therefore, if the function timeout is longer than 30 seconds, the deploy will fail due to Cloudformation validation.
We probably need to set the SQS visibility timeout to the same number of seconds as the function timeout.

### Steps to reproduce

```yaml
FunctionAnalysisFailedA1:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: AnalysisFailedA1
    Handler: src.main.analysis_failed.handler
    Timeout: 90
    Events:
      SNS:
        Type: SNS
        Properties:
          Topic: !Ref RuntimeTopicNotificationArn
          SqsSubscription: true
```

### Observed result

Deploy failed with below error.
```
Resource handler returned message: "Invalid request provided: Queue visibility timeout: 30 seconds is less than Function timeout: 90 seconds (Service: Lambda, Status Code: 400, Request ID: xxx)" (RequestToken: xxx, HandlerErrorCode: InvalidRequest)
```

### Expected result

Deploy succeeded without any errors.

### Additional environment details

1. OS: macOS
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: `SAM CLI, version 1.103.0`
3. AWS region: `ap-northeast-1`

**Comment by ConnorRobertson** [comment]
Hello, @conao3 
This issue was brought up [here.](https://github.com/aws/serverless-application-model/issues/1424#issuecomment-965532841)
Essentially, the way to workaround this is to not use `SqsSubscription: true` and instead create your own `AWS::SQS::Queue` if you want custom options.

Here is an example,
```
Resources:
  Topic:
    Type: AWS::SNS::Topic

  MyFunctionTopicEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucket/key
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 60
      Events:
        TopicEvent:
          Type: SNS
          Properties:
            Topic: !Ref Topic
            SqsSubscription:
              QueueArn: 
                Fn::GetAtt: 
                  - MyFunctionTopicEventQueue
                  - "Arn"
              QueueUrl: !Ref MyFunctionTopicEventQueue
```

The reason that the SQS `VisibilityTimeout:` cannot be automatically set to the Function timeout automatically is that this is a breaking change to some customers potentially. If you read the thread below the comment I linked, then more detail is given about why we cannot implement that fix.
