### ISSUE TITLE
`AWS::Serverless::Api` creates stage named `Stage` instead of requested stage name

### ISSUE THREAD

**Issue by garretwilson** [aws/serverless-application-model#3447]
I have a SAM template similar to the following, for a catch-all REST API with proxy to an AWS Lambda function:

```yaml
  MessageServiceRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api

  MessageServiceRest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: …
      Handler: …
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MessageServiceRestApi
            Path: '/{proxy+}'
            Method: ANY
```

I explicitly define a REST API with a stage name of `api`, and I reference that REST API resource from my cloud function event. Thus I expect to have a single stage named `api`.

However I wind up with two catch-all stages, `Stage` and `api`. Where did the `Stage` stage come from?

Looking at the processed template, I see this:

```json
    "MessageServiceRestApiDeploymentxxxxxxxxxx": {
      "Type": "AWS::ApiGateway::Deployment",
      "Properties": {
        "Description": "RestApi deployment id: …",
        "RestApiId": {
          "Ref": "MessageServiceRestApi"
        },
        "StageName": "Stage"
      }
    },
```

Apparently SAM is creating a REST API deployment for stage named `Stage`. But why? There is nothing in my SAM template that would indicate a stage named `Stage`. Furthermore there is a reference to a stage named `api`, which I did indicate, but _there is no `AWS::ApiGateway::Deployment` for it_. And finally I note that by default (if I don't explicitly specify a `AWS::Serverless::Api`), if I remember correctly, there is no stage named `Stage`, but two stages named `Test` and `Prod` or some such.

My hunch is that there is a bug in SAM in which there is a variable named `Stage` which is being set to `aws`, because that's the stage name I specified; but the variable _name_ (here `Stage`) is being used instead of the variable _value_—e.g. assuming one of the Python string interpolation formats is being used, it should be `$Stage` or `{Stage}`.

**Comment by garretwilson** [comment]
Note also that the `AWS::ApiGateway::Stage` it creates for `api` is pointing to the `Stage` deployment:

```json
    "MessageServiceRestApiapiStage": {
      "Type": "AWS::ApiGateway::Stage",
      "Properties": {
        "DeploymentId": {
          "Ref": "MessageServiceRestApiDeploymentxxxxxxxxxx"
        },
        "RestApiId": {
          "Ref": "MessageServiceRestApi"
        },
        "StageName": "api"
      }
```

I tried to get around this by creating my own deployment for `api`:

```yaml
  MessageServiceRestApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref MessageServiceRestApi
      StageName: api
```

But this results in a "Stage already exists" error. So I tried to create both a stage and a deployment with name `api`, hoping that SAM would not create its `AWS::ApiGateway::Stage` with that name if I create my own:

```yaml
  MessageServiceRestApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref MessageServiceRestApi
      StageName: api

  MessageServiceRestApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: api
      Description: TODO
      RestApiId: !Ref MessageServiceRestApi
      DeploymentId: !Ref MessageServiceRestApiDeployment
```

But no luck—I still get a "Stage already exists" error, and now SAM is adding a duplicate `AWS::ApiGateway::Stage` with the name `aws`.
