### ISSUE TITLE
Using Variables in External Swaggers File Breaks Deployment

### ISSUE THREAD

**Issue by andrewryan1906** [aws/serverless-application-model#345]
I've been using the examples to try and deploy with CloudFormation and kept getting an "Invalid ARN Found" message. I realized that the problem was that I had to use **DefinitionBody** and do an **AWS::Include** to inline my swagger file, vs use it externally.

This works.

But my problem now is, my swagger file has to be sitting up on S3 for me the CloudFormation stack to work. My Swagger file is part of my project and I'd like it to get built & deployment when I run aws cloudformation package/deploy commands.

So what's the best way to do this? How can I use inline Swagger (so I get the ARN variables) but also get CloudFormation to automatically deploy the file to S3 fo me?

**Comment by andrewryan1906** [comment]
Just a follow up.

I can use **DefinitionBoyd** to reference an external Swagger file, but if I do, I lose the CloudFormation transformation variables and I have to hardcode the ARN of my labmdas into my Swagger. This would mean I would need to manually create all of my lambda functions first, before I could use a SAM script, which is obviously less than ideal.

But I just realized that sam-local freaks out when I try to start it up and my SAM template is referencing a swagger file inline with DefinitionBody; so that really now is pushing me to use an external swagger file.

So my updated question is; how can I use an external swagger file and reference it with DefinitionUri, but **not have to reference to my lambda function's ARN explicitly - and thus still get the dynamic creation of lambda functions on deploy?**

**Comment by xdissent** [comment]
You can reference stage variables in the api integration uri:
```yaml
# main template
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: api.yml
      Variables:
        MyFn: !Ref MyFn
  MyFn:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        Api:
          Type: Api
          Properties:
            Path: /my-fn
            Method: GET
            RestApiId: !Ref Api
```

```yaml
# swagger
paths:
  /my-fn:
    get:
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:00000000:function:${stageVariables.MyFn}/invocations
```
You still have to hardcode the region and account ID, but at least you don't have to know the fn arn ahead of time.
