### ISSUE TITLE
Please explain how to version AWS::Serverless::Function artifacts cleanly

### ISSUE THREAD

**Issue by jkellyinsf** [aws/serverless-application-model#3489]
### Description
I'm trying to use sam build ; sam deploy to push up lambdas in a local JAR file, which like every other JAR file in the world has a version number in its path, which I'm trying to stitch in with !Sub.  Sam or something downstream is complaining that 'CodeUri' is not a valid S3 Uri of the form 's3://bucket/key' with optional versionId query parameter.

I've followed the hypnotic _telanovela_ of [5249](https://github.com/aws/aws-sam-cli/issues/5249) and similar issues.  I'm rooting for @garretwilson.  I agree with him this is a basic flow, and I'm a bit dizzy from all the proposed workarounds.

It's 2024, and I'm hoping the SAM team has hatched a clean solution for us.  But in any case, could you please update the [AWS::Serverless::Function documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-codeuri) with a clear recommendation for handling version numbers?  Currently it says you can point to an S3 bucket or to a local artifact, which doesn't do justice to the problems and caveats.

**Comment by GavinZZ** [comment]
Hi @jkellyinsf, thanks for cutting an issue. `AWS::Serverless::Function` supports two ways of defining the `CodeUri` property (see [link](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-codeuri)). One simple way to define the versioning property is documented [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-functioncode.html). 

An example of `CodeUri` property with versioning is provided here:
```
FunctionCode:
  Bucket: mybucket-name
  Key: mykey-name
  Version: 121212
``` 

Going to mark this issue as closed. Feel free to re-open it if you have additional questions.

**Comment by jkellyinsf** [comment]
Thanks for the quick response, @GavinZZ.  I'm not using a version-enabled S3 bucket and desiring to point to a previous s3 version of an artifact.  

The artifact is on my local machine and has a version number in its filename.  I want to specify in CodeUri a local file path string with the version number interpolated dynamically using !Sub.  And I want sam deploy to sync the artifact to S3 as it does when the file path is a constant string.  But instead that gives errors that CodeUri is not a valid s3 path.  

I cannot re-open the issue.

**Comment by GavinZZ** [comment]
Re-opened the issue. Apologize that I misinterpret it. To address the issue you mentioned, there're two potential solutions.

One is to use the format I suggested but changed it to something like this
```
FunctionCode:
  Bucket: mybucket-name
  Key: !Sub 'foo-bar-functions-${Ver}.jar' # assuming Ver is a template parameter
```

Alternatively, you can use what's discussed in https://github.com/aws/aws-sam-cli/issues/5249. 
The SAM template still requires AWS::LanguageExtensions:
```
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Resources:
  TestIngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: !Sub "s3://my-sam-bucket/foo-bar-functions-${Ver}.jar"
```

Personally, I would recommend the first solution as it's cleaner and it doesn't require the use of an additional transform.

**Comment by jkellyinsf** [comment]
Both of those imply that I've previously copied the file up to s3 through some other means, right?

**Comment by GavinZZ** [comment]
If you're using a local file path and you want to apply version number to the files, i.e. you have two local files, namely `hello_world/foo_1.py` and `hello_world/foo_2.py`, what you can do is something like this.

```
Transform: AWS::Serverless-2016-10-31
Parameters:
  Ver:
    Type: String
    Default: '1'
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: !Sub 'foo_${Ver}.handler'
      Runtime: python3.8
      CodeUri: hello_world/
```

**Comment by GavinZZ** [comment]
In the second solution I mentioned above, you can instead point to a local file with `!Sub` intrinsics if that's what you need.

**Comment by jkellyinsf** [comment]
Version functions rather than artifacts?  That's an idea that's probably more feasible in python than it is in java.  Here's an example:
```
Parameters:
  Version:
    Type: String
    Default: "1.2.17"
  
MyLambdaFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: MyLambda
    CodeUri: !Sub "build/artifacts/my-service-${Version}.zip"
    Handler: org.me.MyLambdaImpl
    Runtime: java17
```

**Comment by GavinZZ** [comment]
Thanks for the template. Assuming this is your directory setup, see screenshot below 
<img width="430" alt="Screenshot 2024-01-02 at 12 54 00 PM" src="https://github.com/aws/serverless-application-model/assets/28763956/d2460bdc-fe58-42ff-9e0d-30ed1d0e4d4a">

This is how to point to a file with version number. 
```
Transform: AWS::Serverless-2016-10-31

Parameters:
  Ver:
    Type: String
    Default: '1'

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction/
      Handler: !Sub 'helloworld.App_${Ver}::handleRequest'
      Runtime: java8
      Architectures:
        - x86_64
      MemorySize: 512
```
