### ISSUE TITLE
Bug: Creates unnecessary AWSLambdaVPCAccessExecutionRole  role

### ISSUE THREAD

**Issue by fade2black** [aws/serverless-application-model#3502]
### Description:
SAM seems to add `AWSLambdaVPCAccessExecutionRole` simply because it detects the `VpcConfig` without checking the condition. 

### Steps to reproduce:

I create a simple hello-world lambda function as following:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  SecurityGroupIds:
    Type: String
    Default: ""
  SubnetIds:
    Type: String
    Default: ""

Conditions:
  AlwaysFalseCondition: !Equals 
    - "123"
    - "345"

Resources:
  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloWorld
      PackageType: Image
      Architectures:
        - x86_64
      MemorySize: 2048
      Timeout: 30
      VpcConfig:
        !If 
          - AlwaysFalseCondition
          -  
            SecurityGroupIds: !Split [ ",", !Ref SecurityGroupIds ] 
            SubnetIds: !Split [ ",", !Ref SubnetIds ] 
          - !Ref AWS::NoValue
    Metadata:
        DockerTag: mytag
        DockerContext: ./lib
        Dockerfile: Dockerfile
```

and deploy it as following
```bash
sam build
sam deploy --config-env dev --resolve-image-repos --no-confirm-changeset --no-fail-on-empty-changeset
```
### Observed result:

When it successfully finishes deployment I go to my lambda function and check `Configuration` -> `VPC`. There is no associated security group or subnet. However, when I check the created role it contains two AWS Managed Policies:
- AWSLambdaBasicExecutionRole
- AWSLambdaVPCAccessExecutionRole

### Expected result:
Because the condition under the `VpcConfig` section is always false, it does not associate the lambda with a subnet and a security group as expected. I also expect the sam not to add unnecessary permission `AWSLambdaVPCAccessExecutionRole` because I don't associate the lambda with any VPC. Nevertheless, it adds  `AWSLambdaVPCAccessExecutionRole`.

While the extra privilege does not harm in this particular case, the intention was to remove the `VpcConfig` property using `If` operator and hence prevent adding `VPC Access` privileges.

### Additional environment details:

1. OS: macOS,  Sonoma 14.2
2. `sam --version`: 1.105.0
3. Docker version: 24.0.7
4. AWS region: eu-central-1

### Project structure

🗂️`lib`
⚙︎`samconfig.toml`
❗️`template.yaml`

#### `Dockerfile`
```bash
FROM public.ecr.aws/lambda/ruby:3.2
RUN yum install -y amazon-linux-extras ruby-devel make gcc
COPY Gemfile handler.rb ./
ENV GEM_HOME=${LAMBDA_TASK_ROOT}
RUN bundle config without test development
RUN bundle install

CMD ["handler.Handler.process"]
```
#### Gemfile
```ruby
source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
gem 'net-sftp', '~> 2.1', '>= 2.1.2'
```

#### handler.rb
```ruby
class Handler
  @logger = Logger.new($stdout)

  class << self
    def process(event:, context:)
      log("Received payload: #{event}")
      log('Done.')
    end

    def log(str_info)
      @logger.info { str_info }
    end
  end
end
```

#### samconfig.toml
```toml
version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "hello-world"
s3_bucket = "mybucket124fe5" 
s3_prefix = "dev"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides=[
    "SecurityGroupIds=sg-12345678",
    "SubnetIds=subnet-12345678"
]
```
