### ISSUE TITLE
Api CORS issue with 500 status after setup Cognito authorizer

### ISSUE THREAD

**Issue by Robsonwd** [aws/serverless-application-model#3505]
### Description
I have CORS setup issues on my SAM application. My app after successful deployment, returns me 500 CORS error on requesting lambda from the browser.

### Steps to reproduce
1. Created `AWS::Serverless::Api`
```
Resources:  
  MyGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
      Name: !Sub 'MyGatewayApi-${env}'
      StageName: !Ref env
      # BinaryMediaTypes:
      #   - '*/*'
      Cors: "'*'"
      # Cors: 
      #   AllowMethods: "'*'"
      #   AllowHeaders: "'*'"
      #   AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref CognitoUserPoolArn
        ApiKeyRequired: false # Tried without that
        AddDefaultAuthorizerToCorsPreflight: false # Tried without that
        AddApiKeyRequiredToCorsPreflight: false # Tried without that
      Tags:
        project: !Ref AppName
        environment: !Ref env
```
Added Lambda function with Cognito authorization:

```
GenerateTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'GenerateToken-${env}'
      CodeUri: generate_token/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetToken:
          Type: Api
          Properties:
            Path: /token
            Method: GET
            RestApiId: !Ref MyGatewayApi
        # Options: # Uncommenting this one works, but then 2 requests hit lambda function with method OPTIONS and next with GET
        #   Type: Api 
        #   Properties:
        #     Path: /token
        #     Method: options
        #     RestApiId:
        #       Ref: MyGatewayApi
        #     Auth:
        #       OverrideApiAuth: true
        #       Authorizer: NONE
```
What lambda returns:
```
return {
                    'statusCode': 200,
                    'body': json.dumps({
                        'token': uuid_token
                    }),
                    'headers': {
                        'Access-Control-Allow-Origin': '*',
                        'Access-Control-Allow-Headers': 'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token',
                        'Access-Control-Allow-Methods': '*',
                        'Content-Type': 'application/json'
                    }
                }
```

### Observed result
always I'm getting 500 response with CORS:

```Access to fetch at 'https://[myAPIID].execute-api.us-west-2.amazonaws.com/dev/token' from origin 'localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.```

I tried also in many ways with commented options for API, commenting cors, `ApiKeyRequired`, `AddDefaultAuthorizerToCorsPreflight`, `AddApiKeyRequiredToCorsPreflight` but no effect.

The 500 ERROR is from the API Gateway layer - the request to `/token` doesn't invoke lambda at all cause I didn't see any logs in cloudwatch (but I see logs for example when I uncomment the options event on lambda and dealing with 2 events for 2 methods - no cors issues).

Curl response from options request
```
< HTTP/2 500
< content-type: application/json
< content-length: 36
< date: Mon, 22 Jan 2024 04:08:19 GMT
< x-amzn-requestid: 123123-60d6-462d-96dd-2e2232cc8310
< access-control-allow-origin: *
< x-amzn-errortype: InternalServerErrorException
< x-amz-apigw-id: 123123123id=
< x-cache: Error from cloudfront
< via: 1.1 123123.cloudfront.net (CloudFront)
< x-amz-cf-pop: WWW-P1123
< x-amz-cf-id: 123123-123123-123123==
<
* Connection #0 to host apiid.execute-api.us-west-2.amazonaws.com left intact
{"message": "Internal server error"}%
```

I'm considering trying to move to HttpApi or using Lambda Authorizer or dealing with options event(suboptimal), but saw many similar issues and I think it should work, especially for that kind of simple template. 

### Expected result
Requesting the `/token` endpoint should return the response from the lambda function with token.

### Additional environment details

1. OS: MacOS
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: Tried first on `1.95.0` , but also upgraded to `1.107.0`
3. AWS region: us-west-2

**Comment by GavinZZ** [comment]
Hi @Robsonwd, looking at your template your CORS setup generally looks right to me. I recommend making the below two changes and try again:
1. Add `AddDefaultAuthorizerToCorsPreflight: false` under `Auth` property of your API. This is important so that it doesn't add authorizer to your OPTIONS method.
2. Add `AlwaysDeploy: true` to your API property. This may be important as sometimes a small change in API doesn't get deployed. This property guarantees that it deploys the API.
```
MyGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
        ......
        AlwaysDeploy: true
```

Try to add these two changes in your template, deploy the stack, and try again. Let me know if it still doesn't work for you.


### Appendix: Full template that I tested and it worked

Here is the full template I used and guaranteed that it works:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: MyUserPool

  MyCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref MyCognitoUserPool
      ClientName: MyUserPoolClient

  MyGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
      StageName: dev
      Cors: "'*'"
      AlwaysDeploy: true
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt MyCognitoUserPool.Arn

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world_function
      Handler: hello_world/app.lambda_handler
      Runtime: python3.10
      Events:
        GetToken:
          Type: Api
          Properties:
            Path: /token
            Method: GET
            RestApiId: !Ref MyGatewayApi
```
In my lambda handler, I used the same as you provided:
```
# import requests
import json

def lambda_handler(event, context):
    return {
        'statusCode': 200,
        'body': json.dumps({
            'token': "11111"
        }),
        'headers': {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Headers': 'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token',
            'Access-Control-Allow-Methods': '*',
            'Content-Type': 'application/json'
        }
    }
```
