### ISSUE TITLE
Re-opening issue on CodeDeploy inconsistent state.

### ISSUE THREAD

**Issue by vinkris** [aws/serverless-application-model#351]
Referencing issue: https://github.com/awslabs/serverless-application-model/issues/291

@sanathkr @jarreds 

I was seeing this same issue, more than twice last week. 
Getting following errors when trying to deploy SAM stack using CF:

```
...
20:06:41 UTC-0700 | UPDATE_FAILED | AWS::Lambda::Alias | UserLogoutAliaslive | Already chained. Call unchain() to get rid of the previous chaining.
-- | -- | -- | -- | --
  | 20:03:48 UTC-0700 | UPDATE_FAILED | AWS::Lambda::Alias | UserReturnAliaslive | Already chained. Call unchain() to get rid of the previous chaining.
  | 20:03:29 UTC-0700 | UPDATE_FAILED | AWS::Lambda::Alias | DisconnectAliaslive | Already chained. Call unchain() to get rid of the previous chaining.
  | 19:38:09 UTC-0700 | UPDATE_FAILED | AWS::Lambda::Alias | KinesisScalingAliaslive | Resource update cancelled
19:38:06 UTC-0700 | UPDATE_FAILED | AWS::Lambda::Alias | AdminReturnAliaslive | A conflicting deployment is in progress
...

```
This doesn't happen all the time. However, once it reaches this state, new updates would not succeed anymore. Had to delete and recreate the stack. 

We have about 13 lambdas in the SAM template, with a global setting like this:

```

Globals:
  Function:
    Runtime: nodejs6.10
    MemorySize: 256
    Timeout: 10
    AutoPublishAlias: live
    DeploymentPreference:
      Type: AllAtOnce

AdminReturn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-${EnvName}-adminreturn
      CodeUri:
        Bucket: !Ref BootstrapS3Bucket
        Key: !Ref AzureADFunctionCodeS3Key
      Handler: handler.adminReturn
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref TenantsTable
        - KMSDecryptPolicy:
            KeyId: !Ref AzureADKMSKeyId
      VpcConfig:
        SubnetIds: 
          !Split
            - ','
            - 'Fn::If': [ GentooConsumer, !Sub "${AzureADFunctionSubnetsIds}", 'Fn::ImportValue': !Sub "${BaseVPCStackName}-${EnvName}-SubnetsPrivateAppIds"]
        SecurityGroupIds:
          !Split
            - ','
            - 'Fn::If': [ GentooConsumer, !Sub "${AzureADFunctionSecurityGroupIds}", 'Fn::ImportValue': !Sub "${BaseVPCStackName}-${EnvName}-AzureAdSG"]
      Environment:
        Variables:
          TENANTSTATE_TABLE: !Ref TenantsTable
          DEP_ENVIRONMENT: !Ref EnvName
          ESS_URL: !Ref AzureADESSUrl
          CLIENT_ID: !Ref AzureADMSClientId
          CLIENT_SECRET: !Ref AzureADMSClientSecret
      Events:
        Consent:
          Type: Api
          Properties:
            Path: /adminreturn
            Method: get
            RestApiId:
              !Ref AzureADSyncAPI

```

Did we find the root cause for this? Any help here would be appreciated. Thanks!
