### ISSUE TITLE
Can't reset BinaryMediaTypes to a default value for API Gateway REST API

### ISSUE THREAD

**Issue by polamayster** [aws/serverless-application-model#3511]
### Description

Can't reset/revert changes of API Gateway BinaryMediaTypes to default value after modification.

### Steps to reproduce

1st deploy: set `BinaryMediaTypes: [application~1octet-stream]` - works as expected
2nd deploy: both removing `BinaryMediaTypes` or setting `BinaryMediaTypes: []` do not work, previous value is still used/displayed in AWS Console API settings.

**Comment by aaythapa** [comment]
Hi @polamayster, thank you for reporting, I was able to recreate this issue with the following template.

```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: MyNewStageName

  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.8
      InlineCode: |
        import json
        def handler(event, context):
          return {'statusCode': 200, 'body': json.dumps('Hello World!')}
      Events:
        Get:
          Type: Api
          Properties:
            Path: /get
            Method: get
            RestApiId: !Ref MyApi

```
This isn't particularly a SAM issue and more of an issue with API gateway. To overwrite this you can use the [Mode](https://docs.aws.amazon.com/en_us/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-mode) property, which can be set to `overwrite`. The default is `merge` which is why you see the binary media setting persist even after the stack update. According to the API Gateway docs on the `Mode` property found [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html#cfn-apigateway-restapi-mode)

```
If you don't specify this property, a default value is chosen. For REST APIs created before March 29, 2021, the default is overwrite. For REST APIs created after March 29, 2021, the new API definition takes precedence, but any container types such as endpoint configurations and binary media types are merged with the existing API. 
```

Hope this helped, closing this issue for now, please re-open if the issue persists.
