### ISSUE TITLE
Environment variables not updated

### ISSUE THREAD

**Issue by fade2black** [aws/serverless-application-model#3547]
### Description
I have lambda function in my cloudformation yaml file 
```yaml
ExportFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyFunction
      PackageType: Image
      Architectures:
      - x86_64
      MemorySize: 2048
      Timeout: 60
      Environment:
        Variables:
          USER:   !Sub '{{resolve:secretsmanager:mysecret:SecretString:user}}'
          PASSWORD:   !Sub '{{resolve:secretsmanager:mysecret:SecretString:password}}'
```

### Steps to reproduce
I go and change values of `user` and `password` inside the `mysecret`.
Deployment of the lambda function is triggered by pushing to a Github repo which in turn triggers AWS Codepipeline.
I even tried to trigger the codepipeline manually by clicking on `Release change` from the dashboard.
### Observed result
I check Lambda's environment variables from the dashboard - nothing changes.

### Expected result
Values of lambda's env variables should be updated with new values in the secret. 

### Additional environment details

1. OS: MacOS
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: SAM CLI, version 1.105.0
3. AWS region: eu-central-1

**Comment by moelasmar** [comment]
As per [the CFN service docs for resolving Secrets Manager secrets](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-secretsmanager), you need to do a change to the resource that is referring to the secret manager secrets, so CFN detect the update, and update this resource

see the below paragraph as I quoted from the CFN docs
>Updating a secret in Secrets Manager doesn't automatically update the secret in CloudFormation. In order for CloudFormation to update a secretsmanager dynamic reference, you must perform a stack update that updates the resource containing the dynamic reference, either by updating the resource property that contains the secretsmanager dynamic reference, or updating another of the resource's properties.
For example, suppose in your template you specify the MasterPassword property of an [AWS::RDS::DBInstance](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html) resource to be a secretsmanager dynamic reference, and then create a stack from the template. You later update that secret's value in Secrets Manager, but don't update the AWS::RDS::DBInstance resource in your template. In this case, even if you perform a stack update, the secret value in the MasterPassword property isn't updated, and remains the previous secret value.

My suggestion is to add a dummy environment variable to your lambda function, and to change its value every time you have an update in your secrets, so when you trigger a stack deployment, the lambda function will get updated, and retrieve the new secret values.

```
ExportFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyFunction
      PackageType: Image
      Architectures:
      - x86_64
      MemorySize: 2048
      Timeout: 60
      Environment:
        Variables:
          DUMMY: 1
          USER:   !Sub '{{resolve:secretsmanager:mysecret:SecretString:user}}'
          PASSWORD:   !Sub '{{resolve:secretsmanager:mysecret:SecretString:password}}'
```
I tested this approach, and was working fine for me. I tried to change the Secrets values, and then increment the `DUMMY` environment variable value, and then deploy the updated template, and found the function environment variables got update with the new values.
