### ISSUE TITLE
!If not working on Serverless:Function handler

### ISSUE THREAD

**Issue by des-psl** [aws/serverless-application-model#3554]
### Description
I am trying to have a conditional (!If) on my lambda handler property to execute different logics depending of an env var

### Steps to reproduce
```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  NewRelicEnabled:
    Type: String
    Description: Enable New Relic integration.
    Default: true

Conditions:
  IsNewRelicEnabled: !Equals [!Ref NewRelicEnabled, true]

Globals:
  Function:
    Architectures:
      - arm64
    Handler: !If [IsNewRelicEnabled, test1.handler, test2.handler]

Resources:
  ImportFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: import-function
      CodeUri: application/functions/import/
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: true
        OutExtension:
          - .js=.mjs
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
        Banner:
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);
        External:
          - application/node_modules

 Outputs:
  Condition:
    Description: asdf
    Value: !If [IsNewRelicEnabled, test1.handler, test2.handler]
```

### Observed result
Global handlers variable is resolving to its false value (test2.handler), but at the Outputs, Condition is resolving to true (test1.handler)

### Expected result
Global handlers and Output Condition should both resolving to true (test1.handler)

### Additional environment details

1. OS: Mac
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`:
3. AWS region: eu-east-1
