### ISSUE TITLE
Sam build failed when trying to create a S3 Express One Zone bucket 

### ISSUE THREAD

**Issue by Luna-LHY** [aws/serverless-application-model#3556]
I'm trying to build a sam template that creates a S3 Express One Zone bucket. However, sam deploy failed with 
`Error: Failed to create changeset for the stack: sam-s3express-test, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [MyBucket] is invalid. Resource has incorrect Type; expected 'AWS::S3::Bucket', got 'AWS::S3Express::DirectoryBucket'
`
My sam version is  1.110.0 which is the latest one. It looks like SAM CLI doesn't support creating S3 Express One Zone bucket or did I miss anything in my template?

My template:
````
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
...
...
Resources:

  MyBucket:
    Type: AWS::S3Express::DirectoryBucket
    Properties:
      BucketName: !Ref VideosBucketName
      DataRedundancy: SingleAvailabilityZone
      LocationName: !Ref BucketAvailabilityZoneID
````
