### ISSUE TITLE
Unable to solve mapping for Timeout property

### ISSUE THREAD

**Issue by D-Jurado** [aws/serverless-application-model#3583]
### Description
I'm using a mapping function to set `Timeout` property for my `Type: AWS::Serverless::Function`, I'm not getting any error running `sam build` or `sam validate` but `sam local start-lambda` is throwing the following error: 

> `Lambda functions containers initialization failed because of Invalid Number for Timeout: OrderedDict([('Fn::FindInMap', ['common', 'LambdaFunction', 'Timeout'])])`

### Steps to reproduce
This is the portion of my Cloudformation file where I'm using the map to set Timeout property

``` yaml
Mappings:
  common:
    LambdaFunction:
      Timeout: 900

Resources:
  myFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: !FindInMap [common, LambdaFunction, Timeout]
```

### Observed result
Error log

> Lambda functions containers initialization failed because of Invalid Number for Timeout: OrderedDict([('Fn::FindInMap', ['common', 'LambdaFunction', 'Timeout'])])

### Expected result
Run lambda

### Additional environment details

1. OS: Windows 11
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: SAM CLI, version 1.115.0
3. AWS region: us-east-1
