### ISSUE TITLE
SAM Property FileSystemConfigs support in Globals

### ISSUE THREAD

**Issue by shehenshah14** [aws/serverless-application-model#3649]
AWS SAM lambda function property "FileSystemConfigs" is not supported in Globals section.
With huge product having many lambda functions within one infra template, this property support in Globals section would really be helpful.

Could we please consider this as enhancement.

**Comment by aaythapa** [comment]
Looks like FileSystemConfigs is already supported in the globals section [here](https://github.com/aws/serverless-application-model/blob/develop/samtranslator/plugins/globals/globals.py#L49).

I tested it with template and the transform showed no error when i ran `sam build`

```
Globals:
  Function:
    ...
    FileSystemConfigs:
      - Arn: !GetAtt AccessPoint.Arn
        LocalMountPath: /mnt/EFS

Resources:
  MinimalFunction:
    Type: AWS::Serverless::Function

```

Going to close this issue for now but feel free to re-open if needed
