### ISSUE TITLE
Feature: API Gateway Direct Resolvers (AppSync-style without VTL)

### ISSUE THREAD

**Issue by aleguern-azivko** [aws/serverless-application-model#3743]
# Feature Request: API Gateway Direct Resolvers (AppSync-style without VTL)

## Description
This PR proposes adding AppSync-style direct resolvers to SAM for API Gateway, allowing direct integration with AWS services without the need for Lambda functions or VTL templates.

## Problem Statement
Currently, connecting API Gateway to AWS services like DynamoDB requires:
1. Writing Lambda functions as "glue code"
2. Handling error cases, status codes, and response formatting in code
3. Managing additional Lambda configuration and permissions
4. Writing unnecessary boilerplate for simple CRUD operations

Example of unnecessary Lambda boilerplate:
```typescript
const getProduct = async (event: APIGatewayProxyEvent) => {
  try {
    const { id } = event.pathParameters

    const response = await docClient.send(
      new GetCommand({
        TableName: TABLE_NAME,
        Key: { id },
      }),
    );

    if (!response.Item) {
      return {
        statusCode: 404,
        headers: corsHeaders,
        body: JSON.stringify({ error: 'item_not_found' }),
      };
    }

    return {
      statusCode: 200,
      headers: corsHeaders,
      body: JSON.stringify(response.Item),
    };
  } catch (error) {
    console.error('Error:', error);
    return {
      statusCode: 500,
      headers: corsHeaders,
      body: JSON.stringify({ error: 'Internal Server Error' }),
    };
  }
};
```

## Proposed Solution
Add AppSync-style direct resolvers to SAM for API Gateway, allowing templates like:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GetProductResolver:
    Type: AWS::Serverless::Resolver
    Properties:
      Path: /products/{row}/{id}
      Method: GET
      DataSource:
        Type: AMAZON_DYNAMODB
        Config:
          TableName: !Ref ProductsTable
          ServiceRoleArn: !GetAtt DynamoDBResolverRole.Arn
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "GetItem",
          "key": {
            "row": $util.dynamodb.toDynamoDBJson($ctx.args.row),
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id)
          }
        }
      ResponseMappingTemplate: |
        #if($ctx.error)
          #return($util.toJson({"error": $ctx.error.message}))
        #end
        #if(!$ctx.result)
          #set($ctx.responseOverride.statusCode = 404)
          #return($util.toJson({"error": "item_not_found"}))
        #end
        $util.toJson($ctx.result)

  DynamoDBResolverRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
```

## Implementation Details

The implementation would closely mirror AppSync's resolver pattern:

1. **Data Sources**: Support for direct connections to:
   - DynamoDB
   - RDS Data API
   - OpenSearch
   - EventBridge
   - Step Functions
   - HTTP endpoints

2. **Request/Response Mapping**: 
   - Use a simplified version of AppSync's mapping templates
   - Provide $util helper functions mirroring AppSync's utilities
   - Support path parameters, query parameters, and request body mapping

3. **AppSync-Compatible Utility Library**:
   ```
   $util.toJson()
   $util.parseJson()
   $util.dynamodb.toDynamoDBJson()
   $util.urlEncode()
   $util.base64Encode()
   $util.autoId()
   $util.error()
   ```

4. **Context Object**:
   Provide rich context similar to AppSync:
   ```
   $ctx.args - arguments/parameters
   $ctx.result - service response
   $ctx.error - error information
   $ctx.identity - requestor identity
   $ctx.stash - place to store values
   $ctx.responseOverride - manipulate response
   ```

5. **Response Handling**:
   - Status code setting via $ctx.responseOverride.statusCode
   - Header manipulation
   - Conditional response formatting
   - Error handling

## Benefits

1. **Elimination of Lambda glue code**: Direct connection to AWS services
2. **Reduced costs**: No Lambda invocation charges for simple operations
3. **Simplified architecture**: Fewer moving parts and points of failure
4. **Consistency with AppSync**: Leverage existing AppSync knowledge
5. **Enhanced developer productivity**: Less boilerplate and repetitive code
6. **Better security**: Fine-grained IAM permissions at the resolver level
7. **Improved performance**: Eliminates Lambda cold starts for simple operations

I believe this feature would significantly improve the developer experience for SAM users by eliminating unnecessary Lambda functions for common data access patterns.
