### ISSUE TITLE
SAM Template Schema Missing New Aurora DSQL Resource(s)

### ISSUE THREAD

**Issue by Logan-Dang** [aws/serverless-application-model#3779]
### Description
[SAM template schema](https://github.com/aws/serverless-application-model/tree/develop/samtranslator/schema) does not have the newly-supported AWS::DSQL::* CloudFormation resource type(s), but they are valid in `sam validate --lint` and `sam deploy`. This results in errors when using a yaml lsp.

### Steps to reproduce
1. Add the following resource to a template.yaml file in a SAM application.
```yaml
  db:
    Type: AWS::DSQL::Cluster
    Properties:
      DeletionProtectionEnabled: false 
```
2. Open the file in an IDE that uses the SAM schema for validation.

### Observed result
`Value is not accepted. Valid values: "AWS::Serverless::Connector".`

### Expected result
No errors

### Additional environment details

1. OS: Windows 11
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: 1.140.0
