### ISSUE TITLE
Shorthand CORS notation is useless for GET, HEAD and POST methods.

### ISSUE THREAD

**Issue by shpoont** [aws/serverless-application-model#387]
Example code:
```
Globals:
  Api:
    Name: test
    Cors: "'*'"
Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      ...
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /test
            Method: post
```

The resulting API configuration does not support [preflight requests](https://www.w3.org/TR/cors/#resource-preflight-requests) for GET, HEAD or POST methods.

In addition, since CORS configuration for [simple requests](https://www.w3.org/TR/cors/#resource-requests) can not be done in Lambda proxy integration, but has to be implemented in actual Lambda code, specifying  `Cors: "'*'"` is useless for HTTP methods mentioned above.
