### ISSUE TITLE
CodeUri intrinsic function doesn't work for S3 bucket

### ISSUE THREAD

**Issue by arturstorm** [aws/serverless-application-model#526]
I defined CodeUri param with !Sub function in YAML:

```
Parameters:
  Version:
     Type: String
     Default: latest
     Description: Lambda version.
MyFunc:
      Type: AWS::Serverless::Function
      Properties:
        FunctionName: MyFuncName
        CodeUri: !Sub "s3://my_backet/my_app/${Version}/code.zip"
        Handler: func.handler
        Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/RoleName"
        Runtime: python3.6
        Timeout: 300
        MemorySize: 256
```
And only Specifying CodeUri using inartistic functions caused exception:
```
Resource with id [MyFunc] is invalid. 'CodeUri' requires Bucket and Key properties to be specified`
```

According to https://aws.amazon.com/about-aws/whats-new/2017/02/aws-serverless-application-model-aws-sam-supports-inline-swagger-and-aws-cloudformation-intrinsic-functions/ (Posted On: Feb 17, 2017):
```
Use intrinsic functions to specify URIs - CodeUri and DefinitionUri now accept Amazon S3 objects with a Bucket, Key and Version. This means you can now use intrinsic functions to dynamically specify your code or Swagger file’s location.
```

1. Define "CodeUri" with  intrinsic function: `CodeUri: !Sub "s3://my_backet/my_app/${Version}/code.zip"`
2. run 'sam deploy --template-file template.yaml --stack-name stack_name'

**Observed result:**
Exception:
`Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [MyFunc] is invalid. 'CodeUri' requires Bucket and Key properties to be specified`
**Expected result:**
CodeUri could by defined as S3 bucket using inartistic functions like !Sub

**Comment by jlhood** [comment]
Unfortunately, the SAM translator does not support intrinsic functions in the CodeUri field of `AWS::Serverless::Function` if you are using the S3 URI format of that property. Looking at the code, if it sees the CodeUri is an object (which it always will be if you're using intrinsic functions), it assumes the user is using the form of CodeUri that accepts an [S3 location object](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3-location-object), which is why you're getting that error.

https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/model/sam_resources.py#L336-L343

You should be able to workaround this limitation by using the S3 location format of CodeUri and using your intrinsic functions inside that object. Try this instead:

```
Parameters:
  Version:
     Type: String
     Default: latest
     Description: Lambda version.
MyFunc:
      Type: AWS::Serverless::Function
      Properties:
        FunctionName: MyFuncName
        CodeUri:
          Bucket: my_backet
          Key: !Sub "my_app/${Version}/code.zip"
        Handler: func.handler
        Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/RoleName"
        Runtime: python3.6
        Timeout: 300
        MemorySize: 256
```

If you use this form of CodeUri, the SAM translator just validates that you've provided Bucket and Key parameters and will then pass those values onto the [Code](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-code) property of the `AWS::Lambda::Function` resource in the transformed CloudFormation template.

**Comment by rjlohan** [comment]
Hit this issue when using a !Ref to a Parameter. In our case, we're pointing at a local file so the workaround doesn't help.

**Comment by keetonian** [comment]
@rjlohan Could you provide an example of what you were trying to do? Were you trying to ref a parameter in the `CodeUri` field or in a different location?

**Comment by craigkj** [comment]
Hi there,

I have a similar issue with intrinsic functions with c3 codeUri I think (although specifically with `!Ref` rather than `!Sub`).

What we started with was this:
```yaml
CodeUri: !Ref PathToFunction
```
however this was causing errors, presumably due to the issues with intrinsic functions here, so we switched to something like this which works:
```yaml
CodeUri: ../path/to/my/lambda/function
```
However we quite like the parameterisation... So following the above workaround we end up with this:
```yaml
CodeUri:
    Bucket: some-s3-bucket
    Key: !Ref PathToFunction
```
However locally that path appears to get set incorrectly, so I tried hardcoding it again:

```yaml
CodeUri:
    Bucket: some-s3-bucket
    Key: ../path/to/my/lambda/function
```

But unfortunately still no luck. Presumably because locally I don't have an s3 bucket to reference... which I suspect may be the same issue as @rjlohan is having @keetonian .
