### ISSUE TITLE
"Auth" property do not work with "AWS::Include" DefinitionBody

### ISSUE THREAD

**Issue by mburket** [aws/serverless-application-model#664]
**Description:**

We need to use some cloudformation functions in our swagger. So the "AWS::Include" transform is used in the DefnitionBody. I tried to move the authorizer declaration out of the swagger using the new "Auth" property. But I received an error of "Unable to add Auth configuration because 'DefinitionBody' does not contain a valid Swagger".  Also, I notice the authorizer caching TTL is not an attribute in the "Auth" property?

** Template snippet:**
```
Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref "Environment"
      EndpointConfiguration: REGIONAL
      Auth:
        Authorizers:
          RequestAuth:
            FunctionPayloadType: REQUEST
            FunctionArn: !FindInMap [EnvironmentDependentParams, !Ref "Environment", "AuthorizerArn"]
            FunctionInvokeRole: !FindInMap [EnvironmentDependentParams, !Ref "Environment", "AuthorizerCredentials"]
            Identity:
              Headers:
                - Authorization
              Context:
                - httpMethod
                - path
              ReauthorizeEvery: 0 # OPTIONAL; Service Default: 300
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: s3://accolade-api-swaggers-test-577121982548/users.yml

```
