### ISSUE TITLE
Bug: CloudWatchEvent does not support integers or floats (or lists of integers or floats)

### ISSUE THREAD

**Issue by forrest-lookback** [aws/serverless-application-model#681]
**Description:**

When creating a [CloudWatchEvent](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#cloudwatchevent) it is not possible to use integers or floats within the Input. As an example this impacts Guard Duty severity levels because they are floats or integers in the event, not strings. When doing a SAM export from a lambda function which relies on a cloudwatch event rule that looks like this (manually created):
```
{
  "source": [
    "aws.guardduty"
  ],
  "detail-type": [
    "GuardDuty Finding"
  ],
  "detail": {
    "severity": [
      7,
      7.1,
      7.2,
      7.3,
      7.4,
      7.5,
      7.6,
      7.7,
      7.8,
      7.9,
      8,
      8.1,
      8.2,
      8.3,
      8.4,
      8.5,
      8.6,
      8.7,
      8.8,
      8.9
    ]
  }
}
```
You are presented with an Events section that looks like this:
```
      Events:
        CloudWatchEvent1:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
                - GuardDuty Finding
              source:
                - aws.guardduty
              detail:
                severity:
                  - 7
                  - 7.1
                  - 7.2
                  - 7.3
                  - 7.4
                  - 7.5
                  - 7.6
                  - 7.7
                  - 7.8
                  - 7.9
                  - 8
                  - 8.1
                  - 8.2
                  - 8.3
                  - 8.4
                  - 8.5
                  - 8.6
                  - 8.7
                  - 8.8
                  - 8.9
```
However when you attempt to deploy this template via SAM you get the following Cloudwatch event:
```
{
  "detail-type": [
    "GuardDuty Finding"
  ],
  "source": [
    "aws.guardduty"
  ],
  "detail": {
    "severity": [
      "7",
      "7.1",
      "7.2",
      "7.3",
      "7.4",
      "7.5",
      "7.6",
      "7.7",
      "7.8",
      "7.9",
      "8",
      "8.1",
      "8.2",
      "8",
      "3",
      "8.4",
      "8.5",
      "8.6",
      "8.7",
      "8.8",
      "8.9"
    ]
  }
}
```
Which doesn't work because severity within Guard Duty is a float or integer, not a string. From what I can see there is no way around this within the template file. Variable substitution Cloudformation style won't work because it converts numbers and lists of numbers to strings. The only way I've found to get past this is to manually update the Cloudwatch Event Rule like this:
```
aws events put-rule --name cloudwatcheventname --event-pattern "{\"source\":[\"aws.guardduty\"],\"detail-type\":[\"GuardDuty Finding\"],\"detail\":{\"severity\":[7.0,7.1,7.2,7.3,7.4,7.5,7.6,7.7,7.8,7.9,8.0,8.1,8.2,8.3,8.4,8.5,8.6,8.7,8.8,8.9]}}"
```
Once you do this the event looks like my original example where it is integers or floats. I'm sure it's possible to use https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html plus some lookups or some shell scripts to create the lambda event, then the rule, then attach that to the lambda to get the same results, but I don't really think that's a very good solution when this is what SAM is exporting and it doesn't work the same way as the existing event does.

**Steps to reproduce the issue:**
1. Enable Guard Duty
2. Create a Lambda which relies on a Cloudwatch event rule based on Guard Duty severity
3. Export the Lambda SAM template
4. Use SAM to deploy the template
5. Confirm the Cloudwatch event rule does not catch any severity warnings due to the incorrect type (string versus integer or float)
6. Manually modify the rule so strings are integers or floats, or run my command above
7. Confirm that the cloudwatch event rule is now catching severity warnings

**Observed result:**

Cloudwatch event rule has strings instead of integers or floats in a list of exported integers and floats.

**Expected result:**

Cloudwatch event rule has integers and floats as originally designed.

**Potential solutions:**

1. Integers and floats within CloudWatchEvent lists are supported unless they are within quotes.

2. Supporting a `Type` option within the CloudWatchEvent Type (similar to Parameters within cloudformation itself: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html) so the above would look like this:

```
      Events:
        CloudWatchEvent1:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
                - GuardDuty Finding
              source:
                - aws.guardduty
              detail:
                severity:
                  - 7
                  - 7.1
                  - 7.2
                  - 7.3
                  - 7.4
                  - 7.5
                  - 7.6
                  - 7.7
                  - 7.8
                  - 7.9
                  - 8
                  - 8.1
                  - 8.2
                  - 8.3
                  - 8.4
                  - 8.5
                  - 8.6
                  - 8.7
                  - 8.8
                  - 8.9
                type: float
```

3. Provide support for [AWS::Events::Rule](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html) which as I noted above works as you would expect it to. So the new section would look like this:
```
Events:
  CloudWatchEvent1:
    Type: Rule
    event-pattern:
      source:
        - aws.guardduty
      detail-type:
        - GuardDuty Finding
      detail:
        severity: [7.0,7.1,7.2,7.3,7.4,7.5,7.6,7.7,7.8,7.9,8.0,8.1,8.2,8.3,8.4,8.5,8.6,8.7,8.8,8.9]
```

I'd even be willing to insert the rule JSON from above into my YAML if that made it work without having to go and look up the cloudwatch event details to keep the template streamlined if that was the only reasonable option.

**Comment by mjs2020** [comment]
Lead here by Google. I'm having the same issue using the AWS [CDK](https://docs.aws.amazon.com/cdk/latest/guide/home.html) and using JSON templates.

Here is a snippet of the template I'm loading:

```
    "GuardDutyFindingsToSNSRule6DED8C29": {
      "Type": "AWS::Events::Rule",
      "Properties": {
        "EventPattern": {
          "source": [
            "aws.guardduty"
          ],
          "detail-type": [
            "GuardDuty Finding"
          ],
          "detail": {
            "severity": [
              4,
              4.1,
              4.2,
              4.3,
              4.4,
              4.5,
              4.6,
              4.7,
              4.8,
              4.9,
              5,
              5.1,
              5.2,
              5.3,
              5.4,
              5.5,
              5.6,
              5.7,
              5.8,
              5.9,
              6,
              6.1,
              6.2,
              6.3,
              6.4,
              6.5,
              6.6,
              6.7,
              6.8,
              6.9,
              7,
              7.1,
              7.2,
              7.3,
              7.4,
              7.5,
              7.6,
              7.7,
              7.8,
              7.9,
              8,
              8.1,
              8.2,
              8.3,
              8.4,
              8.5,
              8.6,
              8.7,
              8.8,
              8.9,
              9,
              9.1,
              9.2,
              9.3,
              9.4,
              9.5,
              9.6,
              9.7,
              9.8,
              9.9,
              10
            ]
          }
        },
        "State": "ENABLED",
        "Targets": [ ... ]
      }
    }
```

and getting quoted strings as a result:

```
{
  "detail-type": [ "GuardDuty Finding" ],
  "source": [ "aws.guardduty" ],
  "detail": {     "severity": [       "4",       "4",       "4.1",       "4.2",       "4.3",       "4.4", ...
```

So I think it's not a problem specific to CDK or SAM but rather to how CloudFormation handles `EventPatterns` in objects of type `AWS::Events::Rule`

**Comment by krutsko** [comment]
+1

**Comment by hoffa** [comment]
Tried reproducing with:

```
sam init --name sam-app --runtime nodejs14.x --dependency-manager npm --app-template hello-world
```

And replacing `template.yaml`:

```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        CloudWatchEvent1:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
                - GuardDuty Finding
              source:
                - aws.guardduty
              detail:
                severity:
                  - 1
                  - 1.2
                  - 1.3
                  - 2
```

Looking at Lambda I'm getting the expected event pattern:

```json
{
  "detail-type": [
    "GuardDuty Finding"
  ],
  "source": [
    "aws.guardduty"
  ],
  "detail": {
    "severity": [
      1,
      1.2,
      1.3,
      2
    ]
  }
}
```

Closing as this seems to be resolved.
