### ISSUE TITLE
Api Path Can't Bet Set from Reference

### ISSUE THREAD

**Issue by BurgherJon** [aws/serverless-application-model#687]
I want to do a cloudformation deploy with an events section that looks like this and the parameter "ThePath is set to "/good":

```
Events:
    Api2:
       Type: Api
       Properties:
          Method: ANY
          Path: !Ref ThePath
```

This results in:

```
Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Internal transform failure.
```

When I modify the exact same file to use an actual path instead of a parameter it works fine:
```
Events:
   Api2:
       Type: Api
       Properties:
           Method: ANY
           Path: /good
```

Perhaps the part of the code that is doing the validation won't let this happen because it can't verify that the parameter begins with a "/"?
