### ISSUE TITLE
Tracing field of Serverless::Function does not support intrinsics

### ISSUE THREAD

**Issue by keetonian** [aws/serverless-application-model#983]
**Description:**
Tracing needs to support "Fn::If" and other intrinsic functions

**Steps to reproduce the issue:**
1. Create a template with "Tracing" set to an !If function
2. Deploy

**Observed result:**
Condition is ignored
**Expected result:**
Condition to work

**Comment by stevenmhood** [comment]
I have an example that works with this already:

```
Parameters:
  EnableXRayTracing:
    Type: String
    Description: Enables X-Ray tracing.  Disabled by default.
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'false'
Conditions:
  TracingEnabled:
    Fn::Equals:
    - Ref: EnableXRayTracing
    - 'true'
Resources:
  StreamRepartitionerFunction:
    Type: AWS::Serverless::Function
      ...
      Tracing:
        Fn::If:
        - TracingEnabled
        - Active
        - PassThrough
```

Is this actually complete, then?
