### ISSUE TITLE
Authorizer overrides at function level not working as expected when using swagger and global default authorizer config

### ISSUE THREAD

**Issue by sgates** [aws/serverless-application-model#984]
I've been working with @keetonian via the slack channel on this issue, I'll defer to him for more details and findings.

In a nutshell:
Swagger is used to define API details. It's included in template with
    
    Location: !Sub 's3://${DeployBucket}/${BranchName}/swagger-${Version}.yaml'

There is a global auth config at the API level with a default authorizer (a lambda authorizer). I wish to make specific get requests defined in the sam template have no authorizer, so I added:

    Auth:
      Authorizer: NONE

This doesn't seem to stick (it's ignored when deployed) and the DefaultAuthorizer gets added to the resource anyway. Keeton has reproduced the issue, but hasn't nailed down a cause yet. I'm reporting here for tracking and for others should they hit a similar issue. Thanks!

**Comment by unscriptable** [comment]
We seem to be experiencing this issue.  Is there a known work-around?

**Comment by sgates** [comment]
> We seem to be experiencing this issue. Is there a known work-around?

Kinda-  you can have a post-deploy script that uses the CLI to make changes to the gateway/lambda functions. This isn't ideal :/

**Comment by praneetap** [comment]
@sgates @unscriptable Thanks for reporting this bug! Are you facing this while using IAM auth? We have a fix going out soon that addresses it for IAM - https://github.com/awslabs/serverless-application-model/pull/1015. To track our release you can check out our [release board](https://github.com/awslabs/serverless-application-model/projects/3).

**Comment by sgates** [comment]
@praneetap no, this was for using a custom authorizer (lambda authorizer). I didn't try with IAM, but thanks for mentioning it!

**Comment by unscriptable** [comment]
We're using Cognito.

**Comment by ShreyaGangishetty** [comment]
@sgates @unscriptable this issue should be fixed in the next release. You can track the release in our [release board](https://github.com/awslabs/serverless-application-model/projects/3).

**Comment by unscriptable** [comment]
You rock, @ShreyaGangishetty!  I don't see `1.16.0` on the release board, yet.  Any idea when it's scheduled?

**Comment by sgates** [comment]
@ShreyaGangishetty, that’s awesome news, thanks!

**Comment by ShreyaGangishetty** [comment]
@sgates I have created the [release tracker](https://github.com/awslabs/serverless-application-model/issues/1212) for v1.16.0. We haven't cut v1.16.0 release branch yet, but the progress of release can be tracked [here](https://github.com/awslabs/serverless-application-model/projects/3)

**Comment by sgates** [comment]
@ShreyaGangishetty Great! We're not blocked at the moment, but we do have a kind of hack-y post deploy script, and this will enable us to get rid of that! Thanks!

**Comment by keetonian** [comment]
The fix for this was rolled back in 1.20.0, as it caused several regressions:
* SAM started invalidating several templates with custom swagger/openapi definitions that did not fit the format SAM expected. Most of these templates were valid.
* SAM started adding authorizers to methods it hadn't added them to in the past, causing invalid or undesired template outputs

**Comment by sgates** [comment]
@keetonian good to know, will stand by. Looking forward to a fix in the future!

**Comment by anmoreno** [comment]
@keetonian @ShreyaGangishetty Any updates on this issue? I am currently experiencing this issue where I can't override an endpoint to use a different Authorizer, it always sets the Default Authorizer.

**Comment by sujeshmenon** [comment]
I am facing the same issue when trying to override an API level [Default Authorizer](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-apiauth.html#sam-api-apiauth-defaultauthorizer) with a Function specific [Authorizer](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-apifunctionauth.html#sam-function-apifunctionauth-authorizer). The method still ends up with the Default Authorizer. Is this feature going to be available anytime soon as mentioned in the documentation?

**Comment by unscriptable** [comment]
We would also like an update on this fix.  Every time we push new changes to the OpenAPI spec, the site goes down for 30 seconds while we run scripts to revert the authorization on the open endpoints.  If the fix isn't being actively developed, we need to know so we can find other (non-SAM and/or non-OpenAPI) ways to implement our API.  Thanks!

**Comment by mikematos84** [comment]
I have a similar need by my project is actually using a Cognito user pool authorizer at the API level. Like others, I added an Auth override at the Lambda level but it does not seem to be working as even when I look at the API Gateway it still shows Authorization: COGNITO_USER_POOLS. Is there any possible way to override it in order to have just a few endpoints be accessible without authorization and the rest be secured?

**Comment by unscriptable** [comment]
Hey SAM team. Can we at least get a status update on this problem? Thanks.

**Comment by malikhijazi** [comment]
Are there any workarounds to this that dont entail rewriting the entire sam template in regular cloudformation or having to have downtime every time the api is deployed?

**Comment by unscriptable** [comment]
> Hey SAM team. Can we at least get a status update on this problem? Thanks.

C’mon, SAM team. Just let us know what’s going on please?

**Comment by sujeshmenon** [comment]
@malikhijazi If you are using OpenAPI to define your endpoints, you may want to look at using the [OpenAPI extensions](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-authorizer.html) to do the authorizer override. 
We used this alternative at our end by defining the authorizers and the default authorizer in the SAM template and then overriding the authorizer for the required endpoints in the swagger file like below:

`security:
        - AuthorizerThatOverridesTheDefaultAuthorizer: [ ]`

**Comment by aaythapa** [comment]
Looks like if the API details are defined in the Serverless API the DefaultAuthorizer won't be able to overridden. 
For example this template would override the default auth.
```
MyApiWithAuth:
    Type: AWS::Serverless::Api
    Properties:
      ...
      Auth:
        Authorizers:
          MyLambdaTokenAuth:
            FunctionArn: !GetAtt MyAuthFn.Arn
        DefaultAuthorizer: MyLambdaTokenAuth

MyAuthFn:
    Type: AWS::Serverless::Function
    ...

MyFn:
    Type: AWS::Serverless::Function
    Properties:
      ...
      Events:
        LambdaToken:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiWithAuth
            Method: get
            Auth:
              Authorizer: NONE
            Path: /lambda-token
```
While this template wouldn't override the default auth because the API details are defined in the Serverless API.
```
MyApiWithAuth:
    Type: AWS::Serverless::Api
    Properties:
      ...
      DefinitionBody:
        ...
        paths:
          /lambda-request:
            ...
      Auth:
        Authorizers:
          MyLambdaTokenAuth:
            FunctionArn: !GetAtt MyAuthFn.Arn
        DefaultAuthorizer: MyLambdaTokenAuth

MyAuthFn:
    Type: AWS::Serverless::Function
    ...

MyFn:
    Type: AWS::Serverless::Function
    Properties:
      ...
      Events:
        LambdaToken:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiWithAuth
            Method: get
            Auth:
              Authorizer: NONE
            Path: /lambda-token
```
Unfortunately, fixing this would cause compatibility issues. We will update the docs to clarify further and will look to fix this when we version bump SAM.

**Comment by koxon** [comment]
> Looks like if the API details are defined in the Serverless API the DefaultAuthorizer won't be able to overridden. For example this template would override the default auth.
> 
> ```
> MyApiWithAuth:
>     Type: AWS::Serverless::Api
>     Properties:
>       ...
>       Auth:
>         Authorizers:
>           MyLambdaTokenAuth:
>             FunctionArn: !GetAtt MyAuthFn.Arn
>         DefaultAuthorizer: MyLambdaTokenAuth
> 
> MyAuthFn:
>     Type: AWS::Serverless::Function
>     ...
> 
> MyFn:
>     Type: AWS::Serverless::Function
>     Properties:
>       ...
>       Events:
>         LambdaToken:
>           Type: Api
>           Properties:
>             RestApiId: !Ref MyApiWithAuth
>             Method: get
>             Auth:
>               Authorizer: NONE
>             Path: /lambda-token
> ```
> 
> While this template wouldn't override the default auth because the API details are defined in the Serverless API.
> 
> ```
> MyApiWithAuth:
>     Type: AWS::Serverless::Api
>     Properties:
>       ...
>       DefinitionBody:
>         ...
>         paths:
>           /lambda-request:
>             ...
>       Auth:
>         Authorizers:
>           MyLambdaTokenAuth:
>             FunctionArn: !GetAtt MyAuthFn.Arn
>         DefaultAuthorizer: MyLambdaTokenAuth
> 
> MyAuthFn:
>     Type: AWS::Serverless::Function
>     ...
> 
> MyFn:
>     Type: AWS::Serverless::Function
>     Properties:
>       ...
>       Events:
>         LambdaToken:
>           Type: Api
>           Properties:
>             RestApiId: !Ref MyApiWithAuth
>             Method: get
>             Auth:
>               Authorizer: NONE
>             Path: /lambda-token
> ```
> 
> Unfortunately, fixing this would cause compatibility issues. We will update the docs to clarify further and will look to fix this when we version bump SAM. Going to keep this ticket open until then. Please let us know if this clear things up 👍

I just tested to override with AWS_IAM but it gets set to NONE. So it doesn't override correctly apparently.

```
          Auth:
            Authorizer: AWS_IAM
```

**Comment by paulhcsun** [comment]
There is a workaround released for this issue detailed in this [PR](https://github.com/aws/serverless-application-model/pull/3328). The root of the issue was that any `Auth` would be ignored when your `AWS::Serverless::Api` resource contains a `DefinitionBody`. The workaround is to include the new `OverrideApiAuth: true` property along with your authorizer. For example:
```
MyFn:
    Type: AWS::Serverless::Function
    Properties:
      ...
      Events:
        LambdaToken:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiWithAuth
            Method: get
            Auth:
              Authorizer: NONE
              OverrideApiAuth: true
            Path: /lambda-token
```
The docs for this new property will be released soon and will be linked here once it's available.
